### ISSUE TITLE
Works on emulator(API 27) not working on real device (API 28)

### ISSUE THREAD

**Issue by faslurrajah** [ryanheise/just_audio#100]
**Describe the bug**
I used this link for audio. http://sstamilradio.radioca.st/stream/;
It works in android emulator(API 27). Not working in my real device(API 28). Keep rotating 

**Minimal reproduction project**

**To Reproduce**

**Error messages**

```
No error message shown
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 
![photo6235570899612969554](https://user-images.githubusercontent.com/30668705/83265986-e29de900-a1df-11ea-9c41-412d7c8b30f1.jpg)

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.19.0-2.0.pre.173, on Microsoft Windows [Version 10.0.18362.30], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] Connected device (2 available)

• No issues found!
```

**Additional context**

**Comment by faslurrajah** [comment]
I need an immediate explanation

**Comment by iansamz** [comment]
Same Problem Here. It works on emulator and android but real device has issues.

**Comment by iansamz** [comment]
same question is [here](https://github.com/ryanheise/just_audio/issues/74)

**Comment by ryanheise** [comment]
> I need an immediate explanation

@faslurrajah , The best way to get a faster explanation is to provide as much information as you can in your bug report, including the minimal reproduction project. You've skipped over most sections of the bug report, including the minimal reproduction project and the smartphone/mobile device.

I tested the URL you provided with cleartext but it worked for me on my Google pixel 3a (API 29), so it must be something in your project setup (which you didn't provide) or your specific smartphone (which you didn't provide), and most likely the former.

**Comment by ryanheise** [comment]
> same question is [here](https://github.com/ryanheise/just_audio/issues/74)

Many issues can have the symptom of working on the simulator and not working on the device, so it is better to look at the underlying issue which is different in this case.

**Comment by faslurrajah** [comment]
I found the solution.

I used different audio packages . Nothing worked. All we need to do is allow the INTERNET Permission in AndroidManifist.
