### ISSUE TITLE
Notifiaction click not listen in iOS

### ISSUE THREAD

**Issue by KishanAtrina** [ryanheise/just_audio#1003]
@ryanheise
AudioService.notificationClicked.listen((clicked) {
if (clicked) {
// Navigate to another screen
}
});

the above code i have used for getting me the notification click event so i can navigate to the screen and it is working properly in android but in Ios didn't getting any click event when i click in notification

**Comment by ryanheise** [comment]
Read it before spamming again:

> Oops, it appears that your issue did not follow the template and is missing one or more required sections. Please open a new issue, and provide all required sections and information.
> 
> FAQ:
> 
>   1. Do I really need to submit a minimal reproduction project for a bug? A: Yes. I prioritise bugs _secondarily_ on how many people are affected, and _primarily_ on whether the bug report is complete, in the sense that it enables me to immediately reproduce it and start working on a fix. If a bug is important to you, the best thing you can do is to provide all requested information ASAP so that I can start looking into it ASAP.
> 
>   2. I think I supplied all required information, so did the bot make a mistake? A: The bot only checks the section headings, so when you post a new issue, make sure you leave the section headings intact. (Note that because of this, it is even possible to trick the bot by including only the section headings, and then not providing the requested information under each heading. This is frowned upon, and the issue will be closed manually.)
