### ISSUE TITLE
just_audio causes tremendous amounts of debug spam

### ISSUE THREAD

**Issue by MapperMalte** [ryanheise/just_audio#1008]
Like this

D/BufferPoolAccessor2.0( 7500): evictor expired: 5, evicted: 0
D/BufferPoolAccessor2.0( 7500): bufferpool2 0xe98d8ed8 : 5(163840 size) total buffers - 4(131072 size) used buffers - 21/26 (recycle/alloc) - 8/42 (fetch/transfer)
D/BufferPoolAccessor2.0( 7500): bufferpool2 0xe9632f98 : 0(0 size) total buffers - 0(0 size) used buffers - 10/15 (recycle/alloc) - 5/10 (fetch/transfer)
D/BufferPoolAccessor2.0( 7500): bufferpool2 0xe9631b98 : 0(0 size) total buffers - 0(0 size) used buffers - 109/119 (recycle/alloc) - 16/220 (fetch/transfer)
D/BufferPoolAccessor2.0( 7500): evictor expired: 2, evicted: 2
D/BufferPoolAccessor2.0( 7500): bufferpool2 0xe98d8ed8 : 5(163840 size) total buffers - 4(131072 size) used buffers - 41/46 (recycle/alloc) - 12/82 (fetch/transfer)
D/BufferPoolAccessor2.0( 7500): bufferpool2 0xe98d8ed8 : 5(163840 size) total buffers - 4(131072 size) used buffers - 61/66 (recycle/alloc) - 16/122 (fetch/transfer)
D/BufferPoolAccessor2.0( 7500): evictor expired: 1, evicted: 1

**Comment by ryanheise** [comment]
Tremendous amounts of spam, indeed:

[Search: "It appears your issue did not follow the template"](https://github.com/ryanheise/just_audio/issues?q=is%3Aissue+%22It+appears+your+issue+did+not+follow+the+template%22)

315 results.

> It is really absurd

I think I can relate.
