### ISSUE TITLE
Xcode 15 beta: The app links to non-public libraries in Runner

### ISSUE THREAD

**Issue by aoizoijoizj** [ryanheise/just_audio#1009]
When building app in xcode 15 beta, it shows an error:

`The app links to non-public libraries in Frameworks/just_audio.framework/just_audio: /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore,The app links to non-public libraries in Runner: /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore`

This issue is also appears with audioplayers flutter package so i'm not sure what causes this.

**Comment by ryanheise** [comment]
Can you please provide more information as per the issue template?

Checking online, this error is normally accompanied with a mention of the specific private framework that is being used, and that would be an important clue about what I need to investigate. Are you able to find any such mention in the full error output?

**Comment by aoizoijoizj** [comment]
@ryanheise The issue is simply when you archive the project using xcode 15 beta and having just_audio package
