### ISSUE TITLE
Stop Background Audio service flutter

### ISSUE THREAD

**Issue by mdusaama0** [ryanheise/just_audio#1034]
When I play some music using just_audio & just_audio_background it keeps playing when I kill my app from the background.

I want to stop the music and remove the notification tray when the user removes the app from the task manager.

I tried AppLifeCycle methods and dispose audio player on detached but it is just leaking as the flutter UI is destroyed.

How can I do it?

I want the audio session should be ended after user clear the task manager.

**Flutter SDK version**
3.7.9
insert output of "flutter doctor" here
[✓] Flutter (Channel stable, 3.7.9, on macOS 12.5 21G72 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

Here is the code which I'm currently working on.

`//initialize the background service
  await JustAudioBackground.init(
    androidNotificationChannelId: 'com.ryanheise.bg_demo.channel.audio',
    androidNotificationChannelName: 'Audio playback',
    androidNotificationOngoing: true,
  );`

`@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.detached) {
      print("detached");
      if (Platform.isAndroid) {
        _audioPlayer.dispose();
      }
    }
    super.didChangeAppLifecycleState(state);
  }`

**Comment by mdusaama0** [comment]
@ryanheise please guide.

**Comment by ryanheise** [comment]
Perhaps you are just ignoring the "Oops" message above, right? I think it's fair that if you ignore me, I'll ignore you.
