### ISSUE TITLE
Stop music on swipe the app up in the task manager

### ISSUE THREAD

**Issue by mdusaama0** [ryanheise/just_audio#1035]
**Which API doesn't behave as documented, and how does it misbehave?**
When I play some music using just_audio & just_audio_background it keeps playing when I remove my app from the task manager.

**Minimal reproduction project**
```
//initialize the background service 
await JustAudioBackground.init( 
  androidNotificationChannelId: 'com.ryanheise.bg_demo.channel.audio', 
  androidNotificationChannelName: 'Audio playback', 
  androidNotificationOngoing: true, 
);

@override void didChangeAppLifecycleState(AppLifecycleState state) { 
  if (state == AppLifecycleState.detached) { 
    print("detached");
   if (Platform.isAndroid) { 
    _audioPlayer.dispose(); 
    } 
} 
super.didChangeAppLifecycleState(state); 
}

```

**To Reproduce (i.e. user steps, not code)**
- Play music.
- Swipe up the app from task manager
- music is still playing

**Error messages**

```
No Errors.
```

**Expected behavior**
Music should stop playing.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A51]

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.7.9, on macOS 12.5 21G72 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**
N/A

**Comment by ryanheise** [comment]
@mdusaama0 can you please follow the instructions for submitting a bug? I just went through this with you in your previous submission. I am very doubtful that this is actually a bug, and the only way to find out is for you to go through the process of carefully thinking about each question in the bug report. For example, in the very first section, you never actually clearly showed how this is a bug. and in the second section you didn't provide a link to your fork as clearly requested in the instructions.

Also, are you the same person who posted a question on StackOverflow here?

https://stackoverflow.com/questions/76776014/stop-background-audio-service-flutter

If so, why are you making me talk to you on two different websites? I was already engaging with your question over there, there's no need to use GitHub to simultaneously ask me the same question in two places. GitHub is for bugs, StackOverflow is for questions.

**Comment by mdusaama0** [comment]
> @mdusaama0 can you please follow the instructions for submitting a bug? I just went through this with you in your previous submission. I am very doubtful that this is actually a bug, and the only way to find out is for you to go through the process of carefully thinking about each question in the bug report. For example, in the very first section, you never actually clearly showed how this is a bug. and in the second section you didn't provide a link to your fork as clearly requested in the instructions.
> 
> Also, are you the same person who posted a question on StackOverflow here?
> 
> https://stackoverflow.com/questions/76776014/stop-background-audio-service-flutter
> 
> If so, why are you making me talk to you on two different websites? I was already engaging with your question over there, there's no need to use GitHub to simultaneously ask me the same question in two places. GitHub is for bugs, StackOverflow is for questions.

Yes. You’re right. This is not a bug. I am just asking a question. Sorry for engaging you on both platforms.

**Comment by mdusaama0** [comment]
I'm facing the same mentioned in this issue. https://github.com/ryanheise/audio_service/issues/159
but I'm using just_audio_background instead of audio_service

**Comment by ryanheise** [comment]
That issue was based on a very old version of audio_service, and the features proposed back then already exist by now. In any case, we need to stop talking here since I was already in the process of helping you on StackOverflow.
