### ISSUE TITLE
Player stops playing on IOS with particular files when using ConcatenatedAudioSource

### ISSUE THREAD

**Issue by sudo-ulmas** [ryanheise/just_audio#1046]
**Which API doesn't behave as documented, and how does it misbehave?**
On IOS when you create Playlist using ConcatenatedAudioSource with these files for example https://alquran.qtlms.uz/media/file/oyat/MisharybinRashidAlafasyAasimHafsAasim/002008.mp3
https://alquran.qtlms.uz/media/file/oyat/MisharybinRashidAlafasyAasimHafsAasim/002008.mp3
and hit play, then this happens, the player starts playing and when it reaches the second file, the player just stops instead of continuing to play the second file. Only after some delay(usually a few seconds) the player goes on to play the second file. I don't understand why the player stops between these files, but if I run the same code but put other files player plays normally. 

**Minimal reproduction project**
```
   _player.setAudioSource(
      ConcatenatingAudioSource(
        children: [
          AudioSource.uri(
            Uri.parse(
              'https://alquran.qtlms.uz/media/file/oyat/MisharybinRashidAlafasyAasimHafsAasim/002008.mp3',
            ),
          ),
          AudioSource.uri(
            Uri.parse(
              'https://alquran.qtlms.uz/media/file/oyat/MisharybinRashidAlafasyAasimHafsAasim/002009.mp3',
            ),
          ),
        ],
      ),
    );
```

**To Reproduce (i.e. user steps, not code)**
Load the player with those audio URLs provided and start playing.

**Error messages**
No error messages

**Expected behavior**
audio files should be player one after another without any delay

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A

**Smartphone (please complete the following information):**
 - Device:  iPhone12 mini
 - OS: iOS15.4

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0
    22A380 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices
    (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install
      "cmdline-tools;latest"`
      See
      https://developer.android.com/studio/command-lin
      e for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to
      accept the SDK licenses.
      See
      https://flutter.dev/docs/get-started/install/mac
      os#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Additional context**
N/A

**Comment by sudo-ulmas** [comment]
@ryanheise could you have a look, please?

**Comment by ryanheise** [comment]
Can you please clarify your bug report to describe accurately what happens?

**Comment by sudo-ulmas** [comment]
> Can you please clarify your bug report to describe accurately what happens?

I updated the bug report, please let me know if something is unclear

**Comment by ryanheise** [comment]
> the player starts playing and when it reaches the second file, the player just stops instead of continuing to play the second file

I'm unclear on this. Doesn't the player start playing the first file? Or is the first file not playing?

**Comment by sudo-ulmas** [comment]
> > the player starts playing and when it reaches the second file, the player just stops instead of continuing to play the second file
> 
> 
> 
> I'm unclear on this. Doesn't the player start playing the first file? Or is the first file not playing?

Yes the player start playing the first file but delays for few seconds before continuing to the second and that is the issue.

**Comment by ryanheise** [comment]
Hmm, I thought you said it actually starts playing the second file and then stops after it starts.

Maybe this is what you mean. It starts playing the first file properly, but then delays for a few seconds before starting the second file?

**Comment by sudo-ulmas** [comment]
> Hmm, I thought you said it actually starts playing the second file and then stops after it starts.
> 
> Maybe this is what you mean. It starts playing the first file properly, but then delays for a few seconds before starting the second file?

Yes, this is what I meant, it starts playing the first file properly, but then delays for a few seconds before starting the second file.

**Comment by ryanheise** [comment]
The first file is short, so it is possible that there hasn't been enough time for the second file to load.

I don't think your minimal reproduction gives enough context as to how it is being loaded. For example, does this happen with `example_playlist.dart` if you replace the mp3s with your ones, and you wait before pressing play?

**Comment by sudo-ulmas** [comment]
@ryanheise  Yes, I ran `example_playlist.dart` and replaced mp3s with these 2 files and waited before playing and the same problem happened there. 

Also I am sure this happens not because file is short and player needs enough time to load, because I tested with much shorter files and there is no such problem.

**Comment by sudo-ulmas** [comment]
@ryanheise Could you help us with this issue, please?

**Comment by sudo-ulmas** [comment]
@ryanheise did you have a look?

**Comment by priyesh-bit** [comment]
In my case ios simulator and real device iPhone 14 getting crash when I'm adding songs to playlist. In Android devices, it's working fine. I noticed this issue after updating to flutter `3.13.2` @ryanheise Any idea about this crash in ios 16.6.1

```
  @override
  Future<void> addQueueItems(List<MediaItem> mediaItems) async {
    _playlist = ConcatenatingAudioSource(children: []);
    await _player.setAudioSource(_playlist);

    // manage Just Audio
    final audioSource = mediaItems.map((e) => _createAudioSource(e),).toList();
    _playlist.addAll(audioSource.toList());

    // // notify system
    final newQueue = queue.value..addAll(mediaItems);
    queue.add(newQueue);
  }


  UriAudioSource _createAudioSource(MediaItem mediaItem) {
    return AudioSource.uri(
      Uri.parse(mediaItem.id),
      tag: mediaItem,
    );
  }

```

Error log

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010776c8c0 Flutter`impeller::ContentsFilterInput::GetCoverage(impeller::Entity const&) const + 4
Flutter`impeller::ContentsFilterInput::GetCoverage:
->  0x10776c8c0 <+4>:  ldr    x9, [x0]
    0x10776c8c4 <+8>:  ldr    x2, [x9, #0x18]
    0x10776c8c8 <+12>: br     x2
Flutter`impeller::FilterContentsFilterInput::~FilterContentsFilterInput:
    0x10776c8cc <+0>:  stp    x20, x19, [sp, #-0x20]!
Target 0: (Runner) stopped.
```


Here is my MediaItem

`{id: https://bazawala.com/uploads/music/audio/ff457FYHoao6VwpVnFkfHRAoLpTr1wONCahjpA1a.mp3, title: Wai Wai Charo, album: , artist: null, genre: null, duration: null, artUri: https://bazawala.com/uploads/music/image/hdyGA9DBLuGUj7eeQ3zb3yCOCfPPgoD0YvXDx05I.jpg, playable: true, displayTitle: null, displaySubtitle: null, displayDescription: null, rating: null, extras: {song_meta: {id: 2075, title: Wai Wai Charo, music: uploads/music/audio/ff457FYHoao6VwpVnFkfHRAoLpTr1wONCahjpA1a.mp3, image: uploads/music/image/hdyGA9DBLuGUj7eeQ3zb3yCOCfPPgoD0YvXDx05I.jpg, albums_id: , duration: 267, total_plays: 4, name: , song_file_name: null, type: music, artists: [{"id":586,"name":"Tshewang Toress","image":"uploads/artist/z4H0gN8n6D064gUjjFBbZXxjwaTE99G5qgTaL0hv.jpg"}], album: null}}}`

**Comment by ryanheise** [comment]
@priyesh-bit please submit a separate bug report, as this is not the same bug. I'll mark both your and my comment as off topic.

**Comment by ulmas-ulmas** [comment]
Any updates? having the same issue

**Comment by ryanheise** [comment]
@ulmas-ulmas can you provide me with the mp3 that doesn't work?

**Comment by ulmas-ulmas** [comment]
> @ulmas-ulmas can you provide me with the mp3 that doesn't work?

https://alquran.qtlms.uz/media/file/oyat/MaherAlMuaiqlyAasimHafsAasim/019010.mp3
https://alquran.qtlms.uz/media/file/oyat/MaherAlMuaiqlyAasimHafsAasim/019011.mp3

**Comment by ryanheise** [comment]
I was hoping to get a different example. But I may need to wait until more people report this issue with a different example to see what is going on.

**Comment by ulmas-ulmas** [comment]
@ryanheise any ideas on why this might happen?

**Comment by ryanheise** [comment]
@ulmas-ulmas I'm sorry I will need to wait until this issue is reported by more people, since I am currently focused on some higher priority issues. In the meantime, you can consider helping by investigating yourself.

**Comment by sudo-ulmas** [comment]
Turned out the issue was with the audio file although I checked it for corruption and I could not find anything but when I tried to play them on other players the same issue was there, so I guess we can close this one.

**Comment by ryanheise** [comment]
What about @ulmas-ulmas , have you tested with other players to see whether it's your audio files?

**Comment by sudo-ulmas** [comment]
It's my second account bro))

**Comment by ryanheise** [comment]
But @ulmas-ulmas wrote above:

> "Any updates? having the same issue"

If you are actually the same person, why would you say that you're having the same issue as yourself? Or did you want me to think that you were not the only person who experienced this issue and that there was a second person who also experienced the same issue?

**Comment by sudo-ulmas** [comment]
Yep, sorry about that bro, thought you would help me if there were multiple requests.

**Comment by ryanheise** [comment]
Are they both free GitHub accounts?

**Comment by sudo-ulmas** [comment]
yes

**Comment by ryanheise** [comment]
This is not actually permitted by the GitHub terms of service, section 3 point 3:

> One person or legal entity may maintain no more than one free Account (if you choose to control a machine account as well, that's fine, but it can only be used for running a machine).

You might want to delete your second account, otherwise if someone reports it, GitHub may end up deleting both of your accounts.

**Comment by sudo-ulmas** [comment]
Wow didn't know about that, thank you for informing.
