### ISSUE TITLE
[macos] I am getting an erro on macos when trying to play a sound 

### ISSUE THREAD

**Issue by michalkubizna** [ryanheise/just_audio#1049]
This only happens on macos. It works fine on iOS

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (-11849) Operation Stopped
#0      AudioPlayer._load (package:just_audio/just_audio.dart:850:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1435:28)
<asynchronous suspension>

` @override
  void initState() {
    super.initState();
    
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      _audioPlayer.setAsset('assets/bell.mp3').then((value) {
        _audioPlayer.play();
      });
    });
  }`

**Comment by MuradSh** [comment]
Same. A very weird error.

**Comment by ryanheise** [comment]
@MuradSh do you want to submit a valid bug report?
