### ISSUE TITLE
ios播放声音中断后台音乐的问题，在我的app中如果调用AVAudioSession 播放完声音，后台的音乐不能恢复

### ISSUE THREAD

**Issue by wahkim** [ryanheise/just_audio#1051]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanheise** [comment]
Please read the instructions before posting an issue. If you don't speak English, use translation software. Closing.
