### ISSUE TITLE
MethodChannel.invokeMethod('stop') not working with previously instanciated player

### ISSUE THREAD

**Issue by klitzouille** [ryanheise/just_audio#106]
**Describe the bug**
I updated the plugin on my local repository so that dart AudioPlayer exposes the internal ID as public property.

Now I have the following use case for an alarm app : 
- App schedule a task with Workmanager plugin
- When task is executed (regardless if app is in background or foreground) :
  - Display a notification
  - Store internal ID in shared prefs
  - Play some audio

When user click on the notification and app is launched, I retrieve the internal ID and instantiate a method channel the following way
```
MethodChannel methodChannel = MethodChannel('com.ryanheise.just_audio.methods.' + prefs.getInt('player').toString());
```

Then I invoke the method "stop" and I get the following error message.

**Error messages**
```
PlatformException (PlatformException(Illegal state: Cannot call stop from none state, null, null))
```

**Expected behavious**
Since the player is already instanciated and playing audio, shouldn't its state be "playing" when I try to invoke method "stop" ?

**Smartphone**
 - Device: Xiaomi Redmi Note 6
 - OS: Android 9
 - Vendor: MIUI 11.0.4

**Flutter SDK version**
I'm using Visual Studio Code, hence the erros related to Android Studio

```
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [version 10.0.18363.836], locale fr-FR)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.45.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by ryanheise** [comment]
It is not intended that code outside the plugin use the private method channel of the plugin, and so I wouldn't consider it a bug that this doesn't work. Ideally, this sort of thing would be prevented by Flutter so that the integrity of the plugin is protected.

If you have a use case that isn't supported by the plugin, I would suggest opening a feature request and suggesting the API you would like added.

**Comment by ryanheise** [comment]
If I understand your use case correctly, I don't think you would need any special feature built into this plugin. Most likely the work manager plugin is running your code in a separate isolate. If you have an instance of `AudioPlayer` already playing audio, it will be in a particular isolate. You can use Flutter's existing APIs to communicate between the two isolates using send/receive ports and `IsolateNameServer`, and send a message from your work manager task to the isolate where you're playing audio. You'll then have an actual reference to the `AudioPlayer` instance and can just invoke methods on it directly.

**Comment by klitzouille** [comment]
Thanks for the feedback. Actually, it is the background isolate that is playing the audio, and I want to stop it from the UI whe user has clicked the notification, but I think what described still apply in this use case, am I correct ?

**Comment by klitzouille** [comment]
I got it working, thanks a lot for the help
