### ISSUE TITLE
Android Equalizer does not work when just_audio_backgound is enabled

### ISSUE THREAD

**Issue by emperorKez** [ryanheise/just_audio#1063]
1. Enable just_audio_background
2. Initialiazer AudioPlayer with AudioPipeline
final equalizer = AndroidEqualizer();
      final loudnessEnhancer = AndroidLoudnessEnhancer();

      final player = AudioPlayer(
            audioPipeline: AudioPipeline(androidAudioEffects: [
          equalizer,
          loudnessEnhancer,
          ])
          );

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: androidEqualizerGetParameters() has not been implemented.

**Comment by ryanheise** [comment]
I'm sorry, you need to follow the instructions for submitting a bug report exactly, otherwise I do not look at the issue.
