### ISSUE TITLE
Android Release Mode doesn't await for audio player to finish playing an asset

### ISSUE THREAD

**Issue by taufiq-husain** [ryanheise/just_audio#1073]
**Which API doesn't behave as documented, and how does it misbehave?**

```
  final AudioPlayer soundPlayer = AudioPlayer();
  await soundPlayer.setSpeed(1.0);
  await soundPlayer.setVolume(1.0);
  await soundPlayer.setAsset("assets/audio/intro.mp3");
  await soundPlayer.play(); // Doesn't await to finish playing the audio in Android Release mode
  print("Hello World"); // This is printed before the audio finishes playing from asset
```

**Minimal reproduction project**
Provide a link here using one of two options:
The example (I wrote the code above to replicate the issue)

**To Reproduce (i.e. user steps, not code)**
1. Try the above code or your examples using await on an asset audio file.
2. Run flutter run --release
3. Try it on any physical android device (I'm using a Pixel 6 for testing)
4. It works properly on iOS devices btw (tried on iPhone 13 mini, iPhone 15 Pro and iPhone 11 Pro

**Error messages**

```
N/A. It didn't print any error messages either. I tried with try/catch statements.
```

**Expected behavior**
The audio file should be played till the end before executing the next line of code.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Pixel 6
 - Android 13

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
    • Flutter version 3.13.5 on channel stable at /Users/taufiqhusain/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (7 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/taufiqhusain/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)         • 1C081FDF60009N            • android-arm64  • Android 13 (API 33)
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Additional context**
Great package btw. Love it. Very very very useful. I'm very grateful!

**Comment by taufiq-husain** [comment]
Never mind. It seems that the issue may be because I am playing a soundless video file in the background which basically stops on another from working.

**Comment by ryanheise** [comment]
> **Minimal reproduction project**
> Provide a link here using one of two options:
> The example (I wrote the code above to replicate the issue)

Hi, in case you post more issues again in the future, please note that I require the issue submission instructions to be followed. For example, above when I say to use "one of two options" and you ignore that and use a 3rd option which wasn't in the instructions, I would not process your issue.
