### ISSUE TITLE
Gain Factor for AndroidLoudnessEnhancer is wrong

### ISSUE THREAD

**Issue by Chaphasilor** [ryanheise/just_audio#1089]
**Which API doesn't behave as documented, and how does it misbehave?**
https://pub.dev/documentation/just_audio/latest/just_audio/AndroidLoudnessEnhancer/setTargetGain.html
Docs state:  
> Sets the target gain to a value in **decibels**.

However, the value actually seems to be in 10 decibels.  
See implementation here:
https://github.com/ryanheise/just_audio/blob/3622d11f14d4191e4c1326c32c7a025941af40ec/just_audio/android/src/main/java/com/ryanheise/just_audio/AudioPlayer.java#L763-L766

The used factor is `1000`, whereas the Android documentation ([link](https://developer.android.com/reference/android/media/audiofx/LoudnessEnhancer)) states:  
> The maximum gain applied applied to the signal to process. It is expressed in **millibels (100mB = 1dB)** where 0mB corresponds to no amplification.

So the correct factor appears to be `100`

**Minimal reproduction project**
The example

**To Reproduce (i.e. user steps, not code)**
1. Apply and activate the AndroidAudioEnhancer effect
2. Lower the volume so that the playing track is fairly quiet (make sure it is *really low*! Otherwise you might damage your speakers...)
3. Now set the gain to 10, which should be equal to 10 dB and therefore seem about twice as loud
4. Get your eardrums blows out, since the audio is definitely more than twice as loud :D

**Error messages**

```
n/a
```

**Expected behavior**

The docs say the gain value is in decibels, so setting gain to `10.0` should result in 10 dB gain.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone 10
 - OS: Android 13

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.1)   
[√] Android Studio (version 2022.2)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.83.1)       
[√] Connected device (4 available) 
[√] Network resources
```

**Additional context**

I acknowledge that the unit "Millibel" is a bit confusing in this case, but this is because the base unit is **deci**bel, so 10 bel. The math does work out ^^

**Comment by ryanheise** [comment]
Thanks for spotting that. Unfortunately this would be a breaking change so it would have to go into the next major release which happens less often (so that I don't break apps that are already compensating for this). In the meantime you would need to compensate by passing in parameters adjusted by a factor of 10. Yes, I had apparently confused it with millidecibels.

I would be happy to accept a pull request if you are interested in contributing. This would need to be submitted to the `major` branch rather than the `minor` branch.

**Comment by Chaphasilor** [comment]
Sounds good. I've already implemented the workaround in Finamp, so the major release makes sense. For the PR, is there anything that I should update aside from the actual implementation? Maybe add a note in the docs that the behavior has been fixed or something? :)

**Comment by ryanheise** [comment]
No need to update the docs, but you can add a note to the CHANGELOG indicating the breaking change along with crediting your git username. I've written a checklist [here](https://github.com/ryanheise/just_audio/blob/minor/CONTRIBUTING.md#making-a-pull-request) for some guidance.
