### ISSUE TITLE
I was listening to music using the music software and when I called the play method, my music was interrupted

### ISSUE THREAD

**Issue by afskalsfk** [ryanheise/just_audio#1110]
**Is your feature request related to a problem? Please describe.**
I was listening to music using the music software and when I called the play method, my music was interrupted

**Describe the solution you'd like**
I was listening to music using the music software and when I called the play method, my music was interrupted
**Describe alternatives you've considered**
I was listening to music using the music software and when I called the play method, my music was interrupted

**Additional context**
I was listening to music using the music software and when I called the play method, my music was interrupted

**Comment by ryanheise** [comment]
This is not a feature request. It looks like a bug report. You need to use the other issue type for this where you submit the minimal reproduction project. Closing.
