### ISSUE TITLE
Player seek problem on chrome browser

### ISSUE THREAD

**Issue by amirrezaghabeli** [ryanheise/just_audio#1118]
**Which API doesn't behave as documented, and how does it misbehave?**
Player seek works fine in android and in firefox browser for web.but in web with chrome browser it doesnt work properly and cant seek music forward.

**Minimal reproduction project**
I couldnt find if the bug is in documnets or not.

**To Reproduce (i.e. user steps, not code)**
1. I run it on android it worked.
2. Play audio in web it starts playing.
3. Seek forward and it gets back to zero immediately in chrome only.

**Error messages**
No error is throwed.

**Expected behavior**
It must run without getting confused.

**Screenshots**
No screenshot can taken to show the problem.

**Desktop (please complete the following information):**

 Ubuntu 22.04.1 LTS
  Chrome

**Smartphone (please complete the following information):**
 - Pixel 6 api 30
 - Android

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.13.1, on Ubuntu 22.04.1 LTS 6.2.0-36-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from
      https://www.freedesktop.org/wiki/Software/pkg-config/
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Additional context**
I saw some issues like this on older issues but not a solution

**Comment by ryanheise** [comment]
I am closing this bug report as you should expect. Please also do not continue to spam issues that are invalid for the reasons already given to you.

**Comment by amirrezaghabeli** [comment]
why you close this?I didnt understand.my issues was not spam.it was just because it was my first time opening an issue and I didnt know how to do it properly.

**Comment by ryanheise** [comment]
That's why on your previous issues you were explained why your issue was closed. I don't really want to answer the question "why" if you ignored the reasons already explained to you on all of your previous issues.
