### ISSUE TITLE
[Android] seeking causes the player to play on with no sound but SeekBar still running

### ISSUE THREAD

**Issue by docaohuynh** [ryanheise/just_audio#1124]
**Which API doesn't behave as documented, and how does it misbehave?**
When seek to specific time, seekbar still running with no sound

**Minimal reproduction project**
Provide a link here using one of two options:
1. Using example in just_audio

**To Reproduce (i.e. user steps, not code)**
1. Play audio
2. Click seek
3. Seekbar still process with no sound

**Error messages**

```
No
```

**Expected behavior**
Audio play immediately or show loading state when audio not playing until it actually play

**Screenshots**

https://github.com/ryanheise/just_audio/assets/1791817/cec1485a-658e-4877-b0ab-4bfc78ec0031

**Smartphone (please complete the following information):**
 - Device: Samsung M21
 - OS: Android 12

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.4 22F66 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (4 available)
[✓] Network resources
```

**Comment by ryanheise** [comment]
> Using example in just_audio

I played your video but it doesn't sound like the example in just_audio. That is, you didn't actually provide me a way to reproduce this. It's likely related to the specific audio file you were playing.

**Comment by docaohuynh** [comment]
@ryanheise sorry I change to this audio  https://dl.dropboxusercontent.com/scl/fi/are39lb24ilkkrj8qdxe7/dictation.webm?rlkey=b9b5o1rt37g6lbklullrw8n9f&dl=0

**Comment by ryanheise** [comment]
Just checking but I assume you have read the trouble shooting section in the readme and this is something that is not already addressed there?

**Comment by docaohuynh** [comment]
I have read "Audio file formats/encodings" but don't find the way to address with this issue. I play audio from url source so can not convert to MP3 format

**Comment by ryanheise** [comment]
I asked if you had read the entire troubleshooting section, in which there is more covered than just file formats/encodings.

**Comment by docaohuynh** [comment]
I had read it again and still don't know where to address with this. I think it relate to this issue #1084

**Comment by ryanheise** [comment]
After you have read the troubleshooting, maybe you can share the relevant details regarding the file format and the server headers?

**Comment by docaohuynh** [comment]
I use audio with info
```
Input #0, matroska,webm, from 'dictation.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:01:00.36, start: -0.007000, bitrate: 117 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
```

I upload to dropbox server with response headers
```
Accept-Encoding:
identity,gzip
Accept-Ranges:
bytes
Cache-Control:
max-age=60
Content-Disposition:
inline; filename="dictation.webm"; filename*=UTF-8''dictation.webm
Content-Length:
888388
Content-Range:
bytes 0-888387/888388
Content-Security-Policy:
form-action 'none' ; report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-noscript ; script-src 'unsafe-inline' https://www.google-analytics.com
Content-Security-Policy:
report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-usercontent ; sandbox allow-forms allow-scripts allow-top-navigation allow-popups
Content-Type:
video/webm
```

**Comment by ryanheise** [comment]
Thank you. Since you are the one who uploaded the file to the server, can you explain why you couldn't upload it in a different format?

**Comment by docaohuynh** [comment]
Because in my app user can play any audio from their device

**Comment by ryanheise** [comment]
I have just tested the example after changing the URL to the one provided, but could not reproduce the issue. After seeking, it shows the buffering spinner exactly up until the audio starts playing again. I don't know if that means it is a device specific behaviour, do you see this behaviour on other phones or just this one?

**Comment by docaohuynh** [comment]
I tested on 3 devices and same error when seek to time seekbar running about 1-2s with no sound
- Samsung Galaxy m21 (Android 12)
- Galaxy Tab S6 lite (Android 13)
- Oppo F1s (Android 6)

I can add this code to test seek function
```
Row(
    children: [
      IconButton(
        icon: const Icon(Icons.place_rounded),
        onPressed: () {
          _player.seek(const Duration(seconds: 30));
        },
      ),
      IconButton(
        icon: const Icon(Icons.place_rounded),
        onPressed: () {
          _player.seek(const Duration(seconds: 20));
        },
      ),
      IconButton(
        icon: const Icon(Icons.place_rounded),
        onPressed: () {
          _player.seek(const Duration(seconds: 10));
        },
      ),
      IconButton(
        icon: const Icon(Icons.place_rounded),
        onPressed: () {
          _player.seek(const Duration(seconds: 40));
        },
      ),
    ],
  )
```

**Comment by docaohuynh** [comment]
I had try to add this code to seek function `player.setSeekParameters(SeekParameters.CLOSEST_SYNC);` it seem like fixed it fixed this issue but sometime it play wrong audio frame

AudioPlayer.java
```
int windowIndex = index != null ? index : player.getCurrentMediaItemIndex(); 
player.setSeekParameters(SeekParameters.CLOSEST_SYNC);
player.seekTo(windowIndex, position);
```

**Comment by ryanheise** [comment]
Regarding workarounds, you might also want to experiment with the buffering options. If all of your audio files are short like the one you linked to above, you could try to keep the whole file buffered in memory so that the buffering event that triggers this issue never happens.

**Comment by docaohuynh** [comment]
Tks @ryanheise your your help. I will find some way to convert to another format it just happened in some url so I close this issue
