### ISSUE TITLE
Attempting to play using mediaplayer after encountering an exception in exoPlayer

### ISSUE THREAD

**Issue by luhongalex** [ryanheise/just_audio#1129]
**I have encountered some M3U8 players that cannot be played using ExoPlayer**

The phenomenon of using HlsAudioSource: constantly loading.

Using ProgressiveAudioSource: Unexpected Source error occurred

**I have tried using mediaplayer and it can play normally**
Attempt to play using androidx.media.mediaplayer after exoPlayer throws an exception

![86331700214781_ pic](https://github.com/ryanheise/just_audio/assets/39117934/1ed33069-4012-408a-b341-457bc5c2b2b8)

**Comment by ryanheise** [comment]
Please stop spamming duplicate issues. You have been given instructions on what to do next, please read them.
