### ISSUE TITLE
Upgrade to just_audio 0.2.0 error

### ISSUE THREAD

**Issue by naguchennai** [ryanheise/just_audio#113]
`Because just_audio >=0.2.0 depends on path ^1.7.0 and every version of flutter_test from sdk depends on path 1.6.4, just_audio >=0.2.0 is incompatible with flutter_test from sdk.

So, because FLUTTER_APP depends on both just_audio ^0.2.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because FLUTTER_APP depends on both just_audio ^0.2.0 and flutter_test any from sdk, version solving failed.)
exit code 1`

Cont fix it

**Comment by naguchennai** [comment]
i also have same problem then i switched to flutter Channel dev, mod and update flutter .. then only i will work. i dont know why

**Comment by ryanheise** [comment]
Duplicate of #111
