### ISSUE TITLE
[Web] Audio playback does not work on mobile browsers on both iOS and Android

### ISSUE THREAD

**Issue by JanBeelte** [ryanheise/just_audio#1134]
**Which API doesn't behave as documented, and how does it misbehave?**
The following code works on desktop browsers (Chrome, Firefox, Safari) but does _**not**_ work on mobile browsers (neither Safari on iOS, nor Chrome on Android):
```
await widget.audioPlayer.setAsset("assets/sound.mp3");
widget.audioPlayer.play();
```

**Minimal reproduction project**
See above.

**To Reproduce (i.e. user steps, not code)**
1. Deploy the example to an online hoster (e.g. firebase)
2. Play an audio-file
3. No sound is played

**Error messages**
No error messages

**Expected behavior**
Audio should also play on mobile browsers.

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - Working on all tested plattforms.

**Smartphone (please complete the following information):**
 - Device: several iPhones and Android Phones
 - OS: several versions of iOS and Android

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.16.0)
```

**Additional context**
No additional context

**Comment by ryanheise** [comment]
I think there have been previous issues covering some other quirks with the way phone browsers work, and I did not find any way around that. For example, I think from memory that Safari did not report the correct states that just_audio depends on. Although what you're reporting relates to it not playing the audio at all. It seems like this may be about assets, in which case it may be about the browser's support of data URIs.

I am a bit confused by your bug report, however. You report "the example" but you also provide a snippet of sample code. Which is it? Because those are different.

**Comment by JanBeelte** [comment]
Thanks for the quick response!
I experience the issue with the inline code I provided.
My first issue was closed by the bot which is why I kept the example line because I was afraid the bot would close it again :-)

I agree it might be related to asset streaming, let me validate this assumption and get back to you!

**Comment by JanBeelte** [comment]
Unfortunately it seems to be the same behavior (Desktop Web works, mobile does not) when I pass a URL:
```
await widget.audioPlayer.setUrl("https://firebasestorage.googleapis.com/v0/b/asset_path.mp3");
widget.audioPlayer.play();
```
anything else I could do to help to narrow down the issue?

**Comment by ryanheise** [comment]
> My first issue was closed by the bot which is why I kept the example line because I was afraid the bot would close it again :-)

Hmm, I'm not sure why you find that amusing, I'm the one who wrote the instructions for submitting a minimal reproduction project, and I'm also the one who set up the bot to detect when people ignore those instructions to give a message that explains in detail WHY I require a minimal reproduction project, and also explains this:

> Note that because of this, it is even possible to trick the bot by including only the section headings, and then not providing the requested information under each heading. This is frowned upon, and the issue will be closed manually.)

What I'm doing next is in accordance to the last sentence above. (If you choose to open a 3rd issue, I hope that you will consider that it is physically difficult for me to use computers, and when people ignore those instructions thus making things more difficult for me, it is not fun.)

**Comment by JanBeelte** [comment]
I did not find anything amusing.
I just thought the two liner example is enough given that even if I provide a complete example project you still need to spin up a server somewhere to test the mobile browser.

**Comment by ryanheise** [comment]
It is not minimal in any sense for me to have to spin up a server. The "internet" allows you to provide the server and resource via a URL. Anyway, I see there is no point trying to re-explain the instructions and explain why I really really need what I say I need, when I have already explained it and those explanations have failed in the face of someone who is just going to ignore it. "Re-explaining" is itself extra work which has the same cost on my body as any other kind of unnecessary work, and so I guess I am forced to build a better bot to protect myself.
