### ISSUE TITLE
Windows error "MissingPluginException"

### ISSUE THREAD

**Issue by SuricateTrading** [ryanheise/just_audio#1154]
This code doesn't work on Windows:

```
final _player = AudioPlayer();
await _player.setUrl('...');
```

I'm not even playing the audio. Setting the url causes this error message:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13:5)
<asynchronous suspension>
#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1369:13)
<asynchronous suspension>
```

**Comment by ryanheise** [comment]
Ho @SuricateTrading , since just_audio supports different windows implementations, depending on which particular windows implementation you are using, it would be advised to submit your bug report to the GitHub page for that other package.

**Comment by SuricateTrading** [comment]
> Ho @SuricateTrading , since just_audio supports different windows implementations, depending on which particular windows implementation you are using, it would be advised to submit your bug report to the GitHub page for that other package.

Hi Ryan, I don't understand. Which other package?

**Comment by ryanheise** [comment]
Did you follow the Windows instructions in the README? If you did, it's pretty clear what the other packages are because I linked to them. If you didn't read the Windows instructions in the README, then you probably have no business submitting a bug report.
