### ISSUE TITLE
 Windows error "MissingPluginException"

### ISSUE THREAD

**Issue by SuricateTrading** [ryanheise/just_audio#1155]
I'm using all latest versions, but this code doesn't work on Windows:

```
final _player = AudioPlayer();
await _player.setUrl('...');
```

Error message:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13:5)
<asynchronous suspension>
#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1369:13)
<asynchronous suspension>
```

**Which API doesn't behave as documented, and how does it misbehave?**
**Minimal reproduction project**
**To Reproduce (i.e. user steps, not code)**
**Error messages**
**Expected behavior**
**Screenshots**
**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
**Flutter SDK version**
**Additional context**

**Comment by ryanheise** [comment]
Closing. Please read my comment on your previous bug report.
