### ISSUE TITLE
Customizing Notification Controls

### ISSUE THREAD

**Issue by Joe2316** [ryanheise/just_audio#1158]
I'm looking to customize the notification controls. Specifically, I'd like to disable the next and previous buttons in the notifications or hide the notifications entirely. how i fix it?

**Minimal reproduction project**
wait JustAudioBackground.init(
    androidNotificationChannelId: 'com.ryanheise.bg_demo.channel.audio',
    androidNotificationChannelName: 'Audio playback',
    androidNotificationOngoing: false,
  );

**To Reproduce (i.e. user steps, not code)**

```

**Expected behavior**



**Screenshots**


**Desktop (please complete the following information):**
 - Windows 10

**Smartphone (please complete the following information):**
Device: Pixel 4
OS: Android 13.0

**Flutter SDK version**
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.82.2)
[√] Connected device (4 available)
[√] Network resources
insert output of "flutter doctor" here
```

**Additional context**

**Comment by ryanheise** [comment]
Again? Please try not to create too many invalid issues, it makes it difficult for me to wade through.
