### ISSUE TITLE
Customizing Notification Controls

### ISSUE THREAD

**Issue by Joe2316** [ryanheise/just_audio#1159]
**Which API doesn't behave as documented, and how does it misbehave?**
I'm using just_audio_background package version 0.0.1-beta.11 for my flutter app and I'm seeking assistance in customizing the notification controls. Specifically, I want to either disable the next and previous buttons in the notifications or hide the notifications entirely. Thank you.

**Minimal reproduction project**
The example.

I attempted to use androidNotificationOngoing: false but the notifications are still showing.

await JustAudioBackground.init(
    androidNotificationChannelId: 'com.ryanheise.bg_demo.channel.audio',
    androidNotificationChannelName: 'Audio playback',
    androidNotificationOngoing: false,
  );

**To Reproduce (i.e. user steps, not code)**

**Error messages**
None

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: android 13 pixel 4
 - Windows10

**Flutter SDK version**
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22631.2506], locale en-NZ)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources
insert output of "flutter doctor" here
```

**Additional context**
Add any other context about the problem here.

**Comment by ryanheise** [comment]
:-1: This is now your third invalid issue. You clicked on "bug report" but what you submitted was not actually a bug report. I do not have time to deal with invalid issues, so please stop posting further issues. It is making it very difficult for me to get around to the valid issues submitted by other people.
