### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by gustavotroisi** [ryanheise/just_audio#116]
**To which pages does your suggestion apply?**

https://pub.dev/packages/just_audio#-example-tab-

**Quote the sentences(s) from the documentation to be improved (if any)**

I would like to implement player.play() automatically once a remote file is loaded

**Describe your suggestion**

Hello, is it possible to autoplay a remote audio source? How would be the procedure? many thanks

**Comment by ryanheise** [comment]
@gustavotroisi Can you please fill in the sections of the documentation request template?

**Comment by gustavotroisi** [comment]
Sorry @ryanheise , I tried to explain what I would like to achieve. Many thanks

**Comment by ryanheise** [comment]
The example tab isn't documentation. The documentation is via the link called "API reference". If you then click on the just_audio library, you can see the documentation per class. If you click on `AudioPlayer`, you can see the documentation for that class. Please read through it and tell me which method you would like more documentation on, and please quote the sentence which can be improved as well as your suggestion.
