### ISSUE TITLE
setTimer function for audio

### ISSUE THREAD

**Issue by jngapp** [ryanheise/just_audio#1162]
**Is your feature request related to a problem? Please describe.**
N/a

**Describe the solution you'd like**
Would be nice if this package can include a sleep timer. For example, add a new method called setTimer(Duration), and a getter method called getTimer for the AudioPlayer class, so that after defined Duration, the player will pause (even when the app is in background)

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by ryanheise** [comment]
You didn't think of any alternatives and you didn't describe a problem this would solve, but actually there is an alternative: You can just use a timer in Dart to call pause from within your app. I don't have any plans to add a convenience method within the plugin for this since it is very app specific and does not require plugin support.

**Comment by jngapp** [comment]
Thanks for the response @ryanheise.
I figured out a way to set it.
Here is my approach
**Define sharedpreference pref**
`
SharedPreferences prefs = await SharedPreferences.getInstance();
`

**Define getter/setter for timer**
`
  static Future<void> setTimer(DateTime? value)  async {
    value != null ? await prefs.setString('timer', value.toIso8601String()) : await prefs.setString('timer', '');
  }
`

`
  static DateTime? getTimer() {
    return prefs.getString('timer') != null ? DateTime.tryParse(prefs.getString('timer')!) : null;
  }
`
**To set timer:**
`
      await prefs .setTimer(DateTime.now().add(Duration(minutes: minutes)));
`

**To catch timer end**
`
      if(prefs .getTimer() != null && prefs .getTimer()!.compareTo(DateTime.now()) <= 0) {
        _audioHandler.pause();
        prefs .setTimer(null);
      }
`

Thanks anyway man. This is one of the best packages for Flutter. How do I donate to support you? Please let me know.
