### ISSUE TITLE
just_audio: using await results in playing entire audio before executing next line

### ISSUE THREAD

**Issue by ilimsource** [ryanheise/just_audio#1173]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
 "The example"
` Row(
mainAxisSize: MainAxisSize.max,
mainAxisAlignment: MainAxisAlignment.start,
children: [
Container(
width: 40,
height: 40,
decoration: BoxDecoration(
shape: BoxShape.circle,
border: Border.all(
color: FlutterFlowTheme.of(context)
.primary),
),
child: IconButton(
icon: player.playing
? const Icon(Icons.stop)
: const Icon(Icons.play_arrow),
iconSize: 20,
color: FlutterFlowTheme.of(context)
.secondaryText,
onPressed: () async {
if (player.playing) {
await player.stop();
print('stop current player');
} else {
for (final otherPlayer
in allAudioPlayersList) {
if (otherPlayer != player &&
otherPlayer.playing) {
await otherPlayer.stop();
print(
' Stop other players before starting');
}
}
String mediaFile =
alertItemsListItem.mediaFileName;
if (isiOS) {
mediaFile += '.mp3';
}
await player.setAsset(
'assets/audios/$mediaFile');
print('state updated before playing');
await player.play();
                                    print('after player started');
                                    setState(() {});
                                    print('after set state');
                                  }
                                },
                              ),
),`

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**
I want the IconButton to change after onPressed () async {}. To ensure the [player.play](http://player.play/)(); is started, I added an await statement. Once the button is pressed, I want the icon to change from [Icons.play](http://icons.play/)_arrow --> Icons.stop. so I have added a setState(() {});

I am expecting that once the player has started the setState will be executed.
However, the setState is not executed, until the entire audio is played. which blocks the setstate from executing and therefore my page is not updated to show Icons.stop.

I want the IconButton to change after onPressed () async {}. To ensure the [player.play](http://player.play/)(); is started, I added an await statement. Once the button is pressed, I want the icon to change from [Icons.play](http://icons.play/)_arrow --> Icons.stop. so I have added a setState(() {});

I am expecting that once the player has started the setState will be executed.
However, the setstate is not executed, until the entire audio is played. which blocks the setstate from executing and therefore my page is not updated to show Icons.stop.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 Pro Max
 - OS: [e.g. iOS8.1] 17.2.1

**Flutter SDK version**
```3.13.7
insert output of "flutter doctor" here
``` % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.2.1 23C71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
%

**Additional context**
Add any other context about the problem here.

**Comment by ryanheise** [comment]
Please don't post invalid issues without reading the instructions. I explained so in the bot message which you ignored.

Closing (as the bot message promised).
