### ISSUE TITLE
streaming non https radio links not working

### ISSUE THREAD

**Issue by iHamza7** [ryanheise/just_audio#1176]
**Which API doesn't behave as documented, and how does it misbehave?**
hi 👋
I am using just audio for one of my projects the project works fine with https links but not with non-https i am getting error.
https links are working but not the non-https 

**Minimal reproduction project**

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
 TYPE_SOURCE: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
```

**Expected behavior**
i want the issue to be solved

**Screenshots**
this is the error image
![Screenshot 2024-01-23 234138](https://github.com/ryanheise/just_audio/assets/69922336/4254fa0f-c49e-44e4-accd-09d8ff68dc7d)
and this is the recommended settings for non https links
![Screenshot 2024-01-23 234230](https://github.com/ryanheise/just_audio/assets/69922336/193744b2-928b-41a9-8a53-d251cc358383)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, ]

**Smartphone (please complete the following information):**
 - Device: [andriod]

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.85.2)
[√] Connected device (4 available)
[√] Network resources
```

**Additional context**
the recommendation for non https every thing done but still not working

**Comment by ryanheise** [comment]
Closing your issue as promised!

**Comment by iHamza7** [comment]
why the issue is closed??

**Comment by ryanheise** [comment]
Read the message left on your previous issue.

**Comment by iHamza7** [comment]
can you please give me the solution ?? please
instead of the format which i don't know

**Comment by ryanheise** [comment]
Given how quickly I closed this issue, it should be clear that I don't have time to use this GitHub page as a help service. I also don't have time to explain the instructions for how to submit a valid bug report. The instructions are already clear enough, and you just ignored the instructions, so you do not have my ear. i.e. If you are going to ignore me, I shall ignore you. Please do not post any further issues unless you will take the time to read and follow every instruction without ignoring anything, and I will lock this issue to avoid any more time wasted answering unnecessary questions.
