### ISSUE TITLE
Streaming non https links not working

### ISSUE THREAD

**Issue by iHamza7** [ryanheise/just_audio#1177]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.
setAudioSource is working fine with https links but not with the http link. the documentation and approach for using non-HTTPS links are being done in the project file .

**Minimal reproduction project**
Provide a link here using one of two options:

The project is private any details shall be shared below

**To Reproduce (i.e. user steps, not code)**
1. See screenshots
2. See error

**Error messages**

```
Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.

 TYPE_SOURCE: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
```

**Expected behavior**
should execute the non https links

**Screenshots**
![Screenshot 2024-01-23 234138](https://github.com/ryanheise/just_audio/assets/69922336/857c5666-8fa9-4341-9fa4-9b3623fc5491)
![Screenshot 2024-01-23 234230](https://github.com/ryanheise/just_audio/assets/69922336/46a25c4e-25e0-4fa3-903c-b5f800c9cc58)

**Desktop (please complete the following information):**
  - Not applicable
 

**Smartphone (please complete the following information):**
 - Device: Andriod emulator 11
 - OS: windows 10

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.85.2)
[√] Connected device (4 available)
[√] Network resources
```

**Additional context**

**Comment by ryanheise** [comment]
Closing again for the same reason. The reason this is being closed was explained in the very first comment reply in your first issue. Since you've done this 3 times in a row, please do not post any further issues. Thank you.
