### ISSUE TITLE
Hackers Using  just_audio script for hacking my shoutcast server

### ISSUE THREAD

**Issue by naguchennai** [ryanheise/just_audio#118]
Hackers Using  just_audio script for hacking my shoutcast server
They sent thousand of connection we got 5 server already  crashed and of data hacked  i already rises this problem but they deleted my post no response ...

**Comment by ryanheise** [comment]
Duplicate of #114

**Comment by nanthakumarfm** [comment]
Yes bro My icecast server recieved 500+ listerner from same ip same time i found that app from play store they using flutter with  just_audio

**Comment by ryanheise** [comment]
@nanthakumarfm what was the name of the app? Do you have a link?
