### ISSUE TITLE
http links are not streaming on iOS

### ISSUE THREAD

**Issue by Rochak-ES** [ryanheise/just_audio#1188]
**Which API doesn't behave as documented, and how does it misbehave?**
http links are not streaming on iOS when it do setAudioSource. 

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
   setAudioSource(
                        initialIndex: index,
                      AudioSource.uri(
                                  Uri.parse('http://streaming.softnep.net:8003/'),
                                  tag: MediaItem(
                                    id: (index - 1).toString(),
                                    album: element.radioName,
                                    title: element.radioName ?? '',
                                    artist: element.coverImage,
                                    extras: element.toJson(),
                                  ),
                                ),
                        ),
                      );

**Error messages**

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
flutter: (9999999) Error in handleMethodCall
```

**Expected behavior**
To stream the audio.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3.1 23D60 darwin-arm64, locale en-NP)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.1)
[✓] Connected device (4 available)            
    ! Error: Browsing on the local area network for Brijesh’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

**Additional context**

**Comment by ryanheise** [comment]
Closing as promised by the comment on your previous issue. Please don't make it a 3rd time...

The instructions for submission are clear. But it looks like you are ignoring them. The instructions are still in your bug report - you are supposed to follow what they say.
