### ISSUE TITLE
0.2.1 is incompatible with current Flutter stable version (1.17.4)

### ISSUE THREAD

**Issue by ened** [ryanheise/just_audio#119]
**Describe the bug**
Adding the 0.2.1 version in pubspec.yaml of a source project causes this error:

```
Because just_audio >=0.2.0 depends on path ^1.7.0 and every version of flutter_test from sdk depends on path 1.6.4, just_audio >=0.2.0 is incompatible with flutter_test from sdk.
```
**Expected behavior**
The plugin should be compatible with stable, dev, beta & master branch of Flutter.

**Flutter SDK version**
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)
```

**Comment by ryanheise** [comment]
Thanks, @ened . I tend to live on the beta branch in order to maintain web support for the plugin which isn't yet available on stable, so I didn't notice this.

The next stable release is still a few weeks away, so I have reverted the path dependency back to 1.6.4.

**Comment by ened** [comment]
Many thx!
