### ISSUE TITLE
Duration is null after await setUrl

### ISSUE THREAD

**Issue by maitycyrus** [ryanheise/just_audio#1192]
After loading an audio file the duration remains null for some time. Tested on Web with version [0.9.36]

```
Duration? duration = await audioPlayer.setUrl(audioUrl);

//Here duration is null
print(duration)

Future.delayed(Duration(milliseconds: 1000), () {
  //Here duration is not null
  print(duration)
});
```

**Comment by maitycyrus** [comment]
It's not closed. It's still a bug.

**Comment by ryanheise** [comment]
Why are you thumbing down the instructions which are telling you how to submit a valid bug report?

**Comment by maitycyrus** [comment]
Common. It's boiling down to 3 lines of code. What more do you need? A Docker-Image for reconstructing the problem? :D
