### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by coder-pour-changer-de-vie** [ryanheise/just_audio#120]
Hello, first of thanks for this plugin !

i'm playing Example but dealing with error, i think it is well catched so can you tell me if it can occured from just_audio ?

Erro and flutter proposal are 

"The offending widget is: StreamBuilder<FullAudioPlaybackState>
Build functions must never return null.

To return an empty space that causes the building widget to fill available room, return "Container()". To return an empty space that takes as little room as possible, return "Container(width: 0.0, height: 0.0)"."

To workaround, i added a check with "!snapshot.hasData"
----------------------------------------------------------------------------

child: StreamBuilder<FullAudioPlaybackState>(
          stream: _player.fullPlaybackStateStream,
          builder: (context, snapshot) {
            if (!snapshot.hasData) {
              
              return CircularProgressIndicator();
            }
            final fullState = snapshot.data;
            final state = fullState?.state;
            final buffering = fullState?.buffering;
            ...

But no effect :(

NB: just_audio return stream propoerty. As i understand StreamBuilder is null, but don't know if it a just_audio issue.

Nicolas.

**Comment by ryanheise** [comment]
To help manage incoming issues, can you please use the issue templates by clicking on the "New issue" button? Thanks.
