### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by coder-pour-changer-de-vie** [ryanheise/just_audio#121]
**Describe the bug**
i'm playing Example but dealing with error, i think it is well catched so can you tell me if it can occured from just_audio ?

Error is :
------------
"The offending widget is: StreamBuilder
Build functions must never return null.

Debug suggestion is :
-----------------------------
"To return an empty space that causes the building widget to fill available room, return "Container()". To return an empty space that takes as little room as possible, return "Container(width: 0.0, height: 0.0)"."
To workaround, i added a check with "!snapshot.hasData"

**Minimal reproduction project**
I'm using same code as Example present in the project

**To Reproduce**
Using Example file

**Error messages**

"The offending widget is: StreamBuilder
Build functions must never return null.

**Expected behavior**
Stream available for playing when clickon on related button

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Android nexus 3
 - OS: android 9

**Flutter SDK version**
1.17.4
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale fr_FR.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.46.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Additional context**

i added this workaround under StreamBuilder to handle possible null return, but with no success :(

"if (!snapshot.hasData) {
          return CircularProgressIndicator();
}

**Comment by ryanheise** [comment]
Thanks, I will look into it. Do you happen to have the error output?

**Comment by ryanheise** [comment]
I do recall fixing some rendering errors like this at some point in the past and haven't noticed issues with the latest version, so I'll close this. I can reopen if you find the error still exists.
