### ISSUE TITLE
HTTP headers not being set when running app in Chrome target

### ISSUE THREAD

**Issue by jvaleski** [ryanheise/just_audio#1216]
**Which API doesn't behave as documented, and how does it misbehave?**
neither setUrl(with headers) nor AudioPlayer(with userAgent) are setting headers in generated HTTP request.

**Minimal reproduction project**
Provide a link here using one of two options:
The example

```
// Setting the HTTP user agent
final player = AudioPlayer(
  userAgent: 'myradioapp/1.0 (Linux;Android 11) https://myradioapp.com',
  useProxyForRequestHeaders: true, // default
);

// Setting request headers
final duration = await player.setUrl('https://foo.com/bar.mp3',
    headers: {'header1': 'value1', 'header2': 'value2'});
```

**To Reproduce (i.e. user steps, not code)**
1. use the above code in an app in Android Studio
2. use the two functions above to a) set the user-agent and b) set additional headers
3. run the app with Chrome as the target
4. open inspector and view networking traffic via View->Developer->Developer Tools
5. invoke action necessary to execute the above code
6. inspect the HTTP request made setUrl, and notice that the User-Agent hasn't been set to the UA in the example code, nor are the additional headers present in the HTTP request.

**Error messages**
n/a

**Expected behavior**
expecting the additional headers to show up in the network inspection of the HTTP headers in Chrome

**Screenshots**
here's an example of the captured HTTP request traffic (note lacking headers/user-agent)
```
GET /some-file HTTP/1.1
Accept: */*
Accept-Encoding: identity;q=1, *;q=0
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: bucket.s3.amazonaws.com
Range: bytes=0-
Referer: http://localhost:57853/
Sec-Fetch-Dest: audio
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

**Desktop (please complete the following information):**
 - OS: MacOS + Sonoma 14.4.1
 - Browser: Chrome 123.0.6312.87 (Official Build) (arm64)

**Smartphone (please complete the following information):**
n/a

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.6)
[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
[✓] VS Code (version 1.87.2)
[✓] Network resources
• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment]
This is documented in the README.

![image](https://github.com/ryanheise/just_audio/assets/19899190/f9fd8f9a-291f-4c9a-b9ec-463cb32bc420)
