### ISSUE TITLE
Commandline / terminal sound playback

### ISSUE THREAD

**Issue by sneurlax** [ryanheise/just_audio#1224]
**Is your feature request related to a problem? Please describe.**
Yes, audio can't be played from the commandline on Linux.  See error:
```
Error: Dart library 'dart:ui' is not available on this platform.
```

**Describe the solution you'd like**
Be able to play audio on the commandline.

**Describe alternatives you've considered**
Forking either this or audioplayers for commandline linux sound playback.

**Additional context**
I just want sound control on the commandline, that's it.

**Comment by ryanheise** [comment]
Please submit a bug report rather than a feature request since you are reporting that it doesn't work on Linux.
