### ISSUE TITLE
often music item doesn't loop well if I am using multiple instances

### ISSUE THREAD

**Issue by RaghvindYadav** [ryanheise/just_audio#1227]
**Which API doesn't behave as documented, and how does it misbehave?**
I using this package to play a composition of music. A composition of music have 3 to 6 audio files which have different play length.
For example: A composition have 3 audio file piano, guitar and drum with play length of 30 sec, 80 sec and 1:20 mins respectively.
I want to play a composition for 30 minutes. So I will run all the audio files in loop. the problem is it loop before completing audio play length. i.e my drum's play length is 1:20 mins it replay after 60 seconds or 70 seconds. Not reaching to the end of music.

**Minimal reproduction project**

**To Reproduce (i.e. user steps, not code)**
No need any step, just use multiple audio instance and play 4 to 5 audio files in loop mode one at the same time. 

**Error messages**
Not getting any error.

**Expected behavior**
Music should loop after completing audio's play length.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: iPhone 13, iPhone 15 and in android device too
 - OS:  iOS17.4.1 , android 13

**Flutter SDK version**
Flutter version : 3.19.5

**Additional context**

**Comment by ryanheise** [comment]
> No need any step

But I stated in the instructions that I DO require reproduction steps and a reproduction project. You don't get to decide on your own requirements, unless you would like to fix the bug yourself. I am closing this as an invalid issue (your 3rd attempt at submitting an issue, without following the instructions.)
