### ISSUE TITLE
ConcatinatingAudioSource.clear() sets currentIndex to zero

### ISSUE THREAD

**Issue by innomatica** [ryanheise/just_audio#1228]
**Is your feature request related to a problem? Please describe.**
I use ConcatinatingAudioSource as playlist. When I call
```
await (player.source as ConcatinatingAudioSource).clear();
```
I expect `player.currentIndex` to be set to zero. But it remains unchanged, creating mismatch between `currentIndex` and `sequence`. 

**Describe the solution you'd like**
As described above, currentIndex is set to zero when the sequence is cleared.

**Describe alternatives you've considered**
For now I can do it by resetting the audio source
```
await player.setAudioSource(ConcatinatingAudioSource(children:[]));
```

**Additional context**
None

**Comment by ryanheise** [comment]
Is this a feature request or a bug?

**Comment by innomatica** [comment]
It is a feature request.

**Comment by ryanheise** [comment]
But aren't you saying that it produces unexpected behaviour? I don't understand how this would be a feature and not a bug. If it's a feature, it's also lower priority than a bug.

**Comment by innomatica** [comment]
I think it is not a bug in the sense that the behaviour is not against any part of the documentation. It is against your assumption or expectation.

**Comment by ryanheise** [comment]
The documentation states:

> The index of the current item, or null if either no audio source is set, or the current audio source has an empty sequence.

**Comment by innomatica** [comment]
You are right. I will close this and create a new issue
