### ISSUE TITLE
当音频正在播放时被拨打电话打断，如何恢复播放     How to resume playing audio when it is interrupted by a call

### ISSUE THREAD

**Issue by ZCHUANGJie** [ryanheise/just_audio#123]
当音频正在播放时被拨打电话打断，有什么方法可以监听被打断的原因，并且结束拨打电话时可以重新回复播放？

When the audio is interrupted by a call while it is playing, is there any way to monitor the reason for the interruption and resume playing when the call is over?

**Comment by ryanheise** [comment]
This is not a "bug". I will close this (but please read the FAQ to find your answer)
