### ISSUE TITLE
Audio Looping

### ISSUE THREAD

**Issue by fuzing** [ryanheise/just_audio#125]
I was just wondering if there is any plan to implement audio looping in the (near) future.   This is definitely a feature that I think many would find useful.

My particular use case requires this to be gapless - so if this was made available, that would be awesome.

Cheers, and thanks!

**Comment by ryanheise** [comment]
Hi @fuzing what platforms do you need this for?

**Comment by fuzing** [comment]
I need it for Android and IOS.  Sorry, I'd forgotten to be more specific.

Thanks for your assistance with this.

**Comment by ryanheise** [comment]
Do you need to loop a single track or a whole playlist, or both?

**Comment by fuzing** [comment]
For my application it's just a single track - I use looping to provide an endless ambient background track (jungle noises, sounds of a river, etc.), which is why gapless is important for my use case.

**Comment by ryanheise** [comment]
Hi @fuzing , looping is now supported in the media-source branch. Please see issue #131 for details and I will close this issue.

**Comment by ryanheise** [comment]
Duplicate of #131

**Comment by fuzing** [comment]
Amazing - thank you so very much for your assistance with this!
