### ISSUE TITLE
Track completes too eary

### ISSUE THREAD

**Issue by GoranSustekJr** [ryanheise/just_audio#1256]
**Which API doesn't behave as documented, and how does it misbehave?**
Player stops playing after exactly 2 minutes and 35 seconds on every track I play, if it is longer than 2 minutes and 35 seconds both on android and iOS phones, and on iOS simulator.

**Minimal reproduction project**

**To Reproduce (i.e. user steps, not code)**

**Error messages**
No error messages displayed.

**Expected behavior**
I expect the song to play until the end and then see it stop and then show "ProcessingState.completed".

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - iPhone, Android, iPhone simulator
 - OS: 17.5.0 , 13, 17.0.0

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.22.1, on Ubuntu 24.04 LTS 6.8.0-31-generic, locale en_US.UTF-8)
    • Flutter version 3.22.1 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (11 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/gsustek/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/157/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 18.1.3 (1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.3)
    • Android Studio at /snap/android-studio/157
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • SM A225F (mobile) • R58R91L6PWY • android-arm64  • Android 13 (API 33)
    • Linux (desktop)   • linux       • linux-x64      • Ubuntu 24.04 LTS 6.8.0-31-generic
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 125.0.6422.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Additional context**
I am playing tracks from my server. It plays and buffers to correct length but just stops every time at 2:35 if the track is longer that that. I tried with LockCachingAudio Source and AudioSource.uri. Both play but with said problem. Tried with and without audioLoadConfiguration.

**Comment by GoranSustekJr** [comment]
I have just downloaded few songs that are from my db and they are whole songs.

**Comment by ryanheise** [comment]
Note that this issue is closed.

**Comment by GoranSustekJr** [comment]
Why did you close it?

**Comment by ryanheise** [comment]
You want me to explain it again?

**Comment by GoranSustekJr** [comment]
I do not understand, this is the first time I opened an issue here. When did you explain it? Please explain again.

**Comment by ryanheise** [comment]
I explained in the instructions for submitting a bug report.

**Comment by GoranSustekJr** [comment]
I did not complete all sections?

**Comment by ryanheise** [comment]
Exactly - do you need me to explain which sections you decided to not complete, or do you already know which sections you decided to not complete?

**Comment by GoranSustekJr** [comment]
No, I am very sorry for waisting your time. :(
