### ISSUE TITLE
Compile WEB release plugin dosent work

### ISSUE THREAD

**Issue by natouralDS** [ryanheise/just_audio#1262]
**Which API doesn't behave as documented, and how does it misbehave?**
I can load and play an audio locally, when I test it in debug mode, but not when I compile it in release mode and upload the project to the server.

**Minimal reproduction project**
My code it's similar to tutorials example: https://suragch.medium.com/steaming-audio-in-flutter-with-just-audio-7435fcf672bf?sk=c7163e8496b914c9e0e5446ec6020f04

You can try if go to my page: https://caminaar.com/#/points
and select one point, and click in "view 3D model"
![Captura de pantalla 2024-06-05 a las 10 15 13](https://github.com/ryanheise/just_audio/assets/171024095/90411044-0053-4b93-92a8-2db2152f3d45)

**To Reproduce**
When I compile the web project in release mode the audio plugin does not work for me:
_flutter build web_
But when I compile the web project in this way it's works:
_flutter build web --profile --dart-define=Dart2jsOptimization=O0_

**Error messages**
_Uncaught
at Object.c (https://caminaar.com/main.dart.js:5152:19)
at https://caminaar.com/main.dart.js:65046:15
at ajk.a (https://caminaar.com/main.dart.js:6499:63)
at ajk.$2 (https://caminaar.com/main.dart.js:40541:14)
at aip.$1 (https://caminaar.com/main.dart.js:40535:21)
at agX.afO (https://caminaar.com/main.dart.js:41369:34)
at agX.Fz (https://caminaar.com/main.dart.js:41372:13)
at aeM.$0 (https://caminaar.com/main.dart.js:40888:11)
at Object.tV (https://caminaar.com/main.dart.js:6598:40)
at am.q7 (https://caminaar.com/main.dart.js:40823:3)_

**Expected behavior**

**Screenshots**
![Captura de pantalla 2024-06-05 a las 9 41 14](https://github.com/ryanheise/just_audio/assets/171024095/9ec09bab-c37c-4925-8e9f-8165fad407d4)

**Desktop:**
 - OS: MacOS 14.5
 - Browser: Chrome

**Smartphone:**
 - Device: iPhoneX
 - OS: iOS 17.5.1

**Flutter SDK version**
sdk: '>=3.3.4 <4.0.0'

**Additional context**
The audio file its in the same server as the project
What it's the difference between compilations?
Is there anything else I need to add?
Any idea?

**Comment by ryanheise** [comment]
As per the instructions, can you either fork "this" repo and make minimal changes, or else if the unmodified example in this repo already exhibits the bug then write "example". I do not accept other submissions, they must be minimal according to the steps given in the instructions.

**Comment by SzymonDziak** [comment]
Getting the same error

**Comment by ryanheise** [comment]
Read my previous comment for how to progress this issue. Saying "me too" doesn't move things forward.

**Comment by SzymonDziak** [comment]
> Read my previous comment for how to progress this issue. Saying "me too" doesn't move things forward.

your arrogance will cost you everything

**Comment by busslina** [comment]
> Saying "me too" doesn't move things forward.

It gives more info that indicates it's not just one person who has the problem. E.G. Max Verstappen say to RB engineers: "I'm feeling some weird vibrations on the 6th gear". Then Sergio Perez arrives and says: "Me too". Two words that can mean a lot of info.

> your arrogance will cost you everything

Maybe just a bad day.

I'm having the same problem (or close):
- Platform: Web
- Description: Working good when compiled in debug mode. Failing when compiled in release mode.
- Error I: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
- Error II: MissingPluginException(No implementation found for method disposeAllPlayers on channel com.ryanheise.just_audio.methods)

**Comment by ryanheise** [comment]
Closing the bug report since @natouralDS has not responded.

@busslina you are welcome to submit a new bug report "if" you provide all of the requested parts of the bug report.
