### ISSUE TITLE
Sound is not played on iOS 17.5.1 in background

### ISSUE THREAD

**Issue by mathieusachet** [ryanheise/just_audio#1263]
**Which API doesn't behave as documented, and how does it misbehave?**
It seems that the play() method does not work in the background in iOS 17.5.1.

**Minimal reproduction project**
Provide a link here using one of two options:
The example

**To Reproduce (i.e. user steps, not code)**
Launch a timer to play sound every 10 seconds.
On iOS 17.2.1, sound is played every 10 seconds when app is in background.
On iOS 17.5.1, sound is not played when app is in background

**Expected behavior**
Sound should be played on last iOS version

**Screenshots**

**Desktop (please complete the following information):**
 - OS : iOS 17.5.1

**Smartphone (please complete the following information):**
 - iPhone 15 pro max

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.0 23A344 darwin-arm64, locale fr-FR)
    • Flutter version 3.19.3 on channel stable at /Users/mathieu/fvm/versions/3.19.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (3 months ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mathieu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.13.0

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

```

**Comment by ryanheise** [comment]
> **To Reproduce (i.e. user steps, not code)**
> 
> Launch a timer to play sound every 10 seconds.

You literally did the opposite of the instructions for this section. I'm going to close this issue, and if you open a new one, please read through the instructions and documentation first before asking me to spend time on your issue.
