### ISSUE TITLE
Reduce delay when setUrl and add setAutomaticallyWaitsToMinimizeStalling capability on android

### ISSUE THREAD

**Issue by ariefwijaya** [ryanheise/just_audio#127]
**Is your feature request related to a problem? Please describe.**
I've got delay time after calling setUrl(..) before start play the audio.

**Describe the solution you'd like**
Currently, just_audio has setAutomaticallyWaitsToMinimizeStalling function to reduce the delay but only on ios. It will be nice if 
setAutomaticallyWaitsToMinimizeStalling also worked on android. So the delay time for setUrl will be reduced.

**Describe alternatives you've considered**
How about if we use hls ? can it reduce the delay time more ?

**Comment by ryanheise** [comment]
The latest release exposes all of androids options to control buffering/loading which is about as much as can be done, so I'll close now.
