### ISSUE TITLE
Playing Audio Cache support

### ISSUE THREAD

**Issue by ReaganRealones** [ryanheise/just_audio#128]
**Which API doesn't behave as documented, and how does it misbehave?**
While an online (remote) audio file is playing and maybe almost completed, calling `audioPlayer.seek()` to a past position seems to make another network request

**Expected behavior**
I expected that the playing file is cached into memory, so that while it's playing and may be reaching the end, seeking to a past position should work even without an internet connection since the file is in memory already.

**Flutter SDK version**
```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-UG)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.47.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by ryanheise** [comment]
Can you please complete all sections of the bug report template?

**Comment by AhmedNourJamalElDin** [comment]
This happens for me too.

@ReaganRealones can you complete all sectons, please?
