### ISSUE TITLE
Unhandled Exception: Loading interrupted 

### ISSUE THREAD

**Issue by kingrmb** [ryanheise/just_audio#1280]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
audio_service usage:
1- splash.dart page init Global_AudioHandler

    Global_AudioHandler = await AudioService.init(
      builder: () => AudioPlayerHandlerImpl(),
      config: const AudioServiceConfig(
        androidNotificationChannelId: 'com.ryanheise.myapp.channel.audio',
        androidNotificationChannelName: 'Audio playback',
        androidNotificationOngoing: true,
      ),
    );
2- music play page import Global_AudioHandler
3- then exception below, when i click next-music button, recovery normal

**Error messages**

```
I/ExoPlayerImpl(10130): Release d5dc1bf [ExoPlayerLib/2.18.7] [gold, 2312DRAABC, Xiaomi, 34] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
E/flutter (10130): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Loading interrupted
E/flutter (10130): #0      AudioPlayer._load (package:just_audio/just_audio.dart:874:11)
E/flutter (10130): <asynchronous suspension>
E/flutter (10130): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1494:28)
E/flutter (10130): <asynchronous suspension>
E/flutter (10130): #2      AudioPlayer.setAndroidAudioAttributes (package:just_audio/just_audio.dart:1188:46)
E/flutter (10130): <asynchronous suspension>
E/flutter (10130): 
I/ExoPlayerImpl(10130): Init dffaa53 [ExoPlayerLib/2.18.7] [gold, 2312DRAABC, Xiaomi, 34]

```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS: MacOS + 14.1
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1 23B74 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
```

**Additional context**

same to [https://github.com/ryanheise/just_audio/issues/861](https://github.com/ryanheise/just_audio/issues/url)
@srawlins @fullflash add

**Comment by kingrmb** [comment]
@ryanheise  thanks for time

**Comment by ryanheise** [comment]
Closing, since you have just spammed 3 identical issues without actually following the instructions in any of them, and this creates an unnecessary burden for me. The bot message in your previous two issues also explained that if you do what you did this time, I will be forced to close your issue manually (which is what I am forced to do right now.) If you are going to post a 4th identical issue, please don't do it unless you are going to read the instructions and follow the instructions.
