### ISSUE TITLE
play an audio url file with initial seek position

### ISSUE THREAD

**Issue by mohammadne** [ryanheise/just_audio#130]
in my case I have 2 url which periodically I should pause first audio and play second audio url from a certain position and vice versa. 

so my question is that how to play an audio url file with **initial** seek in the best way.
the current way do it is:
```
await play()
await pause()
await seek()
await play()
```

Thanks @ryanheise

**Comment by ryanheise** [comment]
Hi @mohammadne 

If you do `await player.setClip(...)` you set select a time range of audio to start and end at. Then, if you do `await player.play()` it will wait for that period of audio to completely play before returning.

**Comment by mohammadne** [comment]
yes.
that is what exactly I want.
Thanks.
