### ISSUE TITLE
[GETX] Info: _GetImpl Instance of '_GetImpl' runZonedGuarded: Loading interrupted

### ISSUE THREAD

**Issue by richanshah** [ryanheise/just_audio#1302]
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio using 0.9.39
**Minimal reproduction project**
1. when app started getting below issue from library
[GETX] Info: _GetImpl Instance of '_GetImpl' runZonedGuarded: Loading interrupted

**To Reproduce (i.e. user steps, not code)**
r

**Error messages**
PlayerInterruptedException: Loading interrupted
  File "just_audio.dart", line 879, col 11, in AudioPlayer._load
  File "<asynchronous suspension>"
  File "just_audio.dart", line 1501, col 28, in AudioPlayer._setPlatformActive.setPlatform
  File "<asynchronous suspension>"
  File "just_audio.dart", line 1195, col 46, in AudioPlayer.setAndroidAudioAttributes

**Expected behavior**
need explanation on this error log

**Screenshots**

Flutter (Channel stable, 3.19.6, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)

**Comment by ryanheise** [comment]
Closing invalid bug report since it does not follow the instructions.
