### ISSUE TITLE
Audio stopping after 20 minutes on certain android phones

### ISSUE THREAD

**Issue by jjb182** [ryanheise/just_audio#132]
**Which API doesn't behave as documented, and how does it misbehave?**
On some phones (Galaxy S3 running 4.4.2 and an S9 with newer software) ... audio stops after 20 minutes of run time with the screen off.  On most phones and emulators this does not happen and audio plays indefinitely.

Any ideas?

again, intermittent and dependent on phone presumably.

1. playing just_audio for a local asset
2. close screen
3. wait...
4. 20 minutes and it stops. It restarts once the screen is turned back on and the app is brought to the foreground

**Expected behavior**
On most phone it play background audio perfectly and until stopped by the user.

**Smartphone (please complete the following information):**
only noticed on Galaxy S3 running 4.4.2 and an S9 with newer software--so far

**Flutter SDK version**
1.17.0

**Comment by ryanheise** [comment]
Hi @jjb182 can you please complete all sections of the bug report, and do not delete any sections? Thanks.

**Comment by jjb182** [comment]
Hi Ryan, I added the sdk version 1.17.0, and I thought that I'd note that it is not one continuous file.
I am replaying the same file about every 2.5 seconds.  And when I come back into the Flutter app after the audio failure the whole interface has to update--which is likely for flutter but it seems sluggish.  This might not be a just_audio issue, but some sort of background task issue.  I'll play a long file (30 minute file) with just_audio today on these devices with issues to see if it still fails.

**Comment by ryanheise** [comment]
You are still missing many sections of the bug report. Please go back to the original report and fill in every section (you know where to find the bug report template). Thanks.

**Comment by jjb182** [comment]
Hi Ryan, how do I delete this whole thread.
It turns out that it is definitely not a just_audio issue.  Just_audio works fine when I'm just playing audio in the background--for extended periods of time with one file. 

On my app, I'm doing a lot of background stuff and changing audio files every few minutes, and the background processing is failing which is then no longer calling just_audio to play stuff.

**Comment by ryanheise** [comment]
I see, you may want to look at my other plugin audio_service regarding background audio. I'll close this issue.
