### ISSUE TITLE
conflict with cached_network_image and file_picker

### ISSUE THREAD

**Issue by ghost** [ryanheise/just_audio#1322]
**Which API doesn't behave as documented, and how does it misbehave?**
Dependencies

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
1. try to install just_audio with cached_network_image and file_picker (both latest versions)

**Error messages**

```
Because no versions of just_audio match >0.9.39 <0.10.0 and just_audio 0.9.39 depends on just_audio_web ^0.4.11,
  just_audio ^0.9.39 requires just_audio_web ^0.4.11.
And because no versions of just_audio_web match >0.4.11 <0.5.0, just_audio ^0.9.39 requires just_audio_web 0.4.11.
And because just_audio_web 0.4.11 depends on web >=0.3.0 <0.6.0 and file_picker >=8.1.0 depends on web ^1.0.0, just_audio
  ^0.9.39 is incompatible with file_picker >=8.1.0.
So, because test_project depends on both file_picker ^8.1.2 and just_audio ^0.9.39, version solving failed.


Because no versions of just_audio match >0.9.39 <0.10.0 and just_audio 0.9.39 depends on just_audio_web ^0.4.11,
  just_audio ^0.9.39 requires just_audio_web ^0.4.11.
And because no versions of just_audio_web match >0.4.11 <0.5.0 and just_audio_web 0.4.11 depends on web >=0.3.0 <0.6.0,
  just_audio ^0.9.39 requires web >=0.3.0 <0.6.0.
And because cached_network_image >=3.4.1 depends on cached_network_image_web ^1.3.1 which depends on web ^1.0.0,
  just_audio ^0.9.39 is incompatible with cached_network_image >=3.4.1.
So, because test_project depends on both cached_network_image ^3.4.1 and just_audio ^0.9.39, version solving failed.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
3.24.1
```

**Additional context**

**Comment by ryanheise** [comment]
See #1311 for information about the fix.
