### ISSUE TITLE
Missing purpose string in Info.plist - “Runner.app” bundle should contain a NSMicrophoneUsageDescription

### ISSUE THREAD

**Issue by Jeyanthinath** [ryanheise/just_audio#1323]
**Which API doesn't behave as documented, and how does it misbehave?**
Removing Microphone usage , when compiling the app to app store

**To Reproduce (i.e. user steps, not code)**
1. Use Just Audio Plugin
2. Build an app and upload to Apple store
3. Get Alert from App Store saying "you need to add purpose flag for `NSMicrophoneUsageDescription` 

**Expected behavior**

After adding the audio session flag = 0 , the error should not trigger

**Screenshots**
![image](https://github.com/user-attachments/assets/ef43981f-5d4c-49e6-bc66-a71a75875ca2)

**Smartphone (please complete the following information):**
 - OS: IoS

**Flutter SDK version**
```
Flutter 3.24.1

just_audio: ^0.9.38
```

**Additional context**
My Pod File
``` 

# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
      
    # Remove audio code from just audio
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'AUDIO_SESSION_MICROPHONE=0'
        ]
      end

    end
end

````

**Comment by Jeyanthinath** [comment]
updated the sections

**Comment by ryanheise** [comment]
N/A? You're not going to be one of those people who argues with me about why you are right to skip sections and disrespect my instructions are you? If so, please don't. It only wastes both of our time.

**Comment by Jeyanthinath** [comment]
Hey @ryanheise , update the code above, this is the only place in my project I am using the just audio.

I hope this should be enough for you to debug the issue.

**Comment by ryanheise** [comment]
I've locked this conversation since it is only going to take up time for me to keep asking you to do things that were already explained in the instructions. If you would like to submit a valid issue, please open a new issue and read the instructions carefully before deleting them.
