### ISSUE TITLE
Null Exception

### ISSUE THREAD

**Issue by otangid** [ryanheise/just_audio#1352]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
W/System.err(15459): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.source.ConcatenatingMediaSource.addMediaSources(int, java.util.Collection, android.os.Handler, java.lang.Runnable)' on a null object reference
W/System.err(15459): 	at com.ryanheise.just_audio.AudioPlayer.onMethodCall(AudioPlayer.java:475)
W/System.err(15459): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/System.err(15459): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
W/System.err(15459): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err(15459): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
W/System.err(15459): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(15459): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(15459): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(15459): 	at android.os.Looper.loop(Looper.java:288)
W/System.err(15459): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
W/System.err(15459): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15459): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err(15459): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Expected behavior**
Error when add mediaitem to ConcatenatingMediaSource

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Emulator x86_64
 - OS: Android 12

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 6.8.0-45-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.


Note: Android Studio is installed
```

**Additional context**
Can't initialize mediaitem

**Comment by otangid** [comment]
is there no solution? or is my information incomplete? please help

**Comment by ryanheise** [comment]
> is my information incomplete?

Of course it is incomplete. Just look at your form. The instructions for what you need to complete are STILL THERE and not yet completed:

> **Which API doesn't behave as documented, and how does it misbehave?** Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.
> 
> **Minimal reproduction project** Provide a link here using one of two options:
> 
>     1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
> 
>     2. If the unmodified official example already reproduces the bug, just write "The example".
> 
> 
> **To Reproduce (i.e. user steps, not code)** Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error

And so on. I will eventually delete this issue in my next pass through, and if you would like to submit another bug report, please complete it first.
