### ISSUE TITLE
finding out if a playlist has reached its end

### ISSUE THREAD

**Issue by mohammadamir98** [ryanheise/just_audio#140]
Hi @ryanheise 

**I have a ```ClippingAudioSource```, but I want to know if there is a way to notice when my playlist has reached its end?**

**Comment by ryanheise** [comment]
Hi @mohammadamir98 

You unfortunately deleted all sections of the bug report. I can't process your report until you fill it in properly.

**Comment by ryanheise** [comment]
Hi @mohammadamir98

You unfortunately deleted all sections of the documentation request. I can't process your request until you fill in the form completely.

**Comment by ryanheise** [comment]
I'm going to close this since you have still deleted all sections of the bug report. Please open a new issue, and this time please don't delete the required sections, thank you.
