### ISSUE TITLE
https still not working on iOS

### ISSUE THREAD

**Issue by lawkeen** [ryanheise/just_audio#148]
Hi, will appreciate any help, wrote this at my Info.plist, but http urls still not working at iPhone emulator
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsArbitraryLoadsForMedia</key>
    <true/>
</dict>

Platform:
macOS Catalina 10.15.6

Error-message:
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(-11800, The operation could not be completed, null)

Also getting an error then exiting the screen or doing hot reload 
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Bad state: You cannot close the subject while items are being added from addStream
#0      Subject.close (package:rxdart/src/subjects/subject.dart:152:7)
#1      AudioPlayer.dispose (package:just_audio/just_audio.dart:611:30)

Using an example code.

**Comment by ryanheise** [comment]
Hi @lawkeen , you can remove `NSAllowsArbitraryLoadsForMedia` and it should work.
