### ISSUE TITLE
Bug: Audio glitches on play/stop on Android

### ISSUE THREAD

**Issue by ryanheise** [ryanheise/just_audio#16]
The glitch on play is a matter of the initial data coming out of `MediaExtractor` being a bit funky. I might need to grab the extractors from ExoPlayer.

**Comment by ryanheise** [comment]
This is now resolved by #19 .

**Comment by rohansohonee** [comment]
@ryanheise 
There is still a glitch when running latest commit with exoplayer:

``` dart
audioPlayer.play();
await audioPlayer.seek(Duration(milliseconds: position);
```

I am trying to start playing the audio file from a particular position, but the audio glitches and then continues playing from the specified position. There is a slight, but noticeable glitch. This glitch causes an unpleasant cross fading of audio. It is not transitioning smoothly.

**Comment by ryanheise** [comment]
What if you seek before playing?

**Comment by rohansohonee** [comment]
Same thing happens.
Calling play() always causes a very minor glitch but it's noticeable when cross fading audio.

**Comment by ryanheise** [comment]
I don't know if there's anything I can do about that since it now appears to be within ExoPlayer.

**Comment by rohansohonee** [comment]
How do I cross fade between tracks then??
I will try to figure it out.
