### ISSUE TITLE
Exoplayer pitch and skipSilence

### ISSUE THREAD

**Issue by subhash279** [ryanheise/just_audio#161]
Hi, Great work on the plugin.

**Is your feature request related to a problem? Please describe.**
Exoplayer has option to skipSilence and modify pitch. Is it possible to add them in this plugin.

**Describe the solution you'd like**
Add exoplayer skipSilence and pitch parameters.

**Describe alternatives you've considered**
None

**Additional context**
I am not sure if modifying the pitch will create a voume boost effect(Not much of an audio expert). Can you please let me know if you have an idea on this.

**Comment by ryanheise** [comment]
Hi @subhash279 , I believe ExoPlayer uses sonic for both pitch and speed changing, and this algorithm shouldn't affect the volume. So this in theory should be a simple Android-only feature to add.

However, I should also mention it may be a while before I personally get around to this due to the long list of issues I have to get through, so contributions via PRs are also be welcome.

**Comment by subhash279** [comment]
@ryanheise thanks for the clarification. I will submit a PR for skipSilence. It should be reasonably straightforward. 

Just out of curiosity, do you know if volume boost feature, the one in most podcast apps, can be implemented in exo player? I couldn't find much documentation. If you can let me know how to do it, I can add a PR for that as well!

**Comment by ryanheise** [comment]
Thanks!

Regarding volume boost, I only vaguely recall reading about it, although I'm not sure if I read about it in the ExoPlayer docs or somewhere in the Android SDK documentation itself.

**Comment by stonega** [comment]
@subhash279  
https://developer.android.com/reference/android/media/audiofx/LoudnessEnhancer  
It can work with exoplayer.

**Comment by subhash279** [comment]
@stonega thanks for the link. I will try to see if I can implement it.

**Comment by ryanheise** [comment]
I'll close now that both features are implemented for exoplayer.
