### ISSUE TITLE
Player.durationStream not streaming on iOS.

### ISSUE THREAD

**Issue by GabrieleVolpato** [ryanheise/just_audio#162]
**Which API doesn't behave as documented, and how does it misbehave?**
Player.durationStream is not streaming anything. This seems to be happening only on iOS while using some specific mp3s.

**Minimal reproduction project**
Provide a link here using one of two options:
Just use the example project, using the following audio urls:

```
https://backend.app.hellobaddy.com/api/mobile/audio/8/file?locale=it&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzg0ZmY4NTgxMzlkNTQ1MWJkMzdlYjMwMjJjMjI5Y2FkMzE4ZGZlYjU2YWQxNDIzYzgxNDQzMTFjMjk0ODFlMjA4OTFmZTE5YTgxOGFkZDYiLCJpYXQiOjE1OTgwOTg2MTksIm5iZiI6MTU5ODA5ODYxOSwiZXhwIjoxNjI5NjM0NjE5LCJzdWIiOiIiLCJzY29wZXMiOltdfQ.ArZz-heWm2jHpk-k1q5h1wJlLxLYl5HulqMBoGM_EpIRr_iImmktQeMBYtaBDRPL5TpTS5sM9zttIhGS8eycFgmZftqwBEXAbooEdkSB3FBnCusnD2-7xj1VRPqiY8Bnko2EtzKCwqYomNKLb4DH2rIwK6IvjM31TqmMkjPe8Sa8wiqegtLNeZhz4JK7jAJ56wfxkJ-qKneOl7g1sIpHg8QKLaYY-i2UzL-kOKXwCsdTuJbYxOFVtJrUmCqPaAAofDGlKGbDncwBHT5F_RK6KF-HYb00SPFWuaH5p5BN-FB4EgS_iP3gKF-BA03OrcxaB1jnm9XldIYL94nwc3_ct36ycsSui8LoCLILHf26LB_79coOKMpH6_C6yU1tvEvtTl98krguQt1cqqoIkYQnFnoi6ZCB53y0CLgD7WKicOiaoX8uxY26La519u0WIk0HduqH2b47lLHHxKH0Jx3N_f97r3XCJrfjhUdHwi4hNlNp5_C-lQnXgYtjBfIqyu0MppHDoiJIaC_wmUMfiISXFVLHSx0nosG2v1gWrOntn20QkJyNLexnPreuLfCZuvW1dhAB7I84IDotmmI_sohIvP6_P9d8OYHAJscjA-tfjPIeeZU0e2iCHCBlTUaA0wPWHMdmjI2azrFt7CwV0vv-WXmEPMgRLi7_3cCF1Fg5PSg

https://backend.app.hellobaddy.com/api/mobile/audio/11/file?locale=it&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzg0ZmY4NTgxMzlkNTQ1MWJkMzdlYjMwMjJjMjI5Y2FkMzE4ZGZlYjU2YWQxNDIzYzgxNDQzMTFjMjk0ODFlMjA4OTFmZTE5YTgxOGFkZDYiLCJpYXQiOjE1OTgwOTg2MTksIm5iZiI6MTU5ODA5ODYxOSwiZXhwIjoxNjI5NjM0NjE5LCJzdWIiOiIiLCJzY29wZXMiOltdfQ.ArZz-heWm2jHpk-k1q5h1wJlLxLYl5HulqMBoGM_EpIRr_iImmktQeMBYtaBDRPL5TpTS5sM9zttIhGS8eycFgmZftqwBEXAbooEdkSB3FBnCusnD2-7xj1VRPqiY8Bnko2EtzKCwqYomNKLb4DH2rIwK6IvjM31TqmMkjPe8Sa8wiqegtLNeZhz4JK7jAJ56wfxkJ-qKneOl7g1sIpHg8QKLaYY-i2UzL-kOKXwCsdTuJbYxOFVtJrUmCqPaAAofDGlKGbDncwBHT5F_RK6KF-HYb00SPFWuaH5p5BN-FB4EgS_iP3gKF-BA03OrcxaB1jnm9XldIYL94nwc3_ct36ycsSui8LoCLILHf26LB_79coOKMpH6_C6yU1tvEvtTl98krguQt1cqqoIkYQnFnoi6ZCB53y0CLgD7WKicOiaoX8uxY26La519u0WIk0HduqH2b47lLHHxKH0Jx3N_f97r3XCJrfjhUdHwi4hNlNp5_C-lQnXgYtjBfIqyu0MppHDoiJIaC_wmUMfiISXFVLHSx0nosG2v1gWrOntn20QkJyNLexnPreuLfCZuvW1dhAB7I84IDotmmI_sohIvP6_P9d8OYHAJscjA-tfjPIeeZU0e2iCHCBlTUaA0wPWHMdmjI2azrFt7CwV0vv-WXmEPMgRLi7_3cCF1Fg5PSg
```

**To Reproduce (i.e. user steps, not code)**
Reproduce the former files on an iOS device or simulator and you will see the seekbar stuck at 0.

**Error messages**
There is no error message.

**Expected behavior**
I expect to receive data from the duration stream.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.6.1

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] VS Code (version 1.47.3)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
```

**Additional context**
Everything is working correctly on Android devices.

**Comment by ryanheise** [comment]
Hi @GabrieleVolpato 

I tried copying the MP3 file to my own server and it was able to work fine, so I suspect there are some response headers that you can play around with to get iOS to get it to work. Here were the headers from the URL you provided:

```
HTTP/2 200 
server: nginx
content-type: audio/mpeg
content-length: 2346763
content-disposition: attachment; filename=8_it.mp3
cache-control: no-cache, private
date: Fri, 28 Aug 2020 02:41:42 GMT
x-ratelimit-limit: 60
x-ratelimit-remaining: 59
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
via: 1.1 google
alt-svc: clear
```

Possibly the rate limit is preventing iOS from downloading the entire media file and that in turn is preventing iOS from determining the duration of the audio.

**Comment by GabrieleVolpato** [comment]
I don't think this is rate limit related (you can see you still have 59 requests left here), or it wouldn't work on Android too.
I'm going to look into the server application after this weekend, and I'll try to tweak some response headers to see if anything changes.

I'll let you know as soon as I find something, thank you again for your time!

**Comment by ryanheise** [comment]
Let me know how it goes. There are various similar issues I have heard of before on iOS, one of them being the importance of having a ".mp3" extension in the path, so that's something you can also try (as opposed to using a content-disposition header). Aside from headers, one other thing to play around with is the HTTP protocol version. iOS is a black box, so it could be any of these things or some combination of them that it doesn't like.

Reading up on the purpose of the rate limit headers, I see what you mean, that is certainly not it.

**Comment by GabrieleVolpato** [comment]
I took some time to understand what's going on here and I think I got it: iOS, as well as Safari, requires the webserver to accept byte-range requests to undesrtand the duration. [Apple documentation](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6)
This is a problem for me because audio files are hosted on Google Cloud Storage and my server has to download them for every range request, but it's not a problem of this package, so you can feel free to close this issue.

Sadly, I don't know much about iOS yet, so I don't know if it's possible to guess the duration in some other way.

**Comment by ryanheise** [comment]
That's very interesting, thank you for sharing that research! I think numerous people have run into issues configuring the web server to satisfy iOS and this sheds some light on the mystery.

As for what options are available on the iOS side rather than the server side, I suspect any practical workaround to the limitations of AVPlayer would involve significant work, although one easy workaround that might not be practical is to actually download the file from the server first, and then just play it locally. I think there are some libraries that attempt to provide an alternative to AVPlayer, but it is certainly not on my short term todo list. So if downloading the file first doesn't sound practical, your best bet in the short term may be to tackle the server side issues.
