### ISSUE TITLE
Exoplayer init multiple times ?

### ISSUE THREAD

**Issue by ashishfeels** [ryanheise/just_audio#166]
**Which API doesn't behave as documented, and how does it misbehave?**
not known

**Minimal reproduction project**
https://github.com/ashishfeels/radio_bharat/tree/test-just_audio

**To Reproduce (i.e. user steps, not code)**
I just implemented the audio_session & package after upgrading audio_service

**Error messages**

```
I/ExoPlayerImpl(11716): Init bff6ae6 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 236c827 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 7794ad4 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 769a47d [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init dc74f72 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init c3dbfc3 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init a8a4040 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init df10b79 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 9b6f0be [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 132951f [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init f3206c [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init aede635 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 56d5aca [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init a3b0b1 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init f6e5996 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 6ef1104 [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
I/ExoPlayerImpl(11716): Init 811a6ed [ExoPlayerLib/2.11.7] [coral, Pixel 4 XL, Google, 29]
```

**Expected behavior**
Just wanted to know if exoplayer is created multiple times or its just normal.
**Screenshots**
NA
**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
[[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_IN)
    • Flutter version 1.20.2 at /home/ashish/flutter_linux/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/ashish/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/ashish/Android/Sdk
    • Java binary at: /home/ashish/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/ashish/Downloads/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Pixel 4 XL (mobile) • 75009d9e • android-arm64 • Android 10 (API 29)

• No issues found!

```

**Additional context**
NA

**Comment by ryanheise** [comment]
Let me know once you've filled in the report so that I get notified.

**Comment by ashishfeels** [comment]
@ryanheise updated with my test branch have  a look at it.

**Comment by ryanheise** [comment]
Can you fill in the whole report?

Try to explain why this is a bug, and also fix the smartphone information since surely you can't be dealing with an ExoPlayer log on iOS?

**Comment by ashishfeels** [comment]
@ryanheise  i was just trying to know if its a bug ? like before updating and without audio_session this was not there. that's why i thought of asking you. if it is normal we can close this. also updated the smartphone inofrmation.

**Comment by stonega** [comment]
@ashishfeels  No, it is not a bug, you can try to run example app on your device, I believe it only init once.  Also understand that you need to follow the report guide, as it is not a duty for the developer to answer the question.

**Comment by ashishfeels** [comment]
yeah completely agreed with you @stonega i am going through the example app now. Thanks.

**Comment by ashishfeels** [comment]
@stonega @ryanheise  just a suggestion can we make a discord channel for just_audio support so that dumb questions like this one can be sorted out there ? i hope you guys consider this.

**Comment by ryanheise** [comment]
My priority is to improve the plugin and its documentation, and this GitHub issues page is intended for contributors to help to that end by contributing bug reports, feature requests, documentation requests and pull requests. While I don't offer support personally, community support is available on StackOverflow, they have a pretty reasonable "dumb question" filter, too. I have provided a link to both StackOverflow and Gitter in the "New issue" page.

**Comment by ashishfeels** [comment]
gotcha closing this now. as its not a bug.
