### ISSUE TITLE
onComplete event not fired if there is no UI

### ISSUE THREAD

**Issue by subhash279** [ryanheise/just_audio#168]
Hi, Just looking at the code, I think if there is no dart UI, onComplete event for a specific track will not be fired because I think you would need a headless service for that. Can you please correct me if I am wrong.
I also checked the audio_service plugin and i am not sure if this is possible to listen to a track complete event. Again pls let me know if i am wrong.

**Is your feature request related to a problem? Please describe.**
onComplete event when there is no UI.

**Describe the solution you'd like**
Use a headless service to fire onComplete event or if there is a way to this through audio_service plugin.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ryanheise** [comment]
This package will not provide a service. I have created audio_service for that. It provides what you need.
