### ISSUE TITLE
Just audio 0.0.4 not working with m3u8 !!!!!!!!!!

### ISSUE THREAD

**Issue by cnttechio** [ryanheise/just_audio#17]
Hi @ryanheise 

The newest version, it's not working fine with type m3u8, but the old version 0.0.2 working well. 
Can you help me fix it ?

**Comment by ryanheise** [comment]
@cnttechio I'm not clear on the exact nature of the issue, such as whether this is on Android or iOS, and what exact error was reported in the logs. Can you share details to help me to investigate?

**Comment by ryanheise** [comment]
I have modified the implementation to use ExoPlayer including whatever its default codec support is. Can you try the latest commit and let me know how it goes?

**Comment by cnttechio** [comment]
hi @ryanheise,

I have just clone source from git and run your example with my change file mp3 to m3u8 but it's not working.

My errors:

> E/flutter ( 9537): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Illegal state: Can call stop only from playing/paused/stopped/completed states (connecting), null, null)
E/flutter ( 9537): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter ( 9537): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:321
E/flutter ( 9537): <asynchronous suspension>
E/flutter ( 9537): #2      AudioPlayer._invokeMethod 
package:just_audio/just_audio.dart:269
E/flutter ( 9537): <asynchronous suspension>
E/flutter ( 9537): #3      AudioPlayer.stop 
package:just_audio/just_audio.dart:229
E/flutter ( 9537): #4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
E/flutter ( 9537): #5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
E/flutter ( 9537): #6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter ( 9537): #7      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:486
E/flutter ( 9537): #8      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:264
E/flutter ( 9537): #9      BaseTapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:199
E/flutter ( 9537): #10     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:467

**Comment by ryanheise** [comment]
I've just added some code to hopefully support m3u8 files if they have a `.m3u8` extension. Can you try?

**Comment by cnttechio** [comment]
Amazing, It's working fine on android, so I will integrate into my app and report to you if I have some issues.
Thank @ryanheise  very much & happy new year.

**Comment by cnttechio** [comment]
hi @ryanheise,
I have set the URL file with a token on query string and just audio not working.
Example: 
`_player.setUrl('https://domain.com/abc.m3u8?token=tokenUser')`
Can you show me how to fix it?

**Comment by ryanheise** [comment]
The way I implemented it was to check if the URL ends with `.m3u8` but I see I should factor in the query string. Let me see what I can do.

**Comment by cnttechio** [comment]
Thank you, I'm waiting for you.

**Comment by ryanheise** [comment]
Just committed.

**Comment by cnttechio** [comment]
Great !, it's working fine.
Thank you.

**Comment by ryanheise** [comment]
Thanks for confirming :-)
