### ISSUE TITLE
When complete playing should playingStream emit false

### ISSUE THREAD

**Issue by dfdgsdfg** [ryanheise/just_audio#171]
**Which API doesn't behave as documented, and how does it misbehave?**
When complete playing should `playingStream` emit false

**Minimal reproduction project**
Seems `_playingSubject.add(isPlaying)` only call on user interaction.

**To Reproduce (i.e. user steps, not code)**
1. Play. `playing` and `playingStrean` emit `true`.
2. Playing finished. But `playing` and `playingStream` is still `true`.

**Error messages**
misbehave

**Expected behavior**
When complete playing should `playingStream` emit false

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - OS: Android

**Flutter SDK version**
1.20.2

**Additional context**
N/A

**Comment by ryanheise** [comment]
Closing as not a bug. This is behaving exactly as documented:

https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/play.html

**Comment by dfdgsdfg** [comment]
Then, if I want to know to sound play or not, I have to combine two streams which are playingStream true event and processingStateStream complete event?

**Comment by dfdgsdfg** [comment]
Oh. I can listen processingStateStream and handle stop() method for playingStream.
Got it. Thanks.
