### ISSUE TITLE
Apple Testflight rejection - Needs info.plist NSMicrophoneUsageDescription setting.

### ISSUE THREAD

**Issue by tnaseem** [ryanheise/just_audio#179]
just_audio 0.4.1 on iOS.

I deployed my app to Testflight, and got this rejection email from Apple:

> **ITMS-90683: Missing Purpose String in Info.plist** - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a _NSMicrophoneUsageDescription_ key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Any way to get around this? I'm not using any recording ability, so don't need the microphone. Just playing back audio.

**Comment by BringTheChill** [comment]
just add that on your Info.plist

```
<key>NSMicrophoneUsageDescription</key>
<string>why u dont use mic</string>
```

**Comment by ryanheise** [comment]
Note #180 which supersedes this one. It is the currently pinned issue.
