### ISSUE TITLE
Audio Source from asset

### ISSUE THREAD

**Issue by Riz-waan** [ryanheise/just_audio#189]
**Is your feature request related to a problem? Please describe.**
I would love to be able to use mp3s in assets when creating a playlist.

**Describe the solution you'd like**
Maybe in AudioSource class, we can specify whether to load from an asset, file, or URL.

**Describe alternatives you've considered**
I am not sure, I am new to this plugin and it might already exist, but my testings haven't succeeded.

**Comment by ryanheise** [comment]
There is a method for loading from assets mentioned in the README. I am not sure if you have read its documentation, but it answers your question.

**Comment by Riz-waan** [comment]
Thank you so much! Found it! Sorry for the trouble.

I was trying to do a playlist and I didn't know how to do it, because I followed the readme, and I looked at the documentation for AudioSource, but once I looked at the setAsset method, I realized that itself was implementing URI and that is what I need to do.

**Comment by merfire** [comment]
For anyone that is still having a problem with this, I hope this helps:
```
await audioPlayer.load(
  ConcatenatingAudioSource(children: [
     AudioSource.uri(
      Uri.parse('asset:///assets/audios/song1.mp3'),
      tag: AudioMetadata(title: 'Relaxation', artwork: 'assets/images/album-art-1.png'),
    ),
    AudioSource.uri(Uri.parse('asset:///assets/audios/song2.mp3')),
  ]),
);
audioPlayer.play();
```

I was missing a prefix asset:///.
Use **Uri.parse(asset:///{path-to-file})** to load a file.
_Note:_ AudioMetadata is a custom class with a title and artwork variables as string, it is not a class from just_audio package.
