### ISSUE TITLE
ExoPlayer revisited

### ISSUE THREAD

**Issue by ryanheise** [ryanheise/just_audio#19]
A number of recent issues (#10, #14, #16, and possibly #17) could be addressed by finally switching to ExoPlayer as per the suggestion of @rohansohonee . The reason for not considering it until now was the difficulty of implementing `untilPosition` in ExoPlayer, however studying the APIs further, I think this should actually be possible as well.

It will take some time to read through all the documentation, but I plan to focus my attention here for the next while.

**Comment by ryanheise** [comment]
The latest commit now integrates ExoPlayer, for testing.

I have not yet changed anything substantial in behaviour, but this will make it easier resolve the other open issues listed above.

**Comment by rohansohonee** [comment]
Will test and report.

**Comment by cnttechio** [comment]
I'm very happy when you integrate Exoplayer. I will try to use it in my app and report to you if I have issues.

**Comment by ryanheise** [comment]
@rohansohonee Done.

**Comment by rohansohonee** [comment]
@ryanheise 
In java in the audioplayer constructor the player.addListener(this) is being used as the same listener when creating two instances of audioplayer in dart code.
The id are different but the listener is same.
This means on stopping player A, the player B also stops.

Am I correct???

**Comment by ryanheise** [comment]
That shouldn't be the case, since each instance of the audio player results in a new instance of the Java `AudioPlayer` class.
