### ISSUE TITLE
Calling ConcatenatingAudioSource.add causes crash

### ISSUE THREAD

**Issue by franklink** [ryanheise/just_audio#192]
First of all, thanks for all the hard work you've put into this library as well as audio_service.

I know this is labeled with an "Untested" comment in code but I need to implement this in my project and my testing discovered this bug.

This happens both in iOS and Android.

**Which API doesn't behave as documented, and how does it misbehave?**

Calling add(AudioSource) on a ConcatenatingAudioSource will then call the same platform method as calling insert(int, AudioSource) -> "concatenatingInsertAll". 

This causes a crash in both iOS and Android because the platform method being called is attempting to insert into an index that is out of range of the list in question. Instead of attempting to insert at index when Add is called the native method call should be simply to add the media source to end of the existing list. I would recommend adding a platform method called "concatenatingAdd" which would not require index and should work as intended.

Incidentally, I have successfully tested insert(int, AudioSource) and found that it works in both iOS and Android.

**Minimal reproduction project**
If you require a github project to reproduce this error then I will be happy to oblige, but I believe this bug becomes evident based on the information provided and a look at the native documentation

**To Reproduce (i.e. user steps, not code)**
1. Create ConcatenatingAudioSource with greater than zero number of AudioSource objects and load in player
2. Call ConcatenatingAudioSource.add(AudioSource)
3. Crash

**Smartphone:**
Multiple devices: Pixel 2 XL running Android 11, Emulator Pixel 3 XL running Pie, iPhone 6s iOS  13.6

**Flutter SDK version**
Version 1.20.4

I will be happy to provide Flutter Doctor output or any other data as needed.

Thanks!

**Comment by ryanheise** [comment]
Hi @franklink , I recently changed that code in the 0.5.0 release while converting to the federated plugin model so there is a chance I introduced a bug at that point. Can you test the previous version 0.4.5 and let me know if it still fails? I will need a minimal reproduction project at some point in order to investigate the bug.

**Comment by ryanheise** [comment]
HI @franklink I think I found the issue and have published a 0.5.2 bug fix release. Normally I would wait for you to test it but the fix looked straightforward, and of course I can publish another bug fix release if you report any further issues.

Please let me know whether it works for you and I'll close this issue.

**Comment by franklink** [comment]
Thanks @ryanheise. Sorry I haven't had a chance to look at this recently. I just tested with 0.5.2 and while it does not crash it does not seem to add to the queue. I will investigate further and provide a project to replicate as soon as possible.

**Comment by franklink** [comment]
I got a chance to look into this further and look at your commit. In my initial test I had a missing line in my code to update the queue in AudioService. After fixing - add to queue now works as intended with 0.5.2 in both Android and iOS in my testing.

Thanks again for the quick fix as well as these two great libraries. Cheers!

**Comment by ryanheise** [comment]
Thanks for reporting and testing!
