### ISSUE TITLE
after upgrading to 0.5.0 getting ava.io.FileNotFoundException: assets/mp3/beep.mp3

### ISSUE THREAD

**Issue by kw2019ltd** [ryanheise/just_audio#193]
W/arcodeisraelap(26640): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(26640): Init eb76d8e [ExoPlayerLib/2.11.7] [OnePlus7T, HD1903, OnePlus, 29]
E/ExoPlayerImplInternal(26640): Source error
E/ExoPlayerImplInternal(26640):   com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: assets/mp3/beep.mp3
E/ExoPlayerImplInternal(26640):       at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:87)
E/ExoPlayerImplInternal(26640):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
E/ExoPlayerImplInternal(26640):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(26640):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962)
E/ExoPlayerImplInternal(26640):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(26640):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(26640):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(26640):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(26640):   Caused by: java.io.FileNotFoundException: assets/mp3/beep.mp3
E/ExoPlayerImplInternal(26640):       at android.content.res.AssetManager.nativeOpenAsset(Native Method)
E/ExoPlayerImplInternal(26640):       at android.content.res.AssetManager.open(AssetManager.java:833)
E/ExoPlayerImplInternal(26640):       at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:68)
E/ExoPlayerImplInternal(26640):       ... 7 more
E/AudioPlayer(26640): TYPE_SOURCE: java.io.FileNotFoundException: assets/mp3/beep.mp3
I/flutter (26640): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════

**Comment by RaphaelRevivor** [comment]
Exactly the same problem here. Using another player works fine.

**Comment by ryanheise** [comment]
Hi @RaphaelRevivor , sorry if my Bot's message wasn't clear enough. I will try to improve the messaging. When an issue is closed, that means that no further action will be taken on that issue, and you should open a new issue that provides all requested information in the issue template. To elaborate, I have a long list of issues in the backlog, and it takes a lot of my time and effort to get through them. I therefore prioritise my time on the bug reports that have actually respected the instructions and provided me with a minimal reproduction project (as requested in the instructions). If I didn't do that, it would take me much longer to make my way through the backlog and the average person would have to wait longer for bug fixes to land.

I assume that you both want the bug fixed as soon as possible, but the way to do that is to submit a valid bug report as soon as possible, or to submit a pull request.

(Note that someone else did submit a pull request which is almost ready for integration except for a few minor issues. I can assure you therefore that a new release will be out soon with the fix - but please remember for the future to "help me help you", by filling out all requested information in a bug report, or filing a new "valid" bug report if the old one was invalid.)
