### ISSUE TITLE
Dependency error using just_audio

### ISSUE THREAD

**Issue by tommccaff** [ryanheise/just_audio#199]
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio

**Minimal reproduction project**
Using the example installation to pubspec.yaml.

**To Reproduce (i.e. user steps, not code)**
Insert the following code under the dependencies section of pubspec.yaml, and attempt to do a pub get:
  just_audio: ^0.5.0

**Error messages**
"""Because every version of flutter_test from sdk depends on async 2.4.0 and just_audio >=0.2.0 depends on async ^2.4.1, flutter_test from sdk is incompatible with just_audio >=0.2.0.
So, because just_audio_test depends on both just_audio ^0.5.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because just_audio_test depends on both just_audio ^0.5.0 and flutter_test any from sdk, version solving failed.)"""

**Expected behavior**
Pub get should succeed without an incompatibility error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
OS: Occurs on both Windows 10 and MacOS 10.15.7 using Android Studio 4.0.1

**Smartphone (please complete the following information):**
N/A

**Flutter SDK version**
$ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter\flutter
    • Framework revision 0b8abb4724 (8 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Tom McCaffrey\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\Tom McCaffrey\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Additional context**
I’m trying to use just_audio for a basic iPod style music player app, and right out of the gate I’m getting the following error – a dependency on async is failing:

**Because every version of flutter_test from sdk depends on async 2.4.0 and just_audio >=0.2.0 depends on async ^2.4.1, flutter_test from sdk is incompatible with just_audio >=0.2.0.
So, because just_audio_test depends on both just_audio ^0.5.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because just_audio_test depends on both just_audio ^0.5.0 and flutter_test any from sdk, version solving failed.)**
 
I’ve tried this in Android Studio both on Windows 10 and on my MacBookPro.  The only way I’ve found to get around it was to completely remove my dev_dependencies entirely.

**Comment by ryanheise** [comment]
I can downgrade this package to use an older version of async.

Another way to get around it is for you to upgrade your SDK, since you have quite an old version that depends on an old version of `async`. Another way is you could use a dependency override to force your preferred old version of async so that you can continue using your old SDK.

**Comment by ryanheise** [comment]
I've just downgraded the async dependency to 2.4.0 in git master. Let me know if it works for you.
