### ISSUE TITLE
How can i load audio files from protected urls 

### ISSUE THREAD

**Issue by LacErnest** [ryanheise/just_audio#201]
**Which API doesn't behave as documented, and how does it misbehave?**
I am currently using just_audio 0.5.2 and I am trying to use ConcatenatingAudioSource to load audio files that are both located in assets folder as well as audio files from storage. It seems I cannot load audio files from storage. I have tried this on Android only.

**Minimal reproduction project**
_playlist = ConcatenatingAudioSource(children: audiosStreams)
_init();
_init() async {
    final session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration.speech());
    try {
      await _player.load(_playlist);
    } catch (e) {
      // catch load errors: 404, invalid url ...
      print("An error occured $e");
    }
  }

**To Reproduce (i.e. user steps, not code)**

Create a concatenatingAudioSource
input as children sounds that are fetched from my API
**Error messages**
No error message but an empty playlist 

**Expected behavior**
audioplayer should play my audio files

**Screenshots**

**Smartphone (please complete the following information):**
Device: Pixel_2_API_27:5554, Android Emulator

**Flutter SDK version**
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (9 weeks ago) • 2020-08-05 19:53:19 -0700
Tools • Dart 2.9.0

**Additional context**
the user must be authenticated to fetch audio files from my API

**Comment by ryanheise** [comment]
The instructions asked for a link to your minimal reproduction project, and then under steps to reproduce, this should be user steps, not code.

**Comment by ryanheise** [comment]
Closing due to lack of response.
