### ISSUE TITLE
Address event lag through platform channels

### ISSUE THREAD

**Issue by ryanheise** [ryanheise/just_audio#21]
Note to self: there is a slight lag between the time an event is broadcast from the platform side and the time it is received on the flutter side, which may create surprises for flutter-side state processing. For example, after `await setUrl(...)` completes on the flutter side, the state transition to `stopped` may lag slightly, and for a brief moment querying `player.playbackState` may still report `connecting`.

At some point, this code should be improved so that events are categorised into flutter-side initiated events which should update on the flutter side immediately, and asynchronous events which originate on the platform side, such as when buffering is detected, and for which the lag is not a problem.

**Comment by yringler** [comment]
> For example, after await setUrl(...) completes on the flutter side, the state transition to stopped may lag slightly, and for a brief moment querying player.playbackState may still report connecting.

Yes! I dealt with this exact issue. I ended up using playbackStateStream, and taking the first value which wasn't `connecting`

**Comment by ryanheise** [comment]
Fixed in the latest commit on master.
