### ISSUE TITLE
 Unhandled Exception: NoSuchMethodError: The getter 'state' was called on null.

### ISSUE THREAD

**Issue by volgin** [ryanheise/just_audio#22]
In both iOs and Android, the following line throws an exception:

Unhandled Exception: NoSuchMethodError: The getter 'state' was called on null.
```
 /// The current [AudioPlaybackState].
  AudioPlaybackState get playbackState => _audioPlaybackEvent.state;
```
I took a quick look at the code, but I don't see an obvious reason why _audioPlaybackEvent is null at any point. In either case, the plugin should handle this situation, if it's a valid option, e.g.:

`AudioPlaybackState get playbackState => _audioPlaybackEvent?.state;`

**Comment by ryanheise** [comment]
Possibly #11 would fix this, but until I work out the right way to integrate this, I think in the meantime the way to avoid the error would be to not access this stream until the first event arrives.

**Comment by volgin** [comment]
There is no harm in using the code that I proposed. It returns null instead of throwing an exception inside the plugin code. Let the apps deal with the null logic.

**Comment by ryanheise** [comment]
Ultimately I want to implement this so that it is never null (creating less burden on the user), but I think your suggestion is appropriate as something I could do in the short term. I'll have a look when I get home.

**Comment by ryanheise** [comment]
I've committed a temporary workaround, similar to #11 although addressing the issue at the event level which will propagate to the state level. Let me know if it works for you or whether there is still an issue.
