### ISSUE TITLE
build error.

### ISSUE THREAD

**Issue by zengkid** [ryanheise/just_audio#221]
I created a new flutter project, I only add  dependencies just_audio: 0.5.4 into pubspec.yaml, and then run, I got below errors.
please help how to fixed the issue.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-20.0.jar (com.google.guava:guava:20.0) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ryanheise** [comment]
Hi @zengkid, just to confirm (as a human) I would appreciate if you can open a new bug report while following the instructions carefully. It should be easy to create a minimal reproduction project by forking this project, and simply adding your own project's pubspec dependencies to it without changing any Dart code. Thanks.

**Comment by zengkid** [comment]
Hi, @ryanheise thank your reply, I am a human but not a bot.
I just create a new flutter app and add the just_audio: **0.5.4** only, then throw the error when I run the app.

but I found when I use version **0.5.3,** It work fine.

**Comment by ryanheise** [comment]
I didn't mean that you are bot, I programmed the bot that replied to you above. Too often people don't read the message in that reply so I'm just reaffirming it myself (as a human)  so that you're more likely to follow it. As mentioned by the bot and also by me personally can you please open a new issue following the instructions carefully and providing a minimal reproduction project? I have explained above how you can do that.
