### ISSUE TITLE
How to Play Music Stored on Phone/SD Card?

### ISSUE THREAD

**Issue by rajeshjeshar** [ryanheise/just_audio#222]
```
void start()async{
    ConcatenatingAudioSource(
     children: CategoryProvider().audio.map((e) =>AudioSource.uri(Uri.file(e.path))).toList(),
   );
   await _player.load(_playlist);
  }
```

Tried a lot to play an audio file from storage,but it throws exception "headers required".
Why there is no proper example for this?Example code is fully focusing on the streaming auido files alone?Is this Good?
Please Let me know if any example snippet is given.

**Comment by merfire** [comment]
I am having the same problem and I can't figure it out, idk what am I missing. Is it possible to play audio from storage in a playlist, if so maybe this should be added to documentation or the example.

**Comment by merfire** [comment]
For anyone that is still having a problem with this, I finally got it to work.
```
await audioPlayer.load(
  ConcatenatingAudioSource(children: [
     AudioSource.uri(
      Uri.parse('asset:///assets/audios/song1.mp3'),
      tag: AudioMetadata(title: 'Relaxation', artwork: 'assets/images/album-art-1.png'),
    ),
    AudioSource.uri(Uri.parse('asset:///assets/audios/song2.mp3')),
  ]),
);
audioPlayer.play();
```

I was missing a prefix asset:///.
Use **Uri.parse(asset:///{path-to-file})** to load a file.
_Note:_ AudioMetadata is a custom class with a title and artwork variables as string, it is not a class from just_audio package.
