### ISSUE TITLE
Allow ConcatenatingAudioSource assets to be loaded "on the fly" instead of all at once

### ISSUE THREAD

**Issue by klitzouille** [ryanheise/just_audio#229]
**Is your feature request related to a problem? Please describe.**
When loading a ConcatenatingAudioSource with a lot of assets (200+ audio of 2-10 seconds), it takes up to 5 seconds to finish, and therefore audio playing is delayed by this amount of time.

**Describe the solution you'd like**
It would be great if the load method could provide an additional parameter to specify if we want assets loaded immediately or "on the fly" when playing audio.

**Describe alternatives you've considered**
I used to play audio in a while loop, iterating over all the assets, but imo it would be better to be able to benefit from the ConcatenatingAudioSource perks.

**Additional context**
Audio is playing in an isolate created by AndroidAlarmManager plugin, so I don't see a way to cache all the assets when loading app.

**Comment by ryanheise** [comment]
Have you noticed this behaviour on iOS or Android or both? Are the individual items local or remote?

There is an in `ConcatenatingAudioSource` called `useLazyPreparation` which currently only has any effect on Android, but if I find a way to do it on iOS as well, I will add it.

**Comment by klitzouille** [comment]
I noticed this behaviour on Android, for local items. I already use the useLazyPreparation parameter, but the "initial preparation steps (e.g., manifest loads)" mentionned in exoplayer doc doesn't seem to work.

Here is the code I use :

`ConcatenatingAudioSource source = ConcatenatingAudioSource(
     children: _assets.map((e) => AudioSource.uri(Uri.parse('asset:///assets/' + e))).toList(),
     useLazyPreparation: true
);

await _player.setLoopMode(LoopMode.all);
await _player.load(source);
await _player.play();`

I also tried loading the source after calling the play() method as mentionned but audio is not playing at all.

**Comment by ryanheise** [comment]
It could be that this option also needs to be set on the player.

Can you try editing your copy of the plugin and changing the `ensurePlayerInitialized` method inside of `AudioPlayer.java` to this?

```java
    private void ensurePlayerInitialized() {
        if (player == null) {
            player = new SimpleExoPlayer.Builder(context)
                .setUseLazyPreparation(true)
                .build();
            player.addMetadataOutput(this);
            player.addListener(this);
            player.addAudioListener(this);
        }
    }
```

It would be interesting to know whether this option needs to be set in both places, or whether one option overrides the other.

**Comment by klitzouille** [comment]
Still no luck, I setup a minimal reproducible project here if it can help : https://github.com/klitzouille/just_audio_test
It uses just_audio plugin updated as adviced in your previous response, located here : https://github.com/klitzouille/just_audio

**Comment by ryanheise** [comment]
Probably in that case the bottleneck is in the extracting of the assets. When you use an `asset://` URI, the plugin extracts the asset into a temporary file before playing it. What you should probably do is extract the assets yourself outside of the plugin on the first time the app is installed and loaded, and then pass `file://` URIs into the plugin.

**Comment by klitzouille** [comment]
That did it, thank you for your help.
