### ISSUE TITLE
Position can be greater than duration

### ISSUE THREAD

**Issue by volgin** [ryanheise/just_audio#23]
The end position fired by "getPositionStream()" exceeds the duration returned by the setUrl/setFile calls.

`I/flutter (22305): position: 229886, duration: 229877`

It's a very small discrepancy, but it's enough to break the UI code which does not expect a progress value to exceed the maximum value.

The problem is caused by firing position events every 200ms, which means that the last fire is almost guaranteed to be _after_ the recording finished.

It appears that if you finish "// TODO: emit periodically only in playing state.", it may resolve this issue with plenty of other benefits.

This may also be related to #21 

NB: As a side-note, you may want to rename .getPositionStream() into positionStream to make it  consistent with playbackStateStream.

**Comment by ryanheise** [comment]
Thanks, yes I believe that the lag will affect things, although as an additional safeguard, the reported position should be clipped to the duration.

On the naming issue, `playbackStateStream` is a getter hence it does not need the word `get` in its name, while `getPositionStream` is a normal method that takes a parameter. Effective Dart doesn't specifically advise on a naming convention for this, although the de-facto standard for this seems to be to use the word `get` if its a method.

**Comment by ryanheise** [comment]
In version 0.2.0, the behaviour has been changed so that if the duration is unknown, the raw position will be returned (e.g. in streaming), while if the duration is known, the position will be clipped at `min(position, duration)`. This accounts for the unreliability of the position with respect to the duration.
