### ISSUE TITLE
Audios above a certain size/length fail to loop and cause weird behavior - IOS and Android

### ISSUE THREAD

**Issue by fuzing** [ryanheise/just_audio#239]
**Which API doesn't behave as documented, and how does it misbehave?**
Looping fails when audio is above a certain size/length, resulting in (in the example):
   1. Audio plays from start to finish (ocean plays for around 52 seconds)
   2. Followed by a period of silence (in this case 03:23 of silence)
   3. Repeat at 1

Note that I have replicated the issue on master and 0.5.5, and 0.5.6 (which just came off master anyway)

Note that while I have not used this repo on IOS, I know that IOS also fails because I noticed this first in our IOS app.

If I had to guess, perhaps the player is using/getting/computing the wrong duration and looping on that? (i.e. maybe it's using a duration that's longer than the actual audio and is padding with silence?).  Or perhaps the player is not seeing a completion from the native player (which is odd because this is identical for IOS and Android)

**Minimal reproduction project**
https://github.com/fuzing/jaissue.git
(Ryan - I reused the same repo, but commented out last code - sorry if you're still using for the IOS memleak issue - let me know and I'll replicate in a different branch)

**To Reproduce (i.e. user steps, not code)**
Clone the repo and run (click the + sign to start the audio)

In main.dart, there are instructions on variants that fail and don't fail - based simply on the size/duration of the file.   When the "makeItFail" flag is set to true, you'll see failure for File, Asset and Network.

**Error messages**

```
N/A.
```

**Expected behavior**
Audio should loop (it may be looping with padded silence)

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPad Air - Samsung Tab A - Various other
 - OS: IOS/Android

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] VS Code (version 1.51.0)
[!] Connected device
    ! No devices available

```

**Additional context**
Thank you

**Comment by ryanheise** [comment]
> Looping fails when audio is above a certain size/length, resulting in (in the example):
> 
>     1. Audio plays from start to finish (ocean plays for around 52 seconds)
> 
>     2. Followed by a period of silence (in this case 03:23 of silence)
> 
>     3. Repeat at 1
> 

The audio file contains 03:23 seconds of silence when I check in audacity, so it seems to be working as expected.

**Comment by fuzing** [comment]
Hi Ryan,

If that's the case I apologize for wasting your time.  Let me check the
file.  Possibly my own stupidity.

Many thanks,

Peter B

**Comment by fuzing** [comment]
We can definitely close this out...... my fault.  Rookie mistake..... sorry.

**Comment by ryanheise** [comment]
No worries, happily it turned out to be something easier to deal with!
