### ISSUE TITLE
iOS: load with initialIndex greater than previous playlist size fails

### ISSUE THREAD

**Issue by bacr** [ryanheise/just_audio#240]
**Which API doesn't behave as documented, and how does it misbehave?**
`load `with `initialIndex `greater than previous playlist size fails on iOS (Android works)

**Minimal reproduction project**
https://github.com/bacr/just_audio/blob/master/just_audio/example/lib/main.dart

**To Reproduce (i.e. user steps, not code)**
Run example

**Error messages**

```
Error in handleMethodCall
```

**Expected behavior**
Example will play first playlist for 5 seconds and then change to second playlist.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 emulator, iPhone X
 - OS: iOS 13.5, 14.1

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.5 19F101, locale en-RU)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[!] Android Studio (not installed)
[✓] VS Code (version 1.50.1)
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.
```

**Comment by bacr** [comment]
Hey, @ryanheise! Did you have a chance to look at this?

**Comment by ryanheise** [comment]
Hi @bacr , sorry for the delay. I believe I have now fixed this. Can you try out the latest code on the master branch?

**Comment by bacr** [comment]
@ryanheise thanks! Looks like it's working now.

**Comment by ryanheise** [comment]
Excellent! Thanks for confirming that, and it will be included in the next release.
