### ISSUE TITLE
ConcatenatingAudioSource insert needs _setup

### ISSUE THREAD

**Issue by defsub** [ryanheise/just_audio#247]
**Which API doesn't behave as documented, and how does it misbehave?**

insert() and related methods in ConcatenatingAudioSource do not work - code says these are untested. After tracing through the differences between load() and insert() I noticed that _setup() wasn't being called on newly inserted items. Adding _setup() makes the insert work and playback to work correctly.

Note that my project calls load() initially with several songs to start playback and later allows the user to append songs to the playlist. This is where use of the untested insert() call runs into a problem. 

```
 Future<void> insert(int index, AudioSource audioSource) async {
    children.insert(index, audioSource);
    if (_player != null) {
      _player._broadcastSequence();
      await audioSource._setup(_player); // ADD THIS LINE - add, addAll & insertAll need this also.
      await (await _player._platform).concatenatingInsertAll(
          ConcatenatingInsertAllRequest(
              id: _id, index: index, children: [audioSource._toMessage()]));
    }
  }
```

**Minimal reproduction project**

Try using ConcatenatingAudioSource.insert() and when the player hits that item, it will fail with exception below. I've tested with both https (w/ headers) and local media items. Problem occurs in either case.

**To Reproduce (i.e. user steps, not code)**

See above.

**Error messages**

```
E/ExoPlayerImplInternal(15555): Source error
E/ExoPlayerImplInternal(15555):   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
E/ExoPlayerImplInternal(15555):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1096)
E/ExoPlayerImplInternal(15555):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
E/ExoPlayerImplInternal(15555):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(15555):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(15555):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(15555):       at java.lang.Thread.run(Thread.java:923)
```

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android Pixel 2
 - OS: Android 11

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (3 available)

• No issues found!

```

**Additional context**

I'm building a music player called takeout using audio_service and just_audio. Server and flutter app available [here](https://github.com/defsub).

**Comment by ryanheise** [comment]
Thanks for spotting that! Your solution seems reasonable.

I am sorry for the delay as I am working on some higher priority features. If you are interested in seeing this happen earlier, you might like to consider creating a pull request with your proposed solution, and assuming it works correctly I would be happy to merge it.

(See #204 for a similar pull request in the same section of code.)

**Comment by ryanheise** [comment]
I now have implemented the fix in the latest commit on master. Please let me know whether it works for you and I'll include it in the next release.

**Comment by defsub** [comment]
Thank you @ryanheise. Will try to check it out tomorrow.

**Comment by defsub** [comment]
The fix works for local files however I'm seeing the original exception with an https AudioSource that needs headers. Seems as if headers are being lost along the way. I'll debug it further and get back to you.

**Comment by defsub** [comment]
Tested again with the correct fix. It's working now, thanks @ryanheise .

**Comment by ryanheise** [comment]
Great to hear, thanks for pointing out the issue and testing!
