### ISSUE TITLE
seeking after play local wav file crashed with ExoPlaybackException: Unexpected runtime error

### ISSUE THREAD

**Issue by na-si** [ryanheise/just_audio#257]
**Which API doesn't behave as documented, and how does it misbehave?**
When seek big (more than 80mb) wav files from local storage we always get crash `ExoPlaybackException: Unexpected runtime error `
Play and seek the same file from network works as expected.
just_audio (0.5.7)
audio_service(0.15.1)

**Minimal reproduction project**
```
final AudioPlayer _player = AudioPlayer();
    await_player.setFilePath("/storage/emulated/0/Music/our_project//Moving_Mountains_Cody_Martin_instrumental_LOSSLESS.wav");
    await _player.play();
    await _player.seek(Duration(seconds: 20));
```

**To Reproduce (i.e. user steps, not code)**
Download [song](https://drive.google.com/file/d/1_VQR6sCwg9uQEj3YBbIiLGOYzXZhNEj2/view?usp=sharing), play and seek local file.

**Error messages**

```
D/AudioTrack(13282): ~AudioTrack(sessionID=7441)
D/AudioTrack(13282): stop(sessionID=7441)
E/ExoPlayerImplInternal(13282): Playback error
E/ExoPlayerImplInternal(13282):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
E/ExoPlayerImplInternal(13282):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
E/ExoPlayerImplInternal(13282):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(13282):       at android.os.Looper.loop(Looper.java:207)
E/ExoPlayerImplInternal(13282):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(13282):   Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
E/ExoPlayerImplInternal(13282):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:956)
E/ExoPlayerImplInternal(13282):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(13282):       ... 3 more
E/AudioPlayer(13282): TYPE_UNEXPECTED: Playback stuck buffering and not loading
```

**Expected behavior**
Song has to play and seek without crashes.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 Xiaomi Mi6

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!
```

**Additional context**
We can play and seek this *.wav file using `open_file` library (youtube music, and other music apps). And song is playing by local link without any problem, but we cannot play  it by our app after seeking.

**Comment by ryanheise** [comment]
Hi @nsilina , there are issues open on ExoPlayer regarding this error. See for example:

https://github.com/google/ExoPlayer/issues/8170

I didn't reproduce your issue because you didn't provide a link to your minimal reproduction project. However if you still want to investigate yourself, you can try modifying just_audio's Java code with the techniques described in that issue. Let me know if any of those solutions work and I can expose those methods in the just_audio API.

**Comment by ryanheise** [comment]
Since I haven't heard back from you, I'll close this issue. I have upgraded just_audio to the latest ExoPlayer, so if they have introduced a fix, that fix should also be inherited into just_audio.
