### ISSUE TITLE
ConcatenatingAudioSource audio stuttering on source change with wireless headphones

### ISSUE THREAD

**Issue by sebalaursen** [ryanheise/just_audio#262]
**Which API doesn't behave as documented, and how does it misbehave?**
When connected to wireless headphones on an iOS device ConcatenatingAudioSource on change of source will start for ~500-1000 milliseconds and then rewind back to 0 and start again. Sound kind of like stuttering.

**Minimal reproduction project**
The just_audio example project.

**To Reproduce (i.e. user steps, not code)**
1. Connect wireless headphones to an iOS device
2. Launch example app
3. Press the play button
4. Wait for it to change (don't skip manually) to next source and observe the stutter

**Expected behavior**
Should switch to next source without unnecessary seeking (stuttering).

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.17

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.2

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.84, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!
```

**Additional context**
Observed some differences in logs when audio source is changing with and without wireless headphones. Here is a log on source change with headphones:
```
onComplete
advance to next: index = 1
Queue change detected. Adjusting index from 1 -> 2
On currentItem change, seeking back to zero
ENTER BUFFERING: currentItem changed, seeking
LEAVE BUFFERING: timeControlStatus
LEAVE BUFFERING: currentItem changed, finished seek
```
Without headphones:
```
onComplete
advance to next: index = 1
Queue change detected. Adjusting index from 1 -> 2
LEAVE BUFFERING: timeControlStatus
```
Seems like there is some unnecessary seeking or it's some kind of delay. Haven't tested on Android so it maybe also happening there. Happens with AirPods and other headphones (JBL E65BTNC), wired (EarPods with Lightning Connector) headphones seem to work ok on iOS.

**Comment by ryanheise** [comment]
The log was really helpful, thanks! I do not have the hardware to be able to test this myself, so this detailed report will hopefully allow me to help you.

The code in question is a callback that occurs whenever the player switches to a different item in the queue:

```objc
            // We should already be at position zero but for
            // ClippingAudioSource it might be off by some milliseconds so we
            // consider anything <= 100 as close enough.
            if ((int)(1000 * CMTimeGetSeconds(source.position)) > 100) {
                NSLog(@"On currentItem change, seeking back to zero");
...
```

This hack is something I can hopefully delete altogether but it's there because during the initial development I noticed that sometimes when skipping back to a track that had already been partially played, it had not correctly been repositioned back to the start of the track. This code detects whether the track needs to be reset. It's a bit tricky because it seems that seeking doesn't work unless the player item is the current one, so there is no perfect opportunity to do the seek cleanly.

That said, a quick solution would be to increase the threshold from 100 ms to something higher. It seems that the delta is greater when playing through Bluetooth. Would you mind testing this?

If you change that log message to this, you will be able to see the actual delta:

```objc
NSLog(@"On currentItem change, seeking back to zero. delta=%d", (int)(1000 * CMTimeGetSeconds(source.position)));
```

I will also do some more testing and see if there is a way to eliminate this code altogether.

**Comment by ryanheise** [comment]
I've commented out that block of code and it seems to be working correctly. Can you try the latest commit?

Note that I only tested on the iOS 14.2 Simulator and I no longer have access to older iOS simulators. So the risk is that this code may still be needed for older iOS versions.

**Comment by sebalaursen** [comment]
Hi
Thanks for the response. Tested the lates commit and the stuttering is gone but I noticed a problem with the looping clipping audio source as you mentioned the bit of code had something to do with repositioning audio's. When rewinding the first loop (better a few times) it seems that the next loop will start from the starting point time minus the time rewinded in the previous loop and play to the end point. Attaching a zip with a mp4 with reproduction steps.
[IMG_2458.MP4.zip](https://github.com/ryanheise/just_audio/files/5719021/IMG_2458.MP4.zip)

**Comment by sebalaursen** [comment]
The issue I mentioned above maybe is unrelated, just tested the previous version and it also happens there.

**Comment by ryanheise** [comment]
Thanks for spotting that, good find! Yes it does seem like it could be an unrelated issue that I just hadn't noticed before.

**Comment by sebalaursen** [comment]
Thanks for the quick fix for my issue though. I can imagine it's hard to keep track of this many platforms, I appreciate your work! Thanks again.

**Comment by ryanheise** [comment]
That commented-out workaround, though, may help to solve this new issue that you discovered. If I add this code back in, I would want to ensure that I set the delta threshold high enough.

Did you manage to print out and see what the delta was when playing through Bluetooth?

**Comment by sebalaursen** [comment]
Yeah, forgot about that. Here are few logs with delta:
```
ENTER BUFFERING: timeControlStatus
LEAVE BUFFERING: timeControlStatus
onComplete
advance to next: index = 1
On currentItem change, seeking back to zero. delta=123
ENTER BUFFERING: currentItem changed, seeking
LEAVE BUFFERING: timeControlStatus
LEAVE BUFFERING: currentItem changed, finished seek
LEAVE BUFFERING: ready to play: playing, !waitingToPlay
onComplete
advance to next: index = 2
On currentItem change, seeking back to zero. delta=181
ENTER BUFFERING: currentItem changed, seeking
LEAVE BUFFERING: timeControlStatus
LEAVE BUFFERING: currentItem changed, finished seek
```

```
ENTER BUFFERING: timeControlStatus
LEAVE BUFFERING: timeControlStatus
onComplete
advance to next: index = 1
On currentItem change, seeking back to zero. delta=121
ENTER BUFFERING: currentItem changed, seeking
LEAVE BUFFERING: timeControlStatus
LEAVE BUFFERING: currentItem changed, finished seek
LEAVE BUFFERING: ready to play: playing, !waitingToPlay
onComplete
advance to next: index = 2
On currentItem change, seeking back to zero. delta=120
ENTER BUFFERING: currentItem changed, seeking
LEAVE BUFFERING: timeControlStatus
LEAVE BUFFERING: currentItem changed, finished seek
```

```
ENTER BUFFERING: timeControlStatus
LEAVE BUFFERING: timeControlStatus
onComplete
advance to next: index = 1
On currentItem change, seeking back to zero. delta=121
ENTER BUFFERING: currentItem changed, seeking
LEAVE BUFFERING: timeControlStatus
LEAVE BUFFERING: currentItem changed, finished seek
LEAVE BUFFERING: ready to play: playing, !waitingToPlay
onComplete
advance to next: index = 2
On currentItem change, seeking back to zero. delta=119
ENTER BUFFERING: currentItem changed, seeking
LEAVE BUFFERING: timeControlStatus
LEAVE BUFFERING: currentItem changed, finished seek
```

varies a bit but usually stays in the 120 area, couldn't get to 180 again.

**Comment by ryanheise** [comment]
The temporary solution that I implemented above is actually released and doesn't seem to be causing major problems so I'll consider the issue closed.

The original bug was caused by a workaround to force `ClippingAudioSource` to start at the correct position but I feel that there should be a better solution to that. If I do end up pursuing it, I will pursue it under a different issue.
