### ISSUE TITLE
Repeatedly playing and pausing causes delayed PlaybackEvent in 0.6.3

### ISSUE THREAD

**Issue by moritz-weber** [ryanheise/just_audio#265]
**Which API doesn't behave as documented, and how does it misbehave?**
Starting `play()` for the first time works fine. After `pause()` and `play()`, the `PlaybackEvent` is delayed.
In my case it's delayed by multiple seconds, causing the UI to freeze while playback starts.
The example app works as expected, as it uses `PlayerStateStream` instead which seems to be fine.

**Minimal reproduction project**
Listen to the `PlaybackEventStream` in the example app.
Add the following code to line 58 in main.dart:

    _player.playbackEventStream.listen((event) {
      print(event);
    });

**To Reproduce (i.e. user steps, not code)**
1. Play the third playlist item (easier to watch the console output)
2. Pause
3. Play
4. Watch output

**Error messages**
None.

**Expected behavior**
A PlaybackEvent should be emitted instantly after pressing play. (As was the case in 0.6.2)

**Screenshots**
None.

**Desktop (please complete the following information):**
Does not apply.

**Smartphone (please complete the following information):**
 - Device: bq Aquaris X2 Pro
 - OS: Android 10

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Additional context**

**Comment by AliHoseinpoor** [comment]
i have same issue

**Comment by ryanheise** [comment]
Thanks for reporting this, I will take a look.

**Comment by ryanheise** [comment]
Ah, I think I understand the issue. `PlaybackEvent` is probably misnamed but this does not encapsulate all of the state. It represents only events reported asynchronously by the backend, such as processing state changes, position changes and metadata changes. State that is set by the app (`playing`, `speed`, `volume`, etc.) is not such an event and there are separate streams for those.

`playerStateStream` is actually a derived stream that mixes together `playingStream` and `processingStateStream`, defined using rxdart factories:

```dart
Rx.combineLatest2(playingStream, playbackEventStream,
                (playing, event) => PlayerState(playing, event.processingState))
            .distinct()
```

So this stream will update also whenever the `playing` state changes. You can use rxdart to combine the streams your app needs, in the same way that `playerStateStream` was created. But this motivates a discussion on what streams should be provided by the plugin by default.

Incidentally, I believe the audio_service example makes the same error. It should be rewritten to use `playerStateStream`.

**Comment by ryanheise** [comment]
I plan to add a section to the README clarifying the state model.

This state diagram will be used to depict the orthogonal `processingState` and `playing` states:

![just_audio_states](https://user-images.githubusercontent.com/19899190/103146315-7bf3a480-479b-11eb-828b-fe23255828bf.png)


The `playing` state is only ever changed synchronously when the app calls `play` or `pause` and also implicitly by `stop`. On the other hand, the processing state may change asynchronously based on the state of the player on the platform side.

The purpose of `PlayerState` is to combine these two orthogonal states into a unified state:

```dart
class PlayerState {
  final bool playing;
  final ProcessingState processingState;
}
```

**Comment by ryanheise** [comment]
The README has now been updated with a detailed explanation of the state model.

**Comment by moritz-weber** [comment]
Thanks for your response. My rationale behind using `playbackEventStream` was that it seems to be the only stream that emits an event when a song starts from the beginning with loopMode set to `LoopMode.one`.
I may just use both streams (`playerState` and `playbackEvent`) for different use cases: user changes state vs. state updated by backend.

**Comment by ryanheise** [comment]
Your use case would probably benefit from #174 . Since the position discontinuity event information is in `PlaybackEvent`, it is perfectly reasonable for you to listen to `playbackEventStream`. Have you considered combining `playbackEventStream` with `playingStream` using rxdart?

As for which composite streams should be provided out of the box, I may need to listen to more use cases.

The only candidate for a "super stream" that I'm currently considering is the one you need. Perhaps one way to go about it is to actually modify `PlayerState` by adding in all of the other fields from `PlaybackEvent`. It would always be possible to add more to `PlayerState` over time.

**Comment by AliHoseinpoor** [comment]
Now the example in the audio_service is correctly implemented for the play and pause button?

**Comment by ryanheise** [comment]
It hasn't been fixed yet, sorry. FYI, this is the code that is incorrect:

```dart
    _eventSubscription = _player.playbackEventStream.listen((event) {
      _broadcastState();
    });
```

The above code will not listen to `playing` state changes. The simplest way to fix it would be to keep the above code, but to also add this directly below it:

```dart
    _player.playingStream.listen((playing) {
      _broadcastState();
    });
```

**Comment by moritz-weber** [comment]
Combining `playbackEventStream` and `playingStream` works fine for me. Thanks for the suggestion.

I also think that providing "simpler" streams that users can combine to their needs is the right solution for this. An overview of all the available streams with when to expect new events might be helpful.

**Comment by AliHoseinpoor** [comment]
> It hasn't been fixed yet, sorry. FYI, this is the code that is incorrect:
> 
> ```dart
>     _eventSubscription = _player.playbackEventStream.listen((event) {
>       _broadcastState();
>     });
> ```
> 
> The above code will not listen to `playing` state changes. The simplest way to fix it would be to keep the above code, but to also add this directly below it:
> 
> ```dart
>     _player.playingStream.listen((playing) {
>       _broadcastState();
>     });
> ```

Thank you and your good package

**Comment by ryanheise** [comment]
After some consideration, I have decided to release 0.6.4 which emulates the old 0.5.7 `playbackEventStream` behaviour. I'd definitely like to revisit this in the future and maybe come up with a unified stream that at least covers `PlaybackEvent` and `playing`, but 0.6.4 will at least ease the transition to 0.6.x for a lot of developers.

**Comment by ryanheise** [comment]
To those subscribed to this issue, you may recall this new bit of code in the 0.6 release was rather fragile and took a few attempts to iron out all the bugs.

I have recently made a change to this same section of code on the `minhqdao-fix_timers` branch and just to give a heads up, some of you may like to give it a test ahead of its release to ensure that there are no regressions for your apps.
