### ISSUE TITLE
just_audio 0.6.3 freeze when call skipToNext()

### ISSUE THREAD

**Issue by AliHoseinpoor** [ryanheise/just_audio#267]
**Which API doesn't behave as documented, and how does it misbehave?**
I created a music player program with this package along with audio_service. When I updated the just_audio package to version 0.6.3, I had a problem with the skipToNext () method and everything froze.

**Minimal reproduction project**
```
 @override
  Future<void> onSkipToNext() async {
    skip(1);
  }

  Future<void> skip(int offset) async {
    final int newPos = _queueIndex + offset;

    if (!(newPos >= 0 && newPos < _queue.length)) {
      onStop();
      return;
    }
    if (_playing == null) {
      _playing = true;
    } else if (_playing) {
      await _player.stop();
    }
    _queueIndex = newPos;

    _skipState =
        offset > 0 ? AudioProcessingState.skippingToNext : AudioProcessingState.skippingToPrevious;
    AudioServiceBackground.setMediaItem(mediaItem);
    await _player.stop();
    await _player.seek(Duration.zero, index: _queueIndex);
    _skipState = null;
    if (_playing) {
      onPlay();
    } else {
      _broadcastState();
    }
  }
```

This code of mine works perfectly with the 0.5.7 package, but when I updated it, it got into trouble and everything froze, and it also displays this message in log cat:

```
codec does not support config priority (err -2147483648)
Client defaulted notificationFrames to 3675 for frameCount 11025
```

i have no idea why this is heppening 

**To Reproduce (i.e. user steps, not code)**
1. play a music 
2. go to music page for show music detail 
3. click on skip to next button
4. freeze every thing

**Error messages**
None.

**Expected behavior**
I expect everything to work smoothly beforehand

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: Huawie mate 10 lite
 - OS: android 8

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (not installed)
[✓] VS Code (version 1.47.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

**Additional context**
None

**Comment by ryanheise** [comment]
Can you please fill in the section for the minimal reproduction project by providing a link to the git repository that I can clone?

**Comment by AliHoseinpoor** [comment]
> m

my project is private can i add you in project ?

**Comment by AliHoseinpoor** [comment]
I changed the package version to 0.5.7 and everything was fine, but when I update to 0.6.0, everything goes wrong again and I feel it is because of the setAudioSource() method, which has been replaced by load().

**Comment by ryanheise** [comment]
I'm sorry I wasn't asking to see your project, I am requesting a minimal reproduction project. That is, fork this repository and make minimal changes to the example to reproduce the bug. Here were the original instructions:

> **Minimal reproduction project**
> Provide a link here using one of two options:
> 1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
> 2. If the unmodified official example already reproduces the bug, just write "The example".

What you did was neither of these two options, and I think in your case you will need to take option 1 because the example is actually working fine.

By the way, since the example actually works and it demonstrates how to correctly skip to the next and previous items, it is probably best to just look at that example and copy what it does.

Do you have any specific need to implement things differently from the example? For example, do you need to stop the player before seeking? Here is what the documentation for `stop` says:

```dart
  /// Use [stop] if the app is done playing audio for now but may need still
  /// want to resume playback later. Use [dispose] when the app is completely
  /// finished playing audio. Use [pause] instead if you would like to keep the
  /// decoders alive so that the app can quickly resume audio playback.
```

Since you actually continue playing audio immediately after you call `stop`, it doesn't seem to make sense why you would need to stop the player and unload everything.

> I changed the package version to 0.5.7 and everything was fine, but when I update to 0.6.0, everything goes wrong again and I feel it is because of the setAudioSource() method, which has been replaced by load().

0.6.0 is not backwards compatible with 0.5.7, hence the version number bump. One of those changes is that in 0.5.7, `stop` was really just a convenience method for calling `pause` and then seeking to zero. In 0.6.0, stop actually puts the player into the `idle` state and unloads the audio, as well as releasing the native resources required by the player.

You may be overcomplicating your code by trying to stop, seek and play when you could just call `seekToNext` or `seek` with a desired index.

**Comment by AliHoseinpoor** [comment]
> I'm sorry I wasn't asking to see your project, I am requesting a minimal reproduction project. That is, fork this repository and make minimal changes to the example to reproduce the bug. Here were the original instructions:
> 
> > **Minimal reproduction project**
> > Provide a link here using one of two options:
> > 
> > 1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
> > 2. If the unmodified official example already reproduces the bug, just write "The example".
> 
> What you did was neither of these two options, and I think in your case you will need to take option 1 because the example is actually working fine.
> 
> By the way, since the example actually works and it demonstrates how to correctly skip to the next and previous items, it is probably best to just look at that example and copy what it does.
> 
> Do you have any specific need to implement things differently from the example? For example, do you need to stop the player before seeking? Here is what the documentation for `stop` says:
> 
> ```dart
>   /// Use [stop] if the app is done playing audio for now but may need still
>   /// want to resume playback later. Use [dispose] when the app is completely
>   /// finished playing audio. Use [pause] instead if you would like to keep the
>   /// decoders alive so that the app can quickly resume audio playback.
> ```
> 
> Since you actually continue playing audio immediately after you call `stop`, it doesn't seem to make sense why you would need to stop the player and unload everything.
> 
> > I changed the package version to 0.5.7 and everything was fine, but when I update to 0.6.0, everything goes wrong again and I feel it is because of the setAudioSource() method, which has been replaced by load().
> 
> 0.6.0 is not backwards compatible with 0.5.7, hence the version number bump. One of those changes is that in 0.5.7, `stop` was really just a convenience method for calling `pause` and then seeking to zero. In 0.6.0, stop actually puts the player into the `idle` state and unloads the audio, as well as releasing the native resources required by the player.
> 
> You may be overcomplicating your code by trying to stop, seek and play when you could just call `seekToNext` or `seek` with a desired index.

Thank you very much, my problem was solved
