### ISSUE TITLE
iOS Gapless setSpeed() change

### ISSUE THREAD

**Issue by austinpower1258** [ryanheise/just_audio#269]
My team and I are working on a project that involves playback rate change (setSpeed). We discovered that on Android platforms, the setSpeed function allows the audio to change playback rates seamlessly without any gaps or delays, but on iOS platforms, the setSpeed function contains a short gap or delay of about 0.5 seconds when we change between different speeds (change the playback rate). We were wondering if there was a workaround for this.

**Comment by ryanheise** [comment]
FYI, I have submitted a properly formatted issue here: #271
