### ISSUE TITLE
setAndroidAudioAttributes causing a FlutterJNI exception 

### ISSUE THREAD

**Issue by Eufranio** [ryanheise/just_audio#279]
I have a project that uses just_audio, and after some updates, it stopped playing audio. After hours of debugging, I found that the Future returned by `player.setAudioSource()` never completed. Then I found that when the plugin calls `platform.setAndroidAudioAttributes` [here](https://github.com/ryanheise/just_audio/blob/master/just_audio/lib/just_audio.dart#L870), Flutter displays a FlutterJNI error:

```
W/FlutterJNI( 6633): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 27
```
which caused the method to never return.

The SetAndroidAudioAttributesRequest at that point was `SetAndroidAudioAttributesRequest(contentType: 1, flags: 0, usage: 1)`, if that helps. I'd really like if you could point me to where the error could be originating from, if it's from my code or your plugin.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M30
 - OS: Android 10

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [versÃ£o 10.0.19041.685], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by ryanheise** [comment]
The relevant plugin code has certainly changed, I would appreciate if you can provide a minimal reproduction project so that I can investigate it.
