### ISSUE TITLE
Position is always reset to zero when resuming playback after pause on iOS.

### ISSUE THREAD

**Issue by erikatvojo** [ryanheise/just_audio#282]
**Which API doesn't behave as documented, and how does it misbehave?**

On iOS AudioPlayer always returns position = 0 after pausing and then playing an mp3 from a url.

**Minimal reproduction project**

Assuming an mp3 is set using setUrl and played, paused, played using the methods below then:

@override
Future onPlay() {
print(_player.position.toString()); // position is correct on iOS and Android
_player.play();
print(_player.position.toString()); // position is always 0:00:00 on iOS, correct on Android
}

@override
Future onPause() {
print(_player.position.toString()); // position is always 0:00:00 on iOS, correct on Android
_player.pause();
print(_player.position.toString()); // position is always 0:00:00 on iOS, correct on Android
}

**To Reproduce (i.e. user steps, not code)**

**Error messages**

**Expected behavior**

Expected position to be the same on iOS as on Android.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: iPhone 7 
 - OS: iOS 14.2

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.1 20C69, locale en-SE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)

```

**Additional context**

I'm using audio_service with just_audio and on iOS my progress indicator (which uses AudioService.playbackState.currentPosition) always starts over at zero when I resume playback after pause. I figure that it's related to the behaviour described above. Getting the position for the progress indicator works as expected on Android.

**Comment by ryanheise** [comment]
Before I investigate, can you please provide a link to an actual minimal reproduction project that I can clone, and provide me with the steps on how to reproduce?

**Comment by erikatvojo** [comment]
I tried to reproduce the problem by modifying the just_audio example, but I didn't get position = 0 with the amazonaws mp3s there. So I checked the response headers for the mp3 I was using and it had:

Content-Type: audio/mpeg
Transfer-Encoding: chunked
Connection: keep-alive

while the amazon response has:

Accept-Ranges: bytes
Content-Type: audio/mp3
Content-Length: 91924300

With a response header like Amazons my code now works as expected on iOS as well and I get the correct position. 

While investigating I also discovered that there's a similar behaviour with Safari / Chrome on a Mac. Like with just_audio in iOS, Safari doesn't show position when playing an mp3 with the first response header, but Chrome can keep the correct position using both headers, just like android can.  

Since I can change the response header this is no longer an issue for me. If not being able to get / keep the position is the expected behaviour with the first response header, then this is no longer an issue at all but perhaps worth noting in the documentation. 

Thanks.

**Comment by ryanheise** [comment]
I agree it could be a good idea to add a note to the README. Here is Apple's advice for iOS:

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6

**Comment by ryanheise** [comment]
Hi @erikatvojo , I've opened a new issue #289 which combines a couple of different documentation requests related to Apple behaviour. If I have missed mentioning on that new issue, please feel free to comment so that it gets included in the updated documentation.
