### ISSUE TITLE
bufferedPositionStream doesn't produce a stream on iOS and macOS

### ISSUE THREAD

**Issue by suragch** [ryanheise/just_audio#285]
**Which API doesn't behave as documented, and how does it misbehave?**

```
AudioPlayer.bufferedPositionStream
```

It doesn't provide a stream of updates like Android does.

**Minimal reproduction project**

In "The example" you can observe this if you replace [this line](https://github.com/ryanheise/just_audio/blob/master/just_audio/example/lib/main.dart#L131) with the following:

```
stream: _player.bufferedPositionStream,
```

**To Reproduce (i.e. user steps, not code)**
1. Replace the line above in the example app.
2. Run the app on iOS simulator or macOS

**Error messages**

None

**Expected behavior**

I would expect the stream to update the progress bar. Instead it remains constant. Android on the other hand will update.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catelina 10.15.4

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - OS: iPhone 11 Pro Max 13.2.2

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E266 darwin-x64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)
```

**Additional context**

**Comment by ryanheise** [comment]
Oh, thanks for reporting that. I was sure I had implemented this, and I *had* but it looks like I accidentally reverted the code.

In this code:

```objc
- (void)broadcastPlaybackEvent {
    if (!_eventSink) return;
    _eventSink(@{
            @"processingState": @(_processingState),
            @"updatePosition": @((long long)1000 * _updatePosition),
            @"updateTime": @(_updateTime),
            // TODO: buffer position
            @"bufferedPosition": @((long long)1000 * _updatePosition),
            // TODO: Icy Metadata
            @"icyMetadata": (id)[NSNull null],
            @"duration": @((long long)1000 * [self getDuration]),
            @"currentIndex": @(_index),
    });
}
```

The buffered position is broadcast as `_updatePosition` but it should be `_bufferedPosition`.

I will take a look at this after dinner.

**Comment by suragch** [comment]
I'm glad it's an easy fix! Thank you.

**Comment by ryanheise** [comment]
I've just committed a fix. Can you confirm if it works for you?

**Comment by suragch** [comment]
I just checked on both iOS and macOS. Both are working. Thank you!
