### ISSUE TITLE
Exception from ExoPlayer

### ISSUE THREAD

**Issue by volgin** [ryanheise/just_audio#29]
I ran into one mp3 file which causes the following exception, when playing on Android:

```
E/ExoPlayerImplInternal(19071): Source error.
E/ExoPlayerImplInternal(19071): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
E/ExoPlayerImplInternal(19071): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1095)
E/ExoPlayerImplInternal(19071): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:974)
E/ExoPlayerImplInternal(19071): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(19071): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(19071): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(19071): 	at java.lang.Thread.run(Thread.java:919)
```

The file actually starts playing and sounds normal. Unfortunately, the audio player becomes unresponsive - all further calls (setting a new file/URL) fail. The audio player appears to be permanently stuck in the .connecting state.

The same file plays with no problems on iPhone. I also ran a check to see if this is a valid mp3 file, and it is.

1. Any ideas why a file would play normal on iPhone (and in web browsers), but fail on Android?

2. Is there a way to catch such exceptions?

**Comment by ryanheise** [comment]
The only thing I can think of is that it might not really be an mp3 file. Maybe you can try opening the file on your desktop or laptop using software that can show you the codec info. Once I know what format it is, I can try to enable that in ExoPlayer.

**Comment by volgin** [comment]
Good catch. It was a wrong codec.

I still need to be able to catch such exceptions and, ideally, prevent the player from crashing. Currently we cannot pre-validate every file that we play. Skipping files that ExoPlayer cannot play would be a good enough solution.

**Comment by volgin** [comment]
After looking through the plugin code, it appears that there is no way out of AudioPlaybackState.connecting. No other method can be called from this state, making it a dead-end if a player is stuck in this state.

**Comment by ryanheise** [comment]
I'll use #31 to track the exception reporting code.
