### ISSUE TITLE
Add duration field in AudioServiceBackground.setState()

### ISSUE THREAD

**Issue by AliHoseinpoor** [ryanheise/just_audio#290]
**Is your feature request related to a problem? Please describe.**
I want to access the duration of the song. To do this I came to listen to the durationStream event and there I change the duration of the media item and then with AudioServiceBackground.setMediaItem (newMediaItem); I return the new media Item.

```
_durationStream = _player.durationStream.listen((event) {
      final newMediaItem = mediaItem.copyWith(duration: event);
      AudioServiceBackground.setMediaItem(newMediaItem);
    });
```

**Describe the solution you'd like**
As it is possible to return the position in AudioServiceBackground.setState (), it will be very good if it is added to this duration.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ryanheise** [comment]
Can you go into more detail about the problem you're trying to solve? You can access the duration of the song via `AudioService.currentMediaItemStream`.

**Comment by AliHoseinpoor** [comment]
> Can you go into more detail about the problem you're trying to solve? You can access the duration of the song via `AudioService.currentMediaItemStream`.

I am using your just_audio and auduo_service packages at the same time and I want to get the duration of the song from the player. I saw the example audio_service package and when you were creating the media item list, you gave it the duration manually, but I want to get this duration from the player. To do this, I came to use durationStream. Now, if it is possible to send a duration song in AudioServiceBackground.setState () , it will be very good to find out how long it is in ui.

**Comment by ryanheise** [comment]
But why is this required in light of the other stream I mentioned in my previous comment?

**Comment by AliHoseinpoor** [comment]
> But why is this required in light of the other stream I mentioned in my previous comment?

Because when we do not enter the duration field manually in the media item, when we use AudioService.currentMediaItemStream to get the duration returns null

**Comment by ryanheise** [comment]
If you call `AudioServiceBackground.setMediaItem(newMediaItem)` where `newMediaItem` is the item with the updated duration, that should notify the client via `AudioService.currentMediaItemStream`, and so that stream *should* solve your use case. If it does not correctly notify the stream, then that is a bug in audio_service. Is there a reason why you specifically want the duration update to be notified one one stream rather than the other stream? I'm not sure if I understand you, but if you can listen to one stream, why can't you listen also to the other stream?

**Comment by AliHoseinpoor** [comment]
> If you call `AudioServiceBackground.setMediaItem(newMediaItem)` where `newMediaItem` is the item with the updated duration, that should notify the client via `AudioService.currentMediaItemStream`, and so that stream _should_ solve your use case. If it does not correctly notify the stream, then that is a bug in audio_service. Is there a reason why you specifically want the duration update to be notified one one stream rather than the other stream? I'm not sure if I understand you, but if you can listen to one stream, why can't you listen also to the other stream?

I guess there is a bug in AudioService because I did what you said in the beginning but mediaItem was not updated. The code I wrote is as follows:
```
_durationStream = _player.durationStream.listen((event) {
      final newMediaItem = mediaItem.copyWith(duration: event);
      AudioServiceBackground.setMediaItem(newMediaItem);
    });
```

**Comment by defsub** [comment]
@AliHoseinpoor can you try the PR below and see if this works for you? I use this approach and the SeekBar works as expected. This PR updates the example app to dynamically update duration.

[https://github.com/ryanheise/audio_service/pull/585](https://github.com/ryanheise/audio_service/pull/585)

**Comment by AliHoseinpoor** [comment]
> @AliHoseinpoor can you try the PR below and see if this works for you? I use this approach and the SeekBar works as expected. This PR updates the example app to dynamically update duration.
> 
> [ryanheise/audio_service#585](https://github.com/ryanheise/audio_service/pull/585)

thanks a lot. I will definitely try your code

**Comment by AliHoseinpoor** [comment]
> @AliHoseinpoor can you try the PR below and see if this works for you? I use this approach and the SeekBar works as expected. This PR updates the example app to dynamically update duration.
> 
> [ryanheise/audio_service#585](https://github.com/ryanheise/audio_service/pull/585)
I built a new project and I tested this code and it was okay. Thank you very much, brother.
@ryanheise And thank you so much for your help
I'll close this issue now.
