### ISSUE TITLE
在ios上，有耳机连接时，还是扬声器播放，必现

### ISSUE THREAD

**Issue by Pianzhous** [ryanheise/just_audio#291]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
insert output of "flutter doctor" here
```

**Additional context**

**Comment by ryanheise** [comment]
I'm sorry but this issue doesn't follow the instructions. Please use Google translate to read them.
