### ISSUE TITLE
On iOS, when the Bluetooth headset is connected, it still plays from the speaker

### ISSUE THREAD

**Issue by Pianzhous** [ryanheise/just_audio#292]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
Normal connection Bluetooth headset, and then play, headset no sound, or speakers play
**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```
**Expected behavior**
 i want iOS playback to be able to play using the default audio player

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS14.2]

**Flutter SDK version**
```  Flutter 1.22.0
insert output of "flutter doctor" here
```[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1316], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Additional context**
Add any other context about the problem here.

**Comment by ryanheise** [comment]
Hi @Pianzhous can you fill in the sections of the bug report? In particular, does this happen with the example? Are there any features you would like added to audio_session to help?

**Comment by kociubin** [comment]
I'm currently experiencing this issue on iOS 14.5.  I'm unable to get audio to play over bluetooth.  

Please let me know if there are any additional details I can provide to help to resolve it.

**Comment by ryanheise** [comment]
I'll close this issue since there has been no response from @Pianzhous about providing the answers to my questions.

@kociubin would you be willing to open a bug report providing the information I need to investigate it? If so, please click the "New issue" button at the top of the page and follow the instructions.

**Comment by Pianzhous** [comment]
It could be a phone problem. On an older iPhone X, the problem can occur when the Bluetooth signal is unstable. It works when the Bluetooth signal is stable on a different phone.
