### ISSUE TITLE
Show Online Radio Stream's Now Playing Info at Notification

### ISSUE THREAD

**Issue by asa767** [ryanheise/just_audio#296]
**Is your feature request related to a problem? Please describe.**
Is there a way to show now playing info at notification area when palying an online radio stream by getting info from seperate online radio api.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by ryanheise** [comment]
Hi @asa767 , I have created another plugin especially for that called audio_service. I highly recommend it ;-) If you have any questions about how to use it after trying the example, there is a project FAQ and I also regularly answer questions on StackOverflow.

Note that audio_service and just_audio can be used together, and you'll find the audio_service example does just that.
