### ISSUE TITLE
Stream Playback stops after few minutes in standby mode

### ISSUE THREAD

**Issue by bordieris** [ryanheise/just_audio#30]
Android 9. I'm trying to use it to play a web radio endless stream. It seems working until screen goes black for standby.
How can I make the app playing stream also when in standby?

**Comment by rohansohonee** [comment]
Hi @bordieris 

You can use ``audio_service`` plugin which will enable background audio playback.
Both plugins i.e ``just_audio`` & ``audio_service`` are developed by @ryanheise.
It is recommended you use @ryanheise plugin.
Hope this is helpful.

**Comment by bordieris** [comment]
I already saw audio_service, and its example, that doesn't work for me (buttons don't play any sound). I just can't figure out what's the essential part of code I need to use in my player just to have the sound working in background (no controller in lock screen needed, etc.)

**Comment by ryanheise** [comment]
If the `audio_service` example doesn't work for you, I would encourage you to file a bug with that project using the bug issue template.
