### ISSUE TITLE
Clear guidance on setting a distinct HTTP useragent

### ISSUE THREAD

**Issue by jamescridland** [ryanheise/just_audio#302]
**Is your feature request related to a problem? Please describe.**

Podcasters need to know what platform and app is consuming the free content they provide

**Describe the solution you'd like**

a) a clear note to never use the default useragent for a production project

b) a guidance on how to write a useragent

**Describe alternatives you've considered**

There are no alternatives. Bad bot.

**Additional context**

Hi there,

Bit concerned that there is no documentation at https://pub.dev/packages/just_audio about setting the HTTP user-agent. It's vital for podcasters to be able to monitor which app is using the free content that podcasters produce - and ideally there should be:

a) a clear note to never use the default useragent for a production project

b) a guidance on how to write a useragent

just_audio/0.2.0 (Linux;Android 6.0) ExoPlayerLib/2.12.2 is the default useragent.

It should be something like

mypodcastapp/1.2 (Linux;Android 6.0) https://mypodcastapp.com please.

There's a full list of useragents over here: https://github.com/opawg/user-agents

Thank you for helping podcasters everywhere with this.

**Comment by ryanheise** [comment]
_**James Cridland?**_ Nice to have you here!

Thanks for proposing this.

My original rationale for not including such documentation was that it is not traditional for low level audio APIs to give programmers guidance on this, but rather to just leave it up to the programmer to user the API as they see fit.

But in hindsight, there is no harm in providing guidance, and I am aware of the problem this creates for podcasters. I'll see about adding something.

**Comment by jamescridland** [comment]
> it is not traditional for low level audio APIs to give programmers guidance on this

It *is* traditional for HTTP libraries such as this one to have a really clear section on "how to change the user-agent". It's the first thing I typically do, to then contact the podcast app to ask them nicely and give them the exact instructions on how to set it.

https://podnews.net/about/podcast-stats is what comes out of knowing where your audience is: for a product being demonstrated as a podcast player, it would be super-useful to make it really clear how to change the user-agent.

Thanks! :)

**Comment by ryanheise** [comment]
I was talking about traditional "low level audio APIs" which just_audio was originally designed to mirror (Android/iOS/macOS native APIs). These [did](https://developer.android.com/reference/android/media/MediaExtractor#setDataSource(android.content.Context,%20android.net.Uri,%20java.util.Map%3Cjava.lang.String,%20java.lang.String%3E)) [not](https://developer.android.com/reference/android/media/MediaPlayer#setDataSource(android.content.Context,%20android.net.Uri,%20java.util.Map%3Cjava.lang.String,%20java.lang.String%3E)) [provide](https://developer.apple.com/documentation/avfoundation/avurlasset/1508727-urlassetwithurl) such guidance. Note: this was not intended as a point of contention, but merely as background on where that original decision came from.

As someone who sympathises with your cause, I would suggest focusing on the last sentence of my previous reply ;-) It is a point of agreement. Of course you are also welcome to submit a pull request.

A possible way forward:

1. In the immediate term, you can pass on to the podcast app developer in question that the second code snippet in the [README](https://pub.dev/packages/just_audio) shows how to set an HTTP header.

2. In a future documentation release, the second code snippet could be changed to use `user-agent` as the example, and the documentation could mention the best practice. The specific doc pages to be updated are [here](https://pub.dev/packages/just_audio), [here](https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/setUrl.html), [here](https://pub.dev/documentation/just_audio/latest/just_audio/AudioSource/uri.html) and [here](https://pub.dev/documentation/just_audio/latest/just_audio/UriAudioSource/UriAudioSource.html).

3. In a more distant future release, I may consider a breaking API change that would make the user-agent header mandatory on HTTP data sources. Naturally, this would have to be ignored in the web implementation.

**Comment by ryanheise** [comment]
The latest commit adds some instructions in the README on how to set the user agent. It falls short of offering specific guidance on how to write a user-agent string, although I could consider linking to an external, reputable source that does provide such guidance, if you can recommend one.

I've opened a separate issue #305 for the API change that treats `userAgent` as a special parameter.

**Comment by jamescridland** [comment]
Super - thanks. I think that's enough for now.

You could link to https://github.com/opawg/user-agents for examples of useragents if you wanted.

**Comment by ryanheise** [comment]
Thanks, I would probably prefer linking to something more general than podcasting.

Incidentally, I don't understand the opawg list's approach to the "AppleCoreMedia" user agent string. Can you explain it?

This particular user agent string does not identify the Apple Podcasts app, it identifies the core media component that is embedded into many different audio apps. Consequently, this is also the default user agent string when just_audio is running on iOS.

Note that iOS does not document how to change the default user agent using this media player API, and they don't make it easy to change either, so identifying "AppleCoreMedia" with the Apple Podcasts app would significantly inflate the numbers.

I'm sure you're aware of this, but I was curious what your approach is, since it doesn't seem to be evident on the link you provided.

**Comment by jamescridland** [comment]
https://towardsdatascience.com/the-user-agent-that-crazy-string-underpinning-a-bunch-of-analytics-86507ef632f0 has detail of the RFCs behind user-agents. Most important, though, is just to say "please set a user-agent for your own app". 

> Incidentally, I don't understand the opawg list's approach to the "AppleCoreMedia" user agent string. Can you explain it? This particular user agent string does not identify the Apple Podcasts app, it identifies the core media component that is embedded into many different audio apps. ... identifying "AppleCoreMedia" with the Apple Podcasts app would significantly inflate the numbers.

Agreed. It's why OPAWG specifically does not identify it as Apple Podcasts. Here's a snippet:

```
    {
        "user_agents": [
            "^AppleCoreMedia/1\\..*iPhone"
        ],
        "device": "phone",
        "examples": [
            "AppleCoreMedia/1.0.0.15G77 (iPhone; U; CPU OS 11_4_1 like Mac OS X; en_us)"
        ],
        "os": "ios",
        "description": "AppleCoreMedia library",
        "developer_notes": "This is a library used by a number of apps when progressively downloading podcasts. It is not (just) Apple Podcasts, and should not be treated as an Apple Podcasts useragent"
    }
```

We know it's on an iPhone (in this case), and we know it's iOS (in this case), but that's all we know. Apple don't let you change this user-agent: it would be really helpful if they did.

My own approach is to examine the RSS useragent when generating the RSS file, and stamp the audio files with a platform ID. Then, when an app downloads it, instead of downloading `podcast.mp3` it is downloading a file called `podcast.mp3?_from=pocketcasts`. That allows me to, with certainty, apportion that download to PocketCasts rather than Apple Podcasts. You can see my [RSS logs](https://podnews.net/about/rss-stats) and my [podcast download logs](https://podnews.net/about/podcast-stats) - click the "show details" link within these pages to see the full gory detail.

This makes it most useful to use user-agents on both RSS requests *and* audio requests, given the prevalence of "AppleCoreMedia", "Android Download Manager", "dalvik" or similar generic useragents.

**Comment by ryanheise** [comment]
I see, that's an interesting technique.

By the way, I originally looked at the yaml file instead of the json file and it seems to be a bit out of date (it identifies AppleCoreMedia as Apple Podcasts).

**Comment by jamescridland** [comment]
Aha. I think I'll see if anyone noticed if it's deleted...

-- 
https://podnews.net • https://james.cridland.net • https://james.crid.land

Tel/SMS/Signal: +61447692743

**Comment by ryanheise** [comment]
Closing now that #305 is implemented, the README gives a user-agent example, and the API docs provide further details. The README example is admittedly terse, but anything more elaborate tends to make people not read the "read me".
