### ISSUE TITLE
What does "compose audio" mean?

### ISSUE THREAD

**Issue by zxl777** [ryanheise/just_audio#306]
Does it mean playing multiple audio at the same time?

Or playlist ?

**Comment by ryanheise** [comment]
Composition refers to an audio source that has nested children. The composite audio sources are:

* ConcatenatingAudioSource
* LoopingAudioSource
* ClippingAudioSource

These are compositional and can be deeply nested. If you want to play audio files simultaneously, please search for this question on StackOverflow where it has already been answered (link on the "New issue" page)

**Comment by zxl777** [comment]
Thank you. the link is :
https://stackoverflow.com/questions/65390691/how-to-play-two-or-more-audio-files-simultaneously-with-just-audio-and-audio-s

I tried the flutter_sound: ^7.5.3+1, flutter_sound_lite: ^6.2.0, audioplayers: ^0.17.3
In the end just_audio was selected, I was even more surprised that I finally found just_audio, because I have been searching pub.dev with the keyword is "sound" https://pub.dev/packages?q=sound

**Comment by ryanheise** [comment]
That's really interesting, I had completely failed to mention the word "sound" anywhere in the plugin so it wasn't searchable by that word. This should be corrected in the latest update. Thanks for sharing that!
