### ISSUE TITLE
ProcessingState.Completed not triggered until end of ConcatenatingAudioSource

### ISSUE THREAD

**Issue by smkhalsa** [ryanheise/just_audio#316]
**Which API doesn't behave as documented, and how does it misbehave?**

The `ProcessingState.Completed` state is only triggered when the final source in a `ConcatenatingAudioSource` has completed.

I assume this is not the intended behavior, but if it is, what is the recommended way to be notified when each individual track completes?

**Minimal reproduction project**

The example

**To Reproduce (i.e. user steps, not code)**

In the example, set a listener on the player that triggers when the ProcessingState == Completed. 

```dart
    _player.processingStateStream
        .where((state) => state == ProcessingState.completed)
        .listen((state) {
      print(state);
    });
```

**Error messages**

N/A

**Expected behavior**

`ProcessingState.Completed` should fire when each child source of the ConcatenatingAudioSource completes

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: MacOS

**Smartphone (please complete the following information):**
 - Device: iPhone12 Pro Max simulator

**Flutter SDK version**
```
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.1)
[✓] Connected device (2 available)
```

**Additional context**

N/A

**Comment by smkhalsa** [comment]
Also, I need to be able to pause the player when the current track completes *before* the player seeks to the next track.

**Comment by ryanheise** [comment]
This is intended behaviour, but there will in future be additional streams for listening to track changes.

Can you check if #174 is what you want? If so, I'll close this as a duplicate of that issue.

Note that a workaround is also posted in that issue.

**Comment by smkhalsa** [comment]
Hmm, ok. What's the reasoning for not firing ProcessingState.Completed when each child of the concatenating source completes?

That seems like the most intuitive to me, but I'm probably missing something.

Simply comparing indices won't work for my use case.

I'm trying to log each unique "listen" for each child source, and if "repeat one" is on, the index wouldn't change.

**Comment by smkhalsa** [comment]
To expand on my use case a little more, I define a unique "listen" as having listened to at least 30 seconds of a particular song (or the entire duration if it's shorter). I keep a Set of seconds that have been listened to, then log the listen when the length of that Set exceeds 30. I need to then clear the set when the song reaches its end so that if a user has the song on repeat, it will be treated as a new listen.

**Comment by ryanheise** [comment]
> Hmm, ok. What's the reasoning for not firing ProcessingState.Completed when each child of the concatenating source completes?
> 
> That seems like the most intuitive to me, but I'm probably missing something.

It is based on the exoplayer model. Your use case would need to be handled by a new feature, but it sounds like #174 .

> I'm trying to log each unique "listen" for each child source, and if "repeat one" is on, the index wouldn't change.

True, that means my suggested workaround on #174 isn't perfect although the feature itself described in #174 sounds like what you need.

I am holding off any changes that involve the platform interface until after null safety reaches stable but in the meantime I would suggest describing your use case on that issue, and I can probably provide a better workaround that will work with loop one.

**Comment by smkhalsa** [comment]
Thanks @ryanheise.

> It is based on the exoplayer model.

Got it. I've taken a look at the exoplayer API and understand now that this would be implemented as a separate `onPositionDiscontinuity` listener with a `reason` of `Player.DISCONTINUITY_REASON_PERIOD_TRANSITION`

> I am holding off any changes that involve the platform interface until after null safety reaches stable

Understood.

> I would suggest describing your use case on that issue, and I can probably provide a better workaround that will work with loop one.

I've added a comment to #174. I'd definitely appreciate any workarounds you may be able to suggest.
