### ISSUE TITLE
Sleep timer

### ISSUE THREAD

**Issue by AliHoseinpoor** [ryanheise/just_audio#320]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
Is it possible to set a sleep time for the player?
For example, a playlist is running and we set the player to stop after 10 minutes.

**Describe alternatives you've considered**
None 

**Additional context**
None

**Comment by ryanheise** [comment]
```dart
await Future.delayed(Duration(minutes: 10));
await player.pause();
```

Due to its single responsibility design, the plugin is just responsible for paying audio, and where there is a more appropriate API to handle some other responsibility, like timers, it is preferable to use it. Note that dart also has a Timer class which could be used to provide this functionality, so there are several alternatives.

just_audio does provide higher precision timing for single items in the form of clipping but if your duration is 10 minutes, then you probably don't need that.

**Comment by AliHoseinpoor** [comment]
> ```dart
> await Future.delayed(Duration(minutes: 10));
> await player.pause();
> ```
> 
> Due to its single responsibility design, the plugin is just responsible for paying audio, and where there is a more appropriate API to handle some other responsibility, like timers, it is preferable to use it. Note that dart also has a Timer class which could be used to provide this functionality, so there are several alternatives.
> 
> just_audio does provide higher precision timing for single items in the form of clipping but if your duration is 10 minutes, then you probably don't need that.

Because the timer must work in the background, you can not use the flutter timer itself because it does not work in the background.
I guess it might be the best place to use a timer in audio_service

**Comment by ryanheise** [comment]
Even in audio_service, iOS will suspend the process if it's inactive for a while (i.e. not playing audio). But since you will be playing audio for the duration of the timer, I don't expect that to be an issue in your case.

**Comment by AliHoseinpoor** [comment]
> Even in audio_service, iOS will suspend the process if it's inactive for a while (i.e. not playing audio). But since you will be playing audio for the duration of the timer, I don't expect that to be an issue in your case.

Thank you very much for your help.
Yes, I only need the timer when playing a song and I do not think there will be a problem if I use the timer in audio_service
