### ISSUE TITLE
ClippedAudioSource missing duration

### ISSUE THREAD

**Issue by smkhalsa** [ryanheise/just_audio#321]
**Which API doesn't behave as documented, and how does it misbehave?**

When setting a clipped version of the previous audio source, the duration doesn't get set correctly.

**Minimal reproduction project**

https://github.com/smkhalsa/just_audio/commit/4457877f25dc3e70a43758d947c433b7b184ba8a

**To Reproduce (i.e. user steps, not code)**

1. Set a normal (i.e. non-clipped) audio source.
2. Set a clipped audio source using the same URI

The returned Future from step 2 is null, and the `player.durationStream` doesn't receive the correct updated duration. 

**Error messages**

N/A

**Expected behavior**

I expected the Future returned by the second call to `setAudioSource` to resolve to the correct Duration for the clipped source.

I also expected the `player.durationStream` to trigger with the duration for the clipped source.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: MacOS

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max

**Flutter SDK version**
```
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (3 available)
```

**Additional context**

N/A

**Comment by ryanheise** [comment]
Interesting, thanks for finding this bug. It turns out there were a few bugs related to setting a `ClippingAudioSource` after another audio source had already been set. This is due to some optimisations the code tried to make to detect and reuse the buffer of decoded data for the same URL.

This should be fixed in the latest commit (to `master` for the moment - `nnbd` will come later). Can you let me know how it goes?

**Comment by smkhalsa** [comment]
@ryanheise thanks for the quick fix. I've tested it, and it is now working correctly.

**Comment by ryanheise** [comment]
Great to know, thanks!
