### ISSUE TITLE
Playing audio from remote stream of WebRTC connection

### ISSUE THREAD

**Issue by AniketBhadane** [ryanheise/just_audio#322]
**Is your feature request related to a problem? Please describe.**
Playing audio received from Remote stream in WebRTC connection.

**Describe the solution you'd like**

    MediaStream _localStream = await createStream();
    RTCPeerConnection pc = await createPeerConnection({});
    
    _localStream.getTracks().forEach((track) async => await pc.addTrack(track, _localStream));	
    
    pc.onTrack = (event) {
      // how can I play the Audio stream in event.streams[0] ?
    };
    	
    Future<MediaStream> createStream() async {
      final Map<String, dynamic> mediaConstraints = {
        'audio': true,
        'video': false
      };
    
      MediaStream stream = await MediaDevices.getUserMedia(mediaConstraints);
      return stream;
    }

**Describe alternatives you've considered**
I did not find an alternative

**Additional context**
The code snippet above shows the requirement in the onTrack method

**Comment by ryanheise** [comment]
Have you considered [flutter_webrtc](https://pub.dev/packages/flutter_webrtc) ?

**Comment by AniketBhadane** [comment]
> Have you considered [flutter_webrtc](https://pub.dev/packages/flutter_webrtc) ?

Yes, I have. The code snippet is from the flutter_webrtc plugin examples itself. But it does not provide any way to play Audio. Is there any way in Flutter to play Audio in a MediaStream?

**Comment by ryanheise** [comment]
Taking a brief look at flutter_webrtc, it looks like `MediaStream` can only be played internally by that plugin. So the only way forward would be to add a feature request to that project (which I can see you have already done). I'll close this feature request since it is not appropriate for inclusion in just_audio.
