### ISSUE TITLE
Playing audio from base64 data

### ISSUE THREAD

**Issue by AniketBhadane** [ryanheise/just_audio#323]
**Is your feature request related to a problem? Please describe.**
Playing audio from base64 data

**Describe the solution you'd like**
Playing audio from base64 data

**Describe alternatives you've considered**
I suppose [audioplayers ](https://pub.dev/packages/audioplayers)plugin has following:
```
  playLocal() async {
    Uint8List byteData = .. // Load audio as a byte array here.
    int result = await audioPlayer.playBytes(byteData);
  }
```

**Additional context**
The base64 data may be received from the server as result of an api call

**Comment by ryanheise** [comment]
Hi @AniketBhadane 

Playing audio from a byte stream is listed in the README as one of the supported features. You can use `StreamAudioSource`.

**Comment by AniketBhadane** [comment]
> Hi @AniketBhadane
> 
> Playing audio from a byte stream is listed in the README as one of the supported features. You can use `StreamAudioSource`.

Hi @ryanheise, I could not see any examples for using StreamAudioSource. Please can you guide on the usage of StreamAudioSource?

**Comment by ryanheise** [comment]
I am not at my computer right now but if you search for that class name on this GitHub issues page you will be able to find examples.

**Comment by AniketBhadane** [comment]
> I am not at my computer right now but if you search for that class name on this GitHub issues page you will be able to find examples.

From [#187 ](https://github.com/ryanheise/just_audio/issues/187), I saw to following code:

class MyAudioSource extends StreamAudioSource {
  Uint8List _buffer;

```
  MyAudioSource(this._buffer) : super("Bla");

  @override
  Stream<List<int>> read([int start, int end]) {
    return Stream.value(_buffer.skip(start).take(end - start));
  }

  @override
  int get lengthInBytes {
    return _buffer.length;
  }
}

await player.setAudioSource(MyAudioSource(buffer));
```

When you get time , please can you let me know whether this is how its supposed to be done?

**Comment by AniketBhadane** [comment]
Just to add to the question, my data looks like `data:audio/ogg;base64,xxxxxxxxx`. Does that mean `UriAudioSource` can be used as well?

**Comment by ryanheise** [comment]
Yes that is correct although the API has changed slightly since then. Can you take a look at the new API documentation and give me feedback? If it is not good enough, I will improve it.

**Comment by ryanheise** [comment]
> Just to add to the question, my data looks like `data:audio/ogg;base64,xxxxxxxxx`. Does that mean `UriAudioSource` can be used as well?

You should first convert it into a byte array.

**Comment by AniketBhadane** [comment]
> > Just to add to the question, my data looks like `data:audio/ogg;base64,xxxxxxxxx`. Does that mean `UriAudioSource` can be used as well?
> 
> You should first convert it into a byte array (Dart has standard libraries which you can search for for decoding base64 data into a byte array).

OK, thank you, please can you let me know whether the code I pasted above having `MyAudioSource` is how its supposed to be done? When you get time.

**Comment by ryanheise** [comment]
I already replied to you:

> Yes that is correct although the API has changed slightly since then. Can you take a look at the new API documentation and give me feedback? If it is not good enough, I will improve it.

**Comment by AniketBhadane** [comment]
> I already replied to you:
> 
> > Yes that is correct although the API has changed slightly since then. Can you take a look at the new API documentation and give me feedback? If it is not good enough, I will improve it.

It would be very helpful if the documentation is updated with how to play audio from such base64 data. I personally could not find concrete examples on how to play such data. Please let me know your thoughts.

**Comment by ryanheise** [comment]
Are you unsure how to convert base64 data into an array of raw bytes?

**Comment by AniketBhadane** [comment]
> Are you unsure how to convert base64 data into an array of raw bytes?

I think I can convert base64 to Uint8List using base64.decode function. But I'm not sure how to play audio from this Uint8List. As you mentioned that the API has been slightly modified since then, is the code mentioned in above comment the right way to do it?

**Comment by ryanheise** [comment]
> As you mentioned that the API has been slightly modified since then, is the code mentioned in above comment the right way to do it?

Sorry if I was being unclear. What I meant is that that code has the right "idea" and should at least give you inspiration on how to go about it, but you will also need to consult the documentation.

**Comment by ryanheise** [comment]
@AniketBhadane I'll close this feature request since `StreamAudioSource` exists (although possibly future versions of just_audio will provide an alternative to `StreamAudioSource` for a byte array rather than a stream.)
