### ISSUE TITLE
Package upgrade crash

### ISSUE THREAD

**Issue by denkoul** [ryanheise/just_audio#326]
Because just_audio >=0.3.0 <0.7.0-nullsafety.0 depends on uuid ^2.2.0 and [My Project] depends on uuid ^3.0.1, just_audio >=0.3.0 <0.7.0-nullsafety.0 is forbidden.
So, because consultation depends on just_audio ^0.6.14+1, version solving failed.
pub get failed (1; So, because [My Project] depends on just_audio ^0.6.14+1, version solving failed.)

**Comment by denkoul** [comment]
Also the same with `path_provider: ^2.0.0`

**Comment by ryanheise** [comment]
(hmm, I guess my bot is inactive?)

This does not look like a crash, it looks like you just need to upgrade your dependencies to nullsafe versions. You didn't include any of sections requested in the bug report template so I don't know what sdk version you're using, but you can try upgrading your just_audio dependency to the latest nullsafety release which is `0.7.0-nullsafety.2`.

**Comment by ryanheise** [comment]
Closing based on the previous comment.
