### ISSUE TITLE
Cancel Loading or connecting audio

### ISSUE THREAD

**Issue by ReaganRealones** [ryanheise/just_audio#33]
How possible is it to cancel a loading audio i.e an audio in "AudioPlaybackState.connecting" state as neither dispose or stop work on it as shown on the usage tips in the IDE. So if the audio is still connecting and the user cancels, how can I Stop the loading of this file as right now, it continues loading and plays thereafter.

**Comment by ryanheise** [comment]
I'm currently working on addressing issue #28 which should allow you to call `stop` during the `connecting` state. Hopefully will commit within the day.

**Comment by ReaganRealones** [comment]
Okay, thank you so much... Will be waiting or checking on you tomorrow :)

**Comment by ryanheise** [comment]
You can try the latest git commit to see if it helps. Note: this primarily addresses an issue on Android. If your issue is on iOS, then I might need more information on what the error is.

**Comment by ReaganRealones** [comment]
@ryanheise, the `buffering` state seems to have been removed? So how can I know when the audio is buffering?

**Comment by ryanheise** [comment]
Hi @ReaganRealones , there is more information about the change in #28 linked above where I gave an explanation of the new state model.

**Comment by ReaganRealones** [comment]
@ryanheise, okay sure have checked it out. Understood, that but the issue is still, while the player is connecting and the user cancels, it still continues to connect and thereafter plays. i.e calling `stop` while the player is in `connecting` state does not cancel playing music,

**Comment by ryanheise** [comment]
I am using #28 to track this issue so I have copied your question over to there. Please take a look as I've left you a reply/question.

**Comment by ReaganRealones** [comment]
@ryanheise, sure thing.... Going to head over there
