### ISSUE TITLE
pls support

### ISSUE THREAD

**Issue by sigjak** [ryanheise/just_audio#330]
**Is your feature request related to a problem? Please describe.**
Currently playing .pls files seems not to be supported.

**Describe the solution you'd like**
Supporting buffering and playing .pls files, a common format for many BBC radio streams

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by keaganhilliard** [comment]
May not be what you are looking for but it looks like .pls files are just text files that contain a list of urls. It's probably best to write a simple parser and then pass the resulting list of URIs to `just_audio`

**Comment by sigjak** [comment]
Your are absolutely right. Thank you for the help!
