### ISSUE TITLE
VisibilityDetector Feature

### ISSUE THREAD

**Issue by maares** [ryanheise/just_audio#335]
Hi I've been using the library a few hours, I'm amazed on the simplicity and keen implementation!

**Is your feature request related to a problem? Please describe.**
As a user I would like to have an option to listen to audio "widget" Visibility, the same way you listen to Stream.

Simplified Use case intended to stop audio on onVisibilityChange (custom logic by user)
-App contains two Tabs
-Tab A contains a list of Audios
-Tab B contains a list of Audios
-Tab A is playing an Item of list of Audios
-User switched to Tab B, 
-Widget no longer visible but audio keeps playing (which is not intended)

Simplified Use case intended to Keep audio on onVisibilityChange (custom logic by user)
-App contains an article with a podcast
-User plays podcast and continues to scroll down to read the article
-Widget no longer visible but audio keeps playing (which is intended)

**Describe the solution you'd like**
As you set the AudioSource

```
await audioPlayer.setAudioSource(
        AudioSource.uri(Uri.parse(audioUrl)),
      );
```
You could also set the overlay controls
```
audioPlayer.setAudioOverlay(widget:  myCustomAudioControlsWidget());
```

This widget which contains the controls of audioPlayer on top of it has [VisibilityDetector](https://github.com/google/flutter.widgets/tree/master/packages/visibility_detector) implementation, which will stream it's "Fraction of visibility"to audioPlayer.

```
audioPlayer.visibilityStream.listen((event) async {
        await visibilityStreamListener(event: event);
      });

```
```
Future<void> visibilityStreamListener({required double fraction}) async {
        ///0 meaning is no longer visible
        if(fraction == 0) audioPlayer.stop();
        
        ///just play once you build
        if(fraction > 0) audioPlayer.play();
}
```

**Additional context**
This might reduce the redundancy of having separated logic (widget & audio player) to control the audio stream in different scenarios

**Comment by ryanheise** [comment]
Thanks for your kind words, although this feature is not a good fit for just_audio.

By design, just_audio has no dependencies on widgets. The design philosophy of just_audio is that it "just" plays audio (i.e. it's a single responsibility plugin). Anything that can in theory be provided by an external plugin will not be incorporated into just_audio. In this case, I am certain that the app itself could implement this logic without requiring any changes to the plugin.

**Comment by maares** [comment]
Hi @ryanheise, I understand and respect 100% your line of thought. Already implemented VisibilityDetector on the UI as you mention. Thanks for the response and your awesome library!
