### ISSUE TITLE
does this plugin plays audio in background automatic ??

### ISSUE THREAD

**Issue by Rabyn900** [ryanheise/just_audio#344]
**To which pages does your suggestion apply?**

- Direct URL 1
- Direct URL 2
- ...

**Quote the sentences(s) from the documentation to be improved (if any)**

> Insert here. (Skip if you are proposing an entirely new section.)

**Describe your suggestion**

...

**Comment by ryanheise** [comment]
As this is a question rather than a valid documentation request, please ask it via StackOverflow.
