### ISSUE TITLE
Music keeps playing

### ISSUE THREAD

**Issue by alazarLaz** [ryanheise/just_audio#349]
Music keeps playing even when the music Instance.pause() is called. I was Trying to play another song from music list by pausing the old one but both keep playing, what should I do?

**Comment by ryanheise** [comment]
> Music keeps playing even when the music Instance.pause() is called. I was Trying to play another song from music list by pausing the old one but both keep playing, what should I do?

It sounds like it may be a bug, so I would recommend filling in a bug report. See the instructions for how to do it when you click on new issue.
