### ISSUE TITLE
iOS Testing help wanted

### ISSUE THREAD

**Issue by ryanheise** [ryanheise/just_audio#35]
All features mentioned in the README as "untested" for iOS are virtually all implemented, although just not 100% confirmed through testing.

If an untested feature works for you, I would be grateful if you could report that below and I will reflect that in the README.

**Comment by codeeuser** [comment]
I am using iOS. I found sound from assets is not working.

**Comment by ryanheise** [comment]
Thanks @codeeuser , if you encounter a bug, I would suggest opening a new issue / bug report, supplying information such as the error logs and example code used to reproduce the bug.

Can you confirm whether anything did work?

**Comment by MickaelHrndz** [comment]
Hello,

Audio streaming from URL is not working on an **iPhone 4s** with **iOS 9.3.6**. Just_audio doesn't output any message. Audio_service is wrapped around it but also tried with an AudioPlayer by itself. I have the wifi turned on.

On an **iPhone 5 (iOS 10.3.1) simulator**, XCode raises these errors :
```
Undefined symbol: _FlutterMethodNotImplemented
Undefined symbol: _FlutterEndOfEventStream
Undefined symbol: _OBJC_CLASS_$_FlutterEventChannel
Undefined symbol: _OBJC_CLASS_$_FlutterCallbackCache
Undefined symbol: _OBJC_CLASS_$_FlutterEngine
Undefined symbol: _OBJC_CLASS_$_FlutterMethodChannel
```
There is also a number of warnings. Here is a screenshot  : https://imgur.com/a/PteK1Zx

On **iPhone 5s (iOS 10.3.1)** simulator (and iPhones above), it works fine. I couldn't try a 4s simulator.

**Comment by viniciuszani** [comment]
Tested `read from file` from iOS with `mp3` files and it works as expected.
One disclaimer: the AVPlayer apparently can't play files without an extension (`.mp3`). Be sure to add it when saving files locally to be played.

Models where tests were conducted:
- iPhone 6s (iOS 13.3.1)
- iPhone 11 (OS 13.3.1) 
- iPhone X (OS 13.3.1)

**Comment by suragch** [comment]
What is the status on this? The lack of confirmed iOS support is the one thing that is making me hesitate to switch to this library.

**Comment by snaeji** [comment]
I have been using this player and testing for two types on iOS:

- Mp3 files from url (Works great)
- HLS live streams with 2 hours seeking window (Small issues)

The issues regarding the HLS live stream are that the duration and position are negative values. I have some Swift code that i use to check for a sliding window, will try to convert it to objective-C or share it in an issue.

**Comment by ryanheise** [comment]
I will close this issue as there have since been several feature-specific issues opened for iOS, and I will be able to handle any remaining issues in this fashion. Thank you to those who helped testing the very first version of just_audio!
