### ISSUE TITLE
Pending timers during flutter tests

### ISSUE THREAD

**Issue by minhqdao** [ryanheise/just_audio#356]
**Which API doesn't behave as documented, and how does it misbehave?**
When an instance of `AudioPlayer()` is created the usual way, a `!timersPending` error is obtained during `flutter test` although `_audioPlayer`is properly disposed.

**Minimal reproduction project**
The example

**To Reproduce**
1. Remove the `expect` method from `widget_test.dart`
2. Run `flutter test`

**Error messages**

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1245 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1245:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:806:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
...

The test description was:
  Verify Platform version
```

**Expected behavior**
There should be no pending timers after the audio player was disposed.

**Desktop:**
 - Run `flutter test` in your terminal

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-arm,
    locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

**Additional context**
Alternative way to reproduce: Create an instance of `AudioPlayer()` in any project, call `_audioPlayer.dispose()` in the state's dispose method and run `flutter test`.

**Comment by ryanheise** [comment]
Thanks, @minhqdao . I use a timer for `positionStream` so maybe that's it. Perhaps we just need to add a brief delay before the test finishes so that the `positionStream` has enough time to release all of its momentum.

**Comment by ryanheise** [comment]
I just tried to reproduce this but I'm not sure what you mean by removing `expect`. This is called 168 times - do you mean remove each of those 168 method calls?

**Comment by minhqdao** [comment]
Thanks for checking, @ryanheise ! I meant the test file inside `just_audio/just_audio/example/test`. It includes a single expect call, which also threw an error. So changing it to expect something that exists or removing it leaves you with the `!timerspending` error.

This issue could also be reproduced in other projects of ours. If it helps you, I'll provide you with a link tomorrow. I also tried pumping for certain durations, but the problem still persisted. And this part also looks somewhat suspicious to me:

```
    currentTimer = Timer.periodic(step(), yieldPosition);
    durationSubscription = durationStream.listen((duration) {
      currentTimer.cancel();
      currentTimer = Timer.periodic(step(), yieldPosition);
    });
    playbackEventSubscription = playbackEventStream.listen((event) {
      controller.add(position);
    });
    return controller.stream.distinct();
```

**Comment by ryanheise** [comment]
Ah, I see. I don't actually use that directory anyway which is why I didn't notice anything.

I should probably let you know that recently (for medical reasons) I'm struggling a bit to do everything myself at the moment. i am still figuring out how to proceed from here because there is so much more that I want to achieve with this library, but I may need to start leaning on the community more. Would you be interested in helping to make the project better by looking at this particular issue in the context of your own project and if you have any success finding the cause, maybe you would consider contributing a pull request?

**Comment by minhqdao** [comment]
Sorry to hear about your (hopefully temporary) situation. Alright then, I'll give it a try over the next couple of days/Easter. However, I'm quite new to all of this and I wouldn't consider myself an expert on working with streams yet. But you gotta start somewhere, right? I'll let you know if it worked. 🙂
