### ISSUE TITLE
stopping player in loading state makes it no-op

### ISSUE THREAD

**Issue by nt4f04uNd** [ryanheise/just_audio#367]
**Which API doesn't behave as documented, and how does it misbehave?**
on any device, stopping the player in "loading" state makes it completely no-op

**Minimal reproduction project**
example app from audio_service https://github.com/ryanheise/audio_service/tree/one-isolate/audio_service/example

**To Reproduce (i.e. user steps, not code)**
in loading state stop the player

**Error messages**
none

**Expected behavior**
player would behave normally

**Screenshots**

https://user-images.githubusercontent.com/39104740/113491594-b2e3ff80-94da-11eb-84da-b72975a2aeb1.mp4

**Desktop (please complete the following information):**
see flutter doctor

**Smartphone (please complete the following information):**
see flutter doctor

**Flutter SDK version**
<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel unknown, 2.1.0-13.0.pre.391, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.391 at c:\dev\src\flutter
    • Framework revision 9609753089 (24 hours ago), 2021-04-03 00:39:00 +0300
    • Engine revision 9651d11fe8
    • Dart version 2.13.0 (build 2.13.0-190.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (5 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
</details>

**Additional context**
no

**Comment by ryanheise** [comment]
`load()` or `setAudioSource()` will call `_setPlatformActive(true)` which will allocate the decoder, and `stop()` will call `_setPlatformActive(false)` which will release the decoder.

We need to obviously be careful about apps simultaneously calling different methods on the same player instance where one is activating the platform resources and the other is deallocating them, so there is some "carefully" written code in `_setPlatformActive` (but obviously not careful enough) to ensure that simultaneous requests are not lost.

Will need to debug to understand what's going on.

**Comment by ryanheise** [comment]
I have added a fix on the `minhqdao-fix_timers` branch. Let me know how it goes for you. This section of code is a bit tricky to work with so hopefully it doesn't cause any new issues, but at least all of the unit tests are passing.

**Comment by ryanheise** [comment]
Can you confirm whether this works for you? If so, I will try to push out a release.

**Comment by nt4f04uNd** [comment]
i will check that the next day (i'm going to sleep now)

**Comment by nt4f04uNd** [comment]
seems to be working out fine for me

**Comment by ryanheise** [comment]
Fix is merged and published.
