### ISSUE TITLE
Notification native

### ISSUE THREAD

**Issue by isaac5003** [ryanheise/just_audio#373]
**Is your feature request related to a problem? Please describe.**

it's not a problem, it's an improvement. I would like you to add native notification

**Describe the solution you'd like**

I would like them to add the notification functionality in the notification bar in Android and IOS that can be customizable

**Describe alternatives you've considered**

An alternative could be: 1) customizable titles
2) customizable image
3) customizable notification colors
4) customizable buttons for example that you can add buttons for play, pause, next, previous

**Additional context**

.attached reference image
![20210408_015959](https://user-images.githubusercontent.com/65372686/113992219-75e87780-9810-11eb-8c78-027693e0e904.png)

**Comment by mvolpato** [comment]
@isaac5003  You can achieve that by combining `just_audio` with [`audio_service`](https://github.com/ryanheise/audio_service).

**Comment by ryanheise** [comment]
Yes, this is also pointed out in the README (search the README for mention of audio_service). If you follow the link to audio_service you will see it also comes with an example showing integration with just_audio.

I'm working on a new version of audio_service that will make things even easier, and I hope to eventually provide a plug-n-play option called just_audio_background (see the pull request, but it's not ready for use yet and won't be until the new version of audio_service is ready). So for now, you can follow the audio_service example.

**Comment by isaac5003** [comment]
@mvolpato , @ryanheise  Thanks for taking the time to reply

**Comment by rupakswadesh** [comment]
In just_audio_background package, can i remove stop button from notification media control?

**Comment by ryanheise** [comment]
To just the update this topic, yes just_audio_background beta has now been released.

It doesn't have any options to configure which buttons to show, that's all hard coded. However, I am taking feature requests for this. Please open a new feature requests describing your use case, and I'll close the current issue.
