### ISSUE TITLE
Laggy audio on screen off or If the app is in background

### ISSUE THREAD

**Issue by mustafabhatkar** [ryanheise/just_audio#376]
First of all, Thank you for creating this package and sharing it with us. 

**Which API doesn't behave as documented, and how does it misbehave?**
`await player.setLoopMode(LoopMode.one);
await player.play();`

**Minimal reproduction project**
https://github.com/mustafabhatkar/just_audio.git

I've updated the project with the "audio_service" package

**To Reproduce (i.e. user steps, not code)**

Run the app
1.  Tap play
2. Turn off the screen or put the app in the background

**Error messages**
No error message but the audio is super laggy and happens only If the screen is off or If the app is in the background

Here is the sample of laggy audio when played in the background 
https://drive.google.com/file/d/1xNEQ3esQaHY2mL2hM6n5ASEXTdf8GlMo/view?usp=sharing

**Expected behavior**
Audio should play without any lag

**Smartphone (please complete the following information):**
 - Device: Oneplus 5
 - OS: Android 10

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.55.1)
[√] Connected device (3 available)

• No issues found!
```

**Additional context**
I tried to put my audio code in the Background Task using the **audio_service** package. But the lag was still there when the app was in the background or on screen off.
In my app, I am playing an mp3 file from assets. My audio file is similar to "Nature Sounds" used in The Example project and it plays fine when the app is in the foreground. But when I set the loop mode to "LoopMode.one" and put the app in the background or turn off the screen It becomes super laggy.

**Comment by ryanheise** [comment]
It is worth pointing out that the example is not designed to run in the background, so you may need a different minimal reproduction project. I have tested the audio_service example itself and did not notice any lag.

**Comment by mustafabhatkar** [comment]
Hi @ryanheise,

I've added the minimal reproduction project link and the laggy audio sample in the **Error messages**. I've used the "audio_service" package in the reproduction project.
I tested out the app on Xiaomi redmi 7A and the audio played smoothly on that device in the background and foreground.

It is very laggy on Oneplus 5 though, please listen to the sample in **Error messages**

**Comment by mvolpato** [comment]
@mustafabhatkar did you try the [example from audio_service](https://github.com/ryanheise/audio_service/blob/master/example/lib/main.dart) on the Oneplus 5 as well?

**Comment by mustafabhatkar** [comment]
No, I only tested the [just_audio example](https://github.com/ryanheise/just_audio/tree/master/just_audio/example) and because there was a lag, I tried putting the audio playback code in  [audio_service](https://pub.dev/packages/audio_service)'s background task hoping that the lag would go away. But it didn't help :(

I will try the **audio_service**  example as well and let you know.

**Comment by mustafabhatkar** [comment]
Playback was smooth once I enabled the notification in **audio_service**'s background task using   **AudioServiceBackground.setState()** method

**Comment by leidig54** [comment]
I'm also having this issue on a Samsung S8.

Looped audio, when the app is in the background, crackles/lags after a minute or so. Returning the app to the foreground restores normal playback.

Is there a solution that doesn't involve implementing audio_service?

**Comment by ryanheise** [comment]
For correct background operation on Android, you must display a system notification to alert the user that your app is consuming resources in the background. So at some point you will need to decide what content you want to display in that notification, and you'll need a plugin for that (e.g. audio_service or the upcoming just_audio_background).
