### ISSUE TITLE
currentPosition stream more precise

### ISSUE THREAD

**Issue by TorstenFH** [ryanheise/just_audio#379]
**Is your feature request related to a problem? Please describe.**
I would like to have a more accurate position of the audio stream playing long audio files (about 4-6 min). (music app with visual metronome which has to be really precise). The precision on short audio files or if you play only parts with .setClip() is very much higher.
 
**Describe the solution you'd like**
Would be perfect to have the stream more precise reproducing longer audio files.

**Describe alternatives you've considered**
I'm testing putting ClippedAudioSource-parts of the same audio file in a row to increase precision: That works but I have tiny gaps between the clips. 

**Additional context**
That's the output of the stream of long audio file (4 min):
flutter: 0:00:00.000000
flutter: 0:00:00.054140
flutter: 0:00:00.167762
flutter: 0:00:00.366783
flutter: 0:00:00.533532
flutter: 0:00:00.573075
flutter: 0:00:00.766909
flutter: 0:00:00.969712
flutter: 0:00:01.167380

That's the output of the same audio file clipped - duration about 10 seconds:
flutter: 0:00:00.000000
flutter: 0:00:00.000422
flutter: 0:00:00.010100
flutter: 0:00:00.049084
flutter: 0:00:00.088383
flutter: 0:00:00.128441
flutter: 0:00:00.159397
flutter: 0:00:00.192391
flutter: 0:00:00.224440
flutter: 0:00:00.255870
flutter: 0:00:00.288338
flutter: 0:00:00.323036
flutter: 0:00:00.353224
flutter: 0:00:00.387712
flutter: 0:00:00.424481
flutter: 0:00:00.454398
flutter: 0:00:00.487521
flutter: 0:00:00.527156
flutter: 0:00:00.560073
flutter: 0:00:00.591127
flutter: 0:00:00.640827
flutter: 0:00:00.672362
flutter: 0:00:00.706826
flutter: 0:00:00.738610
flutter: 0:00:00.771073
flutter: 0:00:00.806330
flutter: 0:00:00.837457
flutter: 0:00:00.870430
flutter: 0:00:00.911650
flutter: 0:00:00.943860
flutter: 0:00:00.975498
flutter: 0:00:01.008404

**Comment by ryanheise** [comment]
`positionStream` was intended for UI animations where fewer updates are required on long audio. But your use case is a much simpler one, and probably doesn't require a library feature. Two ways:

1. You could use `createPositionStream` and adjust the min and max periods to your liking.
2. You could simply create a periodic stream using standard Dart libraries that emits a value every X milliseconds. You can choose the value to emit, so you could just emit the player's current position.

**Comment by TorstenFH** [comment]
Wow, thank you so much. I didn't see `createPositionStream`. Works perfect!!!
