### ISSUE TITLE
codec does not support config priority (err -2147483648)

### ISSUE THREAD

**Issue by gOzaru** [ryanheise/just_audio#381]
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio: ^0.6.15+1
I had to use this because the newest version gets conflict with Firebase Admin.
I am trying to open Mp3 file from link in Param['url'] written in Error messages below. 
It worked if you copy the link and paste it in browser.  

**Minimal reproduction project**
Sorry this repository is my client's project. 

**To Reproduce (i.e. user steps, not code)**
1. Run debug mode
2. Click on Song: "Lost in Nowhere"
3. Wait for opening new Page
4. See error: codec does not support config priority (err -2147483648)

**Error messages**
```
I/ExoPlayerImpl(24003): Init b29f453 [ExoPlayerLib/2.13.1] [generic_x86_64, Android SDK built for x86_64, unknown, 26]
I/OMXClient(24003): Treble IOmx obtained
I/ACodec  (24003): codec does not support config priority (err -2147483648)
D/AudioTrack(24003): Client defaulted notificationFrames to 3675 for frameCount 11025
I/flutter (24003): Param['url']: https://firebasestorage.googleapis.com/v0/b/testfirebase-599e9.appspot.com/o/data%2Fuser%2F0%2Fcom.example.firebase_music_app%2Fcache%2Ffile_picker%2FLost%20In%20Nowhere.mp3?alt=media&token=63ceefae-6596-4881-b7f4-9230dc08bec8
I/zygote64(24003): Background concurrent copying GC freed 14679(1245KB) AllocSpace objects, 18(524KB) LOS objects, 49% free, 5MB/10MB, paused 14.620ms total 126.451ms
```

**Expected behavior**
It has to run the Audio mp3 very well, but somehow it gives different error. 

**Screenshots**
[Code](https://pasteboard.co/JXOcvX1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Android Studio Emulator 
 - OS: SDK 30

**Flutter SDK version**
```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.4 at G:\Flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at G:\SDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.55.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 8.0.0 (API 26) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 90.0.4430.72
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!
```

**Additional context**
I hope I can find out where it goes wrong. 
Thank you for helping out.

**Comment by ryanheise** [comment]
The 0.6.x series is no longer supported so if there is a bug it will need to be tested and fixed on the 0.7 series or later. Note however that errors of this sort are usually due to the codec support of Google's ExoPlayer library itself and cannot be fixed directly in just_audio. You can try reporting a bug upstream with ExoPlayer if that is the case.

**Comment by gOzaru** [comment]
I just changed to latest version of just_audio: ^0.7.4 
It seems that the just_audio cannot accept URL which has ? symbol. 
I used 
`audioPlayer.setUrl("params['url']"); //error here `
This is my URL: 
[link to mp3](https://firebasestorage.googleapis.com/v0/b/testfirebase-599e9.appspot.com/o/data%2Fuser%2F0%2Fcom.example.firebase_music_app%2Fcache%2Ffile_picker%2FLost%20In%20Nowhere.mp3?alt=media&token=63ceefae-6596-4881-b7f4-9230dc08bec8)

May I know what kind of parse I should use?

**Comment by gOzaru** [comment]
Okay, now I know where I went wrong. 
I tested this on Emulator and then I got the error, not on real device. 
I just tested it in my Redmi 6A and it ran very well. 
The audio is great now. 
Case is closed.
