### ISSUE TITLE
List of tutorials

### ISSUE THREAD

**Issue by suragch** [ryanheise/just_audio#383]
**To which pages does your suggestion apply?**

- https://github.com/ryanheise/just_audio/tree/master/just_audio

**Quote the sentences(s) from the documentation to be improved (if any)**

Proposing new content

**Describe your suggestion**

One difficultly I had when I was learning just_audio (and audio_service) was how to apply the documentation and the example project to my use case. Both the docs and the example app by necessity cover a wide range of functionality. This makes it somewhat difficult for new users. I'd like to propose including a list of tutorials in the documentation that would walk users through more specific use cases. I've just completed one and I'm thinking about writing more:

- https://suragch.medium.com/playing-short-audio-clips-in-flutter-with-just-audio-3c80eb7eb6ea

If there are any poor practices in that tutorial I'd be happy to revise it.

**Comment by suragch** [comment]
This is related to #319, which also includes a link to a good tutorial.

**Comment by suragch** [comment]
Here is a second tutorial in the series:

- https://suragch.medium.com/steaming-audio-in-flutter-with-just-audio-7435fcf672bf

**Comment by ryanheise** [comment]
Nice tutorials, @suragch ! Along with @mvolpato 's tutorial this would make a nice section in the README. I can wait for your 3rd article if you like before updating the README.

**Comment by suragch** [comment]
@ryanheise Thank you. Yes, I can finish the third tutorial first. That will be on playlists. I'll add it here when I'm done.

**Comment by suragch** [comment]
Here is the third tutorial:

- https://suragch.medium.com/managing-playlists-in-flutter-with-just-audio-c4b8f2af12eb

**Comment by ryanheise** [comment]
Awesome! Will try to a documentation release at my next opportunity.

**Comment by suragch** [comment]
The tutorials are on Medium and sometimes Medium paywalls non-subscribers if they've read more than a certain number of articles per month. The links I posted above are normal links, but here are the friend links. It would probably be better to use these so that no one gets paywalled.

1. [Playing short audio clips in Flutter with Just Audio](https://suragch.medium.com/playing-short-audio-clips-in-flutter-with-just-audio-3c80eb7eb6ea?sk=aaf6cc523c2c6fc747b5087277932607)
2. [Streaming audio in Flutter with Just Audio](https://suragch.medium.com/steaming-audio-in-flutter-with-just-audio-7435fcf672bf?sk=c7163e8496b914c9e0e5446ec6020f04)
3. [Managing playlists in Flutter with Just Audio](https://suragch.medium.com/managing-playlists-in-flutter-with-just-audio-c4b8f2af12eb?sk=1b1ffa2cb0b3ed50a320d8cc32cef342)

**Comment by ryanheise** [comment]
Hi @suragch I have just published a documentation release including links to your tutorials and @mvolpato 's tutorial. Thanks to both of you for writing up such helpful guides! I'm sure that it will really help new plugin users come to terms with the API in a way that the API docs themselves would not.

**Comment by suragch** [comment]
Great! Thank you.

**Comment by giga10** [comment]
@suragch 

Great tutorials for newbies. Thank you. Waiting for the one about audio_service... 😉
