### ISSUE TITLE
heavy appbundle size.

### ISSUE THREAD

**Issue by thanoofayoob** [ryanheise/just_audio#389]
**Which API doesn't behave as documented, and how does it misbehave?**
When I take a new build of a existing project it's size tripled .
Normally it was 21 mb. Now it' is 90 mb .and when I tried apk analyze tool it is showing like picture below
to the new build i just added 3 packages which includes just audio package. i strongly doubt that just audio is the reason for heavy app bundle size. any similar reported bungs or any solution to this.?

**Screenshots**
![Screenshot from 2021-04-26 12-10-31](https://user-images.githubusercontent.com/67316775/116189733-0860a480-a747-11eb-97e8-f78c89c395a0.png)

**Comment by Saifallak** [comment]
any update on this issue?

**Comment by ryanheise** [comment]
The last update as indicated above was that the issue was closed, and there won't be further updates on a closed issue.
