### ISSUE TITLE
AVPlayerItemStatusFailed on iOS

### ISSUE THREAD

**Issue by codeeuser** [ryanheise/just_audio#40]
I am using the existing example but update the audio source to Flutter asset file. I have included the asset in pubspec.yaml
Device: iPhone 11 Pro Max Simulator
Flutter: v1.12.13+hotfix.7-stable

# To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/sound.mp3

@override
  void initState() {
    super.initState();
    _player = AudioPlayer();
    _player.setAsset('assets/audio/sound.mp3');
  }

The printed log is following. Noted that 'AVPlayerItemStatusFailed' is NSLog message.

Performing hot restart...                                               
Restarted application in 1,233ms.
AVPlayerItemStatusFailed

**Comment by Camerash** [comment]
I have found the solution to this problem.
Apparently, `AVPlayer` used in iOS requires the audio file to have file suffix to play properly (i.e.: ".mp3")
However, the current `setAsset` function creates a temporary file without the suffix, causing it not to work on the iOS side.

I can create a PR later to fix the issue, cheers 👍

**Comment by ryanheise** [comment]
@Camerash Thank you!

**Comment by Camerash** [comment]
For now `_cacheFile` return a file path that does not account for the format suffix, and I don't won't to just hard code `".mp3"` for the file name.
I propose to make the cache file path a variable instead of getter to account for the format suffix when setting it in `setAsset()`. Does that sound go to you? @ryanheise

**Comment by ryanheise** [comment]
Looks good. Now merged and included in release 0.1.1. Thanks!
