### ISSUE TITLE
Buffered audio size

### ISSUE THREAD

**Issue by ReaganRealones** [ryanheise/just_audio#41]
Is it possible to retrieve the amount buffered so far of the song to display on the song progress bar, like u see in the image I have put, is it possible? 
![Screenshot_20200209-175627](https://user-images.githubusercontent.com/36300919/74104423-8433f880-4b65-11ea-8b61-f92f49872f69.png)

**Comment by Aksi0** [comment]
You can modify java code and add to broadcastPlaybackEvent `player.getBufferedPosition();`

**Comment by ReaganRealones** [comment]
Any updates for this?

**Comment by ryanheise** [comment]
I haven't been able to do Flutter development for a few weeks due to a Dart bug on my OS but that was fixed this morning. So no updates as yet. I have a lot of things to catch up on first, but @Aksi0 's comment will help things to go faster, at least on the Android side.

**Comment by yringler** [comment]
@Aksi0, I see you made a fork of just_audio with some really cool additions, available in pub as just_audio2.
Are you working / have you discussed with @ryanheise to work together / get those changes here?

**Comment by ryanheise** [comment]
Yep, I'd be really to accept it as a PR.

For some good news, the Dart bug I mentioned was fixed recently, and hence my Flutter dev environment is now in working order again. If there are no pull requests on this issue before the weekend, I will spend some time implementing the feature on the weekend.

**Comment by ryanheise** [comment]
Just implemented the feature for Android and published a new release. Please let me know whether it works for you.

**Comment by ryanheise** [comment]
This is now implemented on iOS on the media-source branch. This branch contains several other major changes and requires testing. Please post on #131 if you discover issues, and I'll close this one.

**Comment by smkhalsa** [comment]
Shouldn't we implement buffers as an array of position ranges rather than a single Duration since it's possible to have multiple disconnected buffers? (e.g. after seeking)

**Comment by ryanheise** [comment]
@smkhalsa I would encourage you to open a new feature request for buffer ranges.
