### ISSUE TITLE
PlayerException while loading AudioPlayer

### ISSUE THREAD

**Issue by engineerdeep** [ryanheise/just_audio#411]
**Which API doesn't behave as documented, and how does it misbehave?**
AudioPlayer._load throws PlayerException when calling it using `_audioPlayer.setFilePath()` **After a delay**, where path comes from a file from file picker. If you set the file path of the audio player instantly, it doesn't fail. 

**Minimal reproduction project**
Please find the minimal reproducible project - https://github.com/engineerdeep/JustAudioDemo

**To Reproduce (i.e. user steps, not code)**
Check readme of the repo for setting up the project and reproducing the issue.

**Error messages**

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: (-1100) The requested URL was not found on this server.
#0      AudioPlayer._load (package:just_audio/just_audio.dart:716:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1096:28)
<asynchronous suspension>
```

**Expected behavior**
After fetching an mp3 file using the library `flutter_file_picker` and getting the path to the file, `_audioPlayer.setFilePath()` function throws PlayerException when called after a delay. When called instantly, it works as expected. I'm not sure if this issue occurs because apple does not allow fetching the file from a path after a certain amount of time? (I don't think they restrict that because the path to fetch the file remains the same regardless if we call it instantly or after a minute)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: [iPhone X device, iPhone SE simulator]
 - OS: [iOS14.4.2]

**Flutter SDK version**
```
deepashok λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup
      for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

**Additional context**
The issue seems rather odd, you may ask why am I waiting for 60 seconds to set file path for the audio player? You're right, I've found this weird setup to reproduce the issue but what I'm actually doing is assigning the path to the audio player. The Audio player is part of a list, so if the list is re-rendered cause something else changed, it re-renders the Audio player and the audio player stops working as it throws a PlayerException.

**Comment by engineerdeep** [comment]
@ryanheise Hey! Did you get a chance to have a look at this? Would really appreciate your input on this if you have time please. Thank you!

**Comment by ryanheise** [comment]
I haven't had a chance to look at it yet, but according to your bug report, it's not clear that this is a bug in just_audio. Can you add some code to print out whether or not the file actually exists before passing that into `setFilePath`?

**Comment by engineerdeep** [comment]
Thanks for the reply, yeah I was skeptical as well whether the bug is in just_audio or not, but after debugging I saw that the path returned by file picker was same when I re-pick the file. I actually tested if the file exists now and it turns out you're absolutely right, it returned `false` for `existsSync` function. I'll have a look at the file picker package, thanks alot for your input!

**Comment by ryanheise** [comment]
I will close this issue on just_audio, and best wishes your investigations.

**Comment by engineerdeep** [comment]
For anyone that faces this issue, I fixed the issue by caching the file to local storage after picking it from file_picker package and then using the cached file's path to load the audio player. Thanks again @ryanheise! 🙏
