### ISSUE TITLE
Support AVAudioPlayer.pan

### ISSUE THREAD

**Issue by actow** [ryanheise/just_audio#413]
**Is your feature request related to a problem? Please describe.**
lack of the ability to adjust volume between the left and right channels

**Describe the solution you'd like**
Expose AVAudioPlayer.pan
https://developer.apple.com/documentation/avfaudio/avaudioplayer/1390884-pan

**Describe alternatives you've considered**
none

**Additional context**
This would enable the creation of basic 3D sound effects.

**Comment by actow** [comment]
On Android. It's probably MediaPlayer.setVolume(left, right) or SoundPool.play(...)

**Comment by ryanheise** [comment]
I have implemented this on Android although it is not yet pushed to GitHub. For iOS I do not use `AVAudioPlayer` so this solution won't work. However, this will be easier once #334 is done.

Note: I am currently handling this issue in #126 so please add your use case to that issue.
