### ISSUE TITLE
Update rxdart package to 0.27.0

### ISSUE THREAD

**Issue by stepushchik-denis-gismart** [ryanheise/just_audio#415]
**Is your feature request related to a problem? Please describe.**
Rxdart in 0.27.0 has breaking changes such as 

> ValueStream.valueWrapper becomes
> value.
> valueOrNull

(full list is [here](https://pub.dev/packages/rxdart/changelog#0270)).
And when I override rxdart in the app to 0.27.0 I crash in just_audio because now value in ValueStream

> throws [ValueStreamError] if this Stream has no value. 

**Describe the solution you'd like**

- Update rxdart to 0.27.0 
- Change all places with `.value?.` or `.value ??` to `valueOrNull`.
- Chnage all places with `.value!.` just to `.value`

**Describe alternatives you've considered**
There is no any alternatives.

**Additional context**
Rxdart package is [here](https://pub.dev/packages/rxdart).
Changelog is [here](https://pub.dev/packages/rxdart/changelog).

P.S. Thanks you a lot for the great package!

**Comment by ryanheise** [comment]
This is definitely on the todo list, although it will go into the next breaking change release. I'm currently working on trying to get everything stable for that release.

**Comment by ryanheise** [comment]
There may actually be a way I can do this as a non-breaking change which would be preferred. I'll experiment.

**Comment by ryanheise** [comment]
Version 0.7.5 has now been released which supports rxdart 0.27.0 .
