### ISSUE TITLE
Audio not playing while adding new item to queue.

### ISSUE THREAD

**Issue by balasubramanian1612s** [ryanheise/just_audio#436]
Is your feature request related to a problem? Please describe.

When I try to add a mediaitem to queue I need to call setAudioSource method which makes player to start from begining.

Describe the solution you'd like

updateAudioSource like method may be helpfull.

Describe alternatives you've considered

My solution was to store the current position and index of the player and seek to that position and index after the setAudioSource method. But this makes player to pause a while.

@override
Future onAddQueueItem(MediaItem mediaItem) async {
queue.add(mediaItem);
var _position=_player.position;
var _index=_player.currentIndex;
await AudioServiceBackground.setQueue(queue);
try {
await _player.setAudioSource(ConcatenatingAudioSource(
children:
queue.map((item) => AudioSource.uri(Uri.parse(item.id))).toList(),
));
}catch (e) {
print("Error: $e");
}
await _player.seek(_position,index: _index);
}

Additional context

N/A

@ryanheise

**Comment by ryanheise** [comment]
> When I try to add a mediaitem to queue I need to call setAudioSource method

This is not true, `example/lib/example_playlist.dart` demonstrates how add a new audio source without calling `setAudioSource`.

**Comment by balasubramanian1612s** [comment]
Thank you @ryanheise, I was inserting to concatenatingAudioSource and again called setSource.
