### ISSUE TITLE
flutter: (-11849) Operation Stopped For Asset File

### ISSUE THREAD

**Issue by ericel** [ryanheise/just_audio#441]
**Which API doesn't behave as documented, and how does it misbehave?**
just_audio: ^0.7.5 
Gives the following error when trying to use the assets file.
```
 try {
        await _audioPlayer.setAsset('assets/ringtone.mp3');
        //await _audioPlayer.setAudioSource(_audioSource);
      } catch (e) {
        print(e.toString());
      }
```
The method at fault here is setAsset().
Works fine if I use setUrl or any other set method.

**Error messages**

> flutter: (-11849) Operation Stopped

**Smartphone (please complete the following information):**
 - iPhone12 simulator

**Comment by illukinati** [comment]
this one is fatal.
hope they can fix it.

**Comment by ryanheise** [comment]
@illukinati no valid bug report has been submitted yet. If you'd like it to be investigated, would you mind opening a valid bug report?

**Comment by Fleximex** [comment]
It is this error: https://developer.apple.com/documentation/avfoundation/averror/code/failedtoloadmediadata

I am getting the same error. Don't know why though yet. In some instances I get it all the time and in some instances I get it occasionally. Both on a Simulator and physical iPhone.

**Comment by ryanheise** [comment]
@Fleximex hopefully it is the case then that it is just a build/cache issue. But in case it's actually a legitimate bug, I still need a minimal reproduction project.

In case new people come here without reading the above comments, this issue is still closed because I still need the reproduction project before I can, well, reproduce it and investigate it.

**Comment by ericel** [comment]
The workaround for this is to place audio in a folder outside the lib folder. 

I don’t know that is, but that works!!!

**Comment by Abdullah104** [comment]
@Fleximex Your solution worked for me.
