### ISSUE TITLE
onSongEnd Method

### ISSUE THREAD

**Issue by AssassinAguilar** [ryanheise/just_audio#443]
Want to ask a question that how to get onSongEnd to do some things at that point or is there any method for it ?

**Comment by ryanheise** [comment]
I get that you want to ask a question, but when you clicked on the "New issue" button, did you see this?

![just_audio_new_issue](https://user-images.githubusercontent.com/19899190/124943662-09b82280-e050-11eb-9c44-903520055077.png)

Or if you really intended to make a documentation request, did you see this?

![just_audio_doc_request](https://user-images.githubusercontent.com/19899190/124944393-9e228500-e050-11eb-85f2-06ad690fa16d.png)
