### ISSUE TITLE
Add audio output type property?

### ISSUE THREAD

**Issue by Ted-Zhang** [ryanheise/just_audio#451]
**Is your feature request related to a problem? Please describe.**
Since user could use multiple external equipment, such as Speaker, Bluetooth headset, it could be nice to know if user connects to external devices so we could adjust the volume according.

**Describe the solution you'd like**
A device output type property to tell if user has connected to a Bluetooth device?

**Describe alternatives you've considered**

**Additional context**
When some emergency happens, I want to play a warning message with maximum volume, but if it shouldn't go to maximum volume if user connected to a Bluetooth device as it could really damage user's hearing.

**Comment by ryanheise** [comment]
Thank you for the feature request. This feature belongs in audio_session, and fortunately should already be implemented in the latest version of it, so I'll close this.

**Comment by Ted-Zhang** [comment]
Thanks a lot for the quick response, yes, I think I can use the getDevices from the audio_session to get the required devices.

Great packages which works in isolate mode too! 👍 Thank you for your work!
