### ISSUE TITLE
Play a song in the shuffled list with the selected index from the current shuffled playlist (shuffleIndices)

### ISSUE THREAD

**Issue by duypham312** [ryanheise/just_audio#457]
**Is your feature request related to a problem? Please describe.**

Yes, if the playlist is shuffled, I will update the UI to show the order of the current playlist and the user will click on the song on the list to play it. But when I get the selected `index` from the shuffled playlist and use ```seek(Duration.zero, index: index)``` function, it goes to the song with the `index` in the initial order, not the shuffled order

**Describe the solution you'd like**

I want a seek function implemented to use when ```shuffleModeEnabled``` is true and it will play the song with the selected `index` based on the order of the shuffled playlist.

**Describe alternatives you've considered**

Instead, I think syncing the ```sequence``` and ```effectiveSequence``` when shuffling the playlist can solve my problem

**Additional context**

I don't have any screenshots but I'll provide a simple example. If the initial order is ```[song 1, song 2, song 3]``` and the shuffled order is ```[song 1, song 3, song 2]```, when selecting the second song in the shuffled order (`song 3` with the index is `1` in that array), calling ```seek(Duration.zero, index: 1)``` will play the `song 2` because the seek function will operate on the initial order

**Comment by ryanheise** [comment]
Yes `currentIndex` always refers to the index in the original stored order, but for your use case, you can easily map between that and the shuffle indices. What I'd suggest is to just invert the shuffle indices:

```dart
    for (var i = 0; i < shuffleIndices.length; i++) {
      shuffleIndicesInv[shuffleIndices[i]] = i;
    }
```

So then if the user clicks on position `pos` in the shuffled list, you can then jump to it with `player.seek(Duration.zero, index: shuffleIndicesInv[pos]);`.

**Comment by duypham312** [comment]
Currently, I am using a temporary solution as follows:
```
if (_audioPlayer.shuffleModeEnabled) {
  index = _audioPlayer.shuffleIndices![index];
}
_audioPlayer.seek(Duration.zero, index: index);
```
With this solution, I can play the right song with the selected index but when the song is completed, `_audioPlayer` will play the next song based on `currentIndex` that refers to the index in original stored order. How can I make it play with `nextIndex` that is the result of the `_getRelativeIndex(1)`, the same as what `seekToNext()` does?

**Comment by ryanheise** [comment]
If you set shuffle mode enabled, then when the current item completes, it will advance to the next item in shuffle order - see the playlist example. If that doesn't happen for you, I'd suggest submitting a bug report, although I think shuffle mode currently works as expected.

**Comment by duypham312** [comment]
@ryanheise I think there is a problem with auto-next on iOS when `shuffleModeEnabled` is true. You can reproduce this problem by this way:
- Download or clone [this repository](https://github.com/suragch/flutter_audio_service_demo)
- Replace the respective methods in final/lib/services/audio_handler.dart with the following:
```
void _listenForDurationChanges() {
  _player.durationStream.listen((duration) {
    var index = _player.currentIndex;
    final newQueue = queue.value;
    if (index == null || newQueue.isEmpty) return;
    if (_player.shuffleModeEnabled) {
      index = _player.shuffleIndices!.indexOf(index);
    }
    final oldMediaItem = newQueue[index];
    final newMediaItem = oldMediaItem.copyWith(duration: duration);
    newQueue[index] = newMediaItem;
    queue.add(newQueue);
    mediaItem.add(newMediaItem);
  });
}

void _listenForCurrentSongIndexChanges() {
  _player.currentIndexStream.listen((index) {
    final playlist = queue.value;
    if (index == null || playlist.isEmpty) return;
    if (_player.shuffleModeEnabled) {
      index = _player.shuffleIndices!.indexOf(index);
    }
    mediaItem.add(playlist[index]);
  });
}

@override
Future<void> skipToQueueItem(int index) async {
  if (index < 0 || index >= queue.value.length) return;
  if (_player.shuffleModeEnabled) {
    index = _player.shuffleIndices![index];
  }
  _player.seek(Duration.zero, index: index);
}

@override
Future<void> skipToNext() async {
  _player.seekToNext();
}

@override
Future<void> skipToPrevious() async {
  _player.seekToPrevious();
}
```
- Run the app in final/
- Press the shuffle button until the playlist order says Song 1, Song 3, Song 2.
- Play the first song and move the thumb on the seek bar so that it is almost finished. Then let it finish and automatically progress to the next song.
- The next played song is Song 2 even though it should be Song 3.

**Comment by ryanheise** [comment]
It's definitely helpful to know if there is a bug, but can you create a separate bug report for it? Let's keep this feature request focused on this feature request.

**Comment by duypham312** [comment]
Okay, I'll check it out a few more times and create a bug report if necessary

**Comment by ryanheise** [comment]
Closing since the bug report was opened at #460 .
