### ISSUE TITLE
Hide skip buttons in background service

### ISSUE THREAD

**Issue by bafplus** [ryanheise/just_audio#458]
I dont use the skip buttons in my project.
However, they still show in the background service (pulled from top).
Is there a way to hide those skip buttons?

**Comment by ryanheise** [comment]
If you're talking about just_audio_background, then no (at least for the current beta). If you want some customisability, you can make a feature request (or if you can't wait, you can use audio_service directly.) When submitting a feature request, please also ensure you follow the issue template by providing all requested information.

**Comment by bafplus** [comment]
Will do, thanks!
