### ISSUE TITLE
Hide skip buttons in background service player controls

### ISSUE THREAD

**Issue by bafplus** [ryanheise/just_audio#459]
**Is your feature request related to a problem? Please describe.**
I dont use the skip buttons in my project.
However, they still show in the background service (pulled from top).
Is there a way to hide those skip buttons?

**Describe the solution you'd like**
A tag or setting to hide/show such buttons

**Describe alternatives you've considered**
A way to change the code without editing the source directly.

**Additional context**
-

**Comment by ryanheise** [comment]
One approach might be for the plugin to hide the skip buttons if `sequence` contains only one item. Would that work for you, or would you prefer an explicit option?

**Comment by bafplus** [comment]
Im using the supplied example as boilerplate.
Instead of having a playlist, i'm serving streamingurls instead of
audiofiles.
Playlist in the example is more a media-library in that regard.
So basically "just" playing one item only, without a playlist.
But i dont know how you're suggestion handles that "playlist" in regards to
sequence.

Op di 27 jul. 2021 om 14:21 schreef ryanheise ***@***.***>:

**Comment by ryanheise** [comment]
I'm talking about the `sequence` getter:

https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/sequence.html

The proposed logic would be to show the skip buttons if `sequence.length > 1`. I take it in your app `sequence.length == 1`, correct?

**Comment by bafplus** [comment]
I think yes...but im a noob so i may be wrong.
All i did was change the path to audiofile to a streamingurl, so basicly a endless audiofile. Yet i dont know how or if that affects the sequence since i still use the "playlist" as media library (without changing anything other then the source audiofile).
Hope you understand my above answer :-)

You may pm me somehow if you want to take this out of the discussion here...

**Comment by ryanheise** [comment]
`sequence` is the playlist of the player. The skip buttons move forwards and backwards through that sequence.
Try `print(player.sequence.length);` to confirm if you are unsure whether it is `1` in your app. Assuming it is `1` in your app, is this solution acceptable?

**Comment by bafplus** [comment]
In that case, no since i use the current sequence as library.
Yet i do think it can work if i rework my code to set the library outside
of the sequence scope.

But you're proposal should work IF sequence = 1 (just not in my usercase)


Op di 27 jul. 2021 om 15:08 schreef ryanheise ***@***.***>:

**Comment by ryanheise** [comment]
If you do indeed use a sequence as a library but you don't want a playlist, how do you prevent sequence from acting as a playlist? Because after one item plays out it automatically advances to the next item in the sequence.

**Comment by bafplus** [comment]
Simple, i only use livestreams from online radiostations, so simply put,
they won't end :-)

Op di 27 jul. 2021 om 15:41 schreef ryanheise ***@***.***>:

**Comment by ryanheise** [comment]
I see.

If you fix that in your app, I assume you would be satisfied with the proposed solution?

**Comment by bafplus** [comment]
That that should work, so yes

IF i can fix that (noob in flutter ;-) )

Op di 27 jul. 2021 om 15:56 schreef ryanheise ***@***.***>:

**Comment by ryanheise** [comment]
Can you try the the `fix/queue` branch and let me know if it works now for you?

**Comment by bafplus** [comment]
Sure...havent done that before...can you switch branch in pubspec.yaml? And how? :-)

**Comment by giga10** [comment]
@bafplus try this:

```
just_audio: git: url: https://github.com/ryanheise/just_audio.git ref: fix/add_before_load path: just_audio
```

**Comment by ryanheise** [comment]
Although since you want to test the `just_audio_background` package, you may use this:

```yaml
just_audio_background: 
   git:  
      url: https://github.com/ryanheise/just_audio.git 
      ref: fix/queue
      path: just_audio_background
```

**Comment by ryanheise** [comment]
This is now published on pub, so you can do it the normal way. Let me know if you still encounter issues, otherwise I'll close if it is now working.

**Comment by bafplus** [comment]
I just tested it ( i think )
If i only have 1 item in sequence the skip buttons are gone, and thats indeed exactly what i need.
That is what you changed right?

**Comment by ryanheise** [comment]
Yes, and the change also affects multi-item sequences too by disabling the next button when you're on the last item and disabling the previous button when you're on the first item. If the sequence length is 1, then there is no next or previous so both buttons are disabled.

Thanks for the feature request and testing.

**Comment by bafplus** [comment]
Happy to test!
Thanks for helping.

One question tho, in my case sequence should always be 1.
Whats the best way to "override" your code so it wil always be 1?

My next "project" will be chromecast support.
But its very hard stuff since there are no (good) plugins (yet).
Does anyone have a working implementation?
Just selecting target device and "sling" the audiourl is enaugh in my usecase.

**Comment by ryanheise** [comment]
If you need help understanding how to have a sequence of length 1, please either ask for help on StackOverflow or consult the documentation.
