### ISSUE TITLE
Enable cross-protocol redirects in ExoPlayer

### ISSUE THREAD

**Issue by jkubicko** [ryanheise/just_audio#46]
Some podcast providers (e.g. Soundcloud) provides url to online stream, that is cross-protocol redirected (original url returns 302 response) to audio file. ExoPlayer doesn't follow cross-protocol redirects by default. Since I do not have final url, I can't play this file.
Please add an option to enable cross-protocol redirecting
 - Related issue with example [here](https://github.com/google/ExoPlayer/issues/1190)
 - In short: please use [this](https://github.com/Movile/movile-exoplayer/blob/71c5e132a82d0fe898ccb14228965e2eb7125a1b/library/src/main/java/com/google/android/exoplayer/upstream/DefaultUriDataSource.java#L94) constructor [here](https://github.com/ryanheise/just_audio/blob/207ed8a3b805499bc184c9a33a8c1a623b8f0aa3/android/src/main/java/com/ryanheise/just_audio/AudioPlayer.java#L220) with last parameter (optionally) set to true.

Thank you

**Comment by ryanheise** [comment]
Thanks for providing the links, that will help a lot. I'm not sure how long it will take me since I have a bit to catch up on, but when I do get up to it, this should be straightforward to add.

**Comment by ryanheise** [comment]
Fixed by #55 .
