### ISSUE TITLE
Auto-next doesn't work properly when shuffleModeEnabled is true

### ISSUE THREAD

**Issue by duypham312** [ryanheise/just_audio#460]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

I have this problem on iOS. When a song ends, `_player` will not play the next song in the order of the shuffled list if `shuffleModeEnabled` is true. Meanwhile, if I call `_player.seekToNext()` and `_player.seekToPrevious()`, it works fine.

**Minimal reproduction project**
Provide a link here using one of two options:

1. Download or clone [this repository](https://github.com/suragch/flutter_audio_service_demo)
2. Replace the respective methods in final/lib/services/audio_handler.dart with the following:
```dart
void _listenForDurationChanges() {
  _player.durationStream.listen((duration) {
    var index = _player.currentIndex;
    final newQueue = queue.value;
    if (index == null || newQueue.isEmpty) return;
    if (_player.shuffleModeEnabled) {
      index = _player.shuffleIndices!.indexOf(index);
    }
    final oldMediaItem = newQueue[index];
    final newMediaItem = oldMediaItem.copyWith(duration: duration);
    newQueue[index] = newMediaItem;
    queue.add(newQueue);
    mediaItem.add(newMediaItem);
  });
}

void _listenForCurrentSongIndexChanges() {
  _player.currentIndexStream.listen((index) {
    final playlist = queue.value;
    if (index == null || playlist.isEmpty) return;
    if (_player.shuffleModeEnabled) {
      index = _player.shuffleIndices!.indexOf(index);
    }
    mediaItem.add(playlist[index]);
  });
}

@override
Future<void> skipToQueueItem(int index) async {
  if (index < 0 || index >= queue.value.length) return;
  if (_player.shuffleModeEnabled) {
    index = _player.shuffleIndices![index];
  }
  _player.seek(Duration.zero, index: index);
}

@override
Future<void> skipToNext() async {
  _player.seekToNext();
}

@override
Future<void> skipToPrevious() async {
  _player.seekToPrevious();
}
```
**To Reproduce (i.e. user steps, not code)**
1. Go to 'final/'.
2. Run the app on iOS.
3. Press the shuffle button until the playlist order is [Song 1, Song 3, Song 2].
4. Play the first song and move the thumb on the seek bar until it's near the end. Then let it finish and automatically progress to the next song.
5. The next song is Song 2 even though it should be Song 3.
6. You may try it a few times to see the difference.

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

The next song should be Song 3 in that case.

**Screenshots**

**Desktop (please complete the following information):**

I haven't tried on Desktop platform yet

**Smartphone (please complete the following information):**
 - Device: iPhone 8 (Simulator), iPhone X (Simulator)
 - OS: iOS 14.5

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Additional context**

**Comment by ryanheise** [comment]
This may be a bit difficult to investigate, unless you could create a minimal project that I can clone and run directly. Can you fork this repository and make minimal changes to reproduce the error?

**Comment by duypham312** [comment]
You can download this [final.zip](https://github.com/ryanheise/just_audio/files/6885752/final.zip), run the app and do the same things as I mentioned

**Comment by ryanheise** [comment]
Is that minimal? I would prefer if you forked the example and made minimal changes to reproduce the bug.

**Comment by duypham312** [comment]
I tried to minimize [it](https://github.com/ryanheise/just_audio/files/6886676/final.zip). I hope it's minimal enough for you to investigate easily

**Comment by ryanheise** [comment]
You don't need audio_service for this. Would you mind following the instructions?

> **Minimal reproduction project**
> Provide a link here using one of two options:
> 1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
> 2. If the unmodified official example already reproduces the bug, just write "The example".

You can edit `example/lib/example_playlist.dart` with minimal changes since it already demonstrates a playlist with shuffle mode.

I can't force you to do it, but keep in mind that it's quite a lot of work for me to maintain these plugins and fix bugs, so these instructions above are pretty essential in keeping me sane, otherwise everybody would send me their full apps and ask me why their apps aren't working (and with apps of that complexity, there's a good chance the bug is in their app rather than in the plugin. Hence the instructions.)

**Comment by duypham312** [comment]
I think I found the cause of the error in my case. I called the `_player.setShuffleModeEnabled(true)` before calling the `_player.shuffle()` and that resulted in the problem as i mentioned. When I call `_player.shuffle()` before `_player.setShuffleModeEnabled(true)`, it works properly. I don't know why but this only happens on iOS. If you want to investigate this further, you can use this [example_playlist.dart.zip](https://github.com/ryanheise/just_audio/files/6887636/example_playlist.dart.zip). Have a nice day.

**Comment by ryanheise** [comment]
Hi @duypham312 this may be fixed on the `fix/queue` branch if you would like to try it.

**Comment by duypham312** [comment]
I'm glad to hear that. I just tried with `fix/queue` branch and the app doesn't crash anymore. Well done!
