### ISSUE TITLE
Just_audio_background doesn't recognize player loop and shuffle states

### ISSUE THREAD

**Issue by abeyshiferaw0** [ryanheise/just_audio#461]
While working with just audio background package,  setting loops and shuffle mode works well with the the audio player but the next and previous buttons on the notification player doesn't recognize it,

**Comment by ryanheise** [comment]
> **Which API doesn't behave as documented, and how does it misbehave?**
> Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

Can you please fill in this section?

> 
> **Minimal reproduction project**
> Provide a link here using one of two options:
> 
>     1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
> 
>     2. If the unmodified official example already reproduces the bug, just write "The example".
> 

Can you please fill in this section?

> 
> **To Reproduce (i.e. user steps, not code)**
> Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 

Can you please fill in this section?

> **Expected behavior**
> A clear and concise description of what you expected to happen.

Can you please fill in this section?

> **Smartphone (please complete the following information):**
> 
>     * Device: [e.g. iPhone6]
> 
>     * OS: [e.g. iOS8.1]


Can you please fill in this section?

> 
> **Flutter SDK version**
> 
> ```
> insert output of "flutter doctor" here
> ```

Can you please fill in this section?

**Comment by ryanheise** [comment]
I'd be happy to fix the bug if someone would like to submit a valid bug report for it. I will close this one. Please open a new bug report that follows the instructions and provides the requested information, thanks.
