### ISSUE TITLE
just_audio_background:      click  background  skipToNext  to  add  a  new  MediaItem

### ISSUE THREAD

**Issue by 164250072** [ryanheise/just_audio#467]
In the audio playlist, if you get to the last audio, click the background Play skipToNext to ask for a new MediaItem over the network.

Whether  the just_audio_background support the feature.

**Comment by ryanheise** [comment]
You can't customise the skip buttons in just_audio_background, but this plugin uses audio_service under the hood which is much more flexible. You can use audio_service directly and fully customise this button.
