### ISSUE TITLE
Forward/Rewind track by Seconds

### ISSUE THREAD

**Issue by marcqtan** [ryanheise/just_audio#469]
**Is your feature request related to a problem? Please describe.**
I would like to have rewind and forward feature of a track by a specific seconds. E.g. (Manually set rewind to 2 seconds, manually set forward to 3 seconds). 

**Describe the solution you'd like**
When clicking the rewind button, it should rewind the track into the specific position. For example: 
calling player.seekby(-5) = will seek the track into the current playing position minus 5 seconds. calling it again should rewind it again into currentplaying pos - 5

calling player.seekby(5) = will seek the track into the current playing position plus 5 seconds.
Also it should not seek more than the duration of the song. calling it again should forward it again into currentplaying pos + 5

**Describe alternatives you've considered**
Since this is a common feature of an audio player, I was surprised that it hasn't been implemented yet. I've checked the documentation and I can't find anything about it or maybe I'm just missing something?

**Additional context**

**Comment by ryanheise** [comment]
Thanks for the suggestion, although this is easy enough for the app to implement using `seek`:

```dart
player.seek(player.position + Duration(seconds: 2));
```

If you really want a special method to exist in the player, you can always create an extension method for it, so I'll close this as "won't implement".
