### ISSUE TITLE
Cannot Clip item of Playlist

### ISSUE THREAD

**Issue by marcqtan** [ryanheise/just_audio#471]
**Which API doesn't behave as documented, and how does it misbehave?**
The setClip() api is showing an error. I'm using a ConcatenatingAudioSource() since i'm creating a playlist. I want to clip the mp3's of the playlist but when I use setClip() it's showing error below:

`type 'ConcatenatingAudioSource' is not a subtype of type 'UriAudioSource' in type cast
`

**Minimal reproduction project**
You can check the code here: 
[https://github.com/marcqtan/just_audio/blob/master/just_audio/example/lib/main.dart
](https://github.com/marcqtan/just_audio/blob/master/just_audio/example/lib/main.dart
)
**To Reproduce (i.e. user steps, not code)**
1. Run the sample app in the given link
2. Click play button
3. Put a value to "Start" textbox (e.g. 2)
4. Put a value to "End" textbox (e.g. 5)
5. Click "Apply AB"
6. Check logs

**Error messages**

```
type 'ConcatenatingAudioSource' is not a subtype of type 'UriAudioSource' in type cast
```

**Expected behavior**
I should be able to clip mp3 items of a playlist

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac catalina 10.15.17
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Samsung A31
 - OS: Android 10

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment]
This is not a bug, just a shortcoming of the documentation. You cannot clip a `ConcatenatingAudioSource`, you can only clip a `UriAudioSource`. If you want to clip each child within the `ConcatenatingAudioSource`, use `ClippingAudioSource` around each child as demonstarted in `example/lib/example_playlist.dart`.

**Comment by marcqtan** [comment]
@ryanheise 

What if I only want to clip it at a later time? (e.g. using the player.setClip() api)
 The one in example_playlist will only apply during init.

**Comment by ryanheise** [comment]
Just create a new clipping audio source, insert it into the concatenating audio source and remove the old one that it replaces.

**Comment by marcqtan** [comment]
`Just create a new clipping audio source, insert it into the concatenating audio source and remove the old one that it replaces.`

Thanks! this works. Is this the only way? 

I'm thinking of a scenario where I clipped the current playing audio->go to next audio-> go back to previous clipped audio but this time I want the audio to revert back to original unclipped. So in this scenario, I should create a new clipping source again, insert it to concatenating source then remove the old clipped audio. 

Is this flow okay? 
@ryanheise

**Comment by ryanheise** [comment]
That is the only way I can think of with ConcatenatingAudioSource. But if you don't need ConcatenatingAudioSource's ability to create a gapless playback where it auto-advances to the next item once the current one completes, then an alternative is to just call `setAudioSource` each time you want to play a different item, and pass in a `UriAudioSoure` followed by an optional call to `setClip` adjust the start/end.

But whatever works for you is OK to me.

**Comment by marcqtan** [comment]
> That is the only way I can think of with ConcatenatingAudioSource. But if you don't need ConcatenatingAudioSource's ability to create a gapless playback where it auto-advances to the next item once the current one completes, then an alternative is to just call `setAudioSource` each time you want to play a different item, and pass in a `UriAudioSoure` followed by an optional call to `setClip` adjust the start/end.

The alternative way you've mentioned is much cleaner. I won't use ConcatenatingAudioSource anymore and instead just use AudioSource on each item of my playlist.

I just need to handle manually the `skipToNext`, `skipToPrevious` and `completed state` (to automatically play the next item) by introducing a new variable index (to query specific audio item from playlist) and calling `setAudioSource` on each and then i can just call `player.setClip()` to adjust start/end.

For me, this approach is better compared to newClippingSource->insert->remove from source.

Thanks for all the help and for this awesome plugin!

**Comment by marcqtan** [comment]
Another question, if i use the approach above, will it work correctly in Notification Center? 
I mean the next, prev button and automatically play next item in the Notification Center.

**Comment by marcqtan** [comment]
so I've tried, the loop all, and it didn't work for the approach #2. I guess I'll just stick with approach #1.

**Comment by ryanheise** [comment]
If you use just_audio_background, it's hard coded behaviour based on having a playlist so you'd probably then need to use ConcatenatingAudioSource. However, if you use audio_service directly (which just_audio_background uses under the hood), then you have complete flexibility in how you define the next/prev buttons. Ultimately that is what I would recommend for you, since your use case sounds like it will have some non-standard requirements.

**Comment by marcqtan** [comment]
Thanks for the suggestion, I end up using ConcatenatingAudioSource since i'm implementing a playlist. 
Btw, is it possible to use LoopMode.one on the ClippingAudioSource under ConcatenatingAudioSource?

E.g. 

```
ConcatenatingAudioSource(
   children: [
        ClippingAudioSource(start: Duration(seconds: 2), 
             end: Duration(seconds: 10), 
             child: AudioSource.uri(Uri.parse('asset:///audio/Audio1.mp3'))),
        AudioSource.uri(Uri.parse('asset:///audio/Audio2.mp3')),
      ],
    );
)
```

I want to loop only the ClippedAudioSource which is Audio1.mp3.  I called `player.setLoopMode(LoopMode.one)`, and it is working fine in Android. It's looping the clipped audio (Audio1.mp3) correctly but it's behaving incorrectly in IOS.. Sometimes audio can't be heard or there's a delay before the audio will sound in IOS..

**Comment by ryanheise** [comment]
You'll need to submit a bug report.

**Comment by marcqtan** [comment]
> If you use just_audio_background, it's hard coded behaviour based on having a playlist so you'd probably then need to use ConcatenatingAudioSource. However, if you use audio_service directly (which just_audio_background uses under the hood), then you have complete flexibility in how you define the next/prev buttons. Ultimately that is what I would recommend for you, since your use case sounds like it will have some non-standard requirements.

So I end up using just_audio + audio_service plugin to customize playing of tracks and to create my own playlist without using `ConcatenatingAudioSource`. 

I'm overriding `skipToNext(), skipToPrevious() and calling setAudioSource()` to play audio. 

I'm also calling setAudioSource() to play a specific audio track in a playlist. Is it ok to call setAudioSource() multiple times?

Thanks!
@ryanheise
