### ISSUE TITLE
Allow other apps to continue playing audio even if my app playing audio.

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [ryanheise/just_audio#483]
**Is your feature request related to a problem? Please describe.**
When I play audio in my app, The other music player apps like "Spotify" pause their audio.

**Describe the solution you'd like**
When my app start playing music, It should slow down the volume of other app.

**Describe alternatives you've considered**
When my app stop playing music,is resume other apps music instantly.

**Additional context**
No other context.

**Comment by ryanheise** [comment]
Please read the section of the README about the audio session, and then look into the audio_session package. I will close this since it is not a responsibility to be done in just_audio.
