### ISSUE TITLE
Make Exceptions inherit Exception type

### ISSUE THREAD

**Issue by bgoncharuck** [ryanheise/just_audio#492]
## What's wrong 
![зображення](https://user-images.githubusercontent.com/25586948/131062646-e6e991eb-128b-49a1-b95c-c987f9471556.png)

## Expected:
AnyException implements Exception {} or AnyException extends Exception {}

## Why:
Because when you use `try {} on Exception catch(exc)`, it will not be catched.

**Comment by ryanheise** [comment]
Added in 0.9.8.

**Comment by bgoncharuck** [comment]
Thank you so much!
