### ISSUE TITLE
cant use just_audio on web dart_html not found

### ISSUE THREAD

**Issue by voipworld** [ryanheise/just_audio#493]
** dart_html not found**
hello,
i am trying to use just_audio on web, but as i sayd, dart_html not found.
i dont import it, but its allready provided by the main just_audio plugin.
if i declare my player as html5Player i get this issue. otherwise if i just use audio_player class, its saying that the plugin pathProvider is using the getAppDirectory method or similar name dont remember it, that's not available on web.
please help.

**Comment by ryanheise** [comment]
This is not a feature request, it is a bug report. Make sure you click the appropriate bug template and provide a minimal reproduction project, thanks.
