### ISSUE TITLE
[iOS] playerState.state is always AudioPlaybackState.stopped

### ISSUE THREAD

**Issue by hacker1024** [ryanheise/just_audio#5]
If I start playback from a URL, and then check the `playerState.state` while it's playing, it's always `AudioPlaybackState.stopped`.

I haven't tested it on Android as I'm using my own audio plugin with queue support for the platform.

**Comment by hacker1024** [comment]
I have an iPhone SE with iOS 13. (It was a great find in my local e-waste bin)

**Comment by ryanheise** [comment]
First bug report!

Does this issue occur with the example app? If so, are you noticing a different behaviour on the iPhone vs the simulator?

**Comment by hacker1024** [comment]
Hmm, it doesn't happen with the example project.
I also have no audio coming out at all on the example project...

I can't compare my code to the example's because I switched to another audio plugin, though.

**Comment by ryanheise** [comment]
I've rewritten the Android implementation to support some low level features. As a result, you may want to retry this and see if your problem went away.

**Comment by volgin** [comment]
I think this can be closed. iOs works as expected.

**Comment by ryanheise** [comment]
Thanks for testing and reporting.
