### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by nioncode** [ryanheise/just_audio#50]
Thanks for the project.
Could you please tag your releases on github so that it is possibly to watch the repository for new releases to keep up-to-date with development without having to watch all issues?

**Comment by ryanheise** [comment]
Sure, I've just tagged the latest release. Hopefully I can get into the habit and not forget!

**Comment by nioncode** [comment]
Thanks for the fast response, I'm looking forward to follow the development and hopefully start to work with `just_audio` soon.
