### ISSUE TITLE
Can't Playing Streaming Radio

### ISSUE THREAD

**Issue by kojeksoft** [ryanheise/just_audio#501]
Which API doesn't behave as documented, and how does it misbehave?

Not sure which particular api is misbehaving. But seems like the interaction between player and ConcatenatingAudioSource is the problem.

The example in just_audio_background throws an exception if you empty the playlist, add a song by clicking "+" and then tap on the added song in the playlist.

Minimal reproduction project
The example in just_audio_background/example

To Reproduce (i.e. user steps, not code)
1. Use Sample just_audio_background/example 
2. Change 
AudioSource.uri(Uri.parse("https://s3.amazonaws.com/scifri-segments/scifri201711241.mp3")), 
To
AudioSource.uri(https://n01.radiojar.com/4ywdgup3bnzuv?rj-tok=AAABe7D30VkAfEM266RZXz6WWQ&rj-ttl=5")), 

https://n01.radiojar.com/4ywdgup3bnzuv?rj-tok=AAABe7D30VkAfEM266RZXz6WWQ&rj-ttl=5 Is Live Streaming Radio 

Error messages
E/ExoPlayerImplInternal(10152): Playback error
E/ExoPlayerImplInternal(10152):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal(10152):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(10152):       at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(10152):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(10152):   Caused by: com.google.android.exoplayer2.source.ClippingMediaSource$IllegalClippingException: Illegal clipping: not seekable to start
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ClippingMediaSource$ClippingTimeline.<init>(ClippingMediaSource.java:337)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ClippingMediaSource.refreshClippedTimeline(ClippingMediaSource.java:288)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ClippingMediaSource.onChildSourceInfoRefreshed(ClippingMediaSource.java:254)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ClippingMediaSource.onChildSourceInfoRefreshed(ClippingMediaSource.java:39)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.CompositeMediaSource.lambda$prepareChildSource$0$CompositeMediaSource(CompositeMediaSource.java:113)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.-$$Lambda$CompositeMediaSource$lU5TDdLYJk4FzgCLkUChati_nlA.onSourceInfoRefreshed(Unknown Source:4)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:84)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ProgressiveMediaSource.notifySourceInfoRefreshed(ProgressiveMediaSource.java:379)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ProgressiveMediaSource.prepareSourceInternal(ProgressiveMediaSource.java:294)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:197)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:118)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ClippingMediaSource.prepareSourceInternal(ClippingMediaSource.java:210)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:197)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:118)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:126)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ConcatenatingMediaSource.createPeriod(ConcatenatingMediaSource.java:489)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:128)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:118)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.MediaSourceList.createPeriod(MediaSourceList.java:310)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.MediaPeriodHolder.createMediaPeriod(MediaPeriodHolder.java:420)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:104)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriodHolder(MediaPeriodQueue.java:170)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1902)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1889)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:914)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
E/ExoPlayerImplInternal(10152):       ... 3 more
E/AudioPlayer(10152): TYPE_SOURCE: Illegal clipping: not seekable to start
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
I/ExoPlayerImpl(10152): Release fae240a [ExoPlayerLib/2.13.3] [j5y17ltedx, SM-J530Y, samsung, 28] [goog.exo.core]
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (10152): 
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (10152): 
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (10152): 
D/NetworkManagementSocketTagger(10152): tagSocket(104) with statsTag=0xffffffff, statsUid=-1
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (10152): 
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(0, Source error, null, null)
E/flutter (10152): 
I/chatty  (10152): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 1 line
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(0, Source error, null, null)
E/flutter (10152): 
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(0, Source error, null, null)
E/flutter (10152): 
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (10152): 
I/chatty  (10152): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 2 lines
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (10152): 
I/flutter (10152): Error loading playlist: (2) Unexpected runtime error
I/flutter (10152): #0      AudioPlayer._load (package:just_audio/just_audio.dart:785:9)
I/flutter (10152): <asynchronous suspension>
I/flutter (10152): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1351:28)
I/flutter (10152): <asynchronous suspension>
D/InputMethodManager(10152): prepareNavigationBarInfo() DecorView@2f77777[AudioServiceActivity]
D/InputMethodManager(10152): getNavigationBarColor() -855310
V/InputMethodManager(10152): Starting input: tba=com.ryanheise.just_audio_example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(10152): startInputInner - Id : 0
I/InputMethodManager(10152): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(10152): Input channel constructed: fd=104
D/InputTransport(10152): Input channel destroyed: fd=92
D/ViewRootImpl@b128650[AudioServiceActivity](10152): stopped(true) old=false
D/SurfaceView(10152): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280} of ViewRootImpl@b128650[AudioServiceActivity]
D/SurfaceView(10152): show() Surface(name=SurfaceView - com.ryanheise.just_audio_example/com.ryanheise.audioservice.AudioServiceActivity@acfde6f@0[10152])/@0x921b77c io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280}
D/SurfaceView(10152): surfaceDestroyed callback.size 1 #1 io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280}
W/libEGL  (10152): EGLNativeWindowType 0xcf2a7808 disconnect failed
D/SurfaceView(10152): destroy() Surface(name=SurfaceView - com.ryanheise.just_audio_example/com.ryanheise.audioservice.AudioServiceActivity@acfde6f@0[10152])/@0x921b77c io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280}
D/ViewRootImpl@b128650[AudioServiceActivity](10152): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(10152): prepareNavigationBarInfo() DecorView@2f77777[AudioServiceActivity]
D/InputMethodManager(10152): getNavigationBarColor() -855310
D/SurfaceView(10152): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280} of ViewRootImpl@b128650[AudioServiceActivity]
W/libEGL  (10152): EGLNativeWindowType 0xcf2a7008 disconnect failed
D/OpenGLRenderer(10152): eglDestroySurface = 0xe5bd9bc0, 0xcf2a7000
D/ViewRootImpl@b128650[AudioServiceActivity](10152): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x5 surface={false 0} changed=false
D/SurfaceView(10152): onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280} of ViewRootImpl@b128650[AudioServiceActivity]
D/ViewRootImpl@b128650[AudioServiceActivity](10152): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={false 0} changed=false
D/ViewRootImpl@b128650[AudioServiceActivity](10152): stopped(false) old=true
D/SurfaceView(10152): windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280} of ViewRootImpl@b128650[AudioServiceActivity]
D/SurfaceView(10152): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280} of ViewRootImpl@b128650[AudioServiceActivity]
D/ViewRootImpl@b128650[AudioServiceActivity](10152): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x7 surface={true 3260694528} changed=true
D/mali_winsys(10152): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/OpenGLRenderer(10152): eglCreateWindowSurface = 0xe5bd9bc0, 0xc25a4008
D/SurfaceView(10152): show() Surface(name=SurfaceView - com.ryanheise.just_audio_example/com.ryanheise.audioservice.AudioServiceActivity@acfde6f@1[10152])/@0x7b0fda6 io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280}
D/SurfaceView(10152): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280}
D/mali_winsys(10152): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000,  [720x1280]-format:1
D/SurfaceView(10152): surfaceChanged (720,1280) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{acfde6f V.E...... ........ 0,0-720,1280}
E/libEGL  (10152): call to OpenGL ES API with no current context (logged once per thread)
D/ViewRootImpl@b128650[AudioServiceActivity](10152): MSG_RESIZED_REPORT: frame=[0,0][720,1280] ci=[0,48][0,0] vi=[0,48][0,0] or=1
D/ViewRootImpl@b128650[AudioServiceActivity](10152): stopped(false) old=false
D/ViewRootImpl@b128650[AudioServiceActivity](10152): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(10152): prepareNavigationBarInfo() DecorView@2f77777[AudioServiceActivity]
D/InputMethodManager(10152): getNavigationBarColor() -855310
D/ViewRootImpl@b128650[AudioServiceActivity](10152): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={true 3260694528} changed=false
D/ViewRootImpl@b128650[AudioServiceActivity](10152): ViewPostIme pointer 0
D/ViewRootImpl@b128650[AudioServiceActivity](10152): ViewPostIme pointer 1
I/ExoPlayerImpl(10152): Init cdf4e32 [ExoPlayerLib/2.13.3] [j5y17ltedx, SM-J530Y, samsung, 28]
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger(10152): tagSocket(103) with statsTag=0xffffffff, statsUid=-1
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger(10152): tagSocket(103) with statsTag=0xffffffff, statsUid=-1
E/ExoPlayerImplInternal(10152): Playback error
E/ExoPlayerImplInternal(10152):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:587)
E/ExoPlayerImplInternal(10152):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(10152):       at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(10152):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(10152):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:86)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.ClippingMediaPeriod.selectTracks(ClippingMediaPeriod.java:119)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:292)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:255)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:189)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2139)
E/ExoPlayerImplInternal(10152):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:497)
E/ExoPlayerImplInternal(10152):       ... 3 more
E/AudioPlayer(10152): TYPE_UNEXPECTED: null
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (10152): 
I/chatty  (10152): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 2 lines
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (10152): 
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(10152): (HTTPLog)-Static: isSBSettingEnabled false
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (10152): 
I/chatty  (10152): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 2 lines
E/flutter (10152): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (10152): 
I/ExoPlayerImpl(10152): Release cdf4e32 [ExoPlayerLib/2.13.3] [j5y17ltedx, SM-J530Y, samsung, 28] [goog.exo.core]
D/NetworkManagementSocketTagger(10152): tagSocket(92) with statsTag=0xffffffff, statsUid=-1

Expected behavior
Before Update There is no Error, Error after update.

Screenshots
N/A

Desktop (please complete the following information):
 - OS: MacOS BigSur 11.5.2
 - Browser [e.g. chrome, safari + version]

Smartphone (please complete the following information):
 - Device: Samsung SM J530Y
 - OS: Android 9

Flutter SDK version
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale
    en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)

• No issues found!

Additional context
Running Well Before Update

**Comment by ryanheise** [comment]
Closing since this issue does not follow the instructions in the issue template.
