### ISSUE TITLE
ConcatenatingAudioSource not working with Live Radio Streaming

### ISSUE THREAD

**Issue by kojeksoft** [ryanheise/just_audio#503]
Which API doesn't behave as documented, and how does it misbehave?
Not sure which particular api is misbehaving. But seems like the interaction between player and ConcatenatingAudioSource is the problem

Minimal reproduction project
I was modified example and put it in 
https://github.com/kojeksoft/ryanheisejustaudiotest
Please check on AudioSource.uri

To Reproduce (i.e. user steps, not code)
1. Run app with background and didChangeAppLifecycleState (app modified in kojeksoft repository)
2. See error

Error messages
E/ExoPlayerImplInternal(27844): Playback error
E/ExoPlayerImplInternal(27844):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:587)
E/ExoPlayerImplInternal(27844):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(27844):       at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(27844):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(27844):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:86)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.source.ClippingMediaPeriod.selectTracks(ClippingMediaPeriod.java:119)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:292)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:255)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:189)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2139)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:497)
E/ExoPlayerImplInternal(27844):       ... 3 more
E/AudioPlayer(27844): TYPE_UNEXPECTED: null
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
I/ExoPlayerImpl(27844): Release a2cb1f7 [ExoPlayerLib/2.13.3] [j5y17ltedx, SM-J530Y, samsung, 28] [goog.exo.core]
D/NetworkManagementSocketTagger(27844): tagSocket(112) with statsTag=0xffffffff, statsUid=-1
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (27844): 
I/chatty  (27844): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 2 lines
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (27844): 
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (27844): 
I/chatty  (27844): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 2 lines
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (27844): 
I/flutter (27844): Error loading playlist: (2) Unexpected runtime error
I/flutter (27844): #0      AudioPlayer._load (package:just_audio/just_audio.dart:785:9)
I/flutter (27844): <asynchronous suspension>
I/flutter (27844): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1351:28)
I/flutter (27844): <asynchronous suspension>
D/ViewRootImpl@9d731a5[AudioServiceActivity](27844): ViewPostIme pointer 0
D/ViewRootImpl@9d731a5[AudioServiceActivity](27844): ViewPostIme pointer 1
I/ExoPlayerImpl(27844): Init 3a4c6fa [ExoPlayerLib/2.13.3] [j5y17ltedx, SM-J530Y, samsung, 28]
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger(27844): tagSocket(112) with statsTag=0xffffffff, statsUid=-1
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger(27844): tagSocket(113) with statsTag=0xffffffff, statsUid=-1
E/ExoPlayerImplInternal(27844): Playback error
E/ExoPlayerImplInternal(27844):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:587)
E/ExoPlayerImplInternal(27844):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(27844):       at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(27844):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(27844):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:86)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.source.ClippingMediaPeriod.selectTracks(ClippingMediaPeriod.java:119)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.source.MaskingMediaPeriod.selectTracks(MaskingMediaPeriod.java:186)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:292)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:255)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:189)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2139)
E/ExoPlayerImplInternal(27844):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:497)
E/ExoPlayerImplInternal(27844):       ... 3 more
E/AudioPlayer(27844): TYPE_UNEXPECTED: null
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (27844): 
I/chatty  (27844): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 2 lines
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(2, Unexpected runtime error, null, null)
E/flutter (27844): 
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(27844): (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger(27844): tagSocket(112) with statsTag=0xffffffff, statsUid=-1
I/ExoPlayerImpl(27844): Release 3a4c6fa [ExoPlayerLib/2.13.3] [j5y17ltedx, SM-J530Y, samsung, 28] [goog.exo.core]
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (27844): 
I/chatty  (27844): uid=10679(com.ryanheise.just_audio_example) 1.ui identical 2 lines
E/flutter (27844): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(abort, Connection aborted, null, null)
E/flutter (27844): 

Expected behavior
Expected to run with just_audio_background,not closing

Screenshots
N/A

Desktop (please complete the following information):
N/A

Smartphone (please complete the following information):
 - Device: Samsung SM J530Y
 - OS: Android 9

Flutter SDK version
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale
    en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)

• No issues found!

Additional context
N/A

**Comment by ryanheise** [comment]
ConcatenatingAudioSource is only intended for joining finite-length media together with known lengths, so that the next item automatically begins where the previous item ends. A live stream potentially never ends, so it doesn't make sense to use this with ConcatenatingAudioSource.

**Comment by kojeksoft** [comment]
What must I do if i want use it for Live Streaming ?
Another Library ?

**Comment by ryanheise** [comment]
I just said that concatenating live streams is nonsensical. I don't know how to do nonsensical things. Please also read CONTRIBUTING.md which explains that this GitHub page is not intended for asking for help with your app, it is intended for contributors to the development of this plugin.
