### ISSUE TITLE
how to set manual id in AudioPlayer()

### ISSUE THREAD

**Issue by g0coders** [ryanheise/just_audio#504]
I can't set the id on my player, so I can turn off the player using the id, how do I add it?

**Comment by ryanheise** [comment]
This is not actually a bug.

**Comment by g0coders** [comment]
> This is not actually a bug.

yes you are right, but i don't know which one to choose, so i just chose bug, sorry..

**Comment by ryanheise** [comment]
You're asking a question. Isn't it obvious to click on the "Question" option? Please correct me if I'm wrong and it is not obvious, but I'm not sure how to improve the wording of that option.

**Comment by g0coders** [comment]
> You're asking a question. Isn't it obvious to click on the "Question" option? Please correct me if I'm wrong and it is not obvious, but I'm not sure how to improve the wording of that option.

sorry for my english and wrong menu choice bug
