### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH error with ProgressiveAudioSource on Web

### ISSUE THREAD

**Issue by rguntha** [ryanheise/just_audio#506]
**Which API doesn't behave as documented, and how does it misbehave?**
I am playing the songs from server using the below call.

_audioPlayer.setAudioSource(ProgressiveAudioSource(uri));

The song would start playing immediately. It shows that it buffered half way through. But then it stops downloading with the  ERR_CONTENT_LENGTH_MISMATCH message.

So the AudioPlayer makes another request and download the full song.

The song plays successfully, but it is taking two requests often.

**
There are two problems because of this multiple requests

1. The server is doing double work in processing the file and sending and it is taking double bandwidth
2. Most importantly, I am trying to use the otp (One time password) with the link, so that malicious users won't be able to use the same link and download the song. But since the player is requesting the same link twice, I am unable to expire the OTP after the first request. Hence my server is vulnerable for stealing the songs. 
**

**Minimal reproduction project**
Provide a link here using one of two options:
 "The example".

**To Reproduce (i.e. user steps, not code)**
Just playing the song on the server through URL

**Error messages**

```
ERR_CONTENT_LENGTH_MISMATCH
```

**Expected behavior**
I am not sure why the error is happening. The fix may be on my server settings. I request one of the below solutions

1. If the error is because of my server configuration, please help me correct my configurations. If it is due to the fact that I am not using the API properly, then help me correct.
2. Please give a way (A callback function) so that we can refresh the url with a new OTP every time the Player makes the server call.

**Screenshots**
<img width="1680" alt="Screenshot 2021-09-07 at 6 05 47 PM" src="https://user-images.githubusercontent.com/3500293/132345523-a6e60534-623d-409d-8cde-4c666ab1bc2e.png">

> This screenshot shows the error messages

<img width="1680" alt="Screenshot 2021-09-07 at 6 01 09 PM" src="https://user-images.githubusercontent.com/3500293/132345250-17cb0340-38b8-43a7-acae-83df049f2ae2.png">

> This shows that url is requested 3 times. 2 failed and last one success. Please note that the song starts playing even if the request fails. But since the full buffering is not complete, it is making repeated requests until the full song is downloaded. For most of the songs, it is talking 2 requests. Sometimes it is finishing in single request, some times it is taking more than 2 requests.

<img width="1680" alt="Screenshot 2021-09-07 at 6 01 46 PM" src="https://user-images.githubusercontent.com/3500293/132345297-b29acb05-d34c-4307-8e07-28f6f5938371.png">

> Header1

<img width="1680" alt="Screenshot 2021-09-07 at 6 01 54 PM" src="https://user-images.githubusercontent.com/3500293/132345316-45e617ec-9fd2-464d-8751-2d4907526886.png">
> Header2

**Desktop (please complete the following information):**
 - Chrome Browser Version 92.0.4515.159 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.6.0-1.0.pre.154, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
[✓] Connected device (1 available)

```

**Additional context**
On the server side I am using NodeJS+Express with Nginx with https

```
location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                proxy_pass http://localhost:8080; #whatever port your app runs on
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                # proxy_set_header Connection keep-alive;
                # proxy_buffering  off;
        }
```

**Comment by ryanheise** [comment]
> **Minimal reproduction project**
> Provide a link here using one of two options:
> "The example".

The example works fine. Just saying "The example" when the example works fine is not a good way to get me to fix a bug. But from what you've written it looks like there is no bug, the plugin is reporting exactly the error that it should, because it's just being passed from the platform. You can search for what the error means to further your investigation, but please report here if you find an actual bug in this plugin.

**Comment by rguntha** [comment]
Ok. I understand. But as I suggested above,  the retries of the urls are preventing me from implementing the nonce/otp token in the link. So it would be great if we are provided a way to update the link with new nonce token before every time the player retries the link.

**Comment by ryanheise** [comment]
I can't change the way the web browser works. Meanwhile, I just checked your bug report again, and it still incorrectly claims the example exhibits a bug. The issue remains closed.

**Comment by rguntha** [comment]
Ok. Sorry for the miscommunication. I have modified the bug report.

I will request an enhancement to allow for refreshing the url just before the player downloads the content. This allows users to refresh he nonce tokens

**Comment by ryanheise** [comment]
I'm sorry but the instructions clearly say that the minimal reproduction project must be a link to a repository that I can clone. Your private app is NOT the same thing as a minimal reproduction project anyway. Have you read CONTRIBUTING.md?

If you want to make a feature request instead, that's fine, but again I don't know if I can change the way the web browser works. So if you do request a feature, make sure under the "Alternatives" section, you show that you have considered alternative workarounds that don't involve adding this feature to the plugin.

**Comment by ryanheise** [comment]
As mentioned, please make sure you fill in the "Alternatives" section.
