### ISSUE TITLE
New plugin to display waveform?

### ISSUE THREAD

**Issue by ryanheise** [ryanheise/just_audio#507]
**Is your feature request related to a problem? Please describe.**

Some people want to be able to display this:

![image](https://user-images.githubusercontent.com/37028113/132420619-743bbec4-ede5-4ad7-8f56-f537c19d4199.png)

While such a feature doesn't fit into just_audio's responsibilities, I can make it as a separate plugin if enough people want it. Vote with the thumbs up emoji if you need such a plugin.

**Describe the solution you'd like**

A separate plugin that decodes an audio file and extracts waveform data at the requested resolution. Perhaps also provide an option to either extract the whole waveform at once, or extract a particular segment of a particular duration (although note that depending on the audio format and the decoder, the accuracy of the second option will be worse, and sometimes. significantly so.)

**Describe alternatives you've considered**

Decoding audio on-device is still expensive, depending on the length of the audio file, so if that is an issue, an app may still prefer to do this on the server side.

**Additional context**

N/A

**Comment by Mighty683** [comment]
Beside file decoding I think live waveform data would be nice eg: I am creating online radio application and I want to add animation reflecting music streaming in background.

**Comment by ryanheise** [comment]
That is being tracked in a separate issue: #97 .

**Comment by ryanheise** [comment]
Hi everyone, there seems to be sufficient interest in the idea. I can't promise when I'll do it, but it's position in my priority list is going up thanks to your votes :+1:

**Comment by cedvdb** [comment]
This could be of interest:

https://github.com/flutter/flutter/issues/92366 This guy already has something like that

**Comment by ryanheise** [comment]
Thanks everyone for voting. **just_waveform** it is!

I only wish there were an easy way to rename plugins ;-) I've been manually fixing up all the identifiers and file names, and while I'm almost done, I think I'll get some sleep and finish the job in the morning.

**Comment by ryanheise** [comment]
New repo location:

https://github.com/ryanheise/just_waveform

**Comment by ryanheise** [comment]
Latest commit adds a `zoom` parameter allowing you to specify how many pixels per second to extract.

I'll consider this a release candidate for 0.0.1.

**Comment by ryanheise** [comment]
Hi everyone, the plugin has now been published here:

https://pub.dev/packages/just_waveform

Thanks @cedvdb for originally requesting this and everyone else who voted for it. Although I never expected to publish a 4th audio plugin, I'm glad it now exists and hopefully helps to solve a common use case.

There's still more work to be done, but I'll probably be cycling my attention to the other plugins next, so pull requests will certainly be welcome from this point, and so too will **likes on the plugin page linked above**. Let's see if we can get the number of likes above zero! :v:

**Comment by davidAg9** [comment]
> audiowaveform

What codecs are supported please

**Comment by ryanheise** [comment]
Now that the plugin has its own issues page,  I'll close this one too avoid duplicates and cross posting. For further issues, you can post on that project's issues page.
