### ISSUE TITLE
Enhance ProgressiveAudioSource to accept a function to generate a fresh Nonce everytime it calls server to download the content

### ISSUE THREAD

**Issue by rguntha** [ryanheise/just_audio#508]
**Is your feature request related to a problem? Please describe.**
I am streaming propriety audio from a server over web. My content is served by NodeJS+NGINX over SSL. To protect the content, I am using the nonce, or OTP (one time password) so that users may not be able to copy the link and download the song. 

I am using the `AudioPlayer.setAudioSource(ProgressiveAudioSource(uri)) ` call to download the song. The uri contains the nonce token. Which I suppose to expire on the server side after initial request.

But due to the nature of nginx, some times, the audio is not fully delivered resulting in the ERR_CONTENT_LENGTH_MISMATCH error, hence the AudioPlayer is forced to make multiple calls to the same uri (that has the nonce token) so that full song is downloaded and played. Due to this, I am unable to expire the nonce token after the first call, leaving the server vulnerable.

For the past several days, I have been researching for the fix for this issue in nginx configurations, but all my attempts to fix the nginx configurations have failed.

**Describe the solution you'd like**
I would like request for an enhancement to the  ProgressiveAudioSource api, such that it has another constructor that accespts a callback function. Whenever it is requesting the content from server, it calls the callback function to receive a fresh-made uri that contains a fresh nonce token. That way the AudioPlayer can make multiple calls to server without violating nonce.

This feature also becomes extremely useful when constructing long play lists with ProgressiveAudioSource. So that we don't generate a lot of nonce token in advance.

Ex API:
```
ProgressiveAudioSource.fromDynamicURI( 
Future<Uri> Function()
)
```

**Describe alternatives you've considered**
I do not have any other alternatives. I tried to fix the ERR_CONTENT_LENGTH_MISMATCH on the server-side and failed.

**Additional context**
Please refer to the issue I filed earlier in this regard.
[https://github.com/ryanheise/just_audio/issues/506#issuecomment-914823050](https://github.com/ryanheise/just_audio/issues/506#issuecomment-914823050)

**Comment by ryanheise** [comment]
I can't change the way the web browser works, so you'll have to come up with a different server-side approach to what you're doing.

**Comment by rguntha** [comment]
So from what you said, I understand that the AudioPlayer is making only one single call to load the data from the Url. It is the browser which is making the multiple calls in case the earlier calls resulted in partial data.

Is my understanding correct?

**Comment by ryanheise** [comment]
Yes. Once the plugin invokes the API once to play the audio, the browser takes care of the rest. I don't consider it a bug, the browser is just doing it's normal thing. You'll need to research what that is in order to figure out how you should be designing your app.

**Comment by rguntha** [comment]
I understand it now. Yes, it is not a bug of AudioPlayer. Thanks for your patience and guidance.
