### ISSUE TITLE
setUrl : send cookie info

### ISSUE THREAD

**Issue by odrevet** [ryanheise/just_audio#51]
Some remote audio needs an identification to be played. Could be helpful to have setUrl take http params or create a function that takes an HttpRequest as parameter.

**Comment by ryanheise** [comment]
I'm not sure what you mean by http params. Do you mean http headers?

**Comment by odrevet** [comment]
Yes that was what I meant

**Comment by ryanheise** [comment]
I see, it could be useful to have an optional `headers` parameter. Although, unfortunately I don't see a good solution for iOS, only hacks that would not be guaranteed to work into the future. I'll leave this issue open in case someone can suggest a solution.

**Comment by odrevet** [comment]
Many thanks ! Addressed with release 0.2.0
