### ISSUE TITLE
No error event when internet is turned off

### ISSUE THREAD

**Issue by blackraven96** [ryanheise/just_audio#516]
**Is your feature request related to a problem? Please describe.**
Is it possible to add an event when player failed to continue reading a stream ?

Ex: I play a stream. I turn off internet. The event I have is "buffering" and in log "E/ExoPlayerImplInternal(17441): Playback error"
If I turn on internet after this, nothing happen.

**Describe the solution you'd like**
I need an error event. And I will retry playing the stream myself.

**Describe alternatives you've considered**
I need an error event. And I will retry playing the stream myself.

**Additional context**
Thx you a lot for package :)

**Comment by ryanheise** [comment]
So there's no error on the event stream?

**Comment by blackraven96** [comment]
I don't think it's the best way to do this.
You can't detect "E/ExoPlayerImplInternal(17441): Playback error" ? And throw an error ?

**Comment by ryanheise** [comment]
I'm already reporting all ExoPlayer errors on the event stream, via the `onPlaybackError` method of `AudioPlayer.java`.

Can you confirm that the example `example/lib/main.dart` doesn't report this error with the prefix `"A stream error occurred: "`?

**Comment by blackraven96** [comment]
Oh, I'm truly sorry :( I didn't saw the "onError" of "_player.playbackEventStream.listen".

**Comment by sh4msi** [comment]
Hi,
I also have a problem and I think just_audio is a bit flawed in handling errors


![error](https://user-images.githubusercontent.com/6229984/133883286-d8868e49-409c-4a05-b264-568423871d49.jpg)

**Comment by ryanheise** [comment]
That sounds like a bug. Can you open a bug report? I'll then be able to investigate it.
