### ISSUE TITLE
[Feature Request] Auto get duration of mediaitem.

### ISSUE THREAD

**Issue by stonega** [ryanheise/just_audio#52]
Auto get duration from audio file is really needed,  the seek bar would not show if mediaItem dont have duration data right now.  looks like exoplayer have method to get the duration, but I need to learn java first /sad.

Thanks for great work.

**Comment by stonega** [comment]
I am wrong, this is not a just_audio issue,  it is about audio_service.

**Comment by Maadhav** [comment]
Did u find any solution for this?
