### ISSUE TITLE
Can't play mp3 file from local storage

### ISSUE THREAD

**Issue by Xango** [ryanheise/just_audio#520]
**Which API doesn't behave as documented, and how does it misbehave?**

- Playing audio from assets does not work
- The audio just doesn't play.
- An error message is thrown.

Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

- AudioPlayer().setAsset(Path); => produces above error

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
https://github.com/Xango/audio
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
1. Run the app on an IOS Simulator (I ran it on IPhone SE 2nd generation)
2. Click on 'play'

**Error messages**
"""[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: (-11849) Operation Stopped
#0      AudioPlayer._load
package:just_audio/just_audio.dart:785
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform
package:just_audio/just_audio.dart:1351
<asynchronous suspension>
"""

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

- I expected the mp3 file to be played.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS + Big Sur]

**Smartphone (please complete the following information):**
 - Device: [e.g. IPhone SE 2nd Generation (Simulator)]
 - OS: [e.g. IO 14.5]

**Flutter SDK version**
Flutter 2.2.3
```
insert output of "flutter doctor" here
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
```

**Additional context**

- Streaming works just fine with the package.
- I tried playing the file with a different package as well where it works.

**Comment by Xango** [comment]
> **Which API doesn't behave as documented, and how does it misbehave?**
> 
> * Playing audio from assets does not work
> * The audio just doesn't play.
> * An error message is thrown.
> 
> Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.
> 
> * AudioPlayer().setAsset(Path); => produces above error
> 
> **Minimal reproduction project**
> Provide a link here using one of two options:
> 
> 1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
>    https://github.com/Xango/audio
> 2. If the unmodified official example already reproduces the bug, just write "The example".
> 
> **To Reproduce (i.e. user steps, not code)**
> Steps to reproduce the behavior:
> 
> 1. Run the app on an IOS Simulator (I ran it on IPhone SE 2nd generation)
> 2. Click on 'play'
> 3. See error
> 
> **Error messages**
> """[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: (-11849) Operation Stopped
> #0 AudioPlayer._load
> package:just_audio/just_audio.dart:785
> 
> #1 AudioPlayer._setPlatformActive.setPlatform
> package:just_audio/just_audio.dart:1351
> 
> """
> 
> ```
> If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
> ```
> 
> **Expected behavior**
> 
> * I expected the mp3 file to be played.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [MacOS + Big Sur]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. IPhone SE 2nd Generation (Simulator)]
> * OS: [e.g. IO 14.5]
> 
> **Flutter SDK version**
> Flutter 2.2.3
> 
> ```
> insert output of "flutter doctor" here
> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-DE)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [!] Android Studio (version 2020.3)
>     ✗ Unable to find bundled Java version.
> [✓] VS Code (version 1.60.1)
> [✓] Connected device (2 available)
> ```
> 
> **Additional context**
> 
> * Streaming works just fine with the package.
> * I tried playing the file with a different package as well where it works.

**Comment by Xango** [comment]
I'm not sure why. I tried again today and it is working. I'm terribly sorry.

**Comment by Xango** [comment]
I double checked. The issue really only occurs when trying to play audio on IPhone SE 2nd generation so far.
I also tested it on a physical IPhone Device (Iphone X)
And it works there too


Reopening the issue.

**Comment by JohnCoppa** [comment]
I'm seeing this same issue running in debug mode on an iPhone 12.

Mp3 files won't play when calling setAsset('assets/test.mp3'), but calls to setAsset with a .aif file (again in the assets folder) work fine.

Same debug message: 'Expeption has occured.' PlayerException ((-11849) Operation Stopped)

Hope that helps in finding the issue.

**Comment by JohnCoppa** [comment]
@Xango - FWIW, here's how I'm working around this using just_audio and local assets. It's a bit verbose, but gets the job done in my case.

`
import 'dart:io';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:just_audio/just_audio.dart';
...

AudioPlayer _audioPlayer = AudioPlayer();

...

Future<void> playIntro() async {
    var content = await rootBundle
        .load("assets/game_assets/intro.mp3");
    final directory = await getApplicationDocumentsDirectory();
    var file = File("${directory.path}/intro.mp3");
    file.writeAsBytesSync(content.buffer.asUint8List());

    await _audioPlayer.setFilePath(file.path);
    _audioPlayer.play();
  }
`

**Comment by ryanheise** [comment]
@JohnCoppa that is pretty much what just_audio does internally to load an asset, but it has been reported that you might get an error if you don't await the `setAsset` call before playing. However, @Xango 's reproduction project seems to be doing that correctly.

It still sounds like a timing issue. I have actually seen issues before where the `dart:io` library doesn't sync to the filesystem when you think it does, and so inserting a delay between the filesystem write and the just_audio play can work.

In fact, the main difference between the the code snippet directly above and what just_audio does internally is that you've used `writeAsBytesSync` while I've used `await writeAsBytes`. Obviously in Flutter it's not good to use any heavy sync calls in the main isolate so I'd want to avoid that in this plugin, but can you test changing this in the plugin to see if it fixes the problem on your device?

**Comment by JohnCoppa** [comment]
@ryanheise - Thanks for the added perspective. Makes sense about the sync vs async.
I'll give that a try and let you know if that makes a difference in my particular case.

**Comment by Xango** [comment]
> @Xango - FWIW, here's how I'm working around this using just_audio and local assets. It's a bit verbose, but gets the job done in my case.
> 
> ```
> import 'dart:io';
> import 'package:flutter/services.dart';
> import 'package:path_provider/path_provider.dart';
> import 'package:just_audio/just_audio.dart';
> ...
> 
> AudioPlayer _audioPlayer = AudioPlayer();
> 
> ...
> 
> Future<void> playIntro() async {
>     var content = await rootBundle
>         .load("assets/game_assets/intro.mp3");
>     final directory = await getApplicationDocumentsDirectory();
>     var file = File("${directory.path}/intro.mp3");
>     file.writeAsBytesSync(content.buffer.asUint8List());
> 
>     await _audioPlayer.setFilePath(file.path);
>     _audioPlayer.play();
> }
> ```

Thx @JohnCoppa really appreciate the help.
I will test this out and revert ASAP.

**Comment by Xango** [comment]
> @JohnCoppa that is pretty much what just_audio does internally to load an asset, but it has been reported that you might get an error if you don't await the `setAsset` call before playing. However, @Xango 's reproduction project seems to be doing that correctly.
> 
> It still sounds like a timing issue. I have actually seen issues before where the `dart:io` library doesn't sync to the filesystem when you think it does, and so inserting a delay between the filesystem write and the just_audio play can work.
> 
> In fact, the main difference between the the code snippet directly above and what just_audio does internally is that you've used `writeAsBytesSync` while I've used `await writeAsBytes`. Obviously in Flutter it's not good to use any heavy sync calls in the main isolate so I'd want to avoid that in this plugin, but can you test changing this in the plugin to see if it fixes the problem on your device?

@ryanheise I will test it and revert ASAP.
Thx for your support and your efforts maintaining the plugin.

**Comment by rguntha** [comment]
I am facing the following error while loading a file from Assets. It works fine, when I copy the file to getApplicationDocumentsDirectory and read.

Please refer to the github repo https://github.com/rguntha/bytestream.git

```
W/.com.bytestrea(11944): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(11944): Init db921df [ExoPlayerLib/2.15.0] [1901, vivo 1901, vivo, 30]
I/TetheringManager(11944): registerTetheringEventCallback:com.bytestream.com.bytestream
E/ExoPlayerImplInternal(11944): Playback error
E/ExoPlayerImplInternal(11944):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(11944):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
E/ExoPlayerImplInternal(11944):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:594)
E/ExoPlayerImplInternal(11944):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(11944):       at android.os.Looper.loop(Looper.java:257)
E/ExoPlayerImplInternal(11944):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(11944):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal(11944):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(11944):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1025)
E/ExoPlayerImplInternal(11944):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
E/ExoPlayerImplInternal(11944):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(11944):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(11944):       at java.lang.Thread.run(Thread.java:923)
E/AudioPlayer(11944): TYPE_SOURCE: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, JpegExtractor) could read the stream.
I/ExoPlayerImpl(11944): Release db921df [ExoPlayerLib/2.15.0] [1901, vivo 1901, vivo, 30] [goog.exo.core]
I/flutter (11944): Player Processing State: ProcessingState.idle
E/flutter (11944): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: (0) Source error
E/flutter (11944): #0      AudioPlayer._load (package:just_audio/just_audio.dart:778:9)
E/flutter (11944): <asynchronous suspension>
E/flutter (11944): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1346:28)
E/flutter (11944): <asynchronous suspension>
E/flutter (11944): 

```

Flutter Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] Connected device (2 available)

```

**Comment by ryanheise** [comment]
@rguntha if this is the same project you referenced in the other issue for your implementation of `StreamAudioSource` then I already tested it and didn't get any error. Although if you are modifying the same example to reproduce two different issues, it would probably be better to create a separate branch for this particular issue.

**Comment by rguntha** [comment]
@ryanheise 
Thanks. This is the new exclusive repo for asset player https://github.com/rguntha/asset.git
But it is working fine now. I am not sure why it did not work yesterday.

**Comment by Xango** [comment]
@ryanheise @JohnCoppa 
my problem seems to have been solved
Thx again for your amazing work and patronage.
