### ISSUE TITLE
Enable Audio Offload to Minimize Battery Usage

### ISSUE THREAD

**Issue by ezflutter** [ryanheise/just_audio#522]
**Is your feature request related to a problem? Please describe.**

Yes, Exoplayer battery usage is high on long playbacks

**Describe the solution you'd like**

To minimize battery usage, have just_audio enable audio offload when playing long streams

**Describe alternatives you've considered**

I cannot find DefaultRenderersFactory.setEnableAudioOffload and ExoPlayer.experimentalSetOffloadSchedulingEnabled for more details on how to enable audio offload for exoplayer.

**Additional context**

https://exoplayer.dev/battery-consumption.html

**Comment by ryanheise** [comment]
I probably wouldn't want to automatically enable this when playing long streams, as this has implications that are not appropriate for all applications. But I can expose the ExoPlayer API to allow the app to turn it on as required.

**Comment by ryanheise** [comment]
I have now implemented offload scheduling and it is available for testing on the `feature/offload_scheduling` branch.

Note that enabling this will disable other audio processing such `setSpeed`, only one player can have this enabled at a time, it will only come into effect for certain audio formats supported by the hardware such as mp3, and enabling it doesn't guarantee that it will be enabled.

**Comment by ryanheise** [comment]
This is now published on pub.dev so I'll close.

**Comment by ryanheise** [comment]
For those subscribed to this issue, I am migrating to the latest media3 ExoPlayer which has a different offload scheduling API under the hood. To test it out before it gets released, see PR #1377 . Vanilla ExoPlayer now tries to enable offload by default but this potentially also disables gapless and speed changes, so I've coded around this to fit into just_audio.

The way it "should" work is that if offload scheduling is enabled via the constructor parameter, it may prevent you from changing the speed and may disrupt gapless playback depending on device support (offloading + gapless isn't supported before SDK 33). If offload scheduling is disabled (the default), then just_audio will still try to still enable offload scheduling if possible, but only if it won't disrupt gapless or speed changes. That's a slight deviation from the previous behaviour, but tries to give the best of both worlds without breaking anything. (Hopefully I didn't break anything!)

I'll probably need to expose a richer API around this in the future, but for now this is the behaviour based on the one current parameter that is exposed.
