### ISSUE TITLE
 The setAudioSource method will block UI thread in the IOS platform.

### ISSUE THREAD

**Issue by wgouyang** [ryanheise/just_audio#526]
**Which API doesn't behave as documented, and how does it misbehave?**
player.setAudioSource(), It will block the UI thread in the IOS platform(only) when the ConcatenatingAudioSource contains many UriAudioSource items. The more items more apparent.

**Minimal reproduction project**
Provide a link here using one of two options:
https://github.com/wgouyang/just_audio.git

**To Reproduce (i.e. user steps, not code)**
1. Run example_playlist file.
2. Scroll the playlist continuously during loading. It will block after a few seconds until the loading finish.

**Error messages**

**Expected behavior**
Don't block UI thread.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iphone 12 pro max simulator.
 - OS: IOS14.5

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment]
I'm not exactly sure what's going on here, but it seems to only affect the simulator, not real devices. Have you noticed it happening on a real device configuration?

**Comment by ryanheise** [comment]
One other interesting thing is that I notice even on the simulator that the progress indicator still spins during loading which suggests that the UI thread isn't really blocked on the simulator either.

**Comment by wgouyang** [comment]
> I'm not exactly sure what's going on here, but it seems to only affect the simulator, not real devices. Have you noticed it happening on a real device configuration?

No, I haven't tested on a real device, and thank you.

**Comment by Cyp** [comment]
This bug deadlocks the app completely, if using an AudioSource which uses a native plugin to fetch the data.

Note that there's both a Flutter UI thread (which can make spinners spin) and a native UI thread (which receives touch input and is needed for channels to native threads to work). The native UI thread is the one that is blocked while loading.

**Comment by ryanheise** [comment]
@Cyp is that on a physical device or the simulator?

**Comment by Cyp** [comment]
The iOS simulator, haven't tested with a physical device (except for an Android device, but it doesn't happen on Android anyway).

**Comment by ryanheise** [comment]
As mentioned, I think this seems to be an issue with the simulator since physical devices seem to work fine. If you notice any issue with a physical device let me know.
