### ISSUE TITLE
LockCachingAudioSource throws exception when using a Firebase url

### ISSUE THREAD

**Issue by alexda12** [ryanheise/just_audio#527]
**Which API doesn't behave as documented, and how does it misbehave?**
```
soundPlayer.setAudioSource(
      LockCachingAudioSource(
        uri,
)
)
```

**After the above code is run, we get an exception and no audio is played.**

**Minimal reproduction project**

I modified the example caching class in lib/example and just changed the sample url to be  a firebase url that I am using , something similar to : 

`https://firebasestorage.googleapis.com/v0/b/my-server.appspot.com/o/images%2Fuser%2FFIREBASE.COM-QKcTyNaAaIeUK19O6G3EpyRQbAs2%2F2021-09-27%2019%3A23%3A06.132846-7568.aac?alt=media&token=51d8092c-4c49-4e01-8d8f-2461a7830a01`

**To Reproduce (i.e. user steps, not code)**

In : 

`  LockCachingAudioSource(..)
`

Create a Uri which parses a Firebase Uri of this format : 

`https://firebasestorage.googleapis.com/v0/b/my-server.appspot.com/o/images%2Fuser%2FFIREBASE.COM-QKcTyNaAaIeUK19O6G3EpyRQbAs2%2F2021-09-27%2019%3A23%3A06.132846-7568.aac?alt=media&token=51d8092c-4c49-4e01-8d8f-2461a7830a01`

**Error messages**

```
 
flutter: (-11800) The operation could not be completed
flutter:
#0      AudioPlayer._load
package:just_audio/just_audio.dart:785
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform
package:just_audio/just_audio.dart:1351
<asynchronous suspension>
flutter: ----------------------------------------------------
flutter: -----

```

**Expected behavior**
I would expect that a Firebase Uri should be passable to **LockCachingAudioSource** in much the same way that it is accepted in **setUrl** and then we can  **play()** this.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
iPhone 11 Pro Max iOS 15 and also on Simulators.

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (3 available)
```

**Additional context**
N/A

**Comment by ryanheise** [comment]
Can you please create a minimal reproduction project as a git repo and share the link so that I can git clone it?

**Comment by alexda12** [comment]
@ryanheise 

Unfortunately I cannot send you a minimal reproduction since in order to do this I will be exposing google services information for my server.

As mentioned previously - I only changed one line from your example : 

![image](https://user-images.githubusercontent.com/58634787/135257250-da83262f-51b7-44eb-93b3-f4896de7a262.png)


![image](https://user-images.githubusercontent.com/58634787/135256797-3efbeed9-549a-4eb5-a410-da7147a41131.png)

and the structure is : 

![image](https://user-images.githubusercontent.com/58634787/135259468-62dd4691-e83e-4c80-9d5d-3fdcc87df662.png)

**I dont think the folder structure is the issue since I also tried to reference an audio resource from the root firebase storage folder**

just_audio works when you use **setUrl** with a firebase Uri - the issue I'm seeing is when I use **setAudioSource coupled with LockCachingAudioSource** together with a Firebase Uri

**Comment by alexda12** [comment]
I was doing some more debugging on this and noticed that this is where just_audio falls over : 

![image](https://user-images.githubusercontent.com/58634787/135304936-caecf04f-99cb-45a7-b369-6466f2417d6f.png)

It recovers with a _SimpleUri but with a _Uri created from as a result of a Firebase Url it fails.

**Comment by ryanheise** [comment]
Apologies for not commenting on the above closure, but this issue is closed since I don't have any minimal reproduction project. If you can't provide that, please consider continuing the investigation you are doing, and if you are able to fix it through a modification to the class depicted in your screenshot, please consider making a pull request.
