### ISSUE TITLE
Unhandled Exception: PlatformException(error, just_audio_background supports only a single player instance, null, null)

### ISSUE THREAD

**Issue by yasin1376** [ryanheise/just_audio#530]
I implemented the just_audio and just_audio_background to handle the player on the notification and background playing so I faced a problem when I play the audio first on my page, it is working great but when I come back to the screen from another audio this error shows me.

pls, help me with this exception to solve it.

Thanks in advance :)

**Comment by samatzhusup** [comment]
any solution?

**Comment by ryanheise** [comment]
This issue is closed because it didn't provide the information I requested in the instructions. Please open a new issue following the instructions.
