### ISSUE TITLE
Is _readCachedMimeType method always return audio/mpeg ?

### ISSUE THREAD

**Issue by itning** [ryanheise/just_audio#533]
**Which API doesn't behave as documented, and how does it misbehave?**

I read your source code and I use `LockCachingAudioSource` as audio source to play music ,I see the code [here](https://github.com/ryanheise/just_audio/blob/master/just_audio/lib/just_audio.dart#L2672) and this method alway return string `'audio/mpeg'`.

I think `.mime` file never exists, because did not create this file .

Did you forget to write it? Or is it deliberately designed like this?

Thanks.

```dart
/// We use this to record the original content type of the downloaded audio.
  /// NOTE: We could instead rely on the cache file extension, but the original
  /// URL might not provide a correct extension. As a fallback, we could map the
  /// MIME type to an extension but we will need a complete dictionary.
  Future<File> get _mimeFile async => File('${(await cacheFile).path}.mime');

  Future<String> _readCachedMimeType() async {
    final file = await _mimeFile;
    if (file.existsSync()) {
      return (await _mimeFile).readAsString();
    } else {
      return 'audio/mpeg';
    }
  }
```

**Minimal reproduction project**
```dart
import 'package:flutter/material.dart';
import 'package:just_audio/just_audio.dart';

void main() => runApp(const MainApp());

class MainApp extends StatefulWidget {
  const MainApp({Key? key}) : super(key: key);

  @override
  _MainAppState createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  var audioPlayer = AudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              LockCachingAudioSource lockCachingAudioSource = LockCachingAudioSource(
                  Uri.parse(
                      'http://127.0.0.1:8888/file?id=15fb2250c5f545ab9c9e7a49a08df602'));
              await audioPlayer.setAudioSource(lockCachingAudioSource);
              await audioPlayer.play();
            },
            child: const Icon(Icons.play_arrow),
          ),
        ),
      ),
    );
  }
}

```

**To Reproduce (i.e. user steps, not code)**
press icon button and will cache music file to disk and no `.mime` file to create.
![image](https://user-images.githubusercontent.com/19759891/135983357-40f827d7-1cc4-4fd2-abcb-3f5031d0c27f.png)

No file type is written in source code.
![image](https://user-images.githubusercontent.com/19759891/135983563-c083809e-dd3b-43ed-ba73-ce90107684b5.png)

**Error messages**

```
Nothing
```

**Expected behavior**
write `·mime` file to disk

**Screenshots**
Nothing

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: [xiaomi 10 pro]
 - OS: [android 11]

**Flutter SDK version**
```
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19043.1266], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] Connected device (3 available)

• No issues found!
```

**Additional context**

**Comment by ryanheise** [comment]
> **Minimal reproduction project**
> Nothing
> 
> **To Reproduce (i.e. user steps, not code)**
> Nothing

Can you please fill in these two sections according to the instructions? Please edit your issue to do so, thanks.

**Comment by itning** [comment]
> > **Minimal reproduction project**
> > Nothing
> > **To Reproduce (i.e. user steps, not code)**
> > Nothing
> 
> Can you please fill in these two sections according to the instructions? Please edit your issue to do so, thanks.

I`m sorry and I edit my issue.

**Comment by ryanheise** [comment]
OK please slow down a bit and take your time to read the instructions carefully. I will re-open once you have edited your issue appropriately.
