### ISSUE TITLE
Improve LockCachingAudioSource to allow playback between iOS and Android and vice-versa

### ISSUE THREAD

**Issue by sallypeters** [ryanheise/just_audio#534]
**Is your feature request related to a problem? Please describe.**

LockCachingAudioSource - although experimental works extremely well.

We can :

- Record audio (using another Audio plugin) on iOS and it can be played on **both iOS and Android**. It even allows Audio to be recorded on **iOS** and then played on **Android**. 

- Record audio (using another audio plugin) on Android and it can be played on Android **only**

The issue with the current implementation is that recording on Android only allows playback on Android. Regardless of whatever encoding is using (Assume AAC) - Audio that is recorded on Android and then using the **LockCachingAudioSource**  as the AudioSource doesn't allow playback on iOS devices.

The issue isn't anything to do with the encoding since if we persist the recorded audio to  (say) googles Cloud Storage - we can then use : 

```
await _soundPlayer.setUrl(YOUR_AUDIO_URL);
    _soundPlayer.play();
```

And then the SAME Audio plays without issue on both iOS & Android. 

I haven't gone through **LockCachingAudioSource** and compared it to creating an AudioSource via **setUrl** but there must be some slight differences regarding potential Encoding/Mime Types.
 
**Describe the solution you'd like**

**LockCachingAudioSource** should support the same playback as when a new AudioSource is constructed via the helper method **setUrl()**

**Describe alternatives you've considered**
The benefit of using **LockCachingAudioSource** is to provide implicit caching of Audio files. A very rudimentary alternative solution is to simply manage an alternate cache on the users device, use (say) DIO to download in its entirety the audio file and then by-pass **LockCachingAudioSource** if the audio is in the internal cache and use **AudioPlayers** to play from a Local file instead. 

**Additional context**
I have tried both **Sound** & **Flutter Sound Lite** to record Audio. I have then used the audio , persisted to Cloud Storage and then used just_audio's **LockCachingAudioSource** to perform the playback.  As mentioned, playback is only valid on both platforms if initially recorded on iOS. Going from Android doesnt allow playback on iOS. 

Additionally - **AudioPlayers** , **Flutter_sound_lite** & **Asset_Audio_Player** allow playback from iOS-to-Android and Android-to-iOS.

**Comment by ryanheise** [comment]
Hi @sallypeters this sounds like a bug in `LockCachingAudioSource`. Would you mind opening a bug report regarding the mime type issue in `LockCachingAudioSource` including a sample audio file that can't be played?
