### ISSUE TITLE
Can MediaItem art property support List<int> bytes ?

### ISSUE THREAD

**Issue by itning** [ryanheise/just_audio#537]
**Is your feature request related to a problem? Please describe.**
I use just_audio_background lib MediaItem object to set audio tag, but artUri only support uri type, 
and I art resource is base64 string so I try use Uri.dataFromBytes api to set artUri  but not work.
```dart
UriAudioSource audioSource = AudioSource.uri(
        Uri.parse(url),
        tag: MediaItem(
          // Specify a unique ID for each media item:
          id: music!.musicId ?? '1',
          // Metadata to display in the notification:
          artist: music.singer ?? '',
          title: music.name ?? '',
          artUri: Uri.dataFromBytes(
              base64Decode(MusicDataModel.get().coverBase64 ?? ''),
              mimeType: 'image/png'),
        ),
      );
```

**Describe the solution you'd like**
I want artUri support `List<int> bytes` type

**Describe alternatives you've considered**
like this:

```dart
UriAudioSource audioSource = AudioSource.uri(
        Uri.parse(url),
        tag: MediaItem(
          // Specify a unique ID for each media item:
          id: music!.musicId ?? '1',
          // Metadata to display in the notification:
          artist: music.singer ?? '',
          title: music.name ?? '',
          artUriData: base64Decode(MusicDataModel.get().coverBase64 ?? '')
        ),
      );
```

**Additional context**

Nothing

**Comment by ryanheise** [comment]
This would not be feasible on all platforms in an efficient way. For example, on Android and iOS this would involve sending bitmaps over platform channels quite frequently which would slow things down considerably. Instead, on those platforms you are better off writing the data to a file and then passing a `file://` URI. On web, maybe your approach will work (and maybe it already works).

What platform(s) are you building for, and will one of the above solutions work for you?
