### ISSUE TITLE
Pause doesn't work if called immediately after play

### ISSUE THREAD

**Issue by amitrotner** [ryanheise/just_audio#562]
**Which API doesn't behave as documented, and how does it misbehave?**
Pause doesn't work if called immediately after play. 

In my case, I have two players and I don't want them to play together. If the first play starts playing and immediately after that, the second one starts playing, I would like to pause the first one before playing the second.

This scenario is demonstrated using this piece of code:
 
```dart
IconButton(
                icon: Icon(Icons.audiotrack_outlined),
                iconSize: 64.0,
                onPressed: () async {
                  _player.play();
                  // ensure playing before pausing
                  await _player.playerStateStream.any((state) => state.playing);
                  await _player.pause();
                  _player2.play();
                },
              )
```

As you can see, I wait until the first player starts to play (waiting until the state.playing is true) before pausing it and playing the second one. However, _player.pause() doesn't really pause the player when called.

**Minimal reproduction project**
https://github.com/amitrotner/just_audio - modified main.dart under example

**To Reproduce (i.e. user steps, not code)**
1. Go to https://github.com/amitrotner/just_audio.
2. Run https://github.com/amitrotner/just_audio/blob/master/just_audio/example/lib/main.dart
3. Press the 'audiotrack_outlined' icon.

**Expected behavior**
Pause the first player before playing the second one.

**Screenshots**
https://github.com/amitrotner/just_audio/blob/master/just_audio/Screenrecorder-2021-10-19-15-56-44-517.mp4?raw=true

As you can see, the first player continue playing (although the progress bar is stuck and the icon is play). Only after pressing the play button twice, it pauses. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 10T Pro 5G M2007J3SY
 - OS: Android 11 (API 30)

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19042.1288], locale en-IL)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (version 4.1)
    X Unable to determine bundled Java version.
[√] Android Studio (version 4.2)
[√] VS Code (version 1.61.0)
[√] Connected device (3 available)
```

**Comment by ryanheise** [comment]
The fix has now been published in 0.9.14. Thanks for helping to report and test.
