### ISSUE TITLE
Confusing semi-endorsement of Windows/Linux

### ISSUE THREAD

**Issue by stuartmorgan** [ryanheise/just_audio#582]
**Which API doesn't behave as documented, and how does it misbehave?**
This is not API-related.

The pubspec for the app-facing package lists `just_audio_libwinmedia` as a default package, but doesn't include `just_audio_libwinmedia` in the `dependencies` section. The result is that the package is displayed as supporting Windows and Linux on pub.dev, but doesn't actually work out of the box on those platforms.

It's not clear to me what this is intended to accomplish. If you are comfortable endorsing that implementation, why isn't it a dependency? If you are not, what is the `default_package` entry for? This "semi-endorsement", for lack of a better term, isn't an intended use case of `default_package`.

**Minimal reproduction project**
N/A

**To Reproduce (i.e. user steps, not code)**
1. Look at `pubspec.yaml`

**Error messages**
https://stackoverflow.com/questions/69812860/missingpluginexceptionno-implementation-found-for-method-init-on-channel-com-ry looks like the error I would expect to result from this.

**Expected behavior**
No endorsement, or a complete endorsement.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows or Linux

**Smartphone (please complete the following information):**
N/A

**Flutter SDK version**
N/A

**Additional context**
I'm aware that the README says to include that dependency in the app, but I'm not sure why you're making that a manual step if the intent is endorsement.

**Comment by ryanheise** [comment]
Ah, I see. When the just_audio_libwinmedia implementation was first submitted as a pull request, it was submitted as an endorsed plugin. However, since it's still quite new and needs some time for bugs to be ironed out, I made an edit to remove the endorsement and require app developers to explicitly add it if they want to try it.

It seems I overlooked the `platforms` section.

Another reason for delaying endorsement is that when I last checked, there was no way to both endorse a default implementation and also allow an app to override that default with an alternative Windows or Linux implementation. Is that now possible?

**Comment by stuartmorgan** [comment]
> It seems I overlooked the `platforms` section.

I would definitely recommend fixing that in the interim then, to avoid having pub.dev (and the pubspec) indicate platform support that's not actually there.

> Another reason for delaying endorsement is that when I last checked, there was no way to both endorse a default implementation and also allow an app to override that default with an alternative Windows or Linux implementation. Is that now possible?

If the default implementation and the alternative both use `dartPluginClass`, it should work. (Eventually it should work regardless of implementation method, but even a method-channel-based implementation based on a shared method channel can use `dartPluginClass` to register a trivial subclass of the method channel implementation so it's not a major limitation.)

**Comment by ryanheise** [comment]
That's good to know, thanks. just_audio_libwinmedia does use `dartPluginClass` fortunately.

For now, I have republished just_audio without the confused semi-endorsement which should fix the immediate issue.

**Comment by ryanheise** [comment]
It appears to be now updated on pub.dev so I'll close this issue.
