### ISSUE TITLE
sound in background not working on all devices

### ISSUE THREAD

**Issue by serraojoao** [ryanheise/just_audio#592]
In some devices the sound in background is just not playing, i am seeding the player with an asset file (local bytestreams file) using the following sample.

await _audioPlayer.setAsset('local file path').then((_) {
                    _audioPlayer.load().catchError((onError) {
                    });
                  }).then((_) {
                    _audioPlayer.play().catchError((onError) {
                    });
                  }).catchError((onError, stackTrace) async {
                    await FirebaseCrashlytics.instance.recordError(
                        onError, stackTrace,
                        reason: 'Error fetching audio asset');
                  });

The above code is inside a background location update so when the location changed a sound is triggered.

Deploying the build in a iPhone 7 with iOS 15.1 it works as expected however in iphone 11 pro with iOS 15.1 it simple does not play the sound.  Any idea what can cause this? can this be hardware related?

No errors are logged, behaves as it worked properly but sound just does not play

**Comment by ryanheise** [comment]
Please don't delete all of the instructions in the issue template. I will close this, but you can open a new issue if you fill in all sections of the form as necessary.
