### ISSUE TITLE
Example needs to be updated to use AndroidX

### ISSUE THREAD

**Issue by Sun3** [ryanheise/just_audio#6]
The example android app needs to be updated to use AndroidX or it will not compile.

File: gradle.properties
Add the following:
```
android.useAndroidX=true
android.enableJetifier=true
```
Full gradle.properties file: 
```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

Thanks.

**Comment by ryanheise** [comment]
Hi @Sun3 I have updated the plugin to AndroidX in Git although I need to complete some iOS coding before I can publish it.

**Comment by ryanheise** [comment]
Published.
