### ISSUE TITLE
Music does not stop even after clearing the app from the cache

### ISSUE THREAD

**Issue by dhruvarora91** [ryanheise/just_audio#609]
**Which API doesn't behave as documented, and how does it misbehave?**
Music does not stop even after clearing the app from the cache

**Minimal reproduction project**
"The example"

**To Reproduce (i.e. user steps, not code)**
1. Run the app.
2. Clear the app from the cache.
3. The audio still plays.

**Expected behavior**
As soon as we clear the app from the cache, the music should stop.

**Desktop (please complete the following information):**
 - OS: Arco Linux

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL Emulator, Poco X3 Pro
 - OS: Android

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on Linux 5.10.84-1-lts, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)

• No issues found!
```

**Additional context**
N/A

**Comment by nzackoya** [comment]
This is the most important one I guess. Is there any workaround for now until we get the fix?

**Comment by ryanheise** [comment]
You haven't stated a bug because you didn't answer the first question in the bug report. Which API is not behaving as documented? Can you show me the part of the documentation you're referring to?

**Comment by ryanheise** [comment]
To clarify, I'm referring to this section:

> **Which API doesn't behave as documented, and how does it misbehave?**
> Music does not stop even after clearing the app from the cache

What is the documented behaviour, and can you provide a link to it so I know what you're referring to?

**Comment by dhruvarora91** [comment]
[In Just Audio Background example ](https://github.com/ryanheise/just_audio/blob/master/just_audio_background/example/lib/main.dart)

**Comment by ryanheise** [comment]
I think you don't understand what documentation is, or what an API is, right? Because you have mentioned neither documentation nor an API.

**Comment by dhruvarora91** [comment]
I am just saying that when you run the just_audio_background example, when we clear the app from the cache, the music still plays. Is there any way to stop the music then like onTaskRemoved in audio_service package.

**Comment by ryanheise** [comment]
I'm not asking you for any of that, I'm simply asking you to answer the first question in the bug report. If you are going to ignore the first question of the bug report, then this is not to be classified as a bug and you should close the issue.

**Comment by ryanheise** [comment]
I'm closing this, but if you believe it is a bug and can provide the details requested in the first question I can reopen.
