### ISSUE TITLE
additional audiosource: Uint8List

### ISSUE THREAD

**Issue by t-m-z** [ryanheise/just_audio#624]
**Is your feature request related to a problem? Please describe.**
I want to extract Bytedata as an Uint8List - which is an audiofile - from another file and play it.

**Describe the solution you'd like**
Besides URL, local files and assets also a Uint8List should be accepted as an audio source.

**Describe alternatives you've considered**
Save the Bytedata to a local file and open it for playing.

**Additional context**
No.

Kind regards

**Comment by ryanheise** [comment]
Another alternative is to implement `StreamAudioSource`. If you search past issues you may find some sample code with a simple implementation that just returns a byte array.

**Comment by t-m-z** [comment]
Am I right that you point to
ryanheise/just_audio#531 - Improve StreamAudioSource Documentation
ryanheise/just_audio#484 - Please Enhance StreamAudioSource to return small chunks from the byte array

A confirmation would be helpful.
Thanks in advance.

**Comment by ryanheise** [comment]
Yes, there may even be some more issues in the archive on this topic.

**Comment by t-m-z** [comment]
Thanks - I will search and study these.

Have a successful 2022 and stay healthy

**Comment by ryanheise** [comment]
I'll close this since `StreamAudioSource` can support this with a stream such as `Stream.value(byteArray)`.
