### ISSUE TITLE
await setAutomaticallyWaitsToMinimizeStalling never returns a value on Android

### ISSUE THREAD

**Issue by snaeji** [ryanheise/just_audio#63]
On Android if you await setAutomaticallyWaitsToMinimizeStalling() the function never completes. It should probably just return false on an Android device?

Simple example code would be:

```
await _player.setUrl('www.url.com/mp3');
await _palyer.setAutomaticallyWaitsToMinimizeStalling(true); <- Stalls here
await _player.play();
```

**Comment by stonega** [comment]
/// Sets automaticallyWaitsToMinimizeStalling for AVPlayer in iOS 10.0 or later, defaults to true.​
 /// Has no effect on Android clients​
 You can find it in code comment.

**Comment by ryanheise** [comment]
Thanks for finding the bug. I think it should probably be a no-op on Android, in which case the Android side is probably missing a `success()` call. I'll take a look after the current task I'm working on, but in the meantime I suppose you can check if `Platform.isIOS` before calling.

**Comment by ryanheise** [comment]
This should be fixed in the latest commit.

**Comment by snaeji** [comment]
Great work! Sorry that i forgot to reply to the earlier comment. I had the same solution to use a platform check :)
