### ISSUE TITLE
Can not get remote audio duration, when i use  player.setUrl()。

### ISSUE THREAD

**Issue by xiaoxin-sky** [ryanheise/just_audio#636]
**Which API doesn't behave as documented, and how does it misbehave?**
When I use `await player?.setUrl('http://192.168.2.190:3334/')` to obtain the length of audio stream, it always returns `flutter: 0:00:00.000000`. The address http://192.168.2.190:3334/ is provided by my local nodejs server. I have always suspected that there is a problem with the response header returned by the server. I have tried many times yesterday, but it has not been solved. 
My own resources can't get the duration, but the resources in other people's issue can get the duration；

**Minimal reproduction project**

**I provide the minimum sample repository of my nodejs service as follows:**

[https://github.com/xiaoxin-sky/nodejsAudioServer](https://github.com/xiaoxin-sky/nodejsAudioServer)，You can start an audio streaming service through this warehouse. After starting, access your local IP: 3334, and you will get the audio streaming resources. But you can't get duration through my nodejs service. `await AudioPlayer().setUrl('http://id:3334/')`，then run `play()`

**other peoples's resource：** 
[https://portal.homeenglish.com.br/uploads-aula/C_IM_S_A_03_groceries.mp3](https://portal.homeenglish.com.br/uploads-aula/C_IM_S_A_03_groceries.mp3) ,You can get the returned duration through the following command `await AudioPlayer().setUrl('https://portal.homeenglish.com.br/uploads-aula/C_IM_S_A_03_groceries.mp3')`，then run `play()`;

**To Reproduce (i.e. user steps, not code)**
Start the node service
1. git clone https://github.com/xiaoxin-sky/nodejsAudioServer
2. cd nodejsAudioServer
3. npm start

**Error messages**
no error

**Expected behavior**

Expect to get duration

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: [iPhone8]
 - OS: [iOS14.4.1]
 - nodejs: [v14.17.2]

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Additional context**

**Comment by ryanheise** [comment]
What are your response headers for this URL? Make sure they conform to apple's requirements.

**Comment by xiaoxin-sky** [comment]
> What are your response headers for this URL? Make sure they conform to apple's requirements.

First of all, thank you for your reply.Any way，I replace the native nodejs and use express, and then  the duration can be obtained amazingly. With the same logic, I don't know what happened, but I make sure that the response headers I return are the same. Do you know which field is used to get the duration of my audio stream?

``` js
if (req.headers.range) {
    var range = req.headers.range;
    var parts = range.replace(/bytes=/, "").split("-");
    var partialstart = parts[0];
    var partialend = parts[1];

    var start = parseInt(partialstart, 10);
    var end = partialend ? parseInt(partialend, 10) : total - 1;
    var chunksize = end - start + 1;
    var readStream = fs.createReadStream(filePath, { start: start, end: end });
    res.writeHead(206, {
      "Content-Range": "bytes " + start + "-" + end + "/" + total,
      "Accept-Ranges": "bytes",
      "Content-Length": chunksize,
      "Content-Type": "audio/mpeg",
    });
    readStream.pipe(res);
  } else {
    res.writeHead(200, {
      "Content-Length": total,
      "Content-Type": "audio/mpeg",
    });
    fs.createReadStream(filePath).pipe(res);
  }
```

**Comment by xiaoxin-sky** [comment]
Although I didn't use native nodejs to solve this problem, because I didn't know how to return the correct response header, I finally chose express. If you have any good ways to solve the problem of nodejs response header, please comment.

**Comment by ryanheise** [comment]
The thing about range requests is that they advertise to the client that it is able to make further range requests for different parts of the file. E.g. If the duration metadata is stored at the end of the file, the client will want to jump to the end of the file to read that bit, and will make a range request for that specific bit. If your server doesn't support that, that's probably why it doesn't work.
