### ISSUE TITLE
Live stream playback doesn't work

### ISSUE THREAD

**Issue by ashishpatel1992** [ryanheise/just_audio#64]
I am unable to play Live Stream URL
Server is using Icecast to stream.
Sample Stream URL: http://canada1.reliastream.com:8052/live?type=.mp3

**Expected Solution**
It should be able to play live stream audio

**Comment by stonega** [comment]
I tested it on android side, works fine.
If you are using android, too, these may help you.
First you need to turn on usesCleartextTraffic in AndroidManifest.xml if you haven't.
`<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>`
Then use the leatest version.  
`just_audio:
    git:
      url: https://github.com/ryanheise/just_audio.git `

**Comment by ashishpatel1992** [comment]
Thanks a lot it is working now.
Can you add this into documentation? Easier for everyone
