### ISSUE TITLE
(Linux?) play() sometimes buffers forever

### ISSUE THREAD

**Issue by nathanfranke** [ryanheise/just_audio#641]
**Which API doesn't behave as documented, and how does it misbehave?**
`AudioPlayer.setUrl`
`AudioPlayer.play`

**Minimal reproduction project**
The example

**To Reproduce (i.e. user steps, not code)**
1. Run lib/example_playlist.dart
2. Click play

**Error messages**
Note sure if this is causing the issue.
```
CONSOLE JS ERROR Unhandled Promise Rejection: AbortError: The operation was aborted.
```

**Expected behavior**
Playback starts shortly after pressing play.

**Screenshots**
![image](https://user-images.githubusercontent.com/14253836/151875764-bd8d9ade-4ad7-4878-b428-a5bb390f664a.png)

**Desktop (please complete the following information):**
 - OS: Linux x86_64 on kernel 5.15.18-1-lts
 - Browser: N/A (Using desktop)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 2.8.1, on Arch Linux 5.15.18-1-lts, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
```

**Additional context**
It seems to work sometimes, but most of the time it does not.

**Comment by ryanheise** [comment]
Hi @nathanfranke I would suggest reporting this bug on the [just_audio_libwinmedia](https://github.com/bdlukaa/just_audio_libwinmedia/issues) project but check if there is already an existing issue for it.
