### ISSUE TITLE
Audio play faster first time for few second in android

### ISSUE THREAD

**Issue by nimisharanipabacancy** [ryanheise/just_audio#649]
**Which API doesn't behave as documented, and how does it misbehave?**
While playing first time audio.

**Minimal reproduction project**
This issue is also reproduce in plugin example
https://github.com/ryanheise/just_audio/tree/master/just_audio/example

**To Reproduce (i.e. user steps, not code)**
As the audio initialise, start playing audio instantly, then audio will play in 1.5x speed(faster than normal) after some second it's playing with normal speed.

**Error messages**

**Expected behavior**
Audio should play in normal speed in first time as well.

**Smartphone (please complete the following information):**
 - Android version (11)
 
**Flutter SDK version**
Flutter 2.10.0-0.0.pre • channel master 

**Additional context**

**Comment by ryanheise** [comment]
Are you able to record a video of this? It doesn't happen on my own phone.

**Comment by emresakar** [comment]
If you run your app on a virtual device, it can happen. Can you please try to run on a real device?

**Comment by ryanheise** [comment]
I only test on real devices.

**Comment by emresakar** [comment]
Sorry, I actually wrote that for [nimisharanipabacancy](https://github.com/nimisharanipabacancy) :)
I already experienced this issue on Android back in 2017 while I was using Java to develop my app. It is known that, android emulators can give audio faster than normal for the first 2-3 seconds. Also, some audio crackling can happen. It does not mean on real devices these problems can occur. So, it would be great for you if [nimisharanipabacancy](https://github.com/nimisharanipabacancy) tries his app on a real device than give details about the bug, if experienced any.

**Comment by ryanheise** [comment]
Ah, thanks for clarifying :-)

**Comment by nimisharanipabacancy** [comment]
I am testing is emulator. while test in real device with version - 9 it is working fine.

**Comment by ryanheise** [comment]
Shall we close this then?

**Comment by nimisharanipabacancy** [comment]
Yes, Thanks.
