### ISSUE TITLE
Recover from UnknownHostException (no network) and Play from local asset list

### ISSUE THREAD

**Issue by emresakar** [ryanheise/just_audio#653]
Hello,

**Is your feature request related to a problem? Please describe.**
I am currently using ConcatenatingAudioSource to play audio from network. Lets say I am hosting 10 mp3 files on my server and my app plays these. When user's internet connection is lost, after a few seconds just_audio tries to play next mp3 file. An exception occurs since there is no network. Then, just_audio tries to play next mp3 file. Exception occurs. It goes like this until just_audio hits the last mp3 in the list. After just_audio tries to play all the mp3 files that are in the list, it stops even though its setLoopMode is set to LoopMode.all.

So, my first question; is this a desired feature? In my opinion, since setLoopMode is set to LoopMode.all, just_audio should keep trying to play mp3 files constantly even if there is no network. Thanks to that, when user's internet connection established again, just_audio will be able to start playing something.

My second question (or feature request) will be related to first one. Since just_audio stops playing after trials, when there is no network, how do we recover and make it to start playing a mp3 file from the list when a network connection is established again?

And my final question (or feature request); how do we use ConcatenatingAudioSource to play mp3 files from assets folder? Since its children takes a AudioSource list, which is populated by AudioSource.uri method, I could be able to use it for loading mp3 files from assets folder.

**Describe the solution you'd like**
Possible solutions have been discussed above.

**Describe alternatives you've considered**
A timer will be checking whether player is playing or not. If player is not playing, player.play() will be executed. But what if user is on the phone? Or user might be playing something else?

**Additional context**
No additional context.

Since I am not a Flutter expert, these questions might be a little bit weird :)
Thanks.

**Comment by ryanheise** [comment]
This feature request should be split up into multiple. Can you create separate issues following the template in each case? Note that there may be existing issues already covering some of your feature requests, so you might want to search them first.

**Comment by emresakar** [comment]
Thanks for answering :). I actually was not sure about whether these are questions or future requests. Because there may be workarounds or direct solutions to what I ask here. What I understand from your answer is, these are future requests, there is no way to handle what I detailed above. If so, I will be closing this issue and opening a separate one for recovering no network error while setLoopMode is set to LoopMode.all.

**Comment by ryanheise** [comment]
No, I only took a cursory glance at what you wrote so far, and cannot confirm whether they are feature requests or questions. But if you are making feature requests, then please fill in one issue per feature, following the format of the template. If you just want to know how to achieve something and haven't read the documentation, best to read the documentation first but then if you're still not sure, ask on StackOverflow as that is the designated place for questions. It is one of the links you'll see when you open a new issue.

**Comment by ryanheise** [comment]
Also I'll mention it again, but please also search past issues before opening new ones to ensure it is not a duplicate issue in each case.
