### ISSUE TITLE
Loop mode for ConcatenatingAudioSource

### ISSUE THREAD

**Issue by DanielCardonaRojas** [ryanheise/just_audio#654]
Hi @ryanheise  first of all thank you for making this plugin.

I'm trying out this package on web platform and I'm encountering the following issue: 

I'm creating a ConcatenatingAudioSource and I was expecting the loop mode to behave differently.

For example: 

```dart
     final source = ConcatenatingAudioSource(
        useLazyPreparation: false,
        children: [
          AudioSource.uri(Uri.parse('asset://assets/samples/click_1.wav')),
          AudioSource.uri(Uri.parse('asset://assets/samples/click_2.wav')),
        ],
      );

player.setAudioSource(source);
player.setLoopMode(LoopMode.one);
```

My expectation was that having this setup the both concatenated audio samples would play in loop (click_1.wav followed by click_2.wav) however it does not... Do I need to implement a custom ShuffleOrder for this to work or is there a missing feature to 
get this behaviour.

**Comment by ryanheise** [comment]
Hi @DanielCardonaRojas you may click the last menu item called "Question" to ask a question, not "Feature request".
