### ISSUE TITLE
HLS Windows Support

### ISSUE THREAD

**Issue by aguilaair** [ryanheise/just_audio#667]
**To which pages does your suggestion apply?**

- [Readme](https://github.com/ryanheise/just_audio/blob/master/just_audio/README.md)

**Quote the sentences(s) from the documentation to be improved (if any)**

> "Windows HLS supported"

**Describe your suggestion**

According to https://github.com/ryanheise/just_audio/issues/103#issuecomment-922405803 and my tests, HLS does not work on Windows, it just keeps buffering and will not play.

Tested with https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8, works with Android.

```dart
audioPlayer?.setAudioSource(
      HlsAudioSource(
        Uri.parse(
            "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8"),
      ),
```

**Comment by ryanheise** [comment]
It will be best to open this issue on the just_audio_libwinmedia issues page.

**Comment by aguilaair** [comment]
Do you want me to move it?

**Comment by ryanheise** [comment]
Yes, it would be best.
