### ISSUE TITLE
Is there any method to stop foreground notification ? I want create a logout function for my app and want to stop displaying foreground notification 

### ISSUE THREAD

**Issue by Prateek0Srivastav** [ryanheise/just_audio#670]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
insert output of "flutter doctor" here
```

**Additional context**

**Comment by Prateek0Srivastav** [comment]
I have used player.stop, player.dispose but they doesn't work

**Comment by ryanheise** [comment]
You completely ignored the instructions - closing.

**Comment by Prateek0Srivastav** [comment]
which instructions ? can be more specific cause i am new to flutter , please help me up to resolve my issue

**Comment by ryanheise** [comment]
Have you read your own bug report? You left all of the instructions in there without actually reading any of what it says.

**Comment by ryanheise** [comment]
Also, the title of your bug report doesn't even seem like it is a bug. If you are just asking for help, when you click on the new issue button you need to read the instructions there too because there is a special option for asking first help. You clicked the wrong one because you didn't actually read what it said.

**Comment by Prateek0Srivastav** [comment]
okay I will be more specific about my issue I want to develop button on it, I want a function that I want logout from my app and stop displaying the foreground ongoing notification, I have used player.stop(), player.dispose(). but still the foreground ongoing notification is there.

**Comment by ryanheise** [comment]
Are you just going to keep writing more comments rather than follow the instructions? In that case, I'm sorry I will have to lock this thread because I don't have time for that.
