### ISSUE TITLE
The stop() method does not work with just_audio_background package

### ISSUE THREAD

**Issue by terry1213** [ryanheise/just_audio#672]
**Which API doesn't behave as documented, and how does it misbehave?**
If I use just_audio with just_audio_background, the **stop()** method does not work.

**Minimal reproduction project**
<https://github.com/terry1213/just_audio/tree/master/just_audio_background/example>

**To Reproduce (i.e. user steps, not code)**
1. Play the audio player.
2. Stop the audio player. (In the 'just_audio_background' example, I just changed the pause button to the stop button.)
3. The audio player does not stop.
4. An error occurs if I try to play the audio again.

**Error messages**

```
Unhandled Exception: PlatformException(error, Platform player already exists, null, null)
```

**Expected behavior**
The audio player stops.

**Screenshots**
No screenshot.

**Desktop (please complete the following information):**
 - OS: MacOS 11.6

**Smartphone (please complete the following information):**
 - Device: Iphone SE2
 - OS: IOS 15.3.1

**Flutter SDK version**
2.10.2
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-arm, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**
just_audio: 0.9.20, just_audio_background: 0.0.1-beta.4

As I said before, I changed the pause button to the stop button in the 'just_audio_background' example just for test.
And I added some print() in **init()**, **disposeAllPlayers()**, **disposePlayer()** methods to check the audio player's state(and id).

When the app starts, the following message appears in the console.
```
flutter: background disposeAllPlayers(): null // I know that this is not an error because the app started right now so there is no player to be disposed.
flutter: init(): 1cf09bdd-1867-4fc0-bce1-7119ef554aae
```

If I touch stop button to stop the '1cf09bdd-1867-4fc0-bce1-7119ef554aae' player, the **disposePlayer()** is called.
```
flutter: background disposePlayer(): null
```
However the '1cf09bdd-1867-4fc0-bce1-7119ef554aae' player can not be stopped because the _player is null.

I think **disposeAllPlayers()** makes this problem. When I removed the code that calls **disposeAllPlayers()**, the error does not occur.

**Comment by ryanheise** [comment]
Related to #668 ?

**Comment by terry1213** [comment]
@ryanheise I think so.

**Comment by ryanheise** [comment]
OK, I am able to reproduce this on iOS, (Android is working). Thanks for the reproduction case, I'll try to get to the bottom of it.

**Comment by terry1213** [comment]
Thank you. I'll be waiting.

**Comment by ryanheise** [comment]
I have a fix, will push shortly for testing.

**Comment by ryanheise** [comment]
I have just pushed a fix to the branch `fix/bg_unresponsive_stop`. Let me know how it goes for you.

**Comment by terry1213** [comment]
I tested with the branch `fix/bg_unresponsive_stop`. The **stop()** method works well. Thank you!

But there seems to be another problem. The player is not disposed when the app hot restarts.(Features that added from 0.0.1-beta.4 version of just_audio_background package.)

**Comment by ryanheise** [comment]
Did this ever work for just_audio_background? I noticed it doesn't work, but to me that is a limitation of "dart" federated plugin implementations.

**Comment by ryanheise** [comment]
If you want that, you might want to instead use audio_service directly.

**Comment by terry1213** [comment]
Oh, I got mixed up.

**Comment by terry1213** [comment]
Then, there is no more problem. Thank you.

**Comment by ryanheise** [comment]
The fix is now published (beta 5), thanks again for reporting the bug.
