### ISSUE TITLE
Make an ABC audio file from an A file, B file, C file. I want to make an audio file from others audios files

### ISSUE THREAD

**Issue by EuHigorBarbosa** [ryanheise/just_audio#674]
**Is your feature request related to a problem? Please describe.**
I want to make an audio file from others audios files. Concatenating several audios in one audio.

**Describe the solution you'd like**
I would like to produce only one audio file after combining several audios one after other.

**Describe alternatives you've considered**
Take several audios files in local path and make an output file that have all other audios inside them. 

**Additional context**
Just this, make an ABC audio file from an A file, B file, C file.

**Comment by ryanheise** [comment]
just_audio is not intended as a general purpose studio for creating audio files, it is only for playing audio files. I can't say whether this goal will change in the future, but for now this feature request is outside the scope of this plugin, so I'll close.
