### ISSUE TITLE
Preload/Buffer Entire AudioFile

### ISSUE THREAD

**Issue by Colton127** [ryanheise/just_audio#675]
**Is your feature request related to a problem? Please describe.**
My app downloads multiple audio files and a video simultaneously. I use LockCachingAudioSource to cache while streaming. Using await player.setUrl(preload: true) appears to buffer the file only about 10% in, or in a ten-minute audio file, about 1:30. I got this value by listening to the bufferposition stream. I want the audio file to continue preloading even if it is paused. I will then use a listener to wait until ~5 minutes of the audio file is loaded before playing the audio and video. By doing this, I ensure that my main audio file is always available.

**Describe the solution you'd like**
A simple parameter to make it so having preload enabled will buffer the audio file entirely, even if the audio file is paused. 

```
        await newPlayer.setAudioSource(
          LockCachingAudioSource(Uri.parse(url)), preload: true, fullPreload: true,
        );
```

**Describe alternatives you've considered**
Using player.play() does not continue buffering the position until it is needed to do so. I've thought of setting volume to 0, speed to something insane (like 50x), and then using .play().

**Additional context**
No, but thanks so much for a wonderful plugin. Performance of Just_Audio is stellar -- I've had up to 40 AudioPlayer instances running simultaneously on Android, and have even changed the volume of a player over 120 times a second with virtually zero impact on performance.

**Comment by ryanheise** [comment]
That sounds like a good idea, although I'm surprised this isn't already working. Do you have a way I can reproduce this, such as an audio URL?

**Comment by Colton127** [comment]
> That sounds like a good idea, although I'm surprised this isn't already working. Do you have a way I can reproduce this, such as an audio URL?

Sure!
` var a = AudioPlayer();
                      const String url = 'https://experience.b-cdn.net/audio/music/mountainmist.mp3';
                      await a.setUrl(url, preload: true);
                      a.bufferedPositionStream.listen((event) {
                        print('AudioPlayer Buffer Position Stream Listener: $event');
                      });`
Output:
`AudioPlayer Buffer Position Stream Listener: 0:01:09.276000
`

It never goes beyond 1:09.

**Comment by ryanheise** [comment]
Have you tried plugging that same URL into the caching example in the repo?

**Comment by Colton127** [comment]
> Have you tried plugging that same URL into the caching example in the repo?

Just tried it.

```
class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  final _player = AudioPlayer();
  final _audioSource = LockCachingAudioSource(Uri.parse(
    // Supports range requests:
    "https://experience.b-cdn.net/audio/music/mountainmist.mp3",
    // Doesn't support range requests:
    //"https://filesamples.com/samples/audio/mp3/sample4.mp3",
  ));
```
 ```
 Future<void> _init() async {
    final session = await AudioSession.instance;
    await session.configure(AudioSessionConfiguration.speech());
    _player.playbackEventStream.listen((event) {}, onError: (Object e, StackTrace stackTrace) {
      print('A stream error occurred: $e');
    });
    _player.bufferedPositionStream.listen((event) {
      print('Buffered Position Event: $event');
    });
    try {
      //await _audioSource.clearCache();
      await _player.setAudioSource(_audioSource);
    } catch (e) {
      print("Error loading audio source: $e");
    }
  }

```

Output: 
`Buffered Position Event: 0:01:09.276000
`

I think the way it is right now is fine for most use cases. Preload buffers enough to where the player is ready to be played at any time. Some people have very long audio files, so buffering only when necessary helps conserve bandwidth.

 My case is a bit special, and I appreciate your help.

**Comment by ryanheise** [comment]
I may have misunderstood your feature request. `LockCachingAudioSource` does trigger the whole file to download all at once, but you're not talking about that. You want it additionally to actually load the entire audio into RAM all at once? Why is that?

**Comment by Colton127** [comment]
In that instance, I may have misunderstood bufferedPosition. It was my thinking that bufferedPosition would reflect the total duration downloaded, not just what's in RAM.

The idea is that, say you have a 30-minute audio file. You want to ensure continuous playback for your users. Thus, you may want a certain amount of said audio file to buffer before playback begins, like ten minutes.

**Comment by ryanheise** [comment]
First of all, bufferedPosition has nothing to do with caching, it is an API that is present on all audio sources and is to do with the way that the playing process works. In order to play audio, there is an intensive processing pipeline that involves decoding the audio data (e.g. from MP3 into PCM) and the player should try to prepare just enough ahead of time so that the player can continue playing continuously, without necessarily wasting all of your RAM.

The download process is a different thing for caching and that is what the caching example shows how to use.

When you ran the caching example, you will hopefully have seen the download progress indicator which runs all the way to the end, not stopping at 1 minute. I confirmed this after plugging in your URL.

You don't need to hold the entire file in RAM to get continuous playback, you only need to hold a small lookahead buffer, and you need a reliable storage media that won't cut off midway through. The cache file gives you the second requirement since unlike a network connection, a file read won't get cut off midway through.

**Comment by Colton127** [comment]
> First of all, bufferedPosition has nothing to do with caching, it is an API that is present on all audio sources and is to do with the way that the playing process works. In order to play audio, there is an intensive processing pipeline that involves decoding the audio data (e.g. from MP3 into PCM) and the player should try to prepare just enough ahead of time so that the player can continue playing continuously, without necessarily wasting all of your RAM.
> 
> The download process is a different thing for caching and that is what the caching example shows how to use.
> 
> When you ran the caching example, you will hopefully have seen the download progress indicator which runs all the way to the end, not stopping at 1 minute. I confirmed this after plugging in your URL.
> 
> You don't need to hold the entire file in RAM to get continuous playback, you only need to hold a small lookahead buffer, and you need a reliable storage media that won't cut off midway through. The cache file gives you the second requirement since unlike a network connection, a file read won't get cut off midway through.

Ryan,

I have no idea how I missed the download progressBar within the example. To tell the truth, I haven't been in an ideal headspace all day. My apologies for the inconvenience. 

Thanks a lot for the clarification, and for the excellent plugin.
