### ISSUE TITLE
The plugin audio_session requires your app to be migrated to the Android embedding v2.

### ISSUE THREAD

**Issue by sgehrman** [ryanheise/just_audio#677]
The plugin audio_session requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

not sure why this started. I'm building for macOS. my project is set for Android embedding properly, but I'm not even building for android.

**Minimal reproduction project**
https://fuck.this/duh

**To Reproduce (i.e. user steps, not code)**
1. waste of time
3. stupid
5. annoyin

**Error messages**

```
wat?
 ```

**Expected behavior**
duh

**Screenshots**
 
**Desktop (please complete the following information):**
 macos

**Smartphone (please complete the following information):**
 - what?
 - 
**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability```

**Additional context**
Add any other context about the problem here.

**Comment by sgehrman** [comment]
fuck this.  so annoying.

I figured it out.  

android:name="${applicationName}"

I didn't change that.  I don't even build for Android.  not sure why this started happening.

**Comment by ryanheise** [comment]
@sgehrman Ironically (since you thought I was wasting your time), what you are doing with that type of abusive language and ignoring the bug submission instructions -- is wasting my time. I don't know if wasting time as a general concept matters to you at all, or whether you only care about your own time and not the other people's time who have devoted much of their time freely providing you open source software that you now use.

That said, congratulations on now becoming only the second person to ever be blocked here. The first person was similarly angry, but also created sock puppet accounts to give the illusion of more users demanding that I fix the same bug.

Good luck with your project, but also goodbye and please don't come back. 👋 

> The plugin audio_session requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
> 
> not sure why this started. I'm building for macOS. my project is set for Android embedding properly, but I'm not even building for android.
> 
> **Minimal reproduction project** https://fuck.this/duh
> 
> **To Reproduce (i.e. user steps, not code)** Steps to reproduce the behavior:
> 
>     1. waste of time
> 
>     2. stupid
> 
>     3. annoyin
> 
> 
> **Error messages**
> 
> ```
> wat?
> ```
> 
> **Expected behavior** duh
> 
> **Screenshots**
> 
> **Desktop (please complete the following information):** macos
> 
> **Smartphone (please complete the following information):**
> 
>     * what?
> 
> 
> **Flutter SDK version**
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, 2.11.0-0.1.pre, on macOS 12.2.1 21D62 darwin-x64, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.65.2)
> [✓] Connected device (2 available)
> [✓] HTTP Host Availability```
> 
> **Additional context**
> Add any other context about the problem here.
> ```
