### ISSUE TITLE
Playback breaking in filenames containing Unicode

### ISSUE THREAD

**Issue by LQR471814** [ryanheise/just_audio#686]
**Which API doesn't behave as documented, and how does it misbehave?**
The `ProgressiveAudioSource` object is unable to play `file://` URIs containing unicode characters.

**Minimal reproduction project**
[example repository](https://github.com/LQR471814/just_audio.git)

**To Reproduce**
1. Navigate to `just-audio/example`
2. Modify the `directory` variable with the absolute path of the example folder
3. Run the application
4. The "loading" ring should never stop spinning

**Error messages**
None

**Expected behavior**
Playback should occur almost immediately as is with the commented code below.

**Desktop (please complete the following information):**
 - Windows 10 Version 10.0.19044 Build 19044

**Flutter SDK version**
- channel `stable`
- version `2.10.3`
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
    ! Device emulator-5562 is offline.
[√] HTTP Host Availability

• No issues found!
```

**Comment by ryanheise** [comment]
You might want to report directly to the just_audio_libwinmedia project, although note that the developer is also working on an new windows implementation from scratch which you also might like to try and give early feedback on:

https://github.com/bdlukaa/just_audio/tree/master/just_audio_windows

**Comment by LQR471814** [comment]
got it. thanks!
