### ISSUE TITLE
just_audio_background can't start with empty playlist

### ISSUE THREAD

**Issue by yhcharles** [ryanheise/just_audio#692]
**Which API doesn't behave as documented, and how does it misbehave?**
In `just_audio_background/example`, if we [assign `_playlist` to an empty list](https://github.com/ryanheise/just_audio/blob/29f201dff0a24e62acf07277f3226a504bb9e9d3/just_audio_background/example/lib/main.dart#L26). Then the `processingState` will be `loading` forever. Even if we add new items to the list later, by clicking on the ["add button"](https://github.com/ryanheise/just_audio/blob/29f201dff0a24e62acf07277f3226a504bb9e9d3/just_audio_background/example/lib/main.dart#L269).

**Minimal reproduction project**
A fork of just_audio repo, only `just_audio_background/example/lib/main.dart` is changed
[The example in just_audio_background](https://github.com/yhcharles/just_audio/blob/master/just_audio_background/example/lib/main.dart)

**To Reproduce (i.e. user steps, not code)**
1. Download https://github.com/yhcharles/just_audio/blob/master/just_audio_background/example/lib/main.dart
2. Run this example in iOS simulator
3. Since the initial playlist is empty, we can see the player status is "loading"
4. Click the "+" button, add new items to playlist, but the status is still loading

**Error messages**
See the attached gif

**Expected behavior**
Expect after new items added to playlist, the player can start to play.

**Screenshots**
![1](https://user-images.githubusercontent.com/2959773/160064224-898f5969-0fe5-420d-aa52-fba8c3c1d3d9.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: iPhone13 simulator
 - OS: iOS 15.4

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.3-0.0.pre.1, on macOS 12.3 21E230 darwin-arm, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Additional context**

**Comment by ryanheise** [comment]
Can you please provide a valid reproduction project and reproduction steps that follow the instructions faithfully? That is, the problem with your bug report is that you selected the option to indicate that the unmodified example exhibits the bug, and then under "User Steps NOT Code" you gave me instructions on how to modify the code of the example. User Steps should never contain coding steps. Does it make sense? I accept there may be a legitimate bug which I want to investigate, but I need the above first.

**Comment by yhcharles** [comment]
@ryanheise Sure, updated in the issue description. Thanks for looking into this!

**Comment by pasrot943** [comment]
I had the same problem, I gave it a "fake" playlist from the start and a Boolean that changes from false too true the first time the AudioPlayer starts. Next time the boolean is true and the real playlist starts.

**Comment by ryanheise** [comment]
I have just pushed a fix to the `fix/caching` branch. Please let me know how it goes in your own app.

**Comment by yhcharles** [comment]
Thanks! It's working now.

**Comment by ryanheise** [comment]
This fix is now published.
