### ISSUE TITLE
Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3) (Android)

### ISSUE THREAD

**Issue by Abdullatif-Eida** [ryanheise/just_audio#693]
**Which API doesn't behave as documented, and how does it misbehave?**
Just audio package does not lunch because of flutter_zoom_sdk: ^1.1.0+3 

**Minimal reproduction project**
Provide a link here using one of two options:
1. there are no error in the just audio as a code the error happen because of other package called   flutter_zoom_sdk: ^1.1.0+3 

**To Reproduce (i.e. user steps, not code)**
1. Go to ' you android phone open pubspec.yaml and add  flutter_zoom_sdk (https://pub.dev/packages/flutter_zoom_sdk)'
2. Click on 'run flutter pub get then run your app'
3. See error

**Error messages**

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)

     Go to the documentation to learn how to <a href="d.android.com[/r/tools/classpath-sync-errors]()">Fix dependency resolution errors<[/a]()>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
no opy & paste error message

**Expected behavior**
i am Expecting my app to run without any problem 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Big Sur + 11.6.2]
 - Browser [e.g. chrome + 99.0.4844.82]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3 a]
 - OS: [e.g. Android Tiramisu]

**Flutter SDK version**
environment:
  sdk: ">=2.16.1 <3.0.0"

Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

insert output of "flutter doctor" here
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.2 20G314 darwin-x64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Additional context**
I am trying to use https://pub.dev/packages/just_audio package and the flutter_zoom_sdk and I am facing this error 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.15.0-runtime (com.google.android.exoplayer:exoplayer-common:2.15.0) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)
   
Go to the documentation to learn how to <a href="d.android.com[/r/tools/classpath-sync-errors]()">Fix dependency resolution errors<[/a]()>.

is there any solution 

Note: when deleting one of mentioned packages from pubspec.yaml the app run without any problem

**Comment by Abdullatif-Eida** [comment]
I solved the problem 
to solve it fo to android > app > build.gradle > dependencies and add this line
implementation ('com.google.android.exoplayer:exoplayer-ui:2.14.1')

**Comment by Abdullatif-Eida** [comment]
If you can modify the package that will be better

**Comment by ryanheise** [comment]
I'm not really sure what can be done inside this plugin to solve this problem. Did you have anything in mind specifically?

I think the issue is that both plugins have pulled in the exoplayer library but incompatible versions of it which are conflicting. just_audio is pulling in a more up to date version, but checking the release notes there is now an even newer version of exoplayer so this problem may reoccur.

**Comment by Abdullatif-Eida** [comment]
i made the same issue with flutter_zoom_sdk may he can update exoplayer version

**Comment by ryanheise** [comment]
And then I'll update just_audio's version again in the future, and the issue will return.

Maybe the only solution is the one that you've come up with, in which case one thing I can do is update the README with information on how to deal with conflicting plugins.

**Comment by Abdullatif-Eida** [comment]
I think that's the best solution to add 
this issue to README with information on how to deal with conflicting plugins and how to solve this problem.

**Comment by ryanheise** [comment]
I've upgraded ExoPlayer to 2.17.1 on the `fix/flutter3` branch, which is going to temporarily resolve this error (until the next time it happens).

**Comment by ryanheise** [comment]
The ExoPlayer changes have now been published in release 0.9.22.

**Comment by Abdullatif-Eida** [comment]
thanks

**Comment by ryanheise** [comment]
Reopening since the readme hasn't been updated.

**Comment by ryanheise** [comment]
I have drafted a new section in the README in the `fix/insert_skip` branch.

**Comment by ryanheise** [comment]
The release has now been published, closing.
