### ISSUE TITLE
Tried stream hls audio from this link https://streaming.fabrik.fm/yfm/echocast/audio/low/index.m3u8 and it doesn't work, getting error 

### ISSUE THREAD

**Issue by bombo774** [ryanheise/just_audio#695]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
insert output of "flutter doctor" here
```

**Additional context**

**Comment by ryanheise** [comment]
You didn't bother to fill in any of the sections. Closing.
