### ISSUE TITLE
Duration is WRONG

### ISSUE THREAD

**Issue by Nedimko123** [ryanheise/just_audio#698]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
insert output of "flutter doctor" here
```

**Additional context**

**Comment by ryanheise** [comment]
You ignored all of the instructions so unfortunately I'll have to close this. I can't act on a bug report that doesn't provide any of the information needed to reproduce and investigate it.

**Comment by Nedimko123** [comment]
I fixed it, I had to remove the unnecessary stuff from the mp3 files, since I recorded them from microphone and now it shows the correct duration. Linux command in terminal: yes | for f in *.mp3 ; do ffmpeg -i "new$f" -b:a 96k -map a "$f"; done

If anyone was wondering what my flutter command was:  
var duration = await player.setAsset(
                                          'assets/' +
                                              searchList[index]['link']
                                                  .toString());

And it without removing unnecessary stuff from the mp3 file it showed the wrong duration ;)
