### ISSUE TITLE
Because just_audio requires the Flutter SDK, version solving failed.

### ISSUE THREAD

**Issue by ifehrim** [ryanheise/just_audio#70]
Resolving dependencies...
Because just_audio requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
Process finished with exit code 1

**Comment by ryanheise** [comment]
I assume you ran `flutter pub get`? If that didn't work, can you also try `flutter packages upgrade`?

**Comment by ifehrim** [comment]
i don't know , now is ok , thank you, i thing it's my local environment  issue
