### ISSUE TITLE
Just Audio background Player not cleared of IOS Control center after disposed 

### ISSUE THREAD

**Issue by pasrot943** [ryanheise/just_audio#702]
**Which API doesn't behave as documented, and how does it misbehave?**
The player is not cleared of IOS Control Center after it is  disposed which leads to the creation of another instance the next time I'm using the player and hence an error is throwed since it's only allowed to have 1 instance in Just Audio Background. The background audio stops and it seems to work.
If I'm tapping the Play button in the IOS Control Center at this moment then the player clears immediately and the instance gets disposed, and it's working like nothing happened. 

It is working perfectly on Android devices.

**Minimal reproduction project**
Provide a link here using one of two options:
https://github.com/pasrot943/just_audio/tree/master/just_audio_background/example/lib

**To Reproduce (i.e. user steps, not code)**
1. Choose a playlist
2. tap any of the songs
3. go back to playlist page to get the player disposed
4. the error should now be present

**Error messages**

```
Since I got this in a real device I don't see the real error message. But I got it earlier and it is the "More than 1 instance is not allowed" message
```

**Expected behavior**
Expect it to get cleared like it does on android

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: Iphone 12 mini
 - OS: [IOS 15.3.1]

**Flutter SDK version**
```
insert output of "flutter doctor" here
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale
    en-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

**Additional context**
Add any other context about the problem here.

**Comment by ryanheise** [comment]
Can you clarify how you can reproduce it by getting the real error message?

**Comment by pasrot943** [comment]
I noticed that the error doesn't come from the Player itself but the
subscription I'm using(RevenueCat) it had a null check operator error.

> Message ID: ***@***.***>
>
Sorry for wasting your time. It really seemed that the error came from the
player, because of the player not working after logout.

Thanks for the great job you are doing.

**Comment by ryanheise** [comment]
Is there still an issue for the plugin or will you close it? If there is still an issue, please edit your issue to reflect the expected and actual behaviour, and the bits about the error.
