### ISSUE TITLE
[just_audio_background] Add headers to the `MediaItem` for `artUri`

### ISSUE THREAD

**Issue by pro100svitlo** [ryanheise/just_audio#704]
**Is your feature request related to a problem? Please describe.**
Right now there is no possibility to show image in `MediaItem` with headers (auth headers)

**Describe the solution you'd like**
Add exatra param like `headers`, `Map<String, String>`, and use those to load the image.

**Describe alternatives you've considered**
For now, I disabled images, cos they can not be shown in the notification.

**Comment by ryanheise** [comment]
I assume you're referring to just_audio_background?

There is another alternative to consider besides disabling images, you can separately write some code to download the images with headers to your app's cache, and then pass in the `file://` URI into `MediaItem`.

**Comment by pro100svitlo** [comment]
>I assume you're referring to just_audio_background?

yes, I am.

>you can separately write some code to download the images

also yes, it can be a workaround. but i guess it still would be nice to add `headers`, the same way it is added to the `audio straming`.

**Comment by ryanheise** [comment]
This will depend on the feature first being added to audio_service. This is being tracked in https://github.com/ryanheise/audio_service/issues/583 .

**Comment by ryanheise** [comment]
This has now been implemented and released with just_audio_background 0.0.1-beta.7.

To use, provide a value for `artHeaders` in each media item alongside your `artUri`.
