### ISSUE TITLE
acc audio file does not work with on seek method 

### ISSUE THREAD

**Issue by jack84156** [ryanheise/just_audio#709]
**Which API doesn't behave as documented, and how does it misbehave?**
onSeek(url.acc) Acc format always return duration audio to zero  

**Minimal reproduction project**
Provide a link here using one of two options:

AudioPlayer MyPlayer );

initState{
MyPlayer = AudioPlayer ();
MyPlayer.setUrl(url with acc format or local file with acc format )
}

myCustumSlider(
onSeek; (duration){
MyPlayer.seek(duration) // i tested too many none acc audio urls and it seek correctly but not with the acc file or urls 
}
)
.....
onPressed(){
MyPlayer.play();
}

**Expected behavior**

Expected behavior to seek normally like any audio file format but with acc format it is always seek to zero

**Flutter SDK version**
2.10.5 stable

insert output of "flutter doctor" here
```

[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
[√] Android Studio (version 2021.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

**Comment by ryanheise** [comment]
Hi @jack84156 before you make attempt number 3 at submitting an issue, please check the instructions carefully.

It seems you ignored these instructions:

> Provide a link here using one of two options:
> 1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
> 2. If the unmodified official example already reproduces the bug, just write "The example".

What you did was copy and paste code directly into the issue. That is not what the instructions asked you to do.
