### ISSUE TITLE
seek method always seek to zero with acc audio format

### ISSUE THREAD

**Issue by jack84156** [ryanheise/just_audio#710]
**Which API doesn't behave as documented, and how does it misbehave?**

.seek(); : it is always seek to zero (only with `acc `audio format )

my repo 
https://github.com/jack84156/myFirstIssue

**To Reproduce (i.e. user steps, not code)**
1. swipe the slider to specify point 
2. Click on the seek method
3. return value to zero

**Error messages**
no error message 
```
```

**Expected behavior**
seek value to normal duration where the finger point on slider .

**Screenshots**
![d](https://user-images.githubusercontent.com/98435195/164381557-5ec6127f-9e90-4a38-8c21-e71441834f0b.png)

**Desktop (please complete the following information):**
 - OS: [windows 11 + 21H2]
 - Browser [chrome+  [100.0.4896.127])

**Smartphone (please complete the following information):**
 - Device: [redmi note 9]
 - OS: [android]

**Flutter SDK version**
2.10.5
```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
[√] Android Studio (version 2021.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!



**Additional context**
seek to zero always in case i use audio file with acc format , urls too.

**Comment by ryanheise** [comment]
Why did you ignore my previous comment to you on your previous issue?

**Comment by jack84156** [comment]
i am really sorry 
i am new in GitHub , beside i did not understand  what does mean the following
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

i an not English speaker . i still 13 years old and still learn English and programming .. i noticed that bug and i loved to feedback 
sorry :(

**Comment by ryanheise** [comment]
What language do you speak?

**Comment by jack84156** [comment]
Arabic

**Comment by ryanheise** [comment]
I have copied the text into [Google Translate](https://translate.google.com/) and got this:

قدم ارتباطًا هنا باستخدام أحد الخيارين:
1. قم بتشكيل هذا المستودع وتعديل المثال لإعادة إنتاج الخطأ ، ثم قم بتوفير ارتباط هنا.
2. إذا كان المثال الرسمي غير المعدل ينتج الخطأ بالفعل ، فقط اكتب "المثال".

Is it clearer?

**Comment by jack84156** [comment]
that was the problem , i already used google translate to see what does it mean but the translation was horrible , but anyway i will do my best to understand it and try open new issue . thank you ryanheise for trying to translate it to me , you made me happy

**Comment by ryanheise** [comment]
I will leave this issue open, and you can click the edit menu to fix it.

**Comment by jack84156** [comment]
thank you

**Comment by ryanheise** [comment]
Here is another online translator: https://www.systransoft.com/lp/arabic-translation/

**Comment by jack84156** [comment]
yes now it make sense .. i edited my issue

**Comment by sam4523** [comment]
i have the same issue , i am recording voice using flutter_sound plugin with acc format , then use jsut_audio to play it but on seek does not work as expected .. any updates @jack84156 ?

**Comment by ryanheise** [comment]
On Android, ExoPlayer is used to play audio, and it has this FAQ:

https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable

AAC itself is fine, but that should be wrapped in a container format that stores a seek table. E.g. m4a should work which wraps AAC.

**Comment by ryanheise** [comment]
@sam4523 if you are using flutter_sound, I believe that project may come with some transcoders that you could use to convert it to a more appropriate format for seeking. Otherwise you may need to try an alternative recorder plugin (which I can't recommend).

**Comment by sam4523** [comment]
@ryanheise so any recourse or link or tutorial how to fix it ?

**Comment by ryanheise** [comment]
I can't recommend anything, which means you would need to research recorder plugins yourself, or research transcoder plugins yourself.

**Comment by sam4523** [comment]
@ryanheise you said :  if you are using flutter_sound, I believe that project may come with some transcoders that you could use to convert it to a more appropriate format for seeking.

do you mean flutter_sound it's self come with some transcoders?  so i should to search on it more to fix my issue ? thanks

**Comment by ryanheise** [comment]
I said "maybe" it comes with transcoders, but those transcoders are from memory inherited from ffmpeg which has its own plugin, from memory. The licence might also be not to your liking. There might also be other approaches, like server-side transcoding, but you might want to ask on StackOverflow if you are generally asking for ways to solve a problem, and reserve this issues page for problems that need to be fixed within this plugin itself.

**Comment by sam4523** [comment]
@ryanheise thank you

**Comment by ryanheise** [comment]
Based on https://github.com/ryanheise/just_audio/issues/333#issuecomment-1140288765 I have implemented constant bitrate seeking as a fallback option for AAC and also certain MP3 files that don't otherwise support seeking. Note that this is an approximate form of seeking, so not as good as if you encoded the file with a seek table.

The fix is implemented on the `minor` branch. Let me know if it solves your issue and I'll push out a release.

**Comment by jack84156** [comment]
@ryanheise WOW , yes now it seek as expected .. thanks a lot for this awesome fix .. all my aac files seeking correctly .. please push out a release.

**Comment by ryanheise** [comment]
I believe this update has now been released.

**Comment by jack84156** [comment]
yes thanks my bad ,,
