### ISSUE TITLE
Saving the current progress of audio player

### ISSUE THREAD

**Issue by vlashada** [ryanheise/just_audio#716]
**Is your feature request related to a problem? Please describe.**
I want to resume from the current track and current position in a playlist when the user restarts the app.

**Describe the solution you'd like**
An api, or another way to easily save the progress for next time.

**Describe alternatives you've considered**
I just got into coding, so I really am not sure.

**Additional context**

**Comment by ryanheise** [comment]
It should be the app's responsibility to manage persistence and restore state if desired. just_audio already provides tn API to start at any given position so if your app wants to persist and restore the state, just_audio can be called with the appropriate parameter.

I'll close this feature request, but you can ask someone for help on StackOverflow regarding how to accomplish your goal.
