### ISSUE TITLE
audio streaming become off after 10 minute of screeon lock

### ISSUE THREAD

**Issue by akhilprogrammer** [ryanheise/just_audio#72]

**Comment by akhilprogrammer** [comment]
on new android devices audio streaming off after 10 minute of screen lock.in lollipop or marshmallow no problem

**Comment by ryanheise** [comment]
You can wrap your code in `audio_service` to achieve this (the link is at the top of the `just_audio` README).

**Comment by akhilprogrammer** [comment]
can you give a simple example. example of audio_service is diificult to understand. if you like send a example to akhilprogrammer@gmail.com

**Comment by akhilprogrammer** [comment]
with minimal code not using

**Comment by ryanheise** [comment]
At least please read the README file of that project before asking for an example. That README references both an example and a tutorial.
