### ISSUE TITLE
Customly Sort the Current Playing Playlist

### ISSUE THREAD

**Issue by hbtalha** [ryanheise/just_audio#722]
**Is your feature request related to a problem? Please describe.**
I don't think it is related to a problem afa I know.

**Describe the solution you'd like**
I have been trying to find a way to sort the current playing playlist by every metadata extracted with [flutter_media_metadata](https://pub.dev/packages/flutter_media_metadata).

**Describe alternatives you've considered**
I went into the just_audio.dart file to see if I could understand the code and see how I could alter the order of songs in the current playlist while a song is playing but I couldn't find where as a beginner to Flutter.
I was able, however, to modify the code [in this function](https://github.com/ryanheise/just_audio/blob/f234a9a7681ea712a6a9d64590a601af0a6b2a38/just_audio/lib/just_audio.dart#L461) and I was able to sort the playlist as I wished but it only works when I seek to next or previous, so if I let a song finish the next song will be according to the original sequence set.

**Additional context**
...

**Comment by ryanheise** [comment]
Closing as it's not a feature request. You should click the "Ask a question" link instead of the "Feature request" link.

**Comment by ryanheise** [comment]
I'm sorry but I am busy developing the plugin and can't offer you tips on how to write your program. But if you ask on StackOverflow and ask a good question, hopefully someone in the wider community can help you.

**Comment by hbtalha** [comment]
OK, from what I am seeing then I will have to implement a way to sort the playlist myself, right?

**Comment by hbtalha** [comment]
Ok

**Comment by hbtalha** [comment]
@ryanheise If I may ask: how the player get the next song to play after a song ends, where exactly in the code does that happen? That's where I am having problems (as a Flutter beginner) .
