### ISSUE TITLE
Alternate platforms not loading correctly

### ISSUE THREAD

**Issue by bleonard252** [ryanheise/just_audio#725]
**Which API doesn't behave as documented, and how does it misbehave?**
The platform interface API, particularly load() and the other implemented functions 

**Minimal reproduction project**
The example, optionally with `just_audio_mpv: ^0.0.1-pre.1` in place of the libwinmedia line in `pubspec.yaml`.

**To Reproduce (i.e. user steps, not code)**
1. Open the example app.

**Error messages**

```
No error messages
```

**Expected behavior**
The audio that is attempting to load/play in the example loads or plays.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Debian Unstable)
 - Browser: n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a

**Flutter SDK version**
```
✓] Flutter (Channel master, 3.1.0-0.0.pre.703, on Debian GNU/Linux bookworm/sid 5.16.0-4-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.67.0-insider)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

**Additional context**
I have a `print` in [`just_audio_mpv`](https://github.com/bleonard252/just_audio_mpv) that should run in debug mode (like the `MPV started` that does log now) at the top of the load() function, so I have deduced that it isn't being called by `just_audio` at all. I've looked at `just_audio_web` and `just_audio_libwinmedia` to see if I had forgotten to call something but it looks like that isn't the case.

**Comment by ryanheise** [comment]
This looks interesting!

It is getting late here, but I will certainly be trying this out tomorrow.

**Comment by ryanheise** [comment]
I've finally got my Linux system upgraded, and have reproduced the issue. I'll take a look to see what's going on. I can see that JustAudioMpv is being installed at least.

**Comment by ryanheise** [comment]
It looks like just_audio_mpv is hanging on `setVolume` during initialisation.

**Comment by bleonard252** [comment]
Interesting. Upon further investigation on my end I believe I forgot to 1. start MPV and 2. make sure MPV was started before letting just_audio do stuff with it. Now I'm getting mpv(_dart) related errors like "property unavailable". Thanks for the help. Maybe making sure it's ready before returning would make a helpful addition to the init() function docs ;)

**Comment by bleonard252** [comment]
now just_audio calls disposePlayer() after every track? is it supposed to do that

**Comment by bleonard252** [comment]
The last non-SDK thing in the stack trace is 
```
_setPlatformActive.subscribeToEvents.<anonymous closure> (.../just_audio-0.9.21/lib/just_audio.dart:1262)
```
I can't tell what's calling that. The events *should* already be being listened to, so I don't understand...

**Comment by ryanheise** [comment]
That seems to mean that your code is broadcasting a player state of `idle`. If you do that, it's a signal to stop/destroy the player instance.

**Comment by ryanheise** [comment]
This section in the README may help regarding the states:

https://github.com/ryanheise/just_audio/tree/master/just_audio#the-state-model

In the past, the plugin would only enter the `idle` state in response to a user-triggered action, such as `stop` or `dispose`, although since the creation of just_audio_background, I made that bidirectional so that a transition to the `idle` state will also trigger a `dispose`.
