### ISSUE TITLE
Upgrade Android to ExoPlayer 2.17.1

### ISSUE THREAD

**Issue by sharyer-Ilyas-Khan** [ryanheise/just_audio#731]
**Is your feature request related to a problem? Please describe.**
Producing a duplication error with other plugins, which are using Exo player 2.17.1

**Describe the solution you'd like**
Please update the Android to Exoplayer 2.17.1

**Describe alternatives you've considered**

**Additional context**

![t](https://user-images.githubusercontent.com/70968849/169530342-ce53ebb2-98bf-44ff-8953-12f603f4a81b.PNG)

**Comment by ryanheise** [comment]
Please see #693 .

**Comment by ryanheise** [comment]
FYI, I have migrated to ExoPlayer 2.17.1 in the latest commit on the `fix/flutter3` branch.

**Comment by sharyer-Ilyas-Khan** [comment]
okay, Thank you so much 👍

**Comment by ryanheise** [comment]
Now published in just_audio 0.9.22.
