### ISSUE TITLE
.setVolume and listener on iOS doesn't work

### ISSUE THREAD

**Issue by amedeopro** [ryanheise/just_audio#733]
Listener on iOS doesn't work, it works only on Android

**Minimal reproduction project**
I have two playlists and at a certain time one of the two must lower the volume of the one that is playing the song and raise it only at the end of the second playlist, this works only on Android

**To Reproduce (i.e. user steps, not code)**
there are no steps to follow

**Error messages**

```
i not have an error
```

**Expected behavior**
I expect that as soon as playlist B is played, the volume of playlist A will be lowered but then it will be raised when the song of playlist B ends

**Screenshots**
i can get a screenshoots of my code now, i paste my code here

```dart
    if(canPlayMessaggi){
      _braniPlayer.setVolume(0.2);
      _messaggiPlayer.setAudioSource(_playlist);
      _messaggiPlayer.play();
      _messaggiPlayer.playerStateStream.listen((state) async {
        if(!state.playing){
          await _braniPlayer.setVolume(1);
        }
      });
    }
```

**Desktop (please complete the following information):**
 - OS: iOS (all version)

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS15.4

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale
    it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**
i think the listener not works in iOS, can you help me?

**Comment by amedeopro** [comment]
I also tried this way but nothing to do:

```dart
_messaggiPlayer.playerStateStream.listen((state)  {
        if(state.processingState == ProcessingState.completed){
           _braniPlayer.setVolume(1);
        }
      });
```

**Comment by ryanheise** [comment]
Why are you ignoring the instructions for submitting a valid issue, twice? Your issue didn't fill in the sections correctly, and after the bot pointed that out to you, you continued ignoring the instructions.

**Comment by amedeopro** [comment]
I'm sorry I will immediately create a new issue as suggested by the bot
