### ISSUE TITLE
First instance of AudioPlayer doesn't play any sound on Android's Firefox

### ISSUE THREAD

**Issue by jcblancomartinez** [ryanheise/just_audio#737]
**Which API doesn't behave as documented, and how does it misbehave?**
play method doesn't play any sound the first time it is invoked on an AudioPlayer instance. If you click play on other AudioPlayer instance it works as expected. After that, if you play the first instance, it also plays the sound.

The behavour is as expected on the same device with Chrome and also on iOS and desktop browsers.

**Minimal reproduction project**
The example".

**To Reproduce (i.e. user steps, not code)**
1. Go to [this link](https://www.soloninterests.com/showcase/resource__5541a59b-0dad-41ca-a27b-d08946762031).
2. Click on play
3. The sound doesn't play.
4. See error: "Uncaught Error: NotAllowedError: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

**Error messages**

```
Uncaught Error: NotAllowedError: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

**Expected behavior**
Audio should play as expected.

**Desktop (please complete the following information):**
 - OS: NA
 - Browser: NA

**Smartphone (please complete the following information):**
 - Device: Xiaomi Poco M3 Pro 5G
 - OS: Android 11
 - Browser: Firefox 100.3.0

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on Ubuntu 20.04.4 LTS 5.13.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by ryanheise** [comment]
The error message you see is from the web browser, not the plugin. It means you are trying to play audio in a way that browsers do not allow. You can learn more about this behaviour by performing a Google search for that error message.

Although it's not a just_audio bug, so I'll close this issue.
