### ISSUE TITLE
Player state is not preserved while opening page again.

### ISSUE THREAD

**Issue by nicks258** [ryanheise/just_audio#739]
**Which API doesn't behave as documented, and how does it misbehave?**
Thank you for wonderful plugin. I am developing as application which play audio playlist in an app. But I found as issue whenever i open the playlist page again and again new audio is playing but expected behavior is that it should return the older state of the player is playing. I can't dispose the player on pop of the page because I want to play the audio until or unless user stops it.
Can you please help. @ryanheise

**Minimal reproduction project**
Provide a link here using one of two options:
1. Create a page with initializing player and play audio file and pop back to last page and come again and play another audio or same audio file two audio will play. **Do not dispose the player while pop back** 

**To Reproduce (i.e. user steps, not code)**
Kindly refer to attached screen recording.

**Error messages**

```
No Error messages
```

**Expected behavior**
Player should return that audio is already playing. using  `playerState?.playing`

**Screenshots**

https://user-images.githubusercontent.com/11635407/170452976-fd90807d-8743-4e1e-8b29-e50e87d278da.mp4

**Smartphone (please complete the following information):**
 - Android 12

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 3.0.1 at C:\Users\Sumit\Documents\EGDownloads\flutter_windows_1.17.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
```

@ryanheise

**Comment by ryanheise** [comment]
You haven't identified the API where the supposed bug is, so it sounds like a bug in your app rather than the plugin. Why did you not answer the questions for the first two sections of the bug report? If there is a bug, I can't investigate it without those two sections properly supplied.

**Comment by ryanheise** [comment]
Hi @nicks258 I will close this since it is not a valid bug report. Since it appears you probably just need help understanding how to achieve the desired behaviour, I would suggest that you instead follow the "Ask a question" link which takes you to community support on StackOverflow. Best wishes.
