### ISSUE TITLE
Cannot build release for Android with 0.9.22

### ISSUE THREAD

**Issue by mark8044** [ryanheise/just_audio#741]
**Which API doesn't behave as documented, and how does it misbehave?**
Just audio package does not lunch with any of the `0.9.x` versions

**Minimal reproduction project**
My project is way to massive to share here, and I do not specifically use just audio in my project, however it is a dependency for https://pub.dev/packages/fwfh_just_audio which is a dependency for https://pub.dev/packages/flutter_widget_from_html, which I believe is how I'm using just_audio.

Of note, `flutter_widget_from_html` package has not changed in over 3 months, so I'm not exactly sure why just_audio moved up to the 0.9.x version on my system when a I did a `flutter pub outdated` and `upgrade` today

There is no such error when I manually put in the dependency for a lower version `just_audio: ^0.8.1`, but `just_audio: ^0.9.0` and above fails.

So because I directly place the just_audio dependency into my pubspec and the same error occurs, I don't think it has anything to do with flutter_widget_from_html, as well as that hasn't had any update recently.

There is no such error when building on iOS, only Android for Release

**Steps to reproduce the behavior:**
1. use `just_audio: ^0.9.22` as a dependency in pubspec.yaml
2. Run `flutter build apk`

**Error messages**
```
Execution failed for task ':just_audio:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users//.gradle/caches/transforms-3/0a679862f6c55d82fb9a949f1fd4603f/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
```

**Expected behavior**
Build should proceed successfully
Changing pubspec.yaml to `just_audio: ^0.8.1` is successful 

**Screenshots**
None relevant

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
Fails on Android, specific device is not relevant as this has to do with the APK build

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6.6 20G624 darwin-x64, locale en-US)
    • Flutter version 3.0.1 at /Users/ch/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (9 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/ch/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)


[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Additional context**
Although I mention the dependency issue above, it should be noted that placing `just_audio: ^0.9.22` (or any 0.9.x) fails with the same error message above and placing `just_audio: ^0.8.1` is successful.  So I don't believe this has any issue with the dependency per se.

I am more then happy to provide any more information on my app, dependencies or build, I just don't know what else is relevant to this error without guidance

**Comment by ryanheise** [comment]
Since we had a previous discussion where I basically asked you to follow the instructions to the letter, I can see from your above issue submission that you have no interest in actually doing that. Please do not post another issue -- unless you care to follow the instructions. (Please, otherwise it is too time consuming for me to keep asking you the same questions that were already all written in the original instructions.) That is all.

**Comment by mark8044** [comment]
> Since we had a previous discussion where I basically asked you to follow the instructions to the letter, I can see from your above issue submission that you have no interest in actually doing that. Please do not post another issue -- unless you care to follow the instructions. (Please, otherwise it is too time consuming for me to keep asking you the same questions that were already all written in the original instructions.) That is all.

Damn.  Ok message received.  I mainly posted this up to help you.  I can get around the issue easily, but maybe it affects your potential users?  

Best

**Comment by ryanheise** [comment]
If there is a bug, I will wait for someone to submit a valid (actionable) bug report.

**Comment by mark8044** [comment]
> If there is a bug, I will wait for someone to submit a valid (actionable) bug report.

True, I understand where you are coming from.   But if that error message has any meaning to you I can hunt and get more information for you
```
Execution failed for task ':just_audio:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users//.gradle/caches/transforms-3/0a679862f6c55d82fb9a949f1fd4603f/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
```



I actually just upgraded my gradle (7.2.1) and kotlin (1.6.20) versions and the error message changed slightly

```
Execution failed for task ':just_audio:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/build/just_audio/intermediates/merged_res/release/values/values.xml:156: AAPT: error: resource android:attr/lStar not found.
```

**Comment by ryanheise** [comment]
You want help, I get it. But this is not the designated place to seek help. It is the place for contributors to submit valid GitHub issues, and pull requests. If you believe that you are helping me, you are in fact not. Rather, you are seeking help, and as per the instructions, the designated place for getting help is StackOverflow.

I have locked this discussion to further comments because you continue to show no interest in respecting and following the instructions and procedures put in place for this project.
