### ISSUE TITLE
Audio not playing on iPad Air 

### ISSUE THREAD

**Issue by hivesey** [ryanheise/just_audio#75]
**Describe the bug**
I am playing MP3's from assets. Works fine in iOS simulator but does not work when running on iPad device. 
I am testing it on iPad Air  and ver is 12.4.5

**Minimal reproduction project**
If the example project exhibits the bug, please mention that here, otherwise fork this project and modify the example to reproduce the bug. Provide the link to your repository here.

**To Reproduce**

**Error messages**
No exceptions or error msgs

**Expected behavior**

**Smartphone (please complete the following information):**
 iPad Air  and ver is 12.4.5

**Flutter SDK version**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/XYZ/Documents/me/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/XYZ/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/XYZ/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPad • 32855abc9d99fefdcab49abfc0d57e57654d4b8e • ios • iOS 12.4.5

• No issues found!
```

**Comment by ryanheise** [comment]
I have manually re-inserted the parts of the bug template that you deleted. If you can fill them in, it may make it easier for someone to investigate your bug.

I personally do not have access to an iPad so I cannot test this, so if someone is able to help you, providing the reproduction files and mp3 asset may help.

Does it also happen on an iPhone?
