### ISSUE TITLE
Pump android compileSdkVersion to 33

### ISSUE THREAD

**Issue by youssefali424** [ryanheise/just_audio#757]
**Is your feature request related to a problem? Please describe.**
we can't build apps currently with compileSdkVersion 33

**Describe the solution you'd like**
we can build with compileSdkVersion 33 as some other plugins require it

**Describe alternatives you've considered**
trying to build with 33 but it fails because of some deprecation in the package, tried to lower the compileSdkVersion but other packages required it

**Additional context**
![screenshot](https://user-images.githubusercontent.com/38167511/174481134-a6543a93-7102-4310-994a-a12eb5f515b8.PNG)

**Comment by ryanheise** [comment]
Interesting... Thanks for reporting. I'll prepare a fix.

**Comment by ryanheise** [comment]
Can you test the fix I have pushed to the `fix/android33` branch?

**Comment by youssefali424** [comment]
Thank you so much for responding first, yes i can but i might test it later today,

**Comment by youssefali424** [comment]
yes it worked!, it seems really just a deprecation error (instead of a warning) that can't be used in new android sdk

**Comment by ryanheise** [comment]
Thanks for testing. It is a warning, but I have set it up to report all warnings as errors which forces me to keep things up to date whenever upgrading a dependency (in this case the SDK version).

I'll include the fix in the next release.

**Comment by youssefali424** [comment]
That is cool thank you for your efforts, my humble opinion which might be wrong is that it would be better to have "all warnings as errors" in your debugging env and when you release it to [pub](https://pub.dev) you remove it.

**Comment by ryanheise** [comment]
Yes although this is a rather unusual case since very rarely will something from the standard Java SDK be deprecated (it's typically for the hard dependencies like exoplayer), and it is not too different from having to make changes when targeting new major versions of flutter itself.

**Comment by ryanheise** [comment]
This fix should now be released.
