### ISSUE TITLE
Decoding error with German "Umlauts" when using the Useragen option

### ISSUE THREAD

**Issue by scysys** [ryanheise/just_audio#759]
**To Reproduce (i.e. user steps, not code)**

- Use and start this gist file: https://gist.github.com/scysys/7f700cd49f09ba788021504e8d3477aa

Ill just added an other url 

`http://stream.laut.fm/hitradio1`

and your default useragent 

`myradioapp/1.0 (Linux;Android 11) https://myradioapp.com`

from your documentation.

**Error messages**

```
E/flutter (28734): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FormatException: Invalid HTTP header field value: "Hitradio LÃ¼neburg." (at character 11)
E/flutter (28734): Hitradio LÃ¼neburg.
E/flutter (28734):           ^
E/flutter (28734): 
E/flutter (28734): #0      _HttpHeaders._validateValue (dart:_http/http_headers.dart:664:9)
E/flutter (28734): #1      _HttpHeaders._addAll (dart:_http/http_headers.dart:71:20)
E/flutter (28734): #2      _HttpHeaders.set (dart:_http/http_headers.dart:92:5)
E/flutter (28734): #3      _proxyHandlerForUri.handler.<anonymous closure> (package:just_audio/just_audio.dart:3096:34)
E/flutter (28734): #4      _HttpHeaders.forEach.<anonymous closure> (dart:_http/http_headers.dart:122:13)
E/flutter (28734): #5      _HashMap.forEach (dart:collection-patch/collection_patch.dart:164:15)
E/flutter (28734): #6      _HttpHeaders.forEach (dart:_http/http_headers.dart:120:14)
E/flutter (28734): #7      _proxyHandlerForUri.handler (package:just_audio/just_audio.dart:3095:30)
E/flutter (28734): <asynchronous suspension>
```

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale de-DE)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**

I tried a little bit to decode it, but wont find a real solution to it. Ideas?
This behavior only is happening when adding a usergent.

**Comment by scysys** [comment]
really? haha. other informations not needed.

**Comment by ryanheise** [comment]
Sure, maybe if you were running the project you would like to accept such bug reports. But of course if you want me to help you, you will follow my instructions and provide all information I have requested. It's your choice, maybe you don't want it fixed that bad?

**Comment by scysys** [comment]
> Sure, maybe if you were running the project you would like to accept such bug reports. But of course if you want me to help you, you will follow my instructions and provide all information I have requested. It's your choice, maybe you don't want it fixed that bad?

Wow! What is that for an stupid answer Ryan? The other informations just makes no sense what browser or whatever you use. Sure I though about it to also add it to report. But it makes no sense. So I thought its better for YOU to leave them that you only have things what you really need to reproduce. Sorry for opened a report. Was my last one.

**Comment by ryanheise** [comment]
My physical limitations mean I can't easily work on computers but I do my best. When people follow the instructions and template exactly, that makes it actually possible for me to do the work I do within my limitations. If you don't care about any of that and you want me to do things your way, then yes you may leave, I should not have to argue and justify myself. I regrettably can't help you, but hopefully someone else will report the bug in the correct way at which point I will be able to take action. Goodbye and good luck.

**Comment by waplay** [comment]
I confirm, I have the same problem. Stations using special characters in their headers throw an unhandled exception. It would be nice if this behavior could be fixed. Or let us catch this exception, for example, to give the player a second attempt to connect without a user agent.

By the way, this behavior causes not only `player = AudioPlayer(userAgent: userAgent)`, but also any header in `player.setAudioSource(AudioSource.uri())`

To reproduce the problem, it is enough to substitute these urls in the standard example of the library.

```
http://radio.uanyot.com:8000/radio.ogg
https://listen.radioking.com/radio/2725/stream/72647
https://listen1.myradio24.com/6262
```

**Comment by ryanheise** [comment]
@waplay would you mind submitting a bug report so that I can investigate it? As I have explained above, I need this to proceed, so if you can submit one then I'll be able to investigate.

**Comment by waplay** [comment]
@ryanheise I submit a new bug report #765
