### ISSUE TITLE
Official example does not work on M1 Mac (Monterey 12.3.1), error code -11800

### ISSUE THREAD

**Issue by mikeesouth** [ryanheise/just_audio#760]
**Which API doesn't behave as documented, and how does it misbehave?**
I guess it's the just_audio API? When starting the example in an iPad simulator on M1 Mac Monterey I get this error when the app is initializing: `flutter: Error loading audio source: (-11800) The operation could not be completed`

**Minimal reproduction project**
"The example". I just cloned the just_audio repo and started the example project. I get the error when the example is initializing and if I try to press the play button I get this second error message: `flutter: A stream error occurred: PlatformException(-11800, The operation could not be completed, null, null)`

**To Reproduce (i.e. user steps, not code)**
1. Clone the official example. I don't think specific commit is important but I tested with the latest minor branch (commit hash a820b1b22f1680f84bb09bd8e748f9054555a39b)
2. `flutter pub get` in the example directory
3. Start the example on an iPad emulator on iOS
4. The first error is presented when the app is initializing: `flutter: Error loading audio source: (-11800) The operation could not be completed`
5. Press play button, the second error message is presented (same error as last step but with another syntax): `flutter: A stream error occurred: PlatformException(-11800, The operation could not be completed, null, null)`

**Error messages**

```
flutter: Error loading audio source: (-11800) The operation could not be completed
flutter: A stream error occurred: PlatformException(-11800, The operation could not be completed, null, null)
```

**Expected behavior**
I expect the example to work in the iOS simulator on my M1 MacBook Air from 2020. I only tested iPad 9th generation but I guess this problem also exists in other simulators. I believe that this is working on physical devices but I'm not entirely sure (I don't own or have access to a physical iOS device).

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey on MacBook Air 2020 with M1 (apple silicon)
 - Browser: Not applicable, tested on iOS simulator (iPad 9th generation)

**Smartphone (please complete the following information):**
 - Device: iOS simulator (iPad 9th generation)
 - OS: iOS 15.5

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-arm, locale en-SE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Additional context**
I have this problem in my other apps too but I get it 100% in the official example so that's the simplest way to reproduce the problem. I believe that this problem does not occur on physical devices but I haven't tested that yet. My other app works on physical iOS devices but that's using just_audio 0.9.20 and flutter 2.10.5. I haven't tested on physical iOS devices with flutter 3 and just_audio > 0.9.20.

I've tried to use both "setAsset()" and "setFilePath()" in my own app and I get the same error with both methods. I haven't tried to modify the official example in any way, I expect it to work in its unmodified form.

**Comment by ryanheise** [comment]
It sounds like an issue with the way the emulator emulates device storage. My understanding is that it sets up a container as a directory somewhere on the computer's own drive, and if there is a problem with that, I wonder whether any other types of file access for the same file paths would fail. Can you try using the Dart IO APIs to open and read from the same file path and see if you get a more informative error?

**Comment by mikeesouth** [comment]
Hm, thanks for the reply. The just_audio example loads the file using setAudioSource with an Uri, like this: `await _player.setAudioSource(AudioSource.uri(Uri.parse("https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3")));`. I'm not really sure where (and how) just_audio saves this to the device storage.

I tried to use Dart IO to read an asset from the example (nature.mp3), save the data to a file in a temporary directory, then read that file. That seems to work just fine but I guess that wasn't what you were asking :) Can you give me a hint on how to get the file path that just_audio use for temporary storage on the device?

This is the code I tested in `example/lib/main.dart` to just write and read a file on the device storage and it works just as expected - no errors.

```
  Future<void> _init() async {

    // (skipping some lines for previous init() code)

    try {
      final buffer = await rootBundle.load('audio/nature.mp3');
      final bufferAsUint8 =
          buffer.buffer.asUint8List(buffer.offsetInBytes, buffer.lengthInBytes);
      await _writeTempFile(bufferAsUint8);
      final readContents = await _readTempFile();
      print('readContents.length: ${readContents.length}');
    } catch (e) {
      print('Error while trying to write and read mp3 file to temp directory');
    }
  }

  Future<File> _writeTempFile(Uint8List data) async {
    final tempDir = await getTemporaryDirectory();
    final file = File('${tempDir.path}/foo.mp3');
    await file.writeAsBytes(data, flush: true);
    return file;
  }

  Future<Uint8List> _readTempFile() async {
    final tempDir = await getTemporaryDirectory();
    return File('${tempDir.path}/foo.mp3').readAsBytes();
  }
```

**Comment by ryanheise** [comment]
> Hm, thanks for the reply. The just_audio example loads the file using setAudioSource with an Uri, like this: `await _player.setAudioSource(AudioSource.uri(Uri.parse("https://s3.amazonaws.com/scifri-episodes/scifri20181123-episode.mp3")));`. I'm not really sure where (and how) just_audio saves this to the device storage.

No it doesn't. I was just replying to when you said this:

> I've tried to use both "setAsset()" and "setFilePath()" in my own app and I get the same error with both methods.

What those methods have in common is that they do deal with the filesystem, so I thought you were specifically observing the error on these two methods. If it's happening even for remote URLs, then I don't know what it could be. It would still be interesting to know whether it is only this plugin or whether there is another plugin encountering the same issue so as to find the common element.

**Comment by mikeesouth** [comment]
@ryanheise sorry for bothering you with this, case closed. It was the simulator that somehow was in a broken state. Restarting my MacOS did not help but quitting and restarting the simulator did help. Stupid mistake from my side but I had no idea it could break like this.
