### ISSUE TITLE
Artwork in notification is pixelated

### ISSUE THREAD

**Issue by nzackoya** [ryanheise/just_audio#763]
just_audio_background, the artwork added to the MediaItem, in the media notification is pixelated. Tried different dimensions

Minimal reproduction project
https://github.com/ryanheise/just_audio/tree/minor/just_audio_background/example

To Reproduce (i.e. user steps, not code)
Just run your just_audio_background example. Tried different dimensions and ratios, even the image from the just_audio_background example is pixelated. https://media.wnyc.org/i/1400/1400/l/80/1/ScienceFriday_WNYCStudios_1400.jpg

Error messages

N/a

Expected behavior
Clean and quality picture in the notification

Screenshots

Desktop (please complete the following information):
N/A

Smartphone (please complete the following information):

Device: Nokia c1 plus
OS: Android 10
Flutter SDK version
Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (2 weeks ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2

Additional context
N/A

**Comment by nzackoya** [comment]
Seriously?

**Comment by ryanheise** [comment]
You skipped the first section of the bug report which is intended to qualify this as a bug rather than a different type of issue (eg feature request). There is API documentation regarding image resolution, you need to show that the behaviour is contrary to that documented behaviour.
