### ISSUE TITLE
Disposing background service 

### ISSUE THREAD

**Issue by Jens05** [ryanheise/just_audio#768]
**Is your feature request related to a problem? Please describe.**
Yes, when i close my app the music keeps on continuing.

**Describe the solution you'd like**
A boolean field or something like that, that makes it possible to dispose the backgroundservice when the app is closed.

**Describe alternatives you've considered**
WidgetsBindingOberserver, but doesn't do the job

**Additional context**
![image](https://user-images.githubusercontent.com/89305381/177013783-27fa79d4-e7f1-40e0-9f09-94b99ac509fc.png)

**Comment by ryanheise** [comment]
WidgetsBindingObserver is perfectly capable of handling this, but I would suggest seeking help on using that API on StackOverflow since that is an issue with the Flutter API and not with just_audio_background.
