### ISSUE TITLE
Running just audio background in seperate isolate like android_alarm_manager

### ISSUE THREAD

**Issue by DanielChuDC** [ryanheise/just_audio#773]
**Is your feature request related to a problem? Please describe.**
When I try to achieve running just audio with background code but no luck. Then I found just audio background and audio service. I need the ability to run just audio in background code.

**Describe the solution you'd like**
The solution should let developer to connect to the isolate, which describe in [Can I connect to my audio handler from background code?](https://github.com/ryanheise/audio_service/wiki/FAQ)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ryanheise** [comment]
This plugin has nothing to do with isolates or isolate communication. Although, it was built in such a way that it should work correctly when run in a background isolate that you establish yourself, such as one created by android_alarm_manager or flutter_isolate. If you want to communicate or connect between multiple isolates in your app, you should use the standard Flutter APIs to carry out that inter-isolate communication, but just_audio does not care (or need to care) about how you do that communication. If you happen to use audio_service, then it does offer some APIs to help you communicate between isolates, but those are just built on top of the standard Flutter APIs anyway, so you always have the ability through standard Flutter APIs to do that.

**Comment by DanielChuDC** [comment]
Alright! Thanks for the explanation! Closing this enhancement now.
