### ISSUE TITLE
Stream automatically skip to next stream in case of failure

### ISSUE THREAD

**Issue by deep1931** [ryanheise/just_audio#780]
### Documented behaviour
NA
### Actual behaviour
In case of multiple streams, if there is any bad stream, or not able to play, it skip automatically to next one. 

### Minimal reproduction project
NA
### Reproduction steps

We can add a bad stream means, stream which is not exists, then try to play, it will automatically skip to next. And in my case, i have internet connectivity issues, mobile data is showing connected but not transferring any data, in this case, it will start buffering for some time and then throws the exception, as below and then stream skip to next.

`errorPlatformException(0, Source error, null, null)`

It should not skip to next, it should stop on same stream.

### Output of flutter doctor
```[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.66.0)
[!] Connected device
    ! No devices available
[✓] HTTP Host Availability

! Doctor found issues in 4 categories.
```
### Devices exhibiting the bug
Android and iOS

**Comment by ryanheise** [comment]
When I look at your past issues here and in audio_service, you have not once ever submitted a valid bug report. Please don't keep doing this, because such issues only use up my time in an unproductive way. If you do decide to keep doing this after what I said to you in your last issue, and in this issue, I'm afraid I'll have to disable your access to posting new issues.
