### ISSUE TITLE
Asset Always in Playing State

### ISSUE THREAD

**Issue by buraksenkus** [ryanheise/just_audio#783]
**Which API doesn't behave as documented, and how does it misbehave?**
I have a 1 second long audio file in mp3 format. When I load this file into an `AudioPlayer` instance and play it, it stays in playing mode all the time and never goes into completed mode.

Here is my implementation

```
class MyPlayer {
  Timer? timer;
  AudioPlayer _player = AudioPlayer();
  double _volume = 0.5;

  void init() {
    _player.setVolume(_volume);
    _player.setAsset("sounds/hit.mp3");
    print("${_player.loopMode}");
    _player.playerStateStream.listen((state) {
      if (state.playing) {
        print("Player is playing!");
      } else {
        switch (state.processingState) {
          case ProcessingState.idle:
            print("Player is idle!");
            break;
          case ProcessingState.loading:
            print("Player is loading!");
            break;
          case ProcessingState.buffering:
            print("Player is buffering!");
            break;
          case ProcessingState.ready:
            print("Player is ready!");
            break;
          case ProcessingState.completed:
            print("Player is completed!");
            break;
        }
      }
    });
  }

  Future<void> togglePlay() async {
      _player.play();
  }
}

```

Here is log output

```
I/flutter (21963): LoopMode.off
I/flutter (21963): Player is idle!
I/flutter (21963): Player is loading!
I/flutter (21963): Player is ready!
I/flutter (21963): Player is playing!
I/flutter (21963): Player is playing!
```

**Note 1: I'm toggling play function from UI after I see ready log in console.**

**Note 2: My main goal is to use a single `AudioPlayer` instance for a specific audio file again and again without creating another instances. Playing will be triggered by me.**

**Minimal reproduction project**
None

**To Reproduce (i.e. user steps, not code)**
Reproduction can be easily done by looking my implementation.

**Error messages**

```
None
```

**Expected behavior**
When the audio file is finished playing (after 1 sec in my case), the state must be `completed` and the `playing` getter returns false.

**Screenshots**
None

**Desktop (please complete the following information):**
None

**Smartphone (please complete the following information):**
 - Device: Samsung A51
 - OS: Android 12
 - Problem also exists in Windows.

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22622.436], locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**
My questions are:
1. Is this a bug or do I have to find out that if the playing sound has completed by another approach?
2. Additionally, it prints "playing" log two times. What is the reason of this?

**Comment by ryanheise** [comment]
> **Minimal reproduction project**
> None

Hmm, you ignored the instructions given to you in your previous issue:

> Do I really need to submit a minimal reproduction project for a bug? A: Yes. I prioritise bugs secondarily on how many people are affected, and primarily on whether the bug report is complete, in the sense that it enables me to immediately reproduce it and start working on a fix. If a bug is important to you, the best thing you can do is to provide all requested information ASAP so that I can start looking into it ASAP.

And also ignored the instructions at the top of the issue template:

> ALL SECTIONS BELOW MUST BE COMPLETED

And...

> My questions are:

didn't follow the instructions in the contributor guidelines:

> How we use GitHub
> 
> We use GitHub as a place and tool for contributors to work together on project development. That is, we use it to report bugs, suggest improvements, and contribute code and documentation to address those bugs or suggestions. It is not used as the place to ask for help (For that we use StackOverflow via the [just-audio](https://stackoverflow.com/questions/tagged/just-audio) tag).

If you would like me to investigate a bug, please follow the instructions to make it easier for me to investigate.

Closing this as an invalid issue.
