### ISSUE TITLE
User Agent is not added to redirected URLs

### ISSUE THREAD

**Issue by snipd-mikel** [ryanheise/just_audio#796]
**Which API doesn't behave as documented, and how does it misbehave?**
When configuring the player to use a custom User Agent, the User-Agent header is only sent on the first request. However, if the url is a redirect url (which seems to be quite common on the podcast world), the following requests don't contain the configured user agent.

**Minimal reproduction project**
Use the default project, just change the audio url and configure the user agent (as explained on next step).

**To Reproduce (i.e. user steps, not code)**
1. Configure a custom user agent on the player
2. Play an audio which resolves to a redirect: (https://play.podtrac.com/npr-510282/edge1.pod.npr.org/anon.npr-mp3/npr/pchh/2022/08/20220810_pchh_05aaa4b9-373a-4307-ac0d-5012aad593cb.mp3?awCollectionId=510282&awEpisodeId=1116295815&orgId=1&topicId=1138&aggIds=93568166&d=1544&p=510282&story=1116295815&t=podcast&e=1116295815&size=24717733&ft=pod&f=510282)
3. Check the network requests and check the different redirected requests. Only the first one has the correct user agent.

**Error messages**
N/A

**Expected behavior**
The user agent should also be set on redirected requests.

**Screenshots**
N/a

**Additional context**
Currently the ProxyHttpClient used to set the user agent is doing so by setting the user agent header on the request. However, according to this issue https://github.com/dart-lang/http/issues/268, that header is not added to the redirects. The proper way of doing that is to set the userAgent property on the HttpClient() instance.

I will create a PR to address this issue. Let me know if you need more information.

**Comment by ryanheise** [comment]
That's an interesting find, and your proposed solution makes perfect sense. I look forward to your PR!

**Comment by snipd-mikel** [comment]
Here is the PR: https://github.com/ryanheise/just_audio/pull/797 :)
