### ISSUE TITLE
It would be nice to have a fast way to see all info about the player and its state to help debug any issues

### ISSUE THREAD

**Issue by CodingRox82** [ryanheise/just_audio#798]
**Is your feature request related to a problem? Please describe.**
Right now I have a strange issue that I can't figure out. When I enter my group's chat screen, the player plays the target audio just fine. However, when I hit the back button in the app (Navigator.pop()) and then go back into the chat screen, the audio doesn't work. I hit the same play button as I did in the first time and it just doesn't play anything.

**Describe the solution you'd like**
It would be nice to have either a built in feature or maybe just boilerplate code that I can copy and paste anywhere in my app to see information about the player, if it exists. For example, I copy paste the block of code on my play button event and after the player attempts to play the audio, it would show the following:

-the target filepath
-player state
-any errors related to playback
-any other useful info???

I'm assuming that boilerplate code would be simpler here compared to a built in feature like a function that I can run whenever to see this info. Whatever is easier.

**Describe alternatives you've considered**
Currently trying to build my own boilerplate code, but I'm relatively new to Dart so this is gonna take me a bit to figure out.

**Additional context**

**Comment by ryanheise** [comment]
It sounds like you are asking for diagnostic information that is already available through this API, and I refer you to the documentation to see all of the ways to access the different state and error messages. I don't plan to add any new API if it is already available in the current API. If you are struggling with the documentation, you can make a separate issue describing which section of the documentation was unclear, or if you are asking for help to do it, you can try clicking the link to ask a question.

**Comment by CodingRox82** [comment]
Yes, I am already working through the docs to find what I need. I was only mentioning this because if everything seems to revolve around the AudioPlayer() class, then maybe there could be a set of boilerplate code that we could all just splash into our code anywhere to see relevant info about the player quickly.

**Comment by CodingRox82** [comment]
Please disregard.
