### ISSUE TITLE
problem with seek() for streamed MP3 file

### ISSUE THREAD

**Issue by fpv999** [ryanheise/just_audio#802]
**Is your feature request related to a problem? Please describe.**
seek() works improperly for streamed MP3 files, because just_audio.dart code first updates playing position, then it calls native player to seek streamed file. This causes a time offset between real playing position and the one obtained by `playbackState.value.position`.

**Describe the solution you'd like**
```

--- a/just_audio/lib/just_audio.dart
+++ b/just_audio/lib/just_audio.dart
@@ -1104,6 +1104,8 @@ class AudioPlayer {
       default:
         try {
           _seeking = true;
+          await (await _platform)
+              .seek(SeekRequest(position: position, index: index));
           final prevPlaybackEvent = _playbackEvent;
           _playbackEvent = prevPlaybackEvent.copyWith(
             updatePosition: position,
@@ -1114,8 +1116,6 @@ class AudioPlayer {
               PositionDiscontinuityReason.seek,
               prevPlaybackEvent,
               _playbackEvent));
-          await (await _platform)
-              .seek(SeekRequest(position: position, index: index));
         } finally {
           _seeking = false;
         }
```

**Describe alternatives you've considered**
The other solution would be to refactor `playbackState.value.position` to read position from native player, which is not that nice.

**Additional context**
Let me know if this solution seems right, or there are some flaws that I just don't see.

**Comment by fpv999** [comment]
Unfortunately my solution is not perfect too. Then I need a way to read position from a native player :/

**Comment by ryanheise** [comment]
I'm not clear on the issue. Is it a bug? Which platforms does it occur on?

Are you saying that when you drag the seek handle to some position, you would like that seek handle to jump back to the original position until the seek completes? I don't think that would be an expected behaviour.

**Comment by fpv999** [comment]
It's a bug. The problem is that the actual playing positions is often smaller than the one returned from `playbackState.value.position`. And it happens after you seek (drag the seekbar).

**Comment by ryanheise** [comment]
If it is a bug, maybe a "feature request" is not the best template to use.

**Comment by fpv999** [comment]
Maybe.

**Comment by ryanheise** [comment]
OK, I'll close this one. Please answer my above questions in the new bug report that you create, including the question about which platforms/devices you have tested on.

**Comment by fpv999** [comment]
I don't have time now. I'll prepare a test project later. Anyway it happens for sure on Android (8, Huawei).
