### ISSUE TITLE
AVAudioSession.ErrorCode.cannotInterruptOthers

### ISSUE THREAD

**Issue by nohli** [ryanheise/just_audio#807]
**Which API doesn't behave as documented, and how does it misbehave?**
`AudioPlayer.play()`

**Minimal reproduction project**
(error in production)

**To Reproduce (i.e. user steps, not code)**

0. Add `just_audio` to project
1. Use one audio player instance to play a constant audio
2. Put app to background
3. Use another audio player instance and try `play()` while app is in background/other audio (outside of the app) is playing

**Error messages**

```
PlatformException(560557684, The operation couldn’t be completed. (OSStatus error 560557684.), null, null)

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
<asynchronous suspension>
#2      AVAudioSession.setActive (package:audio_session/src/darwin.dart:148)
<asynchronous suspension>
#3      AudioSession.setActive (package:audio_session/src/core.dart:236)
<asynchronous suspension>
#4      AudioPlayer.play (package:just_audio/just_audio.dart:903)
<asynchronous suspension>
```

**Expected behavior**
No exception

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: iPhone

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (2 available)
    ! Error: X is not connected. Xcode will continue when X is connected. (code -13)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**
The error is [this one](https://developer.apple.com/documentation/avfaudio/avaudiosession/errorcode/cannotinterruptothers).
My question is: If I add `audio_session` to the project, does it help handling playing audio when other audio is active and does it fix this exception?

**Comment by ryanheise** [comment]
I'm sorry I can't investigate on my end without a minimal reproduction project.
