### ISSUE TITLE
Fail to play .m4a format

### ISSUE THREAD

**Issue by erickcchoi** [ryanheise/just_audio#82]
**Describe the bug**
Fail to play .m4a media, In the Example code, only modify the media source to :
        .setUrl("http://aod.cos.tx.xmcdn.com/group75/M02/77/28/wKgO3V6iDFyjDEazAAE-CfKc_4A012.m4a")

**Minimal reproduction project**
In the Example code, only modify the media source to :

  @override
  void initState() {
    super.initState();
    _player = AudioPlayer();
    _player
        .setUrl("http://aod.cos.tx.xmcdn.com/group75/M02/77/28/wKgO3V6iDFyjDEazAAE-CfKc_4A012.m4a")
        // .setUrl("https://rthkaudio1-lh.akamaihd.net/i/radio1_1@355864/master.m3u8")
        .catchError((error) {
      // catch audio error ex: 404 url, wrong url ...
      print(error);
    });
  }

**To Reproduce**
Just run the example code.

**Error messages**
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/HostConnection( 4118): createUnique: call
D/HostConnection( 4118): HostConnection::get() New Host Connection established 0x7cbe4b431dc0, tid 4210
D/HostConnection( 4118): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_1
D/eglCodecCommon( 4118): allocate: Ask for block of size 0x1000
D/eglCodecCommon( 4118): allocate: ioctl allocate returned offset 0x3ff805000 size 0x2000
D/EGL_emulation( 4118): eglMakeCurrent: 0x7cbe4b431a00: ver 3 1 (tinfo 0x7cbe4b4187c0)
E/eglCodecCommon( 4118): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 4118): glUtilsParamSize: unknow param 0x000082da
D/EGL_emulation( 4118): eglMakeCurrent: 0x7cbe4b431be0: ver 3 1 (tinfo 0x7cbe4b418680)
I/Choreographer( 4118): Skipped 66 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 4118): eglMakeCurrent: 0x7cbe4b431a00: ver 3 1 (tinfo 0x7cbe4b4187c0)
W/t_audio_exampl( 4118): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl( 4118): Init 8340654 [ExoPlayerLib/2.11.4] [generic_x86_64, Android SDK built for x86_64, Google, 29]
D/NetworkSecurityConfig( 4118): No Network Security Config specified, using platform default
E/ExoPlayerImplInternal( 4118): Source error
E/ExoPlayerImplInternal( 4118):   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:282)
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal( 4118):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 4118):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 4118):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal( 4118):   Caused by: java.io.IOException: Cleartext HTTP traffic to aod.cos.tx.xmcdn.com not permitted
E/ExoPlayerImplInternal( 4118):       at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
E/ExoPlayerImplInternal( 4118):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
E/ExoPlayerImplInternal( 4118):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:550)
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:454)
E/ExoPlayerImplInternal( 4118):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:280)
E/ExoPlayerImplInternal( 4118):       ... 7 more
E/AudioPlayer( 4118): TYPE_SOURCE: Unable to connect
I/flutter ( 4118): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect

**Expected behavior**
Play the m4a file same as mp3.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10

**Smartphone (please complete the following information):**
 - Device: Android simulator API 29 version 10
 - OS: Android

**Flutter SDK version**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.815], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

• No issues found!

Sorry, I did the wrong m4a url in the previous test, so I just change it to the correct m4a url, but it still fail to run. (I did updated the above url and the error message).

**Comment by ryanheise** [comment]
That does not seem like a valid URL since it has no scheme part.

**Comment by erickcchoi** [comment]
Sorry, I did the wrong m4a url in the previous test, so I just change it to the correct m4a url, but it still fail to run. (I did updated the above url and the error message).

**Comment by stonega** [comment]
> Sorry, I did the wrong m4a url in the previous test, so I just change it to the correct m4a url, but it still fail to run. (I did updated the above url and the error message).

Caused by: java.io.IOException: Cleartext HTTP traffic to aod.cos.tx.xmcdn.com not permitted
If you wish to connect to non-HTTPS URLS, add the following attribute to the application element of your AndroidManifest.xml file:

 `<application ... android:usesCleartextTraffic="true">`

**Comment by erickcchoi** [comment]
It works, Thank you so much for your help.
