### ISSUE TITLE
iOS: Getting (-1200) An SSL error has occurred and a secure connection to the server cannot be made.

### ISSUE THREAD

**Issue by rguntha** [ryanheise/just_audio#825]
**Which API doesn't behave as documented, and how does it misbehave?**
setAudioSource with StreamAudioSource
setAudioSource with LockCachingAudioSource

**Minimal reproduction project**
https://github.com/rguntha/bytestream
[https://github.com/rguntha/bytestream/blob/main/lib/main.dart](url)
`await _audioPlayerJust.setAudioSource(bufferAudioSource);`

> Note: I have followed the documentation and added the below configuration to the info.plist
```<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

**To Reproduce**
- Launch the project in the phone or emulator
- Click the play button
- You will see the error message in the logs

**Error messages**
```
2022-09-27 20:17:17.534212+0530 Runner[430:31691] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: (-1200) An SSL error has occurred and a secure connection to the server cannot be made.
#0      AudioPlayer._load (package:just_audio/just_audio.dart:840:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1421:28)
<asynchronous suspension>
```

**Expected behaviour**
The exception should not appear and it should proceed to invoke the request method in the StreamAudioSource class

**Smartphone**
iPhone 12 with iOS 15.x
iPhone 6 with iOS 12.5.5

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] HTTP Host Availability
```

**Additional context**
I am using just_audio latest version 0.9.29

**Comment by ryanheise** [comment]
Can you try editing the example in the official repository instead of creating a new project? That will ensure all else is equal, including config files, and that you only make minimal changes.

**Comment by rguntha** [comment]
Here is the simpler repo which just have 2 files from the just_audio example project
https://github.com/rguntha/just_ssl.git

I have not changed the example code. Just as is copy of example_caching.dart, which demonstrates the LockCachingAudioSource

The SSL occurs in this repo also. I have tried many answers in stackoverflow for this issue, but could not get it to work. Kindly help me.

**Comment by ryanheise** [comment]
The reason I ask people to edit the official example is because I can see via the diff exactly what you changed. It is hard otherwise to see whether all else is equal.

**Comment by rguntha** [comment]
The example app works perfectly fine. But when I create a blank app, copy the files from example app, and setup the Info.plist items for http connections, the LockCachingAudioSource does not work. It is as if, the iOS is ignoring the Info.plist settings.

In the blank app, I have not altered the example app.

So I am not sure if there may be some other settings I am missing. 

I spent more than 2 days going over all the documentation and internet and tried all that I could.

Your help in pointing out the issue is greatly appreciated.

**Comment by ryanheise** [comment]
If your code works when added to the official example, then it is not a just_audio bug.

This is not the place where I help people with their apps, but my last comment is that I would suggest you copy the official example's Info.plist into your own project since the official one works. You will need to figure out on your own what is the difference between yours and the official example's version of that file, maybe use a diff tool.

**Comment by ryanheise** [comment]
Hi @rguntha 

I'm just working through issues I still have open in my browser. Regarding the "diff tool", I don't know if you already ran this but when doing a diff of the official example's `Info.plist` vs your own `Info.plist` I get this difference (the official example is on the left):

```diff
	<key>NSAppTransportSecurity</key>				<key>NSAppTransportSecurity</key>
	<dict>								<dict>
		<key>NSAllowsArbitraryLoads</key>				<key>NSAllowsArbitraryLoads</key>
		<true/>								<true/>
							      >			<key>NSAllowsArbitraryLoadsForMedia</key>
							      >			<true/>
	</dict>								</dict>
```

In other words, `NSAllowsArbitraryLoadsForMedia` should be removed to make it work like the example.

**Comment by rguntha** [comment]
Hi @ryanheise 
Thanks for getting back to me. I followed your earlier advise and diffed the my code and the example code and noticed differences related to IOS version. Upon further investigation I noticed that the IOS target version had inconsistencies among Podfile, AppFrameworkInfo.plist and project.pbxproj file.

This link [https://stackoverflow.com/a/64075795/3095401](url) helped me resolving the issues. 

Then this error disappeared.

I have tried your above suggestion to remove/add NSAllowsArbitraryLoadsForMedia and many other stackoverflow suggestions related NSAppTransportSecurity, but they did not help.

Since the fix that worked is not related to just_audio directly, I have not responded here.

Thanks again for getting back to me

**Comment by ryanheise** [comment]
That's good to hear although you do still need to treat `Info.plist` carefully as NSAllowsArbitraryLoadsForMedia has some interesting version-dependent behaviour. As stated in the documentation for this iOS API:

> In iOS 10 and later and in macOS 10.12 and later, if you include this key with any value, then App Transport Security ignores the value of the [NSAllowsArbitraryLoads](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads?language=objc) key, instead using that key’s default value of NO.
