### ISSUE TITLE
iOS taking long time to load media item compared to android and sometime it simply doesn't load at all.

### ISSUE THREAD

**Issue by darkCavalier11** [ryanheise/just_audio#827]
**Which API doesn't behave as documented, and how does it misbehave?**
`await _player.setAudioSource(...)` taking much longer in setting up the url source for iOS compared to android for some audio having long duration. And my android phone hardware is pretty old compared to the iPhone. These uri are not regular `mp3` uri, rather have a different extension(extracted from youtube) but non the less browser plays these audio urls quicker and smoother than phone.

**Minimal reproduction project**
[fork repo](https://github.com/darkCavalier11/just_audio/tree/minor/just_audio/example)

**To Reproduce (i.e. user steps, not code)**
1. Go to example
2. Run on iOS as well as Android and see the results.

**Expected behavior**
A smooth loading and playing of the audio from the uri as it does on the android side.

**Desktop (please complete the following information):**
 - MacOS 12.6
 - Brave

**Smartphone (please complete the following information):**
 - Device: iPhone(iOS 16), Samsung
 - OS: iOS 16, Android 12

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

```

**Comment by giangphan11** [comment]
Finally, I have exactly the same problem #822

**Comment by ryanheise** [comment]
just_audio uses apple's framework directly to load also so that means it will support whatever audio formats Apple supports and it will take as long to load as Apple takes to load it. All you can do about formats is use another plugin to transcode them if necessary, and use load control parameters to control how fast iOS will start playing.

**Comment by ryanheise** [comment]
This has the same reproduction project as #828 so I'll close this one.
