### ISSUE TITLE
iOS duration for audio showing double than the actual duration

### ISSUE THREAD

**Issue by darkCavalier11** [ryanheise/just_audio#828]
**Which API doesn't behave as documented, and how does it misbehave?**
On completion of the `await _player.setAudioSource(...)` which returns a duration that is double than the actual duration in iOS. These urls are not regular `.mp3` urls rather extracted from youtube, but they are working smoothly on android.

**Minimal reproduction project**
[fork](https://github.com/darkCavalier11/just_audio/tree/bug-audio-duration/just_audio/example)

**To Reproduce (i.e. user steps, not code)**
1. Run the project inside example
2. See the duration in both android and iOS

**Expected behavior**
Duration should be same for both android and iOS.

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Brave

**Smartphone (please complete the following information):**
 - iPhone, Samsung
 - OS: iOS 16, Android 12

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

```

**Additional context**
This issue also there in the `just_audio_backgroud`. The duration shown during an android locked screen is proper but on iOS it is doubled.

**Comment by ryanheise** [comment]
> These urls are not regular `.mp3` urls rather extracted from youtube, but they are working smoothly on android.

Each platform, and sometimes each specific model of phone, has its own supported set of audio codecs. For Android, it supports all of the codecs supported by ExoPlayer. For iOS, it just supports whatever Apple supports. Typically when building apps for iOS, you need to transcode your audio into one of the audio formats natively supported by Apple.

It is probably not surprising that Apple does not support formats created by Google. Maybe you can confirm, what is the format of the file in question?

**Comment by xshiwei** [comment]
也有这个问题

**Comment by ryanheise** [comment]
I didn't get an answer to the question regarding the format (whatever unwrapping the YouTube URL gives you, I am guessing it's a format that iOS doesn't support.) Since iOS supports whatever it supports and I can't change that, you would have to transcode the audio into something that iOS does support, so I'll close as unresolvable.
