### ISSUE TITLE
Manually Specify File Type

### ISSUE THREAD

**Issue by caseycrogers** [ryanheise/just_audio#830]
**Is your feature request related to a problem? Please describe.**
As seen in https://github.com/ryanheise/just_audio/issues/685, the auto-detected and/or header-specified content type can be incorrect and cause crashes.

For streamed files, you can override the content type header but for local files, there's no such option (attempting to specify a content-type header on file `UriAudiosource` cause a null exception).

**Describe the solution you'd like**
An argument for `setFile` (and other constructors where applicable) that allows me to manually override the automatically detected content type.

**Describe alternatives you've considered**
Ability to set headers for file based URI audio sources.

**Additional context**

**Comment by ryanheise** [comment]
Wait, I just told after your last comment that just_audio has no control over this and you either need to work within iOS's system based on filename extensions (when dealing with files), or if you want headers, you need to work with a web server (such as the proxy server included in just_audio and accessible via the StreamAudioSource API). I will not be adding a new feature that does not map to the way files vs HTTP actually work.
