### ISSUE TITLE
Duration is not updated when playing a source which have dynamic duration (DASH/HLS)

### ISSUE THREAD

**Issue by lkho** [ryanheise/just_audio#84]
**Describe the bug**
When working with DASH/HLS streams, the duration can be unknown at the beginning, and being updated many times during playback. The duration returned from the setUrl() initially is not enough. Moreover, the player position is calculated with regards to the duration, thus when the duration is updated to a larger value after some time during playback, the position reporting is capped at a maximum of the initial duration.

**To Reproduce**
1. I don't have a public DASH/HLS url, but any http server which serves the output directory of a ffmpeg command e.g. `ffmpeg -i XXX -f dash -hls_playlist 1 -seg_duration 20 master.mpd` will work.  
(the manifest need to be 'live', which means it will update periodically.)
2. load the DASH/HLS url
3. the initial duration will be reported as the current length of the manifest, up to the point ffmpeg has processed.  
(it is the first segment length if you start playing immediately after you start ffmpeg)  
(you can add `-re` flag before `-i` to slow down transcoding)
4. use the getPositionStream() to track the position of the player
5. when the player position reaches that duration, the value will stay there and stops updating, even though it is still playing.
6. currently the lib does not have method to re-fetch the duration.

**Expected behavior**
the duration should be emitted back to to the UI if it is changed, so the player position can be calculated correctly.

**environment**
 - OS: android 8.0
 - Flutter SDK: `v1.12.13+hotfix.9`
 - just_audio: `0.1.7`

**related issues**
#41 the buffer value will also stop updating, after the buffer reaches the initial duration. (but it is still buffering more content, since the manifest duration has been extended.)

https://github.com/ryanheise/just_audio/blob/fdea4398e7356412e55e5b3896439c0642df0e74/android/src/main/java/com/ryanheise/just_audio/AudioPlayer.java#L84

#68 describes iOS, but on android when the duration is unknown, it also returns negative (`-9223372036854775807L` which is `C.TIME_UNSET` in exoplayer)

**Comment by lkho** [comment]
I have a fork hot-fixing this issue, but is android only. See whether it can help.

https://github.com/lkho/just_audio/tree/pr/android-duration

**Comment by ryanheise** [comment]
Hi @lkho , thanks for that. Certainly clipping the position to the duration should not be done when the final duration is unknown, and your solution conveniently seems to handle the iOS case as well (which was reported for plain mp3s with an unknown duration).

Was there a reason for returning a duration of -1 rather than null on the Dart side if  the duration is unknown? I noticed this was one of the changes you made between your first and second commits. Note that `setUrl` does throw an exception for any error cases, so we could (it seems to me) use null to indicate unknown.

**Comment by lkho** [comment]
> Hi @lkho , thanks for that. Certainly clipping the position to the duration should not be done when the final duration is unknown, and your solution conveniently seems to handle the iOS case as well (which was reported for plain mp3s with an unknown duration).

I only changed the code for handling exoplayer (specifically for live streams, I haven't test plain files, but maybe if the file is from network, AND is not broken, the duration might return a useful value after the initial unknown.)

> Was there a reason for returning a duration of -1 rather than null on the Dart side if the duration is unknown? I noticed this was one of the changes you made between your first and second commits. Note that `setUrl` does throw an exception for any error cases, so we could (it seems to me) use null to indicate unknown.

This is just for backwards compatibility, since I saw the initial value is duration zero, but not null. Emitting a `null` may break things. It can be changed to `null` if you add docs to clarify the meaning.

**Comment by lkho** [comment]
Regarding #41 , (for android exoplayer) my workaround is to remove the check and keep the loop until playback stops, since the duration is not reliable and buffer position can be larger than the duration at anytime, during playback, before the media really ends. I've tried to end the loop and wait for another buffer event to start it again, but _seems_ the buffer event is not reliable too. See if anyone can think of a better solution, or investigate the player events more deeply.

**Comment by ryanheise** [comment]
Just to update this issue, I have merged @lkho 's pull request for Android, and can now look at web and iOS.

I will need to keep an eye on #23 to ensure that we don't get exceptions rendering the seek bar when the position is greater than the duration.

**Comment by ryanheise** [comment]
This is now released in 0.2.0 and the rendering exception has also been fixed.
