### ISSUE TITLE
Unhandled Exception: Loading interrupted

### ISSUE THREAD

**Issue by fullflash** [ryanheise/just_audio#861]
try catch does not catch this error.
we need to catch this error to show an alert to user.

**Comment by ryanheise** [comment]
> try catch does not catch this error.
> we need to catch this error to show an alert to user.

fullflash does not read the bug submission instructions.
We need fullflash to follow these instructions to show a valid bug report to the developers.

**Comment by fullflash** [comment]
this is just a simple remote file play method execution.

no exceptions are handling also i have tried your example it is same.

**Unhandled Exception: (-11829) Cannot Open**
**Unhandled Exception: Loading interrupted** 

```
try {
      return _audioPlayer.setUrl(path);
    } on PlayerException catch (e) {
      // iOS/macOS: maps to NSError.code
      // Android: maps to ExoPlayerException.type
      // Web: maps to MediaError.code
      // Linux/Windows: maps to PlayerErrorCode.index
      print("Error code: ${e.code}");
      // iOS/macOS: maps to NSError.localizedDescription
      // Android: maps to ExoPlaybackException.getMessage()
      // Web/Linux: a generic message
      // Windows: MediaPlayerError.message
      print("Error message: ${e.message}");
    } on PlayerInterruptedException catch (e) {
      // This call was interrupted since another audio source was loaded or the
      // player was stopped or disposed before this audio source could complete
      // loading.
      print("Connection aborted: ${e.message}");
    } catch (e) {
      // Fallback for all other errors
      print('An error occured: $e');
    }
```

**Comment by ryanheise** [comment]
I'm sorry to see from your latest reply that you continue to keep ignoring the instructions. I really do not have time to deal with people who just don't care about the rules. Please do not post any further comments unless it is to tell me that you have read the instructions fully and have updated your bug report to follow the instructions. If you can't submit a valid bug report, then it is probably not a bug, and this is not the correct place to just ask for help. It is the place only to submit legitimate bug reports.
