### ISSUE TITLE
`AudioPlayer.setAsset` method should have `package` parameter

### ISSUE THREAD

**Issue by ewertonls** [ryanheise/just_audio#863]
**Is your feature request related to a problem? Please describe.**
Flutter reads asset paths differently when the asset is in another package, e.g:
Let we have a `my_flutter_app` and a package named `app_assets` and in there we got a mp3 file `assets/compressed/hello.mp3`.
You can't pass it in `my_flutter_app` as `assets/compressed/hello.mp3` because it is in another package, so the app wouldn't be able to load it. The url / path should be: `packages/app_assets/assets/compressed/hello.mp3`

**Describe the solution you'd like**
The method could have a `String? package` parameter, then it would check if it's null or else use the original inputted asset path.

```dart
Future<Duration?> setAsset(
  String assetPath, {
  String? package,
  bool preload = true,
  Duration? initialPosition,
}) {
  final keyName = package == null ? assetPath : 'packages/$package/$assetPath';
  return setAudioSource(
    AudioSource.uri(Uri.parse('asset:///$keyName')),
    initialPosition: initialPosition, preload: preload,
  );
}
```

**Describe alternatives you've considered**
An alternative is to manually set the `packages/package_name/...`.

**Additional context**
The current `AssetImage` and `IconData` and other packages (e.g, lottie) do a similar approach to assets in packages.

**Comment by ryanheise** [comment]
Sounds reasonable to me. Would you be interested in making a pull request?

**Comment by ewertonls** [comment]
~~Yep, today after work I may submit the PR~~
@ryanheise done #864
