### ISSUE TITLE
Not playing audio on iOS with https setUrl

### ISSUE THREAD

**Issue by kyleb-app** [ryanheise/just_audio#875]
**Which API doesn't behave as documented, and how does it misbehave?**
player.setUrl
player.play

**Minimal reproduction project**
Provide a link here using one of two options:
The example

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: (-11850) Operation Stopped
#0      AudioPlayer._load (package:just_audio/just_audio.dart:839:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1420:28)
<asynchronous suspension>
```

**Expected behavior**
Play audio on iOS

**Screenshots**
 - No ss necessary

**Desktop (please complete the following information):**
Not running on desktop

**Smartphone (please complete the following information):**
 - iPhone 7
 - iPhone 14 Pro

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 13.0 22A380 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
    ! Error: Kyle’s Apple Watch needs to connect to determine its availability.
      Check the connection between the device and its companion iPhone, and the
      connection between the iPhone and Xcode. Both devices may also need to be
      restarted and unlocked. (code 1)
[✓] HTTP Host Availability

• No issues found!
```

**Additional context**
Plugin does not play any audio on iOS

**Comment by ryanheise** [comment]
Please don't do the thing that you were just told not to do...

Closing.
