### ISSUE TITLE
[iOS] Cannot load firebase storage audio files

### ISSUE THREAD

**Issue by prateekmedia** [ryanheise/just_audio#883]
**Which API doesn't behave as documented, and how does it misbehave?**
play api

**Minimal reproduction project**
Unfortunately I can't reproduce the error in the example app but I would like to know if any additional step is required in iOS or not, I am using just_audio and just_audio_background both.

**To Reproduce (i.e. user steps, not code)**
1. Load Source
2. Play Audio
3. See error

**Error messages**

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.8adb40f2-02b8-4cea-854d-993e747e6778)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64:34)
<asynchronous suspension>
#2      _PlayerAudioHandler.play (package:just_audio_background/just_audio_background.dart:576:5)
<asynchronous suspension>
#3      _JustAudioPlayer.play (package:just_audio_background/just_audio_background.dart:247:5)
<asynchronous suspension>
#4      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:962:7)
<asynchronous suspension>
```

**Expected behavior**
It should play the audio

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 15

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm (Rosetta), locale en-IN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Additional context**
This only comes in iOS whereas same codebase runs fine on Android.

**Comment by ryanheise** [comment]
Not a valid bug report. If you just have a question, you should look for answers on StackOverflow.

**Comment by prateekmedia** [comment]
That's not a question although I don't know how to reproduce the error, I have done every configuration necessary for iOS setup but it isn't working

**Comment by ryanheise** [comment]
> That's not a question

Yes it is:

> I would like to know if any additional step is required in iOS or not

If you want to know something, ask a question. But the place to do that is StackOverflow.

If you want to report a bug, you need to actually fill in the bug report correctly, including the first section.
