### ISSUE TITLE
Volume change doesn't response on iOS mobile web(safari)

### ISSUE THREAD

**Issue by UlasKasim-dusyeri** [ryanheise/just_audio#889]
**Which API doesn't behave as documented, and how does it misbehave?**
setVolume doesn't change the volume on iOS mobile web(safari)

**Minimal reproduction project**
The example

**To Reproduce (i.e. user steps, not code)**
1. Run just_audio example project by flutter run --release -d web-server --web-hostname 0.0.0.0 --web-port 8888 --web-renderer HTML
2. On your iOS mobile, open the safari browser and go to 'localip:8888'
3. Try to change the volume

**Error messages**

```
Can't see an error message on the web server
```

**Expected behavior**
Changing volume smoothly

**Screenshots**
-

**Desktop (please complete the following information):**
 -

**Smartphone (please complete the following information):**
 - Device: iPad 6
 - OS: 15.6.1

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19044.2251], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.20)     
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2022.1)
[√] VS Code (version 1.73.1)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

**Additional context**
 -

**Comment by ryanheise** [comment]
This is a limitation of the Safari browser on iOS. For some reason, Apple decided not to support the volume feature.

**Comment by ryanheise** [comment]
Reference: https://github.com/mdn/browser-compat-data/issues/12001
