### ISSUE TITLE
Add support for android home widget

### ISSUE THREAD

**Issue by samhu132** [ryanheise/just_audio#896]
**Is your feature request related to a problem? Please describe.**
I want to control the AudioPlayer from home widget on android

**Describe the solution you'd like**
AddING default home widget like the notification to control the player 

**Describe alternatives you've considered**
add documentation to how play the audio from android with java or kotlin

I WILL BE GLAD TO ADD ANY MORE INFO IF NEEDED

**Comment by ryanheise** [comment]
That is certainly an interesting feature proposal.

Although I think it would be best for someone to implement it as a separate plugin that can interoperate with the audio player of your choice (e.g. just_audio), in the same way that just_audio does not directly implement background playback but rather leaves it to separate plugins such as audio_service which do interoperate well with just_audio.

Doing a quick search on pub.dev, there is already another plugin that builds Android app widgets called [app_widget](https://pub.dev/packages/app_widget), and another one called [home_widget](https://pub.dev/packages/home_widget).
