### ISSUE TITLE
Unsupported operation for the web platform

### ISSUE THREAD

**Issue by iliyami** [ryanheise/just_audio#899]
**Which API doesn't behave as documented, and how does it misbehave?**
Playing an audio throw the error mentioned bellow (Unsupported operation), although it start working ...
I think the problem is in "_observeMediaItem" method when the "mediaItem.artUri.schema" is a http.

**Minimal reproduction project**
My forked project of the official example to reproduction: [click](https://github.com/iliyami/audio_service)

**To Reproduce (i.e. user steps, not code)**
1. Just launch the playlist example which I've modified it with "Reproduce the issue" commit.

**Error messages**

```
Error: Unsupported operation: _Namespace
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 200:5               get _namespace
dart-sdk/lib/io/file_impl.dart 376:45                                         lengthSync
packages/audio_service/audio_service.dart 969:30                              _observeMediaItem
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 557:7                                     [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                     _cancelAndValue
dart-sdk/lib/async/stream.dart 1718:11                                        <fn>
dart-sdk/lib/async/stream_pipe.dart 11:14                                     _runUserCode
dart-sdk/lib/async/stream.dart 1716:7                                         <fn>
dart-sdk/lib/async/zone.dart 1586:10                                          runUnaryGuarded
dart-sdk/lib/async/stream_impl.dart 339:11                                    [_sendData]
dart-sdk/lib/async/stream_impl.dart 515:13                                    perform
dart-sdk/lib/async/stream_impl.dart 620:10                                    handleNext
dart-sdk/lib/async/stream_impl.dart 591:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Chrome

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale en-GB)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Additional context**
I've debugged the issue and it seems it's because of the "_observeMediaItem" method in the audio_service.dart file. At line 969, it's using a File object from the dart.io library, and as we know the dart.io library is not supported on the web.

**Comment by ryanheise** [comment]
Does the official example reproduce the bug for you? if so, please edit your bug report to select that option. I understand there is a bug here, but I need the minimal reproduction project before I can proceed.

**Comment by iliyami** [comment]
> Does the official example reproduce the bug for you? if so, please edit your bug report to select that option. I understand there is a bug here, but I need the minimal reproduction project before I can proceed.

Sure, I've just found out this is a bug for the audio_service plugin, so I close this issue here and reopen it in its related repo with a mini project to reproduce the issue. However I edit my bug report and place the project link for bug reproduction here.
