### ISSUE TITLE
Add AudioPlaybackState.COMPLETED and onPlayerCompletion stream listener

### ISSUE THREAD

**Issue by rohansohonee** [ryanheise/just_audio#9]
The audioplayers plugin had features such as onPlayerCompletion stream listener which would get data when the audio file fully completed playback i.e the entire audio file length was played.
I am migrating from this code setup, so having these streams is necessary.

Not only did audioplayers plugin have AudioPlaybackState.COMPLETED but also the audioplayer plugin had it which you are using in audio_service.

Migration from these existing plugins to this just_audio plugin is slightly more difficult due to this.

**Comment by ryanheise** [comment]
I've just added a completed state in the latest commit (untested).

**Comment by rohansohonee** [comment]
Will test this and report back to you

**Comment by rohansohonee** [comment]
This seems to be working. Closing this.
