### ISSUE TITLE
Is it possbile to use dart code to solve the https transport security problem?

### ISSUE THREAD

**Issue by heibor** [ryanheise/just_audio#90]
My https sever is self-signed. I have modify the AndroidManifest.xml file by adding android:usesCleartextTraffic="true" to connect to the non-https port to avoid the transport security problem.

I am wondering whether it's possible to use some dart code as an optional solution to the https trusted connection problem.

For example, here is a [dio solution](https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req). By using dart code, we don't need to modify the AndroidManifest.xml file, maybe the dart code can be used to extend resilience.

**Comment by ryanheise** [comment]
Hi @heibor , I don't consider this to be a feature request. If you want to know how to use the Dart APIs with respect to https with self-signed certificates, you can either read the Dart API documentation, or ask on StackOverflow or Gitter for help.
