### ISSUE TITLE
[iOS] Play method doesn't work for files in Firebase Storage

### ISSUE THREAD

**Issue by prateekmedia** [ryanheise/just_audio#902]
**Which API doesn't behave as documented, and how does it misbehave?**
set audio source and play api doesn't work as documented with firebase storage files like:
https://firebasestorage.googleapis.com/v0/b/besomethinggreat-a89b2.appspot.com/o/stories%2Fcontent%2F1664942224930mp3?alt=media

**Minimal reproduction project**
The example code with the above mentioned link as the audio source on iOS simulator.

**To Reproduce (i.e. user steps, not code)**
1. Open The app
2. Try to load the network audio
3. See error

**Error messages**

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-11828, Cannot Open, null, null)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.8adb40f2-02b8-4cea-854d-993e747e6778)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64:34)
<asynchronous suspension>
#2      _PlayerAudioHandler.play (package:just_audio_background/just_audio_background.dart:576:5)
<asynchronous suspension>
#3      _JustAudioPlayer.play (package:just_audio_background/just_audio_background.dart:247:5)
<asynchronous suspension>
#4      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:962:7)
<asynchronous suspension>
```

**Expected behavior**
It should play the remote audio just like it does in Android

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOs Ventura
 - Browser N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 15

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm (Rosetta), locale en-IN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Additional context**
The Error was Found in iOS Simulator in debug mode, not tested otherwise

**Comment by ryanheise** [comment]
> **Which API doesn't behave as documented, and how does it misbehave?**
> set audio source and play api doesn't work as documented with firebase storage files like:
> https://firebasestorage.googleapis.com/v0/b/besomethinggreat-a89b2.appspot.com/o/stories%2Fcontent%2F1664942224930mp3?alt=media

I'm pretty sure this plugin is not documented to work with firebase storage files. just_audio just wraps around the iOS native APIs which according to their own documentation only works with its supported audio formats, and if the HTTP server serves the media with the correct content type and other required HTTP headers. I am closing as your answer for section 1 does not qualify this as a bug. If you feel there should be better documentation, you may open a documentation request.

**Comment by prateekmedia** [comment]
@ryanheise I don't know why but filling issues here feels like standing in a queue in government offices, even if they know the issue, they would like you to fill everything correctly. Anyways, here we go again the third time.

**Comment by ryanheise** [comment]
The analogy is mostly OK. In both cases, the issues need to be filed correctly. That helps to lower the burden for the people who have to do all the work. Human nature also dictates that people always want something for free and don't give a thought to what has to happen behind the scenes.

The only difference in the analogy is that a government agency has strict filing procedures for accountability, while I have them due to physical/health limitations. Have a nice day.
