### ISSUE TITLE
SequenceStateStream works incorrectly with backgroundAudio

### ISSUE THREAD

**Issue by Nizlan** [ryanheise/just_audio#909]
**Which API doesn't behave as documented, and how does it misbehave?**
AudioPlayer().sequenceStateStream with just_audio_background package. When you set new audioSource with new initial index firstly sequenceStateStream emiting sequenceState with correct new currentIndex, then for some reason with old one and then, again new with new one.
This bug only reproduses with background audio.

**Minimal reproduction project**
https://github.com/Nizlan/just_audio/blob/minor/just_audio_background/lib/just_audio_background.dart

**To Reproduce (i.e. user steps, not code)**
1. Go to just_audio_background/example/
2. Start playing audio
3. Click on refresh button - it will set the same playlist as new audiosource with initial index 2. 
4. What you will see is that the 3rd element(with index 2) will be selected for a moment, then for very short time selection will return to preciously selected audio and then, again new index will be selected. 

**Error messages**

No error messages

**Expected behavior**

After setting new audioSource with new initialIndex SequenceStateStream have to emt only one SequenceState with new initial index.

**Screenshots**

https://user-images.githubusercontent.com/57703588/209853367-4e6fb587-ea0a-497d-a1bf-ed00e8be2e79.mov

**Desktop (please complete the following information):**
 - OS: MacOS 12.4

**Smartphone (please complete the following information):**
 - pixel 3a emulator
 - android 13

**Flutter SDK version**
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-arm, locale en-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Additional context**
In this example this bug not always appeares and that is even more confusing

**Comment by ryanheise** [comment]
Does this issue require just_audio_background, or can it be reproduced with the basic just_audio alone?

**Comment by Nizlan** [comment]
Yes, i could only reproduce it with just_audio_background.

**Comment by ryanheise** [comment]
I have created a fix on the `fix/background_event_lag` branch. Would you like to test it out and let me know how it goes for you?

**Comment by Nizlan** [comment]
Yes, sure

**Comment by Nizlan** [comment]
I can confirm, bug dissapeared

**Comment by ryanheise** [comment]
Thanks for testing, the fix has now been merged and publishing.
