### ISSUE TITLE
`setFilePath` is not working.

### ISSUE THREAD

**Issue by bakatsuyuki** [ryanheise/just_audio#91]
**Describe the bug**
`setFilePath` is not working to file in temporary directory. 
There is no sound and no error message even if run minimal reproduction project.

**Minimal reproduction project**
```
play(Uint8List data) async {
  final player = AudioPlayer();
  final file = File('${(await getTemporaryDirectory()).path}/music.m3u8');
  await file.writeAsBytes(data, flush: true, mode: FileMode.write);
  
  await player.setFilePath(file.path);
  player.play();
}
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS13.3.1

**Flutter SDK version**
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] Connected device (1 available)

• No issues found!
```

Please help me 😭

**Comment by ryanheise** [comment]
I'm not sure, but my guess is that your MacOS runs in a sandbox and may need certain permissions declared in your entitlements or plist files.

**Comment by bakatsuyuki** [comment]
Sorry, I was not told that it occurs in real machine(iPhoneX iOS10.15.3).
And `setUrl` works fine.

By the way, already set to plist
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsArbitraryLoadsForMedia</key>
    <true/>
</dict>
```

If you do not mind, I want a sample that works fine `setFilePath` with file in temporary directory.

**Comment by bakatsuyuki** [comment]
And I'm sorry many times.

Maybe my file is crashed because another library same don't work this file.
And another sample works fine.
Thank you.
