### ISSUE TITLE
Does not work inside of snap

### ISSUE THREAD

**Issue by krille-chan** [ryanheise/just_audio#911]
**Which API doesn't behave as documented, and how does it misbehave?**
audioPlayer.play() does nothing, does not throw an exception or writing something to the logs. It works fine on Linux itself but inside of snap it does not work. I have added `mpv` to the stage packages and added the audio-interface from snap.

**Minimal reproduction project**
https://github.com/krillefear/fluffychat-snap

**To Reproduce (i.e. user steps, not code)**
Build app with snap

**Error messages**

```
None
```

**Expected behavior**
It works

**Screenshots**
---

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on Debian GNU/Linux bookworm/sid 5.19.0-26-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /snap/bin/chromium)
    ! /snap/bin/chromium is not executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.74.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Additional context**
---

**Comment by ryanheise** [comment]
Hi @krillefear , I would suggest reporting this on the [just_audio_mpv](https://github.com/bleonard252/just_audio_mpv/issues) issues database.

**Comment by krille-chan** [comment]
Ah thanks I will do so
