### ISSUE TITLE
Android Equalizer

### ISSUE THREAD

**Issue by sheikhhaziq** [ryanheise/just_audio#915]
**Which API doesn't behave as documented, and how does it misbehave?**
When I try to use "AndroidEqualizer", the songs stop playing.

**Minimal reproduction project**
https://github.com/ryanheise/just_audio/blob/minor/just_audio/example/lib/example_effects.dart

**To Reproduce (i.e. user steps, not code)**
Whenever i try to play any song

**Error messages**

```
 androidEqualizerGetParameters() has not been implemented.
```

**Expected behavior**
The songs should play and I should be able to us Equalizer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
 - Device: OPPO A31
 - OS: Android 9

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.963], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

**Comment by ryanheise** [comment]
Can you please edit your bug report and answer every question properly?

**Comment by sheikhhaziq** [comment]
I tried to use AndroidEqualizer in my app
![Screenshot_20230106_111844](https://user-images.githubusercontent.com/41983383/210938775-754ae905-c48d-48bd-96ca-0e04ac6f37e9.png)
![Screenshot_20230106_111902](https://user-images.githubusercontent.com/41983383/210938802-5615657d-6217-4692-a899-5ad957da872a.png)
Before this songs were playing correctly. But now when try to play song it shows:
![Screenshot_20230106_111959](https://user-images.githubusercontent.com/41983383/210938913-7c08da08-401f-470d-a784-aab551a8dd2a.png)

**Comment by ryanheise** [comment]
I said, can you please "EDIT" your bug report and answer every question PROPERLY? Look at this, for example:

> **Which API doesn't behave as documented, and how does it misbehave?**
> Android Equalizer

Writing "Android Equalizer" does not answer the question of how its behaviour is different from the documentation. Please edit your issue to follow the instructions.

Now the next section says:

> **Minimal reproduction project**
> Provide a link here using one of two options:
> I am getting an error when using AndroidEqualizer

Saying "I am getting an error" is completely unrelated to what the instructions asked you to write.

Until you can submit a valid bug report, I won't be able to help you. Posting new comments is not what I'm asking for, I'm asking you to go back to the original bug report and fix the bug report by editing it and following the instructions.

**Comment by sheikhhaziq** [comment]
I have updated the bug

**Comment by ryanheise** [comment]
> **Minimal reproduction project**
> https://github.com/ryanheise/just_audio/blob/minor/just_audio/example/lib/main.dart

That example doesn't even use the equalizer so how can it be a valid reproduction project?

I sense this is going to be a never ending back-and-forth where you don't follow the instructions.

Also, to say in the first section that "It doesn't work" is a bit lazy as that can be used to describe any bug. It doesn't help me at all.

I'll give you one more chance to edit your bug report and then I'll give up. (Not to say there isn't necessarily a bug, but I also don't appreciate when people waste my time, as time is a scarce resource given my health situation.)

**Comment by sheikhhaziq** [comment]
I'm sorry for my mistakes. I have modified it now

**Comment by ryanheise** [comment]
Can you share a video of what happens?

**Comment by sheikhhaziq** [comment]
https://user-images.githubusercontent.com/41983383/210972275-7c5e6a52-c3f3-4c38-9241-97164e74a8b2.mp4

without using `AudioEqualizer`, songs are playing

**Comment by ryanheise** [comment]
That is not the same reproduction project that you have mentioned in your bug report. Please run the minimal reproduction project linked in your bug report, and then do the steps listed under the How To Reproduce section.

**Comment by sheikhhaziq** [comment]
I'm done with it🙏. Thanks a lot.
