### ISSUE TITLE
Play mono file through both speakers (stereo)

### ISSUE THREAD

**Issue by brylie** [ryanheise/just_audio#918]
**Is your feature request related to a problem? Please describe.**
When I load a mono file, such as a [metronome click](https://freesound.org/people/unfa/sounds/243748/), the sound only plays through one channel on Android.

**Describe the solution you'd like**
It would be nice if the mono file would play through both left and right channels. E.g., it could do so automatically or the developer could specify that it should play in stereo.

**Describe alternatives you've considered**
I can convert the mono file to stereo using Audacity, but that adds a bit more overhead and increases the file size unnecessarily.

**Additional context**

**Comment by ryanheise** [comment]
This has to do with the encoding, not the player. A correct mono file will play from both speakers. I will close since this is not a feature just_audio will implement.
