### ISSUE TITLE
Error implementing settings when instantiating the AudioPlayer class / AudioLoadConfiguration

### ISSUE THREAD

**Issue by edsonl** [ryanheise/just_audio#920]
For example: 
When using the AudioPlayer Class together with just_audio_background. Startup settings are ignored.
But when I use it without just_audio_background it works as expected. It looks like the loading the settings part is not implemented.

final _player = AudioPlayer(
    audioLoadConfiguration: AudioLoadConfiguration(
      androidLoadControl: AndroidLoadControl(
          bufferForPlaybackDuration: const Duration(seconds: 10),
          prioritizeTimeOverSizeThresholds: true),
    ),
 );

**Comment by ryanheise** [comment]
Fixed on the `minor` branch. In future, please respect and follow the instructions when submitting a bug report.
