### ISSUE TITLE
AudioSource.asset static method's tag property not solved.

### ISSUE THREAD

**Issue by Abduraimbek** [ryanheise/just_audio#923]
https://github.com/ryanheise/just_audio/blob/0098b9b38891cc06ed33ff4a7996d65606e3d193/just_audio/lib/just_audio.dart#L2131

I'm using asset files for AudioSource. But above static method do not constructs AudioSource with tag property. So I have to use ProgressiveAudioSource constructor with Uri.parse and tag properties.

**Comment by ryanheise** [comment]
This is fixed in the `minor` branch. In future, please respect and follow the instructions for submitting a bug report.
