### ISSUE TITLE
NSAppleMusicUsageDescription is needed in info.plist

### ISSUE THREAD

**Issue by qHack** [ryanheise/just_audio#926]
**To which pages does your suggestion apply?**

- [Readme](https://github.com/ryanheise/just_audio/blob/minor/just_audio/README.md)

**Quote the sentences(s) from the documentation to be improved (if any)**
> In the "ios" section where it says "Using the default configuration, the App Store will detect that you..."

**Describe your suggestion**

I add the snippet where you compile out the microphone, but when shipping my app to test flight I got an error see below.
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # ADD THE NEXT SECTION
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0'
      ]
    end
    
  end
end
```

I got an email with this error

> ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Runner.app” bundle should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

To solve it I just had to add this to my info.plist

```
<key>NSAppleMusicUsageDescription</key>
<string>Play audio files</string>
```

If I am correct in my understanding that this key is needed, I am happy to make a pull request with the changes.

Thanks for your time.

**Comment by ryanheise** [comment]
> I add the snippet where you compile out the microphone, but when shipping my app to test flight I got an error see below.

That sounds like a bug because you're saying that it is not behaving according to the documentation. However, the documented approach has been working for other people, so it is possible that you just embedded that code snippet in the proper way. Sometimes people have the incorrect white space for example. I'll close this, but feel free to open a bug report first if you've checked and you are still doing everything according to the documentation.
