### ISSUE TITLE
App with just_audio is flagged by App Store Connect

### ISSUE THREAD

**Issue by stevebroshar** [ryanheise/just_audio#932]
When I added just_audio to my flutter project, it started to get flagged by Apple App Store Connect for the two issues below. Thing is, I'm not using microphone or push notifications. The app was not flagged before I added just_audio. I switched to audioplayers to eliminate these issues rather than figure what they mean and how to fix them.

ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Runner.app” bundle should contain a NSMicrophoneUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If your app supports multiple locales, you’re now required to provide a purpose string value in the Info.plist file in addition to a valid localized string across each of your app’s localization folders. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

**Comment by stevebroshar** [comment]
What template?

**Comment by ryanheise** [comment]
The Bug report template. It's hard to miss, when you click "New issue", you will see the Bug report template on that page. But only submit a bug report if it is an actual bug. To save you some time, it sounds like you didn't read the documentation, and in particular, the README file, which talks about this and so it is probably not a bug.

**Comment by stevebroshar** [comment]
Right. Not a bug. It's an annoying behavior ... that I need to add stuff to the project for aspects of the plugin that I'm not using. It would be a nice feature to not have to do this setup if not using those system capabilities.

And I think it worth noting that this makes me shy away from using this plugin since there is another one that doesn't have this issue. That is only a problem is one wants the plugin to be popular; to be used more.

I guess I thought the template was hints. I must have deleted it first thing without reading it closely. Sorry.

**Comment by ryanheise** [comment]
If you want to make a feature request, there is a template for that. When this was initially debated, I think from memory I agreed with your preference, although most people voted for the current behaviour because it followed an established convention at the time. If you create an issue (of course, by reading and following the instructions -- please don't disregard them), then people can vote on it and we can change it.

> I guess I thought the template was hints.

The first line of the template reads:

```
ALL SECTIONS BELOW MUST BE COMPLETED
```

I am not sure how to make that any less hint-like. Of course if you don't read it then that's a problem.
