### ISSUE TITLE
play local file with offset and length

### ISSUE THREAD

**Issue by qianciling** [ryanheise/just_audio#945]
**Is your feature request related to a problem? Please describe.**
I have multiple audio files written into a file in a specific format. And I would like to play the audio files by Offset and ContentLength.How could I achieve it?  
In Android, specific ways to achieve it are as follows.

**Describe the solution you'd like**
refer to **_android MediaPlayer_**
`public void setDataSource(FileDescriptor fd, long offset, long length)`

**Flutter SDK version**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale en-DE)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.2)
> [✓] VS Code (version 1.75.1)
> [✓] Connected device (3 available)
> [✓] HTTP Host Availability

**Comment by ryanheise** [comment]
Please click on "New issue", then click on "Question". Don't use "Feature request" if you just want to ask a question.
