### ISSUE TITLE
How can I stop a player running with Workmanager?

### ISSUE THREAD

**Issue by erol-demirer** [ryanheise/just_audio#948]
Hi guys,

I am developing an alarm application. How can I stop a background player that I use to play alarm sounds? I trigger the player with Workmanager. But I could not find a stable working method on how to stop it.  

Other than the Workmanager cancel methods, I'm just looking for a method to stop the player.

Thanks for your help.

Best Regards

**Comment by erol-demirer** [comment]
@ryanheise  help me please.

**Comment by ryanheise** [comment]
Which word of the bot message above do you need help understanding?

**Comment by erol-demirer** [comment]
Hi guys,

I am developing an alarm application. How can I stop a background player that I use to play alarm sounds? I trigger the player with Workmanager. But I could not find a stable working method on how to stop it.

Other than the Workmanager cancel methods, I'm just looking for a method to stop the player.

Thanks for your help.

Best Regards

**Comment by ryanheise** [comment]
Please stop repeating the same message. You already have my reply as given by the bot message. You then asked for help, as if you didn't understand my reply. So I am willing to help you understand it. Which word in MY bot message didn't you understand?
