### ISSUE TITLE
Skip or replay 10 seconds

### ISSUE THREAD

**Issue by zencubic** [ryanheise/just_audio#95]
I use this package with audio_service. There I want to skip or repeat 10 seconds of audio in the BackgroundAudioTask. Unfortunately I have not found an easy way here so far. I tried to use the seek function but I did not find a simple way to get the current position of the audio. Maybe it would be useful to have a function that can skip (or replay) a given amount of time in the audio.

**Comment by ryanheise** [comment]
I don't think we need to add a specific feature for skipping when you can seek to the current position + 10 seconds.

However, providing a simple way to get the current position would be useful. Currently, you can do this:

```dart
player.playbackEvent.position
```

I suppose I could make it simpler by adding a convenience getter like this:

```dart
player.position
```

**Comment by ryanheise** [comment]
I've added the convenience getter in the latest commit.

**Comment by zencubic** [comment]
Many thanks for your effort :+1:
