### ISSUE TITLE
Does it support recording?

### ISSUE THREAD

**Issue by pen110** [ryanheise/just_audio#957]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanheise** [comment]
Closing as an invalid feature request. You did not bother to follow the instructions by completing all sections and also by searching for existing issues before posting a duplicate. As explained in the readme, this plugin follows the single responsibility philosophy and thus the preference is to use a separate plugin for different responsibilities.
