### ISSUE TITLE
Seek doesn't work properly on Windows

### ISSUE THREAD

**Issue by vorte** [ryanheise/just_audio#971]
**Which API doesn't behave as documented, and how does it misbehave?**
The seek() method doesn't behave as expected on Windows. Calling seek to a specific position seems to update the position data in the positionDataStream, but the actual audio continues playing from the original position.

Not sure if this is a `just_audio` or `just_audio_windows` problem.

**Minimal reproduction project**
The example.

**To Reproduce (i.e. user steps, not code)**
1. Press the Play button.
2. Seek somewhere far ahead using the seek bar - e.g. to the halfway point.
3. The bar updates, but audio continues playing from the beginning.

If you seek a small amount forward (e.g. 5 mins), the seek seems to behave as expected.

**Error messages**
No errors displayed

**Expected behavior**
The audio should always match the seek position on screen.

**Screenshots**
The screen looks as expected, but the audio played doesn't match. E.g. screen shows 45 mins in, but you're actually in the first minute of audio.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 13

Everything works as expected on Android. The issue is **only** present on Windows.

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.22621.1413], locale en-GB)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.6)
[!] Android Studio (not installed)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Additional context**

**Comment by vorte** [comment]
@ryanheise any ideas? I'm happy to raise this on the `just_audio_windows` repo if you think that's where the problem is.

**Comment by ryanheise** [comment]
Please investigate the issue a little further by testing the same feature on other platforms. If you find that it is specific to Windows, then yes it would be appropriate to open the issue on just_audio_windows.

**Comment by vorte** [comment]
I've tested Web as well now, but unfortunately I don't have access to any other platforms. Out of Windows, Android and Web, the issue is **only** present on Windows.

Maybe someone else can help test the other platforms?

**Comment by ryanheise** [comment]
Let's assume it's a Window's specific issue, then. Given that Android and iOS are used widely in production and this bug hasn't been reported for those platforms, it's likely to be Windows-specific.
