### ISSUE TITLE
turn off music when in background

### ISSUE THREAD

**Issue by omar-hanafy** [ryanheise/just_audio#972]
The requested feature is to add the ability to configure the behavior of the `AudioPlayer` in different states of the app, specifically when the app is in the background. Currently, on iOS, the app does not play sounds when it is in the background. However, on Android, the app continues to play sounds in the background, which can be annoying in some scenarios.

The proposed solution is to add a new configuration option to the `AudioPlayer` class that allows the developer to specify the behavior of the player when the app is in the background. This configuration option should allow the developer to choose whether the player should continue playing sounds or pause the playback when the app is in the background.

For example, the developer could create a new instance of the `AudioPlayer` class with the following configuration:

```
final AudioPlayer player = AudioPlayer(
  handleAudioSessionActivation: false,
  handleAudioBackground: true,
  pausePlaybackInBackground: true,
  ...
);
```

With this configuration, the player would pause playback when the app is in the background on both iOS and Android.

This new configuration option would give developers more control over the behavior of the `AudioPlayer` and allow them to provide a better user experience for their users.

**Comment by ryanheise** [comment]
Before you go and create a new issue that actually doesn't completely ignore my instructions, I should mention that this is not a feature that I would implement anyway. Instead, hop onto StackOverflow and ask a question there on how to accomplish what you're trying to do.
