### ISSUE TITLE
Add Option to Prevent Playing Audio/Music While Android App is in the Background.

### ISSUE THREAD

**Issue by omar-hanafy** [ryanheise/just_audio#973]
**Is your feature request related to a problem? Please describe.**
The requested feature is to add the ability to configure the behavior of the `AudioPlayer` in different states of the app, specifically when the app is in the background. Currently, on iOS, the app does not play sounds when it is in the background. However, on Android, the app continues to play sounds in the background, which can be annoying in some scenarios.

**Describe the solution you'd like**
The proposed solution is to add a new configuration option to the `AudioPlayer` class that allows the developer to specify the behavior of the player when the app is in the background. This configuration option should allow the developer to choose whether the player should continue playing sounds or pause the playback when the app is in the background.

For example, the developer could create a new instance of the `AudioPlayer` class with the following configuration:

```
final AudioPlayer player = AudioPlayer(
  handleAudioSessionActivation: false,
  handleAudioBackground: true,
  pausePlaybackInBackground: true,
  ...
);
```

**Describe alternatives you've considered**
I can handle it by overriding didChangeAppLifecycleState. However, I use a cubit to handle audio play globally in the app, so it would be great to be able to configure it through just audio configurations.

**Additional context**
This new configuration option would give developers more control over the behavior of the `AudioPlayer` and allow them to provide a better user experience for their users.

**Comment by ryanheise** [comment]
Closing as I explained in https://github.com/ryanheise/just_audio/issues/972#issuecomment-1503202875 .

>  I can handle it by overriding didChangeAppLifecycleState. However, I use a cubit to handle audio play globally in the app, so it would be great to be able to configure it through just audio configurations.

You can solve the issue as you have stated, and your architectural choices are also up to you. This plugin does not concern itself with widgets, so it is the responsibility of the app to manage this aspect.

**Comment by omar-hanafy** [comment]
Hi @ryanheise, Thank you for your prompt response. I opened this issue based on your suggestion in a previous [issue](https://github.com/ryanheise/audio_session/issues/15#issuecomment-779632594) on audio_session. I understand that this may no longer be a feature that you would implement.

**Comment by ryanheise** [comment]
Thanks for the context, 2 years ago I had heard from another user that the latency was quite significant and so implementing it natively was worth it. How is the latency two years later? Still significant?
