### ISSUE TITLE
PlayerInterruptedException - m4a file recorded with record 

### ISSUE THREAD

**Issue by sunilguptasg** [ryanheise/just_audio#975]
**Which API doesn't behave as documented, and how does it misbehave?**
setAudioSource

**Minimal reproduction project**
not needed

**To Reproduce (i.e. user steps, not code)**
1. Record audio (I am using Windows) - the file is recorded in m4a format (attached file in zip)
2. Recorded audio plays in VLC media player
3. File can be set as source with AudioSource source = AudioSource.uri(Uri.file(widget.sourceUrl!));
the source file looks 'fine' (as compared to a m4a file that has been downloaded from the internet and saved in the same Windows directory)
4. on calling _audioPlayer.setAudioSource(source) ( where _audioPlayer is AudioPlayer() ) - this method throws PlayerInterruptedException

**Error messages**
Exception has occurred.
PlayerInterruptedException (Loading interrupted)

**Expected behavior**
The file should play, like other m4a files - files here play fine: https://getsamplefiles.com/sample-audio-files/m4a

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - none

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19045.2846], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.77.3)
[√] VS Code, 64-bit edition (version 1.64.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

**Additional context**
pubspec.yaml
just_audio: ^0.9.18
just_audio_windows: ^0.2.0

[26d62aa4.zip](https://github.com/ryanheise/just_audio/files/11260002/26d62aa4.zip)

**Comment by ryanheise** [comment]
This sounds like an issue with just_audio_windows - would you mind submitting the issue on that project's GitHub page?

**Comment by bdlukaa** [comment]
Your issue might be related to https://github.com/bdlukaa/just_audio_windows/issues/18

What is the codec being used to encode the files? Can you ensure the given coded is supported in your machine? (See [query codec](https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/codec-query))

https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/supported-codecs

**Comment by benedict1986** [comment]
Hi, I am having the same issue in iOS. I recorded the audio with IOS and then try to replay it in the same app in IOS but could not open the file

To record the audio, I am using

```
await record.start(
        path: path,
        encoder: AudioEncoder.aacLc,
        bitRate: 128000,
        samplingRate: 44100,
      );
```

And to play the audio, I get an error when I run

```
await player?.setAudioSource(AudioSource.file(filePath));
```

The exception message is: "Cannot Open" and I confirm that the file exists.

Thank you

PS: it's working if I record with

```
await record.start(
        path: path,
        encoder: AudioEncoder.wav,
        bitRate: 128000,
        samplingRate: 44100,
      );
```

**Comment by ryanheise** [comment]
Closing this issue and will redirect to https://github.com/bdlukaa/just_audio_windows/issues/18

@benedict1986 Keep in mind that the `record` plugin is known to have had bugs by producing invalid WAV headers that can't be opened on some platforms. You could verify by creating a test WAV file using a more robust application on your desktop, then transferring that file to your iOS device and seeing if it opens. If one WAV file opens and the other doesn't, it's probably not a valid file. The other possibility is that the WAV file wasn't fully written and flushed to disk before attempting to pass it in to just_audio.
