### ISSUE TITLE
Do not autoplay songs after one another in playlist.

### ISSUE THREAD

**Issue by 0xharkirat** [ryanheise/just_audio#981]
**Is your feature request related to a problem? Please describe.**
Currently, in playlist, the next song start playing automatically after previous song is completed. Is there any way I can stop this from happening?

**Describe the solution you'd like**
If there is anyway I can keep track of when the current song is completed playing, I can do the pause method. But currently playerState.processingState == completed only return true when the last song in the playlist is finished.

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanheise** [comment]
Duplicate of #917
