### ISSUE TITLE
Using network security configuration to bypass proxy server safely

### ISSUE THREAD

**Issue by nemedib** [ryanheise/just_audio#984]
**To which pages does your suggestion apply?**
https://github.com/ryanheise/just_audio/blob/minor/just_audio/README.md

**Quote the sentences(s) from the documentation to be improved (if any)**

> If you wish to connect to non-HTTPS URLS, or if you use a feature that depends on the proxy such as headers, caching or stream audio sources, also add the following attribute to the application element:

    <application ... android:usesCleartextTraffic="true">

**Describe your suggestion**

Hello. I believe it is safer to use network security configuration in this case. 
You can add '127.0.0.1' to the network security configuration because the package uses a cleartext HTTP local proxy server that is served on the ipv4 loopback address (127.0.0.1). By excluding it from cleartext traffic restriction, we can ensure that the proxy requests are not blocked. Therefore, the recommended network security configuration should look like this:

android/app/src/main/res/xml/network_security_config.xml
```
<network-security-config>
	<domain-config cleartextTrafficPermitted="true">
		<domain includeSubdomains="false">127.0.0.1</domain>
	</domain-config>
</network-security-config>
````
android/app/src/main/AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example">
    <application android:networkSecurityConfig="@xml/network_security_config">
    </application>
</manifest>
````

Thank you in advance!

**Comment by ryanheise** [comment]
That's a good idea. I think that `usesCleartextTraffic` is still worth including in the README as the simple approach that works in all cases, given that, for example, podcast apps need to be able to play audio from any source listed in the podcast's RSS feed, even if it is `http`. Certainly if an app only needs this for the local proxy, then your solution can be recommended, so both of these use cases need to be documented.

**Comment by ryanheise** [comment]
I have drafted a change do the README below - please let me know if it looks OK to you or if you have any suggestions:

--------

To allow your application to access audio files on the Internet, add the following permission to your `AndroidManifest.xml` file:

```xml
    <uses-permission android:name="android.permission.INTERNET"/>
```

If you wish to connect to non-HTTPS URLs, also add the following attribute to the `application` element:

```xml
    <application ... android:usesCleartextTraffic="true">
```

If you wish to use features that depend on the proxy such as headers, caching or stream audio sources, you also need to enable cleartext access. If you have already enabled the above option, then this will also work for the local proxy. But if your app doesn't generally require access to non-HTTPS URLs on the wider Internet and only requires non-HTTPS access to the local proxy, you may instead prefer to define a network security config that limits cleartext access to localhost (where the proxy runs) by creating the file `android/app/src/main/res/xml/network_security_config.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
	<domain-config cleartextTrafficPermitted="true">
		<domain includeSubdomains="false">127.0.0.1</domain>
	</domain-config>
</network-security-config>
```

Then reference this network security config in your `AndroidManifest.xml` file by adding the following attribute to the `application` element:

```xml
    <application ... android:networkSecurityConfig="@xml/network_security_config">
```

If you need access to the player's AudioSession ID, you can listen to `AudioPlayer.androidAudioSessionIdStream`. Note that the AudioSession ID will change whenever you set new AudioAttributes.

**Comment by nemedib** [comment]
I think everything is covered.
Thank you!

**Comment by ryanheise** [comment]
This is addressed in the latest commit. Thanks for the suggestion!
