### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'MediaItem' in type 

### ISSUE THREAD

**Issue by chitraarasu** [ryanheise/just_audio#991]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
Unhandled Exception: type 'Null' is not a subtype of type 'MediaItem' in type 
```

**Expected behavior**
I am facing issue white try to play. yesterday tried to integrate this package that time worked fine. unfortunately deleted code due to some reason. Now again trying to integrate on same way but getting this issue again and again. trying to fix about 2 days pls help me to fix this issue

**Screenshots**
<img width="1229" alt="image" src="https://github.com/ryanheise/just_audio/assets/75994428/d3545d01-9ff1-4b13-a150-d6179d5dab2d">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - OS: 

**Flutter SDK version**

**Additional context**

**Comment by ryanheise** [comment]
Closing this issue (as promised in the message in your last issue).

**Comment by chitraarasu** [comment]
What is solution for this issue. I have followed documentation properly but still getting this error.

**Comment by ryanheise** [comment]
I guess you're just going to continue ignoring me, and I don't have time for that. Locking the issue. (If you want more context, please read the comment on your previous issue which you ignored. Then please read the instructions for posting an issue which you also ignored.)
