### ISSUE TITLE
just_audio_background audio control behavior needs to be same as app and notification

### ISSUE THREAD

**Issue by aktharOG** [ryanheise/just_audio#995]
Hi i using just_audio and just_audio_background from playing and showing on background. In my i have condition on skip to next on app part its perfect i can controll the button and check next audios behavior and skip to next but this doesn't apply on notification when i skip it not checking my condition .Can U help I need to Controll the notifications button behavior as same as app . I know i can achieve using audio_service but i cant change from just_audio_background. Becouse i almost conpleted project and implementation is completed with audio the ony remianing part is to check the app conditions same in notifications

**Comment by ryanheise** [comment]
Can you please stop spamming the issues board? I've posted the same invalid bug report 3 times now without reading the reply which explains what you're doing wrong.
