### ISSUE TITLE
just_audio_background: Background control buttons accessible but not visible

### ISSUE THREAD

**Issue by jagpreetsethi** [ryanheise/just_audio#999]
**Which API doesn't behave as documented, and how does it misbehave?**
Control Buttons previous / play / pause / next that generally appear on the background running player, are accessible and functions fine but not visible to the user, when using just_audio_background package.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Execute just_audio_background/example/lib/main.dart

**To Reproduce (i.e. user steps, not code)**
1. Execute just_audio_background/example/lib/main.dart
2. Start any song from the playlist
3. Drag background running player from the top. You'll notice control buttons are accessible and function fine but not visible.

**Error messages**
None on the debug console

**Expected behavior**
Control buttons previous / play / pause / next should appear on the background running music player

**Screenshots**
Screenshot - https://i.stack.imgur.com/YACbl.png

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Microsoft Edge

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Simulator
 - OS: iOS 16.4

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.2 22D49 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources
```

**Additional context**
None

**Comment by ryanheise** [comment]
Are you able to confirm that this happens on actual devices?

**Comment by jagpreetsethi** [comment]
Confirming, issue is not seen in iPhone 13 Pro real device! Button is visible and accessible.

**Comment by LastxTemplar** [comment]
is this fixed? I can see this issue on an actual device iPhone X.
@jagpreetsethi did you do anything to fix this?

**Comment by ryanheise** [comment]
@LastxTemplar please submit a new issue with your own reproduction project and steps.

**Comment by jagpreetsethi** [comment]
@LastxTemplar Nope, didn't do anything within the code. I still see icons missing in the simulator instance.

**Comment by LastxTemplar** [comment]
@jagpreetsethi weirdly enough I cant replicate the issue on an actual device anymore, still an issue in the simulator, but i'll look the other way on this for now :D

**Comment by jagpreetsethi** [comment]
@LastxTemplar Even the background music doesn't work fine in the simulator as in when the app is minimized, sound starts to crackle. However, it works fine on a real iPhone device.
